- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa/criteria/AdvancedCriteriaQueryTestSuite.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/querydef/ExpressionImpl.java
fix for https://bugs.eclipse.org/bugs/show_bug.cgi?id=349477:
Type erasure removes Collection from Expression<Collection> and this leads to unexpected method being invoked. Since we know the right type during runtime, we can intercept it and route the execution to the expected path. 
> Bug 349477 - Using criteria.in(…) with ParameterExpression of type Collection creates invalid SQL

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/oxm/XMLMarshaller.java
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/JAXBTestSuite3.java
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/prefixmapper/PrefixMapperContextTestCases.java
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/prefixmapper/PrefixMapperPackageInfoTestCases.java
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/prefixmapper/packageinfonamespace/EmailAddress.java
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/prefixmapper/packageinfonamespace/ObjectFactory.java
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/prefixmapper/packageinfonamespace/package-info.java
MOXy marshaller ignores custom namespace prefix mapping specified in package-info class. It generates default one "ns0" instead custom "PRE". After patch it can use mapping from package-info class. See https://bugs.eclipse.org/bugs/show_bug.cgi?id=531349 .
> Bug 531349 - XmlSchema Prefix is not honoured if root element is  nil

- .travis.yml
- dbws/eclipselink.dbws.test/antbuild.xml
- foundation/eclipselink.core.test/antbuild.xml
- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/framework/TestCase.java
- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/framework/TestCollection.java
- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/framework/TestExecutor.java
- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/framework/TestModel.java
- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/framework/TestSuite.java
- foundation/eclipselink.extension.test/antbuild.xml
- jpa/eclipselink.jpa.test.jse/antbuild.xml
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/modelgen/TestProcessor.java
- jpa/eclipselink.jpa.test/antbuild.xml
- jpa/eclipselink.jpa.wdf.test/antbuild.xml
- jpa/eclipselink.jpars.test/antbuild.xml
- jpa/org.eclipse.persistence.jpa.jpql.test/antbuild.xml
- moxy/eclipselink.moxy.test/antbuild.xml
- sdo/eclipselink.sdo.test/antbuild.xml
- utils/eclipselink.dbws.builder.test/antbuild.xml
While going through issues in old mirror I came across https://github.com/eclipse/eclipselink.runtime/pull/31 and extended that PR to also run LRG tests...
Do we want this in the main repo? I can imagine it can be extended to cover more DBs and tight to every PR... It is not meant to replace nightly jobs on eclipse.org infra. Opinions?
> Add configuration for travis

- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/modelgen/TestProcessor.java
- jpa/org.eclipse.persistence.jpa.modelgen/src/org/eclipse/persistence/internal/jpa/modelgen/visitors/ElementVisitor.java
Note that the test uses Stream and lambda call implying dependency on JDK8+ which should be fine for master (JDK9+) and 2.7 (JDK8+) streams
> [master] Bug 487838: Metamodel gen fails if class hierarchy contains enclosed interfaces

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/oxm/XMLCompositeObjectMappingNodeValue.java
- moxy/eclipselink.moxy.test/resource/org/eclipse/persistence/testing/jaxb/dynamic/xmlschema-import-cross-first.xsd
- moxy/eclipselink.moxy.test/resource/org/eclipse/persistence/testing/jaxb/dynamic/xmlschema-import-cross-fourth.xsd
- moxy/eclipselink.moxy.test/resource/org/eclipse/persistence/testing/jaxb/dynamic/xmlschema-import-cross-second.xsd
- moxy/eclipselink.moxy.test/resource/org/eclipse/persistence/testing/jaxb/dynamic/xmlschema-import-cross-third.xsd
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/dynamic/DynamicJAXBContextCreationTestCases.java
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/dynamic/DynamicJAXBFromXSDTestCases.java
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/dynamic/util/CustomEntityResolver.java
MOXy marshaller in case of inheritance between types from different schemas and namespaces not generates all required namespace definitions. After patch it will generate namespaces for elements based on type inheritance across multiple schemas. See https://bugs.eclipse.org/bugs/show_bug.cgi?id=515225.
> Bug 515225 - Marshaller not generating namespace definition

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/oxm/record/UnmarshalRecordImpl.java
- moxy/eclipselink.moxy.test/resource/org/eclipse/persistence/testing/jaxb/json/nil/nilElements.json
- moxy/eclipselink.moxy.test/resource/org/eclipse/persistence/testing/jaxb/json/nil/nilElementsWrite.json
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/json/JSONTestSuite.java
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/json/nil/MaskFormat.java
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/json/nil/MaskFormatEntry.java
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/json/nil/NilElementsUsageTestCases.java
JSON unmarshaller incorrectly parse nil elements in JSON. It parse them like XML xsi:nil="true" control attribute.
New condition in org.eclipse.persistence.internal.oxm.record.UnmarshalRecordImpl to evaluate nil as a control attribute only when input is XML document.
See https://bugs.eclipse.org/bugs/show_bug.cgi?id=533861 .
> Bug 533861 - JSON unmarshaller incorrectly parse nil elements

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/oxm/XMLCompositeObjectMappingNodeValue.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/oxm/record/XMLReader.java
- moxy/eclipselink.moxy.test/resource/org/eclipse/persistence/testing/jaxb/xmlelementref/stringNillRootNamespace.json
- moxy/eclipselink.moxy.test/resource/org/eclipse/persistence/testing/jaxb/xmlelementref/stringNillRootNamespace.xml
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/JAXBTestSuite.java
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/xmlelementref/nills2/Bar.java
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/xmlelementref/nills2/ObjectFactory.java
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/xmlelementref/nills2/OptFoo.java
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/xmlelementref/nills2/XmlElementRefNillStringRootNamespaceTestCases.java
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/xmlelementref/nills2/package-info.java
Bug 420746 - Unmarshal of JAXBElement field annotated with @XmlElementRef nil not unmarshalling xsi:nil="true" correctly.
MOXy unmarshaller incorrectly unmarshal element declared with @XmlElementRef if attribute (namespace declaration) xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" is positioned outside element with xsi:nil="true" attribute.
There are no other null policies applied, than xsi:nil="true" in the source document. After patch it will set as a field value instance of JAXBElement (from ObjectFactory) with null value instead of null. See https://bugs.eclipse.org/bugs/show_bug.cgi?id=420746 .
> Bug 420746 - Unmarshal of JAXBElement field annotated with @XmlElementRef nil not unmarshalling xsi:nil="true" correctly.

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/oxm/XPathFragment.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/oxm/XMLField.java
- moxy/eclipselink.moxy.test/resource/org/eclipse/persistence/testing/jaxb/xmlelement/same_element_attribute_name_nonamespace.json
- moxy/eclipselink.moxy.test/resource/org/eclipse/persistence/testing/jaxb/xmlelement/same_element_attribute_name_nonamespace.xml
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/xmlelement/EmployeeSameElementAttributeName.java
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/xmlelement/SameElementAttributeNameTestCases.java
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/xmlelement/XmlElementTestSuite.java
Bug 533874 - Attribute and Element with same name results in element not appearing on parse
MOXy doesn't unmarshall XML/JSON document correctly if attribute and element with same name is at the same level.
Input XML Example: ...<employee name="john.smith"><name>...
Input JSON Example: ..."employee": {"@name": "john.smith","name": [...
leads into wrong mapping to entity instance.
This patch repairs mapper selection from HashTable to correctly identify attribute and element.
See https://bugs.eclipse.org/bugs/show_bug.cgi?id=533874 .
> Bug 533874 - Attribute and Element with same name results in element not appearing on parse

- moxy/org.eclipse.persistence.moxy/src/org/eclipse/persistence/internal/jaxb/XMLJavaTypeConverter.java
Bug 503015 - NPE in XMLJavaTypeConverter.java
Possible source of NPE if marshaller, unmarshaller variable will be null.
This case is not covered by special test case. It's not usual to create and use instance of org.eclipse.persistence.internal.jaxb.XMLJavaTypeConverter directly. There are tests in  org.eclipse.persistence.testing.jaxb.xmladapter package.
See https://bugs.eclipse.org/bugs/show_bug.cgi?id=503015 .
> Bug 503015 - NPE in XMLJavaTypeConverter.java

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/queries/ExpressionQueryMechanism.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/version/TestVersioning.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/version/model/IntegerVersionedEntity.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/version/model/TemporalVersionedEntity.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/version/model/TemporalVersionedEntity2.java
fixes #93 
Signed-off-by: Joe Grassel <jgrassel@us.ibm.com>
My solution to resolving the problem is to first check if the database field referenced by the writeLock expression is already part of an existing expression in the updateClause.  For example, during a debug session, I noticed while examining the memory state of the objects available during the method invocation:
```
writeLock	FieldExpression  (id=90)	
field	DatabaseField  (id=87)	
updateClauses	HashMap<K,V>  (id=77)	
[0]	HashMap$Node<K,V>  (id=147)	
key	QueryKeyExpression  (id=152)	
baseExpression	ExpressionBuilder  (id=71)	
derivedFields	ArrayList<E>  (id=168)	
[0]	FieldExpression  (id=90)
field	DatabaseField  (id=87)	
```	
And I thought a potential solution would be to identify the DatabaseField that is member of the writeLock …
> [2.7] Eclipselink#93: Resolve issue with JPA Versoning with java.sql.Timestamp

- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/tests/expressions/ExpressionSubSelectTestSuite.java
SubSelectFromClauseTest2 keeps failing on public build infra while passing on other machines. I haven't managed to reproduce the failure locally so I suggest to disable the test for now.
> Bug 535088: SubSelectFromClauseTest2 failing randomly on public infra

- .travis.yml
- foundation/eclipselink.core.test/antbuild.properties
- foundation/eclipselink.core.test/antbuild.xml
- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/tests/TestRunModel.java
- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/tests/junit/logging/LogCategoryHelper.java
- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/tests/junit/logging/LogCategoryTest.java
- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/tests/junit/logging/LogLevelHelper.java
- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/tests/junit/logging/LogLevelTest.java
- foundation/eclipselink.extension.test/src/org/eclipse/persistence/testing/tests/logging/slf4j/SLF4JLoggerTest.java
This also removes split package between core and core.test and updates travis to use Ant 1.10.2 for the build
> Update core.test script to allow easier testing against modules

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/oxm/XMLMarshaller.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/oxm/record/ContentHandlerRecord.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/oxm/record/NodeRecord.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/xml/SAXDocumentBuilder.java
- moxy/eclipselink.moxy.test/resource/org/eclipse/persistence/testing/jaxb/xmlanyelement/employeeLaxCDATA.xml
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/JAXBTestSuite.java
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/xmlanyelement/EmployeeLaxCDATA.java
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/xmlanyelement/XmlAnyElementLaxCDATATestCases.java
Bug 534812 - HIERARCHY_REQUEST_ERR marshalling a CDATA-containing XmlAnyElement to a Node result
Bug fix in org.eclipse.persitence.NodeRecord.characters().
CDATA handling implementation in org.eclipse.peristence.platform.xml.SAXDocumentBuilder (see MOXy bug 355143).
See https://bugs.eclipse.org/bugs/show_bug.cgi?id=534812
> Bug 534812 - HIERARCHY_REQUEST_ERR marshalling a CDATA-containing XmlAnyElement to a Node result

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/oxm/record/json/JsonStructureReader.java
- moxy/eclipselink.moxy.test/resource/org/eclipse/persistence/testing/jaxb/xmlvariablenode/rootCollectionNull.json
- moxy/eclipselink.moxy.test/resource/org/eclipse/persistence/testing/jaxb/xmlvariablenode/rootCollectionNull.xml
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/xmlvariablenode/AllVariableElementTestCases.java
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/xmlvariablenode/ChildNull.java
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/xmlvariablenode/RootNull.java
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/xmlvariablenode/XmlVariableNodeCollectionNullValueTestCases.java
Bug 484561 - JAXB changes null to "" - when @XmlValue is used for JSON
MOXy JSON unmarshaller incorrectly unmarshalls null into field marked with @XmlValue annotation and when @XmlVariableNode is used.
Instead of null it returns empty string.
See https://bugs.eclipse.org/bugs/show_bug.cgi?id=484561 .
> Bug 484561 - JAXB changes null to "" - when @XmlValue is used for JSON

- moxy/org.eclipse.persistence.moxy/src/org/eclipse/persistence/jaxb/rs/MOXyJsonProvider.java
Bug 513368 - MOXyJsonProvider - returns null on JAXBException
Correction of catch statement to log more details about exception in org.eclipse.persistence.jaxb.rs.MOXyJsonProvider.getJAXBContext() method.
See https://bugs.eclipse.org/bugs/show_bug.cgi?id=513368 .
> Bug 513368 - MOXyJsonProvider - returns null on JAXBException

- .idea/misc.xml
- moxy/org.eclipse.persistence.moxy/src/org/eclipse/persistence/jaxb/compiler/AnnotationsProcessor.java
- moxy/org.eclipse.persistence.moxy/src/org/eclipse/persistence/jaxb/compiler/Property.java
- moxy/org.eclipse.persistence.moxy/src/org/eclipse/persistence/jaxb/javamodel/Helper.java
Changes API in org.eclipse.persistence.jaxb.javamodel.Helper .
Change of static JavaClass variables/fileds into instance fields.
Change of scope of Helper.JAXBELEMENT_CLASS and Helper.OBJECT_CLASS to private.
Create accessor methods getJaxbElementClass(), getObjectClass().
See https://bugs.eclipse.org/bugs/show_bug.cgi?id=529270
> Bug 529270 - MOXy may causes classloader leaks

- moxy/eclipselink.moxy.test/resource/org/eclipse/persistence/testing/jaxb/beanvalidation/sgen_xjc/rich_schema.xsd
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/beanvalidation/BeanValidationBindingsTestCase.java
- moxy/org.eclipse.persistence.moxy/src/org/eclipse/persistence/jaxb/plugins/BeanValidationPlugin.java
Bug 520295 - XBeanVal extension generates unnecesary @NotNull annotation
XJC XBeanVal extension generates unnecesary @NotNull annotations.
This patch extends condition with minOccurs attribute test.
See https://bugs.eclipse.org/bugs/show_bug.cgi?id=520295
> Bug 520295 - XBeanVal extension generates unnecesary @NotNull annotation

- antbuild.xml
- sdo/eclipselink.sdo.test/antbuild.properties
- sdo/eclipselink.sdo.test/antbuild.xml
This removes SDO from 'eclipselink.jar' bundle. It's intended for master only.
> Bug 535830: remove SDO from eclipselink.jar

- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa22/metadata/MetadataASMFactoryTest.java
- jpa/eclipselink.jpa.test/src/org/eclipse/samples/annotations/CycleA.java
- jpa/eclipselink.jpa.test/src/org/eclipse/samples/annotations/CycleB.java
- jpa/eclipselink.jpa.test/src/org/eclipse/samples/annotations/CycleC.java
- jpa/eclipselink.jpa.test/src/org/eclipse/samples/annotations/CycleSelf.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/metadata/accessors/objects/MetadataAnnotatedElement.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/metadata/accessors/objects/MetadataAsmFactory.java
Replaces PR 133.
Contains getAnnotation part of the fix and jUnit to verify self referencing meta-annotation and cycle of 3 annotations (A->B->C->A).
> Bug 535250 - Recursive annotations triggers a StackOverflowError

- utils/eclipselink.dbws.builder.test/src/dbws/testing/secondarysql/SecondarySQLTestSuite.java
- utils/eclipselink.dbws.builder.test/src/dbws/testing/sqlascollection/SQLAsCollectionTestSuite.java
tests in dbws.testing.secondarysql.SecondarySQLTestSuite and dbws.testing.sqlascollection.SQLAsCollectionTestSuite are failing on some JDKs due to different location of xmlns declaration. This is to avoid false alarm by adding second check to tests.
> [nobug]: dbws builder tests are failing on some JDKs

- utils/eclipselink.dbws.builder.test/src/dbws/testing/secondarysql/SecondarySQLTestSuite.java
- utils/eclipselink.dbws.builder.test/src/dbws/testing/sqlascollection/SQLAsCollectionTestSuite.java
Backport of #157 to 2.7
tests in dbws.testing.secondarysql.SecondarySQLTestSuite and dbws.testing.sqlascollection.SQLAsCollectionTestSuite are failing on some JDKs due to different location of xmlns declaration. This is to avoid false alarm by adding second check to tests.
Signed-off-by: Lukas Jungmann <lukas.jungmann@oracle.com>Signed-off-by: Lukas Jungmann <lukas.jungmann@oracle.com>
> [2.7] [nobug]: dbws builder tests are failing on some JDKs

- jpa/eclipselink.jpa.test/antbuild.xml
- jpa/eclipselink.jpa.test/resource/eclipselink-jpa22-model/advanced-ddl-orm.xml
- jpa/eclipselink.jpa.test/resource/eclipselink-jpa22-model/advanced-orm.xml
- jpa/eclipselink.jpa.test/resource/eclipselink-jpa22-model/orm.xml
- jpa/eclipselink.jpa.test/resource/eclipselink-jpa22-model/persistence.xml
- jpa/eclipselink.jpa.test/resource/eclipselink-jpa22-sessionbean-model/server/persistence.xml
- jpa/org.eclipse.persistence.jpa/resource/org/eclipse/persistence/jpa/orm_2_2.xsd
- jpa/org.eclipse.persistence.jpa/resource/org/eclipse/persistence/jpa/persistence_2_2.xsd
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/metadata/xml/XMLEntityMappingsReader.java
this change is present in master and 2.7_WAS branches but apparently missing in 2.7, so backporting it there.
> Bug 521954: Eclipselink is not able to parse ORM XML files using the 2.2 schema

- uploadToNexus.xml
> Bug 537261: maven artifacts should depend on javax.validation 2.0.1.Final

- uploadToNexus.xml
> [2.7] Bug 537261: maven artifacts should depend on javax.validation 2.0.1.Final

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/oxm/record/AbstractMarshalRecordImpl.java
- moxy/eclipselink.moxy.test/resource/org/eclipse/persistence/testing/jaxb/annotations/xmldiscriminator/vehicle-write.json
- moxy/eclipselink.moxy.test/resource/org/eclipse/persistence/testing/jaxb/externalizedmetadata/xmldiscriminator/vehicle-write.json
Bug 536947 – XmlDiscriminatorNode with JSON in MoxyBindings File Is not applied to Root Elements
MOXy before this fix always applied to the JSON root element attribute name ‘type’ if XmlDiscriminatorNode was enabled (via `XmlDiscriminatorNode` annotation or XML binding configuration file). There was same strategy as in XML with
`xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="car"` . There was inconsistency with rest of JSON sub elements where custom name, specified in annotation or binding configuration file, is applied.
After this fix custom name of type attribute is applied to the JSON root element too instead of hardcoded ‘type'.
There were incorrect test/resource files ‘vehicle-write.json’ for test classes `org.eclipse.persistence.testing.jaxb.annotations.xmldiscrimina …
> Bug 536947 – XmlDiscriminatorNode with JSON in MoxyBindings File Is not applied to Root Elements

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/oxm/XMLBinaryDataCollectionMappingNodeValue.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/oxm/XMLChoiceCollectionMappingMarshalNodeValue.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/oxm/XMLCompositeCollectionMappingNodeValue.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/oxm/XMLCompositeDirectCollectionMappingNodeValue.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/oxm/XMLMarshaller.java
- jpa/eclipselink.jpars.test/src/org/eclipse/persistence/jpars/test/service/noversion/TestService.java
- moxy/eclipselink.moxy.test/resource/org/eclipse/persistence/testing/jaxb/collections/emptycollectionholderpopulatedsinglereduced.json
Bug 433822 - JSON_REDUCE_ANY_ARRAYS Marshaller property is not taken into account
MOXy ignored optional marshaller property JSON_REDUCE_ANY_ARRAYS to marshall
array or collection with one item as single item without [] boundary characters.
There was incorrect test/resource file for test CollectionHolderPopulatedSingleItemReducedTestCases.
This is fix for this bug and test CollectionHolderPopulatedSingleItemReducedTestCases too.
See https://bugs.eclipse.org/bugs/show_bug.cgi?id=433822
> Bug 433822 - JSON_REDUCE_ANY_ARRAYS Marshaller property is not taken into account

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/oxm/JsonTypeConfiguration.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/oxm/OXMSystemProperties.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/oxm/XMLRelationshipMappingNodeValue.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/oxm/record/AbstractMarshalRecordImpl.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/oxm/record/SAXUnmarshallerHandler.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/oxm/XMLConstants.java
- moxy/eclipselink.moxy.test/resource/org/eclipse/persistence/testing/jaxb/json/type/type_property_custom_name.json
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/json/JSONTestSuite.java
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/json/type/TypePropertyCustomNameTestCases.java
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/json/type/model/Address.java
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/json/type/model/Contact.java
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/json/type/model/PersonWithType.java
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/json/type/model/Phone.java
- moxy/org.eclipse.persistence.moxy/src/org/eclipse/persistence/jaxb/JAXBContextProperties.java
- moxy/org.eclipse.persistence.moxy/src/org/eclipse/persistence/jaxb/JAXBMarshaller.java
- moxy/org.eclipse.persistence.moxy/src/org/eclipse/persistence/jaxb/JAXBUnmarshaller.java
- moxy/org.eclipse.persistence.moxy/src/org/eclipse/persistence/jaxb/MarshallerProperties.java
- moxy/org.eclipse.persistence.moxy/src/org/eclipse/persistence/jaxb/UnmarshallerProperties.java
- moxy/org.eclipse.persistence.moxy/src/org/eclipse/persistence/jaxb/compiler/MappingsGenerator.java
Bug 536947 v 2.0 – XmlDiscriminatorNode with JSON in MoxyBindings File Is not applied to Root Elements
This fix extends MOXY JAXBContext, MarshallerProperties, UnmarshallerProperties with new JSON_TYPE_ATTRIBUTE_NAME property. It allows to override default type property name “type” for JSON content as MOXy type discriminator with custom name. Before this fix this customization was possible only via XML bindings file xml-discriminator-node attribute in java-type element. Settings from binding file have higher priority if this file is used too.
This fix has test case too.
See https://bugs.eclipse.org/bugs/show_bug.cgi?id=536947
> Bug 536947 v 2.0 – XmlDiscriminatorNode with JSON in MoxyBindings File Is not applied to Root Elements

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/oxm/XMLObjectReferenceMappingNodeValue.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/oxm/mappings/XMLCollectionReferenceMapping.java
- moxy/eclipselink.moxy.test/resource/org/eclipse/persistence/testing/jaxb/annotations/xmlidref/inheritance/control.json
- moxy/eclipselink.moxy.test/resource/org/eclipse/persistence/testing/jaxb/annotations/xmlidref/inheritance/control.xml
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/annotations/AnnotationsTestSuite.java
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/annotations/xmlidref/inheritance/ComplexNode.java
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/annotations/xmlidref/inheritance/LeafNode.java
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/annotations/xmlidref/inheritance/Node.java
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/annotations/xmlidref/inheritance/RootNode.java
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/annotations/xmlidref/inheritance/XmlIdRefInheritanceTestCases.java
- moxy/org.eclipse.persistence.moxy/src/org/eclipse/persistence/jaxb/compiler/AnnotationsProcessor.java
Bug 538228 - @XmpPaths + @XmlIDREF + @XmlElements fail due to bad analyze of referenced types
This is fix for org.eclipse.persistence.jaxb.compiler.AnnotationsProcessor as it is specified in the bug description.
There was problem with resolving @XmlID fields from parent classes if there is inheritance between entities.
But there are some small fixes in classes used by marshaller and unmarshaller too to correctly marshall/unmarshall documents with @XmlIDREF + @XmlPaths + @XmlElements annotations.
See https://bugs.eclipse.org/bugs/show_bug.cgi?id=538228
> Bug 538228 - @XmpPaths + @XmlIDREF + @XmlElements fail due to bad analyze of referenced types

- moxy/org.eclipse.persistence.moxy/src/org/eclipse/persistence/jaxb/JAXBContextProperties.java
- moxy/org.eclipse.persistence.moxy/src/org/eclipse/persistence/jaxb/MarshallerProperties.java
- moxy/org.eclipse.persistence.moxy/src/org/eclipse/persistence/jaxb/UnmarshallerProperties.java
Bug 536947 v 2.0 – XmlDiscriminatorNode with JSON in MoxyBindings File Is not applied to Root Elements (fix for javadoc comments)
This fix extends MOXY JAXBContext, MarshallerProperties, UnmarshallerProperties with new JSON_TYPE_ATTRIBUTE_NAME property. It allows to override default type property name “type” for JSON content as MOXy type discriminator with custom name. Before this fix this customization was possible only via XML bindings file xml-discriminator-node attribute in java-type element. Settings from binding file have higher priority if this file is used too.
This fix has test case too.
This commit contains fix for javadoc comments.
See https://bugs.eclipse.org/bugs/show_bug.cgi?id=536947
> Bug 536947 v 2.0 – XmlDiscriminatorNode with JSON in MoxyBindings File Is not applied to Root Elements (fix for javadoc comments)

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/expressions/ConstantExpression.java
for #212
This change was apparently missing from #219 and causes a NPE test failure in the jpa.jse test bucket
> [2.6_WAS] Bug 537795: Change missed in the port to 2.6_WAS

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/queries/ExpressionQueryMechanism.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/queries/ConstructorReportItem.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/queries/ReportQuery.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/queries/ReportQueryResult.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/criteria/TestCriteriaBuilder.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/criteria/model/L1.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/criteria/model/L1Model.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/criteria/model/L1_.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/criteria/model/L2.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/criteria/model/L2Model.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/criteria/model/L2_.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/querydef/CriteriaQueryImpl.java
for #253 
Most of these changes revolve around adding support for recursively processing the ReportItems/ConstructorReportItems. We now process the `reportItems` for ConstructorReportItem recursively instead of just 1 level down:
```
ConstructorReportItem(null -> [
ReportItem(null0 -> Query Key id Base model.L1),
ReportItem(null1 -> Query Key name Base model.L1),
ConstructorReportItem(null -> [
ReportQueryItem(null0 -> Query Key id Query Key l2 Base model.L1),
ReportQueryItem(null1 -> Query Key name Query Key l2 Base model.L1)
])
])
```
> [master] Issue #253: Add support for embedded constructor result expressions

- .travis.yml
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/descriptors/changetracking/DeferredChangeDetectionPolicy.java
- jpa/eclipselink.jpa.test/antbuild.xml
- jpa/eclipselink.jpa.test/wildfly.properties
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/metadata/listeners/BeanValidationListener.java
Original fix in #248 caused regressions in core tests (as can be seen on nightly downloads page :-/ )
Problem with the original fix is that it did not take into account that user may have custom event listener bound to say 'preUpdate' event where he wants to alter to be modified object somehow. In this case, it is expected that the update event is fired even for unchanged objects and that is not happening after my original fix :-/
Better fix seems to be to bind internal bean validation 'preUpdate' check to the 'aboutToUpdateEvent' - this event is fired only for to be updated objects just before sending the update statement to the DB. In this case, it is also expected to be guaranteed that all user-defined listeners, even those altering the object being changed in ie …
> Bug411013 - 2nd attempt

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/queries/ArrayListContainerPolicy.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/queries/IndirectListContainerPolicy.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/queries/InterfaceContainerPolicy.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/queries/VectorContainerPolicy.java
VectorContainerPolicy is used for all List types.  Likely the Object
passed to cloneFor will not be a Vector, but rather an ArrayList,
LinkedList or some other List derivative.  Getting a ClassCastException
is expected to be the normal code path so doing an instanceof check to
avoid the exception.  instanceof will perform better than the
ClassCastException since you need to do a stack walk in order to
generate the stack trace of the exception.  In general Exceptions should
not be a normal decision mechanism if possible.
> Issue #285: Avoid ClassCastException and IllegalArgumentException in cloneFor implementations

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/databaseaccess/DatabasePlatform.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/EntityManagerSetupImpl.java
for #283
I think the fix for #284 was incorrect. I stumbled across DatabasePlatform.copyInto() and realized that this is where the Cast value is supposed to be copied over at. 
> [master] Bug 540929: jdbc.sql-cast property does not apply - fix

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/SQLServerPlatform.java
Currently, EclipseLink uses Statement#setMaxRows() to apply a result limit when the target database is MS SQL Server. This is dangerous because mssql-jdbc implements setMaxRows() by executing SET ROWCOUNT, which applies to all queries made on the connection until SET ROWCOUNT is executed again.
Normally, that is not an issue, but it can become a problem if, for example, your query includes a call to a user-defined function that executes another query. When that happens, it creates truly baffling bugs that are very difficult to track down. mssql-jdbc acknowledges that SET ROWCOUNT is not an appropriate way to implement setMaxRows() but currently has no ability to replace it with something better; see https://github.com/Microsoft/mssql-jdbc/issues/176.
This PR alters SQLServerPlatform to …
> SQL Server: if possible, use OFFSET and FETCH instead of JDBC methods

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/mappings/OneToManyMapping.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/TestUnidirectionalOneToMany.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/model/CommentB.java
during update of unidirectional 1-m relationship only relationship constraint related fields are being inserted to the DB, so if there are additional fields then these additional fields never get stored into DB.
> Bug 391279: fix the case when existing object is being updated

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/config/PersistenceUnitProperties.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/databaseaccess/DatabasePlatform.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/DB2Platform.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/property/TestParameterBinding.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/EntityManagerSetupImpl.java
> [2.6] Bug #542491: Add new property to force parameter binding

- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/canonical/BasePersistable.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/canonical/DomainClass.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/canonical/DomainInterface.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/canonical/DomainInterface_.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/canonical/DomainPersistable.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/canonical/TestCanonicalMetaModel.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/metadata/MetadataProject.java
for #260
Signed-off-by: Jan Vissers <vissers.j@gmail.com>
> [master] Bug 539822: Fixes #260

- foundation/org.eclipse.persistence.core/core.iml
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/oxm/XMLRelationshipMappingNodeValue.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/oxm/record/SAXUnmarshallerHandler.java
- moxy/eclipselink.moxy.test/moxy.test.iml
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/json/JSONTestSuite.java
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/json/type/TypePropertyCustomNameNamespaceTestCases.java
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/json/type/TypePropertyCustomNameTestCases.java
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/json/type/modelns/Koo1.java
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/json/type/modelns/KooSuper.java
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/json/type/modelns/Namespace.java
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/json/type/modelns/ObjectFactory.java
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/json/type/modelns/Tel.java
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/json/type/modelns/package-info.java
- moxy/org.eclipse.persistence.moxy/src/org/eclipse/persistence/jaxb/JAXBContext.java
This is fix v 3.0 for bug 536947 – XmlDiscriminatorNode with JSON in MoxyBindings File Is not applied to Root Elements
This fix cover additional test cases described in bug [attachment](https://bugs.eclipse.org/bugs/attachment.cgi?id=276944)
This fix extends Unit tests with test case from bugzilla.
> Bug 536947 v 3.0 – XmlDiscriminatorNode with JSON in MoxyBindings File Is not applied to Root Elements

- moxy/eclipselink.moxy.test/resource/org/eclipse/persistence/testing/jaxb/beanvalidation/sgen_xjc/rich_schema.xsd
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/beanvalidation/BeanValidationBindingsTestCase.java
- moxy/org.eclipse.persistence.moxy/src/org/eclipse/persistence/jaxb/plugins/BeanValidationPlugin.java
Fix for the bug 543036 and extended bean validation test.
Before this fix MOXy xjc extension in _BeanValidationPlugin.java_ enabled by _-XBeanVal_ switch generated unnecessary `@NotNull` annotation.
> Bug 543036 – <xsd:simpleType> generates unnecessary NotNull annotation

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/oxm/record/XMLReaderAdapter.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/oxm/record/json/JsonStructureReader.java
- moxy/eclipselink.moxy.test/resource/org/eclipse/persistence/testing/jaxb/json/namespaces/purchase_order.json
- moxy/eclipselink.moxy.test/resource/org/eclipse/persistence/testing/jaxb/json/namespaces/purchase_order.xml
- moxy/eclipselink.moxy.test/resource/org/eclipse/persistence/testing/jaxb/json/namespaces/purchase_order.xsd
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/json/JSONTestSuite.java
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/json/namespaces/NamespaceOnXMLOnlyTestCases.java
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/json/namespaces/model/ObjectFactory.java
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/json/namespaces/model/PurchaseOrderType.java
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/json/namespaces/model/USAddress.java
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/json/namespaces/model/package-info.java
Bug 543063 - JSON cannot be validated against XSD schema when uses namespaces
Fix for the bug 543063 and unit test test.
Before this fix MOXy threw error in case of conversion between JSON and XML, when XML schema validation was used there and XML namespaces was there.
Patch comes from https://bugs.eclipse.org/bugs/attachment.cgi?id=277013
Signed-off-by: Radek Felcman radek.felcman@oracle.com
(cherry picked from commit d5596e9)
> Bug 543063 - JSON cannot be validated against XSD schema when uses namespaces

- antbuild.properties
- antbuild.xml
- moxy/bin/jaxb-compiler.cmd
- moxy/bin/jaxb-compiler.sh
Bug 543339 - jaxb-compiler.(cmd|sh) script error in Java 9 and higher
This is fix for jaxb-compiler.(cmd|sh) script. After this fix will be possible to call this script in Java 8,9,10,11 (before only Java 8).
There is some change in dependencies. _jakarta.activation.jar_ is added there (due Java 11).
> Bug 543339 - jaxb-compiler.(cmd|sh) script error in Java 9 and higher

- moxy/eclipselink.moxy.test/antbuild.properties
- moxy/eclipselink.moxy.test/antbuild.xml
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/osgi/OSGITestHelper.java
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/osgi/OSGiBundleTest.java
ASM version parameter used in OSGi test now should be passed as a Ant/Maven parameter (system property). Before this patch ASM version was hard coded in source file _OSGiBundleTest.java_  => every ASM update required to update this test.
> [Non bug] OSGi tests - ASM version parameter

- utils/eclipselink.dbws.builder.test.oracle/etc/dbsetup_alltests.sql
Bug 540203 - Wrong characters in SQL script dbsetup_alltests.sql
This fix rewrites string concatenation expressions with "||" operator to SQL function CONCAT(…).
See https://bugs.eclipse.org/bugs/show_bug.cgi?id=540203
> Bug 540203 - Wrong characters in SQL script dbsetup_alltests.sql

- features/antbuild.xml
Bug 545221 - org.eclipse.persistence.moxy removed from EclipseLink update site after 2.7.3 ?
P2 site generation fails with eclipse-SDK-4.8M7. After upgrade to eclipse-SDK-4.10 it is OK.
> Bug 545221 - org.eclipse.persistence.moxy removed from EclipseLink update site after 2.7.3

- utils/eclipselink.dbws.builder.test/src/dbws/testing/simplesp/SimpleSPTestSuite.java
Bug 534935 - Wrong SQL date format in Unit test dbws.testing.simplesp.SimpleSPTestSuite
Modification of date value.
See https://bugs.eclipse.org/bugs/show_bug.cgi?id=534935
> Bug 534935 - Wrong SQL date format in Unit test dbws.testing.simplesp.SimpleSPTestSuite

- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/framework/LoadBuildSummary.java
- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/framework/PerformanceComparisonTestResult.java
- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/framework/SessionEventTracker.java
- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/framework/TogglingFastTableCreator.java
- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/framework/UniversalSessionTestAdapter.java
- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/tests/performance/emulateddb/EmulatedConnection.java
- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/tests/performance/emulateddb/EmulatedDriver.java
- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/tests/performance/emulateddb/EmulatedResultSet.java
- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/tests/performance/emulateddb/EmulatedResultSetMetaData.java
- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/tests/performance/emulateddb/EmulatedStatement.java
- foundation/eclipselink.core.test/src/org/eclipse/persistence/tools/beans/MessageDialog.java
Fix javadoc errors in Core Test Framework classes.
Modified classes are part of Core Test Framework in Maven version in the main scope.
This fix removes build blockers for "oss-release" profile.
Mainly it is about Javadoc comments, but in org/eclipse/persistence/testing/tests/performance/emulateddb/Emulated*.java classes are some required method signature (add ` throws SQLException {`) changes.
> Fix javadoc errors in Core Test Framework classes.

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/config/PersistenceUnitProperties.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/config/QueryHints.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/descriptors/DescriptorQueryManager.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/databaseaccess/DatabasePlatform.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/sessions/PropertiesHandler.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/OraclePlatform.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/queries/DatabaseQuery.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/queries/ObjectLevelReadQuery.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/sessions/factories/ProjectClassGenerator.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/query/TestQueryHints.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/query/TestQueryProperties.java
- jpa/eclipselink.jpa.test/resource/eclipselink-advanced-field-access-model/osgi/persistence.xml
- jpa/eclipselink.jpa.test/resource/eclipselink-advanced-field-access-model/persistence.xml
- jpa/eclipselink.jpa.test/resource/eclipselink-advanced-field-access-model/server/persistence.xml
- jpa/eclipselink.jpa.test/resource/eclipselink-advanced-field-access-model/spring/persistence.xml
- jpa/eclipselink.jpa.test/resource/eclipselink-annotation-model/osgi/persistence.xml
- jpa/eclipselink.jpa.test/resource/eclipselink-annotation-model/persistence.xml
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/models/jpa/advanced/Employee.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/models/jpa/composite/advanced/member_2/Employee.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa/advanced/EntityManagerJUnitTestSuite.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa/advanced/PessimisticLockingExtendedScopeTestSuite.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa/composite/advanced/EntityManagerJUnitTestSuite.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa/fieldaccess/advanced/EntityManagerJUnitTestSuite.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa/jpql/AdvancedQueryTestSuite.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa/jpql/JUnitJPQLComplexTestSuite.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/QueryHintsHandler.java
for #402
I was taking a look at the merged requests and I don't think it actually fixed the issue. The JPA spec clearly says that the value you provide to `javax.persistence.lock.timeout` & `javax.persistence.query.timeout` is in milliseconds, but #74 and https://bugs.eclipse.org/bugs/show_bug.cgi?id=456067 elected to just set the default as seconds. I had set the default to SECONDS in 456067 because I didnt want to change behavior, but I feel like this was not correct. The value should be provided in MILLISECONDS and this is what 533724 was opened to address as well.
Also, I quickly tested QUERY_TIMEOUT and it didn't seem to work (the timeout was always set as 0)! I noticed that this property didnt unprepare the query. After fixing that, QUERY_TIMEOUT started working as expected. I added …
> [master] Bug 533724: Set the default to MILLISECONDS

- foundation/org.eclipse.persistence.core/resource/org/eclipse/persistence/internal/helper/VendorNameToPlatformMapping.properties
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/Oracle10Platform.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/Oracle18Platform.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/Oracle8Platform.java
- foundation/org.eclipse.persistence.oracle/src/org/eclipse/persistence/platform/database/oracle/Oracle18Platform.java
- jpa/eclipselink.jpa.test.jse/antbuild.xml
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/oraclefeatures/OracleLOBLocatorSessionCustomizer.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/oraclefeatures/TestOracleLOBLocatorFeature.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/oraclefeatures/model/OracleLobEntity.java
Porting the LOB Locator capabilities from the Oracle platform extensions project to the core Oracle platform (using reflection).  Preserving the original behavior where this is disabled in versions 11+.  In addition, adding a database platform for Oracle 18.
Signed-off-by: Joe Grassel <jgrassel@us.ibm.com>
> [master] Bug 547023 - Add LOB Locator support to core Oracle platform (master)

- foundation/org.eclipse.persistence.core/resource/org/eclipse/persistence/internal/helper/VendorNameToPlatformMapping.properties
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/Oracle10Platform.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/Oracle18Platform.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/Oracle8Platform.java
- foundation/org.eclipse.persistence.oracle/src/org/eclipse/persistence/platform/database/oracle/Oracle18Platform.java
- jpa/eclipselink.jpa.test.jse/antbuild.xml
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/oraclefeatures/OracleLOBLocatorSessionCustomizer.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/oraclefeatures/TestOracleLOBLocatorFeature.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/oraclefeatures/model/OracleLobEntity.java
Porting the LOB Locator capabilities from the Oracle platform extensions project to the core Oracle platform (using reflection). Preserving the original behavior where this is disabled in versions 11+. In addition, adding a database platform for Oracle 18.
Signed-off-by: Joe Grassel jgrassel@us.ibm.com
> [2.7] Bug 547023 - Add LOB Locator support to core Oracle platform

- foundation/org.eclipse.persistence.core/resource/org/eclipse/persistence/internal/helper/VendorNameToPlatformMapping.properties
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/Oracle10Platform.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/Oracle18Platform.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/Oracle8Platform.java
- foundation/org.eclipse.persistence.oracle/src/org/eclipse/persistence/platform/database/oracle/Oracle18Platform.java
- jpa/eclipselink.jpa.test.jse/antbuild.xml
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/oraclefeatures/OracleLOBLocatorSessionCustomizer.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/oraclefeatures/TestOracleLOBLocatorFeature.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/oraclefeatures/model/OracleLobEntity.java
Porting the LOB Locator capabilities from the Oracle platform extensions project to the core Oracle platform (using reflection). Preserving the original behavior where this is disabled in versions 11+. In addition, adding a database platform for Oracle 18.
Signed-off-by: Joe Grassel jgrassel@us.ibm.com
> [2.6_WAS] Bug 547023 - Add LOB Locator support to core Oracle platform 

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/Oracle8Platform.java
- foundation/org.eclipse.persistence.oracle/src/org/eclipse/persistence/platform/database/oracle/Oracle8Platform.java
The bugfix for 547023 used '>' in javadoc in the new Oracle8 platform, which causes problems in javadoc generation. Pull request to fix this.
> Fix erronous Javadoc update from bug 547023

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/config/PersistenceUnitProperties.java
While trying to get the nightly builds for the 2.6_WAS branch back to green, noticed the following Javadoc error (which isn't involved in any of my recent changes):
```
[javadoc] /jobs/genie.eclipselink/eclipselink-nightly-2.6_WAS/workspace/foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/config/PersistenceUnitProperties.java:1039: error: reference not found
[javadoc]      * @see org.eclipse.persistence.config.PersistenceUnitProperties.JDBC_BIND_PARAMETERS
[javadoc]             ^
[javadoc] 1 error
[javadoc] 100 warnings
```
Updating the 2.6_WAS javadoc link to match what is in master
> [2.6_WAS] Fix persistence unit properties javadoc

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/Oracle8Platform.java
The bugfix for 547023 used '>' in javadoc in the new Oracle8 platform, which causes problems in javadoc generation.  Pull request to fix this.
> [master] Fix erronous Javadoc update from bug 547023

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/Oracle8Platform.java
The bugfix for 547023 used '>' in javadoc in the new Oracle8 platform, which causes problems in javadoc generation. Pull request to fix this.
> [2.7] Fix erronous Javadoc update from bug 547023

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/databaseaccess/DatabasePlatform.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa/advanced/AdvancedJPAJunitTest.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa/fieldaccess/advanced/AdvancedJPAJunitTest.java
Bug 547328 - JPA NamedStoredProcedure call getOutputParameterValue class cast exception
This is fix for a SQL BIGINT <-> java.lang.Long (long) mapping during stored procedures/functions call. 
This is fix for unit tests too.
Before this fix SQL BIGINT was mapped to java.lang.Integer (int).
This fix has affection to stored procedures out parameters and stored function return based on BIGINT data type.
JDBC Specification (4.3, 3.0) recommends map JDBC Type: BIGINT <-> Java Type: long
Scope of BIGINT in most DBs is same a Java long see:
https://docs.oracle.com/javase/specs/jls/se11/html/jls-4.html#jls-4.2.1
https://dev.mysql.com/doc/refman/8.0/en/integer-types.html
https://docs.microsoft.com/en-us/sql/t-sql/data-types/int-bigint-smallint-and-tinyint-transact-sql?view=sql-server-2017 …
> Bug 547328 - JPA NamedStoredProcedure call getOutputParameterValue class cast exception

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/logging/LogCategory.java
This would fix `IllegalArgumentException: Unknown logging category name.` on startup when `org.eclipse.persistence.logging.slf4j.SLF4JLogger` is selected as a logger.
> Bug 521424: Add MOXY to logger categories

- foundation/eclipselink.extension.oracle.test/antbuild.xml
Fix for some missing dependencies.
> eclipselink.extension.oracle.test build error fix - 2.7 only

- foundation/org.eclipse.persistence.core/core.iml
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/localization/i18n/JAXBLocalizationResource.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/localization/i18n/TraceLocalizationResource.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/oxm/XMLMarshaller.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/oxm/XMLUnmarshaller.java
- moxy/eclipselink.moxy.test/moxy.test.iml
- moxy/org.eclipse.persistence.moxy/src/org/eclipse/persistence/jaxb/JAXBContext.java
- moxy/org.eclipse.persistence.moxy/src/org/eclipse/persistence/jaxb/JAXBContextProperties.java
- moxy/org.eclipse.persistence.moxy/src/org/eclipse/persistence/jaxb/JAXBMarshaller.java
- moxy/org.eclipse.persistence.moxy/src/org/eclipse/persistence/jaxb/JAXBUnmarshaller.java
- moxy/org.eclipse.persistence.moxy/src/org/eclipse/persistence/jaxb/MOXySystemProperties.java
- moxy/org.eclipse.persistence.moxy/src/org/eclipse/persistence/jaxb/MarshallerProperties.java
- moxy/org.eclipse.persistence.moxy/src/org/eclipse/persistence/jaxb/UnmarshallerProperties.java
- moxy/org.eclipse.persistence.moxy/src/org/eclipse/persistence/jaxb/compiler/MappingsGenerator.java
- moxy/org.eclipse.persistence.moxy/src/org/eclipse/persistence/jaxb/rs/MOXyJsonProvider.java
This is MOXy improvement of logging system.
After this path MOXy can log info about different events related with marshalling/unmarshalling like:
* Set JAXBContext/marshaller/unmarshaller properties (name/value)
* Start marshalling/unmarshalling
* Mappings generation
* List of mappings
* Payload log (content of entities - output depends on `toString()` implementation in POJO)
Logging could be controlled by system properties like
`... -Declipselink.moxy.logging.payload=true -Declipselink.moxy.logging.level=FINE`
or JAXBContext/marshaller/unmarshaller properties like
`props.put(JAXBContextProperties.MOXY_LOG_PAYLOAD, true);`
`props.put(JAXBContextProperties.MOXY_LOGGING_LEVEL, "FINE");`
Payload log messages are produced only when:
`eclipselink.moxy.logging.payload=true && …
> [Non Bug] MOXy logging improvement

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/exceptions/JSONException.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/exceptions/i18n/JSONExceptionResource.java
- moxy/org.eclipse.persistence.moxy/src/org/eclipse/persistence/jaxb/rs/MOXyJsonProvider.java
Bug 545779 - NullPointerException when MoxyJsonProvider reads a JSONArray of primitives. for example "[1]"
Fix for this bug. This exception handing initial implementation for JSON related errors. 
> Bug 545779 - NullPointerException when MoxyJsonProvider reads a JSONArray of primitives. for example "[1]"

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/exceptions/JSONException.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/exceptions/i18n/JSONExceptionResource.java
- moxy/org.eclipse.persistence.moxy/src/org/eclipse/persistence/jaxb/rs/MOXyJsonProvider.java
…rray of primitives. for example "[1]" (#418)
* Bug 545779 - NullPointerException when MoxyJsonProvider reads a JSONArray of primitives. for example "[1]"
Fix for this bug. This exception handing initial implementation for JSON related errors.
(cherry picked from commit 60d9fef07edd9f933a0318684fdbc9743d341812)
> Bug 545779 - NullPointerException when MoxyJsonProvider reads a JSONArray of primitives. for example "[1]" (backport from master#418)

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/mappings/DirectToFieldMapping.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/TestUnidirectionalOneToMany.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/model/CommentC.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/model/CommentD.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/model/ComplexIdC.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/model/ComplexIdD.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/model/PostC.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/model/PostD.java
for #233 
The original 391279 did not account for the usecase of an existing foreign key mapping on the owning side and instead expected the FK would be added by the @JoinColumn. This results in an exception similar to this:
```
Execute query InsertObjectQuery(model.CommentC@378deffb)
INSERT INTO COMMENTC (COMPLEXID_C_A, CONTENT, COMPLEXID_C_A, TYPE) VALUES (?, ?, ?, ?)
Internal Exception: java.sql.SQLSyntaxErrorException: Column name 'COMPLEXID_C_A' appears more than once times in the column list of an INSERT statement. 
```
The issue is due to the use of `ObjectBuilder.buildRow(AbstractRecord databaseRow, Object object, AbstractSession session, WriteType writeType)` in `OneToManyMapping`. This method calls `DatabaseMapping.writeFromObjectIntoRow(Object object, AbstractRecord row, …
> [master] Bug 391279: Fix usecase with existing FK mapping

- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/basic/TestEntityManagerInterface.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/EntityManagerImpl.java
Bug 547173 - EntityManager.unwrap(Connection.class) returns null
Fixes https://bugs.eclipse.org/bugs/show_bug.cgi?id=547173 for Master branch
> [Master] Bug 547173 - EntityManager.unwrap(Connection.class) returns null

- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/basic/TestEntityManagerInterface.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/EntityManagerImpl.java
Bug 547173 - EntityManager.unwrap(Connection.class) returns null
Fixes https://bugs.eclipse.org/bugs/show_bug.cgi?id=547173 for 2.7 branch
> [2.7] Bug 547173 - EntityManager.unwrap(Connection.class) returns null

- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/basic/TestEntityManagerInterface.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/EntityManagerImpl.java
Bug 547173 - EntityManager.unwrap(Connection.class) returns null
Fixes https://bugs.eclipse.org/bugs/show_bug.cgi?id=547173 for 2.6_WAS branch
> [2.6_WAS] Bug 547173 - EntityManager.unwrap(Connection.class) returns null

- .travis.yml
- dbws/eclipselink.dbws.test.oracle/antbuild.xml
- dbws/eclipselink.dbws.test/antbuild.xml
- foundation/eclipselink.core.test/antbuild.xml
- foundation/eclipselink.extension.corba.test/antbuild.xml
- foundation/eclipselink.extension.oracle.spatial.test/antbuild.xml
- foundation/eclipselink.extension.oracle.test/antbuild.xml
- jpa/eclipselink.jpa.test/antbuild.xml
- moxy/eclipselink.moxy.test/antbuild.xml
This is another version of Travis-CI build script.
It reflects following changes in Travis CI environment:
1. Switch to Ubuntu Xenial (see **dist** _.travis.yml_)
2. Different MySQL server startup process (see **services** part in _.travis.yml_)
3. Switch to Open JDK 8, 11 from Oracle JDK due license changes (see **jdk** part in _.travis.yml_)
There is some fix in _antbuild.xml_ files for Open JDK 8. Open JDK 8 installation in Travis (Ubuntu-Xenial) doesn't contains _$JAVA_HOME/release_ file used by Ant build files to detect Java/JDK version. So build process applied incorrect javac release parameter => error message "[javac] javac: invalid target release: 9". In case of missing _$JAVA_HOME/release_ file "1.8.0" value is applied to `test.junit.jdk.JAVA_VERSION` Ant property.
> Travis switch to Open JDK and Ubuntu Xenial

- .travis.yml
- foundation/eclipselink.core.test/antbuild.xml
- moxy/eclipselink.moxy.test/antbuild.xml
Travis switch to Open JDK and Ubuntu Xenial.
Due license troubles JDK switch from OracleJDK to OpenJDK.
There is some fix in antbuild.xml files for Open JDK 8. Open JDK 8 installation in Travis (Ubuntu-Xenial) doesn't contains $JAVA_HOME/release file used by Ant build files to detect Java/JDK version.
> [Non Bug] Travis JDK switch (Oracle JDK -> Open JDK) 2.7 branch

- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/sequence/TestTableQualifier.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/sequence/model/EntityWithSchema.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa/advanced/AdvancedJunitTest.java
Running "test-lrg21" on 2.6_WAS results in the following failure:
```
[junit] Internal Exception: java.sql.SQLSyntaxErrorException: ORA-01918: user 'CUSTOM_SCHEMA' does not exist
[junit] 
[junit] Error Code: 1918
[junit] Call: CREATE TABLE CUSTOM_SCHEMA.CUSTOM_SEQUENCE (SEQ_NAME VARCHAR2(50) NOT NULL, SEQ_VALUE NUMBER(38) NULL, PRIMARY KEY (SEQ_NAME))
[junit] Query: DataModifyQuery(sql="CREATE TABLE CUSTOM_SCHEMA.CUSTOM_SEQUENCE (SEQ_NAME VARCHAR2(50) NOT NULL, SEQ_VALUE NUMBER(38) NULL, PRIMARY KEY (SEQ_NAME))")
```
This issue doesnt occur on 2.7 branch due to this commit: https://github.com/eclipse-ee4j/eclipselink/commit/ec9aac7f48f3b9b9e0b42be459b80464f6ed9f32
So, this is a port of that test bug fix to the 2.6_WAS branch. 
> [2.6_WAS][testBug] move table qualifier test to a better place

- antbuild.properties
- buildsystem/compdeps/pom.xml
- foundation/org.eclipse.persistence.extension/pom.xml
- foundation/org.eclipse.persistence.extension/src/org/eclipse/persistence/internal/sessions/coordination/jgroups/JGroupsRemoteConnection.java
- uploadToNexus.xml
Add support for JGroups ver. 4.x in session coordination mechanism.
That will allow to use newest `KUBE_PING` protocols and resolve some issues with Openshift 4 based replication (see https://github.com/eclipse/che/issues/13607 for example)
Original issue: https://bugs.eclipse.org/bugs/show_bug.cgi?id=531910
> [2.7] Bug#531910 Add support for JGroups ver. 4.x in session coordination

- jpa/eclipselink.jpa.wdf.test/src/org/eclipse/persistence/testing/tests/wdf/jpa1/entitymanager/TestClear.java
This prevents collision with other tests executed against same DB table.
There was collision at the DB row level.
Entities with same id "...new Department(1..." was used in multiple tests above same DB table.
This error happened at new ci-staging.eclipse.org build server.
For example there: https://ci-staging.eclipse.org/eclipselink/view/New%20Jobs/job/eclipselink-nightly-master/4/console
> JPA WDF Tests fix

- jpa/eclipselink.jpa.wdf.test/src/org/eclipse/persistence/testing/tests/wdf/jpa1/entitymanager/TestClear.java
This prevents collision with other tests executed against same DB table.
There was collision at the DB row level.
Entities with same id "...new Department(1..." was used in multiple tests above same DB table.
This error happened at new ci-staging.eclipse.org build server.
For example there: https://ci-staging.eclipse.org/eclipselink/job/eclipselink-nightly-master/4/console
> [2.7] JPA WDF Tests fix

- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/tests/jpql/JPQLSimpleTestSuite.java
- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/tests/jpql/SimpleConcatTestWithConstantsLiteralFirst.java
- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/tests/jpql/SimpleConcatTestWithConstantsLiteralSecond.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/queries/ExpressionQueryMechanism.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa/criteria/JUnitCriteriaSimpleTestSuiteBase.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa/jpql/JUnitJPQLSimpleTestSuite.java
Bug 546533 - QueryKeyExpression.printSQL writes no value
See: https://bugs.eclipse.org/bugs/show_bug.cgi?id=546533
Bug fix + unit tests
> Bug 546533 - QueryKeyExpression.printSQL writes no value

- autobuild.xml
- etc/jenkins/antbuild.xml
- etc/jenkins/build.groovy
- etc/jenkins/build.sh
- etc/jenkins/init.sh
- etc/jenkins/noSign.sh
- etc/jenkins/pom.xml
- etc/jenkins/promote.groovy
- etc/jenkins/promote.sh
- etc/jenkins/promote_init.sh
- etc/jenkins/publish_nightly.sh
- etc/jenkins/setEnvironment.sh
- etc/jenkins/sign.sh
- pom.xml.template
- uploadToNexus.xml
This is patch related with migration to new cloud based Eclipse.org build infrastructure and
" The end of an era: shell access".
There are Jenkins pipelines 
This jobs contains two pipelines:
1. Build part - _build.groovy, init.sh, build.sh, publish_nightly.sh ..._
Build project, execute test, publish to nightly builds.
These files are common for nightly and ci builds. There is parameter CONTINUOUS_BUILD specified (true - continuous build, false - full nightly build)  
2. Promotion part - _promote.groovy, promote_init.sh, promote.sh ..._
Publish Maven artifacts to the Maven repository (OSS staging). This is Jenkins replacement of _promote.sh_ called in shell available at build.eclipse.org infrastructure.
Due this part, there are modifications in some current files in the project root. …
> Jenkins jobs for Ant build

- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/tests/jpql/JPQLSimpleTestSuite.java
- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/tests/jpql/SimpleConcatTestWithConstantsLiteralFirst.java
- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/tests/jpql/SimpleConcatTestWithConstantsLiteralSecond.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/queries/ExpressionQueryMechanism.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa/criteria/JUnitCriteriaSimpleTestSuiteBase.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa/jpql/JUnitJPQLSimpleTestSuite.java
Bug 546533 - QueryKeyExpression.printSQL writes no value
See: https://bugs.eclipse.org/bugs/show_bug.cgi?id=546533
Bug fix + unit tests
Signed-off-by: Radek Felcman radek.felcman@oracle.com
> [2.7] Bug 546533 - QueryKeyExpression.printSQL writes no value

- foundation/org.eclipse.persistence.core/core.iml
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/oxm/record/json/JsonStructureReader.java
- moxy/eclipselink.moxy.test/resource/org/eclipse/persistence/testing/jaxb/json/xmlvalue/personUnmarshalValueFirst.json
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/json/JSONTestSuite.java
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/json/xmlvalue/XMLValuePropValueFirstInJSONTestCases.java
Bug 501058 - Unmarshalling JSON with @XmlValue + @XmlAttribute(s) leaves value blank if value property is before attributes
Bug Fix + unit test.
> Bug 501058 - Unmarshalling JSON with @XmlValue + @XmlAttribute(s) leaves value blank if value property is before attributes

- etc/jenkins/build.groovy
Multiple Jenkins junit plugin calls due java.nio.channels.ClosedChannelException in new/cloud Eclipse.org build infrastructure if it's called once it leads into java.nio.channels.ClosedChannelException. Junit test results from target/reports/TESTS-TestSuites.xml due exception above can't be proceed. File size >60MB is too much.
> [2.7] Jenkins junit pipeline fix

- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/tests/jpql/SimpleConcatTestWithConstantsLiteralFirst.java
- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/tests/jpql/SimpleConcatTestWithConstantsLiteralSecond.java
Bug 546533 - QueryKeyExpression.printSQL writes no value 2.0 - Unit test fix
In the unit test were used double quotas character as wrapper for string literal.
It was functional against MySQL but was not in the Oracle DB.
Unused variable removal.
> [2.7] Bug 546533 - QueryKeyExpression.printSQL writes no value 2.0 - Unit test fix

- dbws/org.eclipse.persistence.dbws/.classpath
- foundation/org.eclipse.persistence.core/.classpath
- jpa/eclipselink.jpa.test.jse/.classpath
- jpa/eclipselink.jpa.test.jse/antbuild.xml
- jpa/eclipselink.jpars.test/.classpath
- jpa/org.eclipse.persistence.jpa/.classpath
- moxy/eclipselink.moxy.test/.classpath
- moxy/eclipselink.moxy.test/antbuild.properties
- moxy/org.eclipse.persistence.moxy/.classpath
- performance/eclipselink.perf.test/.classpath
- performance/eclipselink.perf.test/antbuild.properties
- sdo/eclipselink.sdo.test/antbuild.properties
- utils/eclipselink.dbws.builder.test.oracle/.classpath
- utils/eclipselink.utils.sigcompare/.classpath
- utils/org.eclipse.persistence.dbws.builder/antbuild.properties
Noticed that my changes to various .classpath and antbuild.xml files to point to the ASM 7.1 jar (PR #537) did not make it into the pull request.  Correcting the oversight with this PR.
> [2.6_WAS] Update .classpath and antbuild.xml files to reference ASM 7.1 jar.

- etc/jenkins/build.groovy
MOXy junit reports collection divided into smaller parts due remaining errors in Eclipse.org build infra.
> Jenkins jobs - JUnit test split into smaller parts

- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/tests/jpql/SimpleConcatTestWithConstantsLiteralFirst.java
- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/tests/jpql/SimpleConcatTestWithConstantsLiteralSecond.java
Bug 546533 - QueryKeyExpression.printSQL writes no value 2.0 - Unit test fix
In the unit test were used double quotas character as wrapper for string literal.
It was functional against MySQL but was not in the Oracle DB.
Unused variable removal.
> [master] Bug 546533 - QueryKeyExpression.printSQL writes no value 2.0 - Unit test fix

- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/tests/jpql/AggregateTest.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/queries/ReportQuery.java
This is fix for core tests of MIN/MAX expression. Before this fix, test return type
was database dependent but expected value in assertion java.lang.Integer.
In MySQL these tests correctly passed, but in the Oracle return type was BigDecimal.
This bug is related with EclipseLink core only. In JPA it returns expected data type.
> [2.7] Core MIN/MAX test failure on Oracle RDBMS fix

- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/tests/jpql/AggregateTest.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/queries/ReportQuery.java
This is fix for core test of MIN/MAX expression. Before this fix test return type
was database dependent but expected was java.lang.Integer.
In MySQL these tests correctly passed, but in the Oracle return type was BigDecimal.
This bug is related with EclipseLink core only. In JPA it returns expected data type.
> [master] Core MIN/MAX test failure on Oracle RDBMS fix

- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa/jpql/JUnitJPQLComplexAggregateTestSuite.java
[master] JPA MIN/MAX test failure on Oracle RDBMS fix
This is fix for JPA test of MIN/MAX expression. Before this fix test return type
was database dependent but expected was java.lang.Integer.
In MySQL these tests correctly passed, but in the Oracle return type was BigDecimal.
JPA test using there core methods to get expected value/results and this one has incorrect type.
JPA itself is OK.
Sorry I forgot to fix it in previous PR #558 
> [master] JPA MIN/MAX test failure on Oracle RDBMS fix

- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa/jpql/JUnitJPQLComplexAggregateTestSuite.java
[2.7] JPA MIN/MAX test failure on Oracle RDBMS fix
This is fix for JPA test of MIN/MAX expression. Before this fix test return type
was database dependent but expected was java.lang.Integer.
In MySQL these tests correctly passed, but in the Oracle return type was BigDecimal.
JPA test using there core methods to get expected value/results and this one has incorrect type.
JPA itself is OK.
Sorry I forgot to fix it in previous PR #557 
> [2.7] JPA MIN/MAX test failure on Oracle RDBMS fix

- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa/criteria/JUnitCriteriaSimpleTestSuiteBase.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa/jpql/JUnitJPQLSimpleTestSuite.java
[master] Bug 546533 - QueryKeyExpression.printSQL writes no value 3.0 - JPA Unit test fix
This is additional fix for JPA tests.
In the unit test were used double quotas character as wrapper for string literal.
It was functional against MySQL but was not in the Oracle DB.
Sorry I forgot to fix it in previous PR #550 
> [master] Bug 546533 - QueryKeyExpression.printSQL writes no value 3.0 - JPA Unit test fix

- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa/criteria/JUnitCriteriaSimpleTestSuiteBase.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa/jpql/JUnitJPQLSimpleTestSuite.java
[2.7] Bug 546533 - QueryKeyExpression.printSQL writes no value 3.0 - JPA Unit test fix
This is additional fix for JPA tests.
In the unit test were used double quotas character as wrapper for string literal.
It was functional against MySQL but was not in the Oracle DB.
Sorry I forgot to fix it in previous PR #548 .
> [2.7] Bug 546533 - QueryKeyExpression.printSQL writes no value 3.0 - JPA Unit test fix

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/databaseaccess/DatabasePlatform.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/models/jpa/datetime/DateTime.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/models/jpa/datetime/DateTimePopulator.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/models/jpa/datetime/DateTimeTableCreator.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa/datetime/NullBindingJUnitTestCase.java
Backport of #415 for eclipselink 2.7
> [2.7] Bug 546312 - Add missing mapping for java.time classes to DatabasePlatform

- etc/jenkins/promote.groovy
- etc/jenkins/publish_milestone.sh
- etc/jenkins/setEnvironment.sh
[2.7] Jenkins jobs - release promotion
This is fix to publish milestone releases (RC1, RC2....) and P2 update sites to Eclipse.org.
> [2.7] Jenkins jobs - release promotion

- etc/jenkins/promote.groovy
- etc/jenkins/publish_milestone.sh
- etc/jenkins/setEnvironment.sh
[2.7] Jenkins jobs - release promotion v 2.0
This is fix to publish milestone releases (RC1, RC2....) and P2 update sites to Eclipse.org.
> [2.7] Jenkins jobs - release promotion v 2.0

- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/tests/workbenchintegration/ProjectXMLStoredFunctionCallTest.java
[master] ProjectXMLStoredFunctionCallTest fix (test.core - Oracle12Platform)
In this test (ProjectXMLStoredFunctionCallTest) were wrong query result
types (`java.lang.Integer` instead of `java.lang.Long`).
Project/query definition is loaded in `setup()` method from MWIntegrationCustomSQLEmployeeProject.xml file.
See `<query name="StoredFunctionCallInNamedQuery" xsi:type="data-read-query">` from there.
Procedure arguments specified there are `java.lang.Long`.
This test is executed only on `org.eclipse.persistence.platform.database.oracle.Oracle12Platform`.
> [master] ProjectXMLStoredFunctionCallTest fix (test.core - Oracle12Platform)

- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/tests/workbenchintegration/ProjectXMLStoredFunctionCallTest.java
[2.7] ProjectXMLStoredFunctionCallTest fix (test.core - Oracle12Platform)
In this test (ProjectXMLStoredFunctionCallTest) were wrong query result
types (`java.lang.Integer` instead of `java.lang.Long`).
Project/query definition is loaded in `setup()` method from MWIntegrationCustomSQLEmployeeProject.xml file.
See `<query name="StoredFunctionCallInNamedQuery" xsi:type="data-read-query">` from there.
Procedure arguments specified there are `java.lang.Long`.
This test is executed only on `org.eclipse.persistence.platform.database.oracle.Oracle12Platform`.
> [2.7] ProjectXMLStoredFunctionCallTest fix (test.core - Oracle12Platform)

- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/tests/junit/identitymaps/CacheIdTest.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/identitymaps/CacheId.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/identitymaps/CacheIdComparator.java
Hi
I would like to post a fix for bug #482. The fix is basically an implementation of `CacheId.compareTo()` which supports char, byte or Object arrays in primary keys. The implementation was moved to `CacheIdComparator` for better encapsulation. 
Besides array support, I've changed current implementation for objects which don't implement `Comparable`. Current approach returns `0` when an exception is thrown during comparison. This create inconsistency with `equals()` method. For example: `new Object().compareTo(new Object())` returns `0`,
but new `Object().equals(new Object())` returns `false`. I've switch to compareTo based on hashCodes
which should give equals() consistency and stable results.
Signed-off-by: Michal Stochmialek <uek@kmd.dk>
> #482 - fix for CacheId comparision with BINARY arrays

- buildsystem/compdeps/pom.xml
Jakarta EE 8 already contained JAX-RS 2.1.6, not 2.1.4
> Using JAX-RS 2.1.6

- autobuild.xml
- etc/jenkins/publish_nightly.sh
[2.7] Jenkins jobs - publish nightly builds (bundles, p2site, test results)
This is fix to publish EclipseLink bundles (eclipselink.jar, eclipselink.zip....),
p2site, test results into right directories to easily copy them to Eclipse.org download server.
> [2.7] Jenkins jobs - publish nightly builds (bundles, p2site, test results)

- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa/jpql/AdvancedQueryTestSuite.java
[2.7] JPA test fix for PESSIMISTIC_READ, PESSIMISTIC_WRITE testing - Oracle platform
This is fix for JPA tests for PESSIMISTIC_READ, PESSIMISTIC_WRITE locking.
Before this fix testing methods `testQueryPESSIMISTIC_READLock`,
`testQueryPESSIMISTIC_WRITELock`, `testLockWithSecondaryTable` from
`org.eclipse.persistence.testing.tests.jpa.jpql.AdvancedQueryTestSuite`
loaded lock timeout from persistence.xml file. In this case test raised
`org.eclipse.persistence.exceptions.DatabaseException (internally
java.sql.SQLException: ORA-30006: resource busy; acquire with WAIT timeout expired)`
instead of expected `javax.persistence.PessimisticLockException` (SQL SELECT option `FOR UPDATE NOWAIT`).
> [2.7] JPA test fix for PESSIMISTIC_READ, PESSIMISTIC_WRITE testing - Oracle platform

- etc/jenkins/build.sh
Jenkins build fix - post Mavenize
There is unnecessary call of preparation scripts as a part of Jenkins build.
Before transformation into Maven there were some preparation scripts.
This call will break Jenkins build and must be removed.
> [master] Jenkins build fix - post Mavenize

- bundles/distribution/pom.xml
Double-quoted string does not work on windows because there are  '\\'  escape characters in {org.eclipse.persistence:org.eclipse.persistence.asm:jar}
> fix mavenize on windows,  groovy-maven-plugin.get-asm-bundle-version

- moxy/org.eclipse.persistence.moxy/src/main/java/org/eclipse/persistence/jaxb/compiler/SchemaGenerator.java
- moxy/org.eclipse.persistence.moxy/src/test/java/org/eclipse/persistence/testing/jaxb/schemagen/SchemaGenTestSuite.java
- moxy/org.eclipse.persistence.moxy/src/test/java/org/eclipse/persistence/testing/jaxb/schemagen/inheritance/ChildEntity.java
- moxy/org.eclipse.persistence.moxy/src/test/java/org/eclipse/persistence/testing/jaxb/schemagen/inheritance/InheritanceWithXMLValueTestCases.java
- moxy/org.eclipse.persistence.moxy/src/test/java/org/eclipse/persistence/testing/jaxb/schemagen/inheritance/ParentEntity.java
- moxy/org.eclipse.persistence.moxy/src/test/resources/org/eclipse/persistence/testing/jaxb/schemagen/inheritance/inheritance_xml_value.xsd
This is for for bug #591. MOXy generates invalid XSD if @XmlValue is in parent class.
There is fix and unit test too.
> [master] Fix for #591 - MOXy - invalid XSD generated for @XmlValue from parent class

- etc/jenkins/publish_release.sh
[2.7] Jenkins build - update/P2 site release fix
Before this fix update/P2 site wasn't published during EclipseLink release (final release)
to Eclipse.org download site. It generates zip archive too to make P2 site available for
download (offline usage) from https://download.eclipse.org/rt/eclipselink/updates/ .
This is fix for bug 545221 ( https://bugs.eclipse.org/bugs/show_bug.cgi?id=545221 ) too.
> [2.7] Jenkins build - update/P2 site release fix (bug 545221)

- moxy/org.eclipse.persistence.moxy/src/main/java/org/eclipse/persistence/jaxb/JAXBContext.java
- moxy/org.eclipse.persistence.moxy/src/main/java/org/eclipse/persistence/jaxb/JAXBMarshaller.java
- moxy/org.eclipse.persistence.moxy/src/main/java/org/eclipse/persistence/jaxb/JAXBUnmarshaller.java
This is fix for bug #614, when JAXBContext property value is null, MOXy logging
will throw NPE instead of "Setting JAXBContext property (name/value): ....." message.
There is also fix if (Un)MarshallerProperty MOXY_LOGGING_LEVEL is set as
a `java.lang.String` instead of value from `org.eclipse.persistence.logging.LogLevel` enum.
> [master] MOXy logging should throw NPE - bug fix #614

- jpa/eclipselink.jpars.test/jpars.test.iml
- moxy/org.eclipse.persistence.moxy/src/org/eclipse/persistence/jaxb/JAXBContext.java
- moxy/org.eclipse.persistence.moxy/src/org/eclipse/persistence/jaxb/JAXBMarshaller.java
- moxy/org.eclipse.persistence.moxy/src/org/eclipse/persistence/jaxb/JAXBUnmarshaller.java
[2.7] MOXy logging should throw NPE - fix (backport from master)
This is fix for bug, when JAXBContext property value is null, MOXy logging
will throw NPE instead of "Setting JAXBContext property (name/value): ....." message.
There is also fix if (Un)MarshallerProperty MOXY_LOGGING_LEVEL is set as
a `java.lang.String` instead of value from `org.eclipse.persistence.logging.LogLevel` enum.
> [2.7] MOXy logging should throw NPE - fix (backport from master)

- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/deployment/PersistenceUnitProcessor.java
[2.7 - backport from master] Fix for #494 - JPA Weave: File handle leak: persistence.xml not properly closed
> [2.7 - backport from master] Fix for #494 - JPA Weave: File handle leak: persistence.xml not properly closed

- moxy/eclipselink.moxy.test/resource/org/eclipse/persistence/testing/jaxb/schemagen/inheritance/inheritance_xml_value.xsd
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/schemagen/SchemaGenTestSuite.java
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/schemagen/inheritance/ChildEntity.java
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/schemagen/inheritance/InheritanceWithXMLValueTestCases.java
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/schemagen/inheritance/ParentEntity.java
- moxy/org.eclipse.persistence.moxy/src/org/eclipse/persistence/jaxb/compiler/SchemaGenerator.java
[2.7] Fix for #591 - MOXy - invalid XSD generated for @XmlValue from parent class
This is for for bug #591. MOXy generates invalid XSD if @XmlValue is in parent class.
There is fix and unit test too.
> [2.7] Fix for #591 - MOXy - invalid XSD generated for @XmlValue from parent class

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/databaseaccess/DatabaseCall.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/databaseaccess/DatasourceCall.java
- jpa/eclipselink.jpa.test/pom.xml
- jpa/eclipselink.jpa.test/src/it/java/org/eclipse/persistence/testing/models/jpa21/advanced/Employee.java
- jpa/eclipselink.jpa.test/src/it/java/org/eclipse/persistence/testing/models/jpa22/advanced/Employee.java
- jpa/eclipselink.jpa.test/src/it/java/org/eclipse/persistence/testing/tests/jpa21/advanced/StoredProcedureQueryTestSuite.java
- jpa/eclipselink.jpa.test/src/it/java/org/eclipse/persistence/testing/tests/jpa22/advanced/AnnotationsTestSuite.java
- jpa/eclipselink.jpa.test/src/it/java/org/eclipse/persistence/testing/tests/jpa22/advanced/StoredProcedureQueryTestSuite.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/StoredProcedureQueryImpl.java
[master] Bug #618: Oracle positional parameters with ParameterMode.REF_CURSOR out parameter
This is fix for bug #618 with additional unit tests. There is small refactoring
(renaming) in test method names and NamedStoredProcedureQuery annotation names.
> [master] Bug #618: Oracle positional parameters with ParameterMode.REF_CURSOR out parameter

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/mappings/OneToManyMapping.java
This is fix for bug #626 - NullPointerException at Class OneToManyMapping on concurrent access
Tested locally against Oracle 12c too (core, jpa LRG)
> [master] Bug #626 - NullPointerException at Class OneToManyMapping on concurrent access

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/core/queries/CoreAttributeGroup.java
- jpa/eclipselink.jpa.test/src/it/java/org/eclipse/persistence/testing/tests/jpa/fetchgroups/SimpleSerializeFetchGroupTests.java
[master] Bug 415779 - JpaEntityManager.copy doesn't always preserve object graph
This is partial fix for bug 415779 with unit test. There is fix in CoreAttributeGroup.toString() method.
Before this fix this method can fail if object graph is copied by JpaEntityManager.copy.
> [master] Bug 415779 - JpaEntityManager.copy doesn't always preserve object graph

- .travis.yml
[2.7] Travis Maven configuration change
There is Maven ($M2_HOME) change due Travis environment upgrade.
Today (12-DEC-2019) Travis-CI upgraded Maven from 3.6.0 to 3.6.2.
This is fix for 2.7 branch only to catch up this environment change.
Without this fix 2.7 tests/builds against Travis-CI PR will fail.
> [2.7] Travis Maven configuration change

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/mappings/OneToManyMapping.java
[2.7] Bug #626 - NullPointerException at Class OneToManyMapping on concurrent access
backport from master
This is fix for bug #626 - NullPointerException at Class OneToManyMapping on concurrent access
> [2.7] Bug #626 - NullPointerException at Class OneToManyMapping on concurrent access

- .gitignore
Importing EclipseLink projects into Eclipse as "Existing Maven Projects" causes a bunch of .project/.settings/.classpath files to be generated. These files then show up as new files unstaged in Git. Updating the ignore so that we don't track these generated files on master
> [master] Update GIT ignore for Eclipse generated artifacts

- buildsystem/compdeps/pom.xml
- moxy/eclipselink.moxy.test/pom.xml
org.osgi is not upgraded to 6.0.0 due troubles with osgi.cmpn in MANIFEST.MF is following
```
Require-Capability: osgi.compile.time.only;filter:="(&(must.not.resolve=
*)(!(must.not.resolve=*)))",osgi.ee;filter:="(&(osgi.ee=JavaSE)(version
=1.5))"
```
slf4j is not upgraded to 2.0.0-alpha1 but only to 1.7.30 due ch.qos.logback 
ch.qos.logback is not upgraded to 1.3.0-alpha5 due troubles with
```
Provide-Capability: osgi.serviceloader;osgi.serviceloader="org.slf4j.s
pi.SLF4JServiceProvider"
Require-Capability: osgi.extender;filter:="(osgi.extender=osgi.service
loader.registrar)"
```
> [2.7] Dependencies upgrade

- buildsystem/mavenize/test.properties/el-test.mssql.properties
- pom.xml
This fix adds support for MS SQL Server.
After this one various tests can be executed against MS SQL server e.g.
`mvn verify -pl :org.eclipse.persistence.jpa.jse.test -Pmssql`
`mvn verify -pl :org.eclipse.persistence.core.test -Pmssql`
> [master] Maven build - MS SQL Server support

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/indirection/UnitOfWorkValueHolder.java
This is fix for bug #625 - NullPointerException QueryBasedValueHolder getValue(UnitOfWorkImpl uow) not thread safe
> [master] Bug #625 - NullPointerException QueryBasedValueHolder getValue(UnitOfWorkImpl uow) not thread safe

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/indirection/UnitOfWorkValueHolder.java
This is fix for bug #625 - NullPointerException QueryBasedValueHolder getValue(UnitOfWorkImpl uow) not thread safe.
Backport from master.
> [2.7] Bug #625 - NullPointerException QueryBasedValueHolder getValue(UnitOfWorkImpl uow) not thread safe

- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/moxy/unit/jaxb/compiler/SchemaGeneratorTestCase.java
- moxy/org.eclipse.persistence.moxy/src/org/eclipse/persistence/jaxb/javamodel/Helper.java
[2.7] BUG#558528 - SOAPBINDING ANNOTATION WITH SOAPBINDING.STYLE.RPC MAKES DEPLOYMENT IMPOSSIBLE
> [2.7] BUG#558528 - SOAPBINDING ANNOTATION WITH SOAPBINDING.STYLE.RPC MAKES DEPLOYMENT IMPOSSIBLE

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/databaseaccess/DatabaseCall.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/databaseaccess/DatabasePlatform.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/DB2Platform.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/DB2ZPlatform.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/oracle/plsql/PLSQLStoredProcedureCall.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/queries/StoredProcedureCall.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/jpql/TestComplexJPQL.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/storedproc/TestStoredProcedures.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa21/advanced/StoredProcedureQueryTestSuite.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/StoredProcedureQueryImpl.java
for #636 
Also, contains
for #648
While writing tests for this fix, I noticed that StoredProcedure OUT parameters don't work on DB2zPlatform. This is due to needing to call the DB2z CallableStatement API `getJccObjectAtName` instead of the JDBC API call. This was a change missing from Bug 543846.
So, I moved the java.sql.CallableStatement.getObject() calls from StoredProcedureQueryImpl to DatabasePlatform so that Platform classes can override this CallableStatement method. Currently, DB2zPlatform needs to override this to get OUT values, with named parameters. Other platforms way want to override this in the future.
I am making this change as part of THIS change so that the testing can be delivered for both.
> [2.6_WAS] Bug 558283: Missing parameter markers from DB2z Stored Procedures

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/databaseaccess/DatabaseCall.java
There small fix in Javadoc comments.
Before this fix following Maven command `mvn install -DskipTests -Poss-release` failed.
Line 1415 contained incorrect parameter name (index -> name).
See
https://ci.eclipse.org/eclipselink/view/Current%20Jobs/job/eclipselink-cb-master/48/
https://ci.eclipse.org/eclipselink/view/Current%20Jobs/job/eclipselink-nightly-master/76/
> Bug 558283: Missing parameter markers from DB2 Stored Procedures - Javadoc fix

- etc/jenkins/init.sh
- etc/jenkins/promote_init.sh
There is not possible directly to download Maven artifacts via http protocol now.
See https://ci.eclipse.org/eclipselink/view/Current%20Jobs/job/eclipselink-nightly-2.7/92/console
```
...
--2020-01-24 19:40:28--  http://repo1.maven.org/maven2/junit/junit/4.12/junit-4.12.jar
Resolving repo1.maven.org (repo1.maven.org)... 151.101.124.209
Connecting to repo1.maven.org (repo1.maven.org)|151.101.124.209|:80... connected.
HTTP request sent, awaiting response... 501 HTTPS Required
2020-01-24 19:40:28 ERROR 501: HTTPS Required.
...
```
This change switch all URLs used in the init*.sh (wget) scripts into https protocol.
> [2.7] EclipseLink - Jenkins pipeline (init fix)

- .travis.yml
It is required to switch into https protocol otherwise install phase (external dependencies download) in Travis-CI will fail.
> Travis-CI switch from http to https

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/PostgreSQLPlatform.java
This PR is to support below java.time types for PostgreSQL - 
1. LocalDate
2. LocalDateTime
3. LocalTime
4. OffsetDateTime
5. OffsetTime
Thus during schema creation, SchemaManager will pickup the right database field type via this fieldTypeMapping.
> Support java.time types for Postgres

- foundation/org.eclipse.persistence.corba/pom.xml
- foundation/org.eclipse.persistence.oracle.nosql/pom.xml
- jpa/eclipselink.jpa.spring.test/pom.xml
- jpa/eclipselink.jpa.wdf.test/pom.xml
- jpa/org.eclipse.persistence.jpars/pom.xml
This is fix for oracle profile in Maven build to add dependency to org.eclipse.persistence.oracle artifact/module.
Without this fix integration tests in the modified modules failed with ClassNotFoundException for oracle Maven profile and test property db.platform=org.eclipse.persistence.platform.database.oracle.Oracle12Platform.
> [master] Maven build - Oracle platform fix

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/config/PersistenceUnitProperties.java
PersistenceUnitProperties.QUERY_TIMEOUT Javadoc fix for #702 .
> [master] PersistenceUnitProperties.QUERY_TIMEOUT Javadoc fix.

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/PostgreSQLPlatform.java
This PR is to support below java.time types for PostgreSQL -
1. LocalDate
2. LocalDateTime
3. LocalTime
4. OffsetDateTime
5. OffsetTime
Thus during schema creation, SchemaManager will pickup the right database field type via this fieldTypeMapping.
> [2.7] Postgres java.time types

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/oxm/record/XMLStreamReaderReader.java
Before this fix MOXy produced incomplete error message in case of XML Schema validation failure during unmarshall operation, if schema validation was enabled and non-valid XML document used at the input.
E.G. Error message before fix
`Internal Exception: org.xml.sax.SAXParseException; cvc-complex-type.2.4.a: Invalid content was found starting with element ''. One of '{"http://myschema.com":elementOne}' is expected.]`
Error message after fix
`Internal Exception: org.xml.sax.SAXParseException; cvc-complex-type.2.4.a: Invalid content was found starting with element 'elementTwo'. One of '{"http://myschema.com":elementOne}' is expected.]`
> [master] Fix for a bug 553439 - JAXB Unmarshaller with Schema does not show location of error.

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/PostgreSQLPlatform.java
> [2.7] Bug 537657 - Inserting empty or null varchar arrays doesn't work with PostgreSQL since driver version 42.2.4

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/oxm/record/XMLStreamReaderReader.java
> [2.7] Fix for a bug 553439 - JAXB Unmarshaller with Schema does not show location of error.

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/config/PersistenceUnitProperties.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/sessions/PropertiesHandler.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/queries/StoredProcedureCall.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/sessions/Project.java
- jpa/eclipselink.jpa.test/src/it/java/org/eclipse/persistence/testing/tests/jpa22/advanced/NamedStoredProcedureQueryTestSuite.java
- jpa/eclipselink.jpa.test/src/it/java/org/eclipse/persistence/testing/tests/jpa22/advanced/StoredProcedureQueryTestSuite.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/EntityManagerSetupImpl.java
This is fix for a regression "bug" which is started from 2.7.5 due following:
Until 2.7.4 EclipseLink didn't really passed stored procedure parameters by name like `param1 => value` but there was a bug and EclipseLink transformed stored proc calls (parameter passing) into index based and passed by position.
There is a problem with backward compatibility and people used this way how to call stored procedures although there wasn't support at DB or JDBC level like https://github.com/eclipse-ee4j/eclipselink/issues/623 .
Solution is based on new JPA property which must be added to `persistence.xml` or passed to `javax.persistence.EntityManagerFactory`
e.g. 
`persistence.xml`
```
<properties>
...
<property name="eclipselink.jpa.naming_into_indexed" value="true"/>
...
<properties>
```
or …
> [master] Bug 559613 - StoredProcedureQuery named parameters

- foundation/eclipselink.core.test/src/it/java/org/eclipse/persistence/testing/tests/unitofwork/NestedUnitOfWorkDeleteFromNestedObjectTest.java
- foundation/eclipselink.core.test/src/it/java/org/eclipse/persistence/testing/tests/unitofwork/UnitOfWorkIsolatedAlwaysTestModel.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/sessions/MergeManager.java
Bug #624 - New Object created and deleted in nested UnitOfWork is commited to DB
Bugfix + unit test.
> [master] Bug #624 - New Object created and deleted in nested UnitOfWork is commited to DB

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/descriptors/changetracking/AttributeChangeListener.java
When EntityManager is closed, we de-reference the workingClones and the RepeatableUnitOfWork. We store the UoW reference in the EntityManagerImpl and the AttributeChangeListeners weaved into the workingClones. 
If the application chooses to hold the weaved entities in memory AFTER em.close(), you can see the large memory footprint as the AttributeChangeListeners keep the UoW from being garbage collected! If the attribute is changed to a WeakReference, then I can see the garbage collector de-referencing the UoW once the EntityManager gets closed! 
However, I'm not sure what the further ramifications of this might be... It seems safe enough since the EntityManager should hold the UoW reference alive and the UoW is transient anyway in the AttributeChangeListener so no issues with …
> [master] Change UoW reference to WeakReference for GC

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/config/PersistenceUnitProperties.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/sessions/PropertiesHandler.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/queries/StoredProcedureCall.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/sessions/Project.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa22/advanced/NamedStoredProcedureQueryTestSuite.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa22/advanced/StoredProcedureQueryTestSuite.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/EntityManagerSetupImpl.java
This is fixed by persistence.xml property "eclipselink.jpa.naming_into_indexed" to enable translation from name
based parameters into index based.
> [2.7] Fix for a bug 559613 - StoredProcedureQuery does not work in 2.7.5, same code & configuration worked fine in 2.7.4

- .travis.yml
- foundation/eclipselink.core.test/src/test/java/org/eclipse/persistence/testing/tests/junit/helper/JavaSEPlatformTest.java
- foundation/eclipselink.core.test/src/test/java/org/eclipse/persistence/testing/tests/junit/platform/server/wls/WebLogic_12_PlatformTest.java
- foundation/org.eclipse.persistence.corba/pom.xml
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/helper/JavaSEPlatform.java
This PR extends supported JDKs for EclipseLink build and testing with JDK 14.
Travis-CI tests are extended with JDK 14 too but marked as `allow_failures` -> Travis-CI test will pass if there failures in tests executed by JDK 14
With JDK 14 are now following failures in tests (Maven modules):
`org.eclipse.persistence.corba` - Corba server will not start
`org.eclipse.persistence.distribution` - installer test
> [master] Build JDK 8, 11, 14 support

- jpa/org.eclipse.persistence.jpars/pom.xml
- pom.xml
this fixes failing build in master after the move to jakarta
> proper way to disable non-compilable tests dependend on Jersey for now

- bundles/eclipselink/pom.xml
- bundles/p2site/pom.xml
- bundles/pom.xml
- dbws/org.eclipse.persistence.dbws/pom.xml
- etc/jenkins/release.groovy
- etc/jenkins/release.sh
- foundation/org.eclipse.persistence.corba/pom.xml
- foundation/org.eclipse.persistence.core/pom.xml
- foundation/org.eclipse.persistence.extension/pom.xml
- foundation/org.eclipse.persistence.nosql/pom.xml
- foundation/org.eclipse.persistence.oracle.nosql/pom.xml
- foundation/org.eclipse.persistence.oracle/pom.xml
- jpa/org.eclipse.persistence.jpa.jpql/pom.xml
- jpa/org.eclipse.persistence.jpa.modelgen/pom.xml
- jpa/org.eclipse.persistence.jpa/pom.xml
- jpa/org.eclipse.persistence.jpars/pom.xml
- moxy/org.eclipse.persistence.moxy/pom.xml
- plugins/org.eclipse.persistence.asm/pom.xml
- pom.xml
- sdo/org.eclipse.persistence.sdo/pom.xml
- utils/org.eclipse.persistence.dbws.builder/pom.xml
This PR contains EclipseLink release pipeline and script.
Comments:
- In _release.sh_ RELEASE_VERSION is applied by _versions-maven-plugin_. But there some modules (Oracle) where path is dynamic (based on Maven property) e.g. `${oracle.modules.subdirectory}/org.eclipse.persistence.oracle`. In this case _versions-maven-plugin_ will not update `project.parent.version`. It ignores `-Doracle.modules.subdirectory` command parameter too. _sed_ text editor is used there to change required values in POMs.
- Due a limitations of nexus-staging-maven-plugin there is some change in project POMs. Modules which are not deployed are organized in Maven profile with `<id>no-deploy</id>`. Deploy command is executed with `-Ddeploy` parameter to deactivate this profile.
-git release branch (version change …
> [master] EclipseLink release pipeline and script.

- pom.xml
Jersey 3.0.0-M1 is visible in cetral now, so it's possible to update its dependency to jakartified version.
Signed-off-by: Maxim Nesen <maxim.nesen@oracle.com>
> Jersey version jakartified

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/oxm/NamespaceResolver.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/oxm/NamespaceResolverStorage.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/oxm/VectorUtils.java
Performance fixes:
Avoid creating a Vector object for each NamespaceResolver#getNamespaces() call
Use a simpler List structure instead LinkedHashMap for the interim buffer in the NamespaceResolver#put(String, String) method.
Signed-off-by: Aleksandr Sanitskii <asanitsky@informatica.com>
(cherry picked from commit d5daa33e44ca79a9e41a1190ffcb8b874efb29e5)
> [2.7] Bug 548125: SDO Types generation is very slow for big schemas (backport from master)

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/descriptors/CMPPolicy.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/descriptors/ClassDescriptor.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/queries/DatasourceCallQueryMechanism.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/queries/ExpressionQueryMechanism.java
- jpa/eclipselink.jpa.test.jse/src/META-INF/persistence.xml
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/returninsert/TestReturnInsert.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/returninsert/model/ReturnInsertDetail.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/returninsert/model/ReturnInsertDetailEmbedded.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/returninsert/model/ReturnInsertDetailEmbeddedEmbedded.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/returninsert/model/ReturnInsertDetailPK.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/returninsert/model/ReturnInsertDetailParent.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/returninsert/model/ReturnInsertMaster.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/returninsert/model/ReturnInsertMasterPK.java
This is fix for #709 . Backport from master.
> [2.7] JPA Eclipselink Application Throws IllegalArgumentException With Coherence Enabled - backport

- bundles/eclipselink/pom.xml
- bundles/eclipselink/src/main/assembly/eclipselink-src.jar.xml
- bundles/eclipselink/src/main/assembly/eclipselink.jar.xml
- bundles/nightly/pom.xml
- sdo/org.eclipse.persistence.sdo/pom.xml
-make SDO running on JDK 11+
-added sdo back to eclipselink.jar and make it runnable on JDK 11+
-updated/fixed content of eclipselink.jar/source jar
-fixed up dependency tree for eclipselink.jar (everything is optional as we cannot know what piece of functionality user wants/needs)
-make sure that nightly test results are being garthered AFTER all previous test runs
> Fixing content of sdo jar and eclipselink jar

- uploadToNexus.xml
This fix is required due a switch to new staging server https://jakarta.oss.sonatype.org.
There is a new repository closing policy which requires, that published artifact contains binaries, sources and javadoc archive.
Without javadoc archive https://jakarta.oss.sonatype.org server throws error like:
`[ERROR]     * Missing: no javadoc jar found in folder '/org/eclipse/persistence/org.eclipse.persistence.jpa.jpql/2.7.7-RC1'`
see https://ci.eclipse.org/eclipselink/view/Current%20Jobs/job/Maven%20repo%20operations/8/console .
This solution doesn't have any negative impact to build process performance.
Testing output is available at
https://jakarta.oss.sonatype.org/#view-repositories;orgeclipsepersistence-1005~browsestorage
or 
https://jakarta.oss.sonatype.org/content/repositories/orgeclipsepe …
> [2.7] Javadoc generation before upload to staging server

- bundles/distribution/pom.xml
- bundles/nightly/pom.xml
- bundles/pom.xml
This is fix for broken nightly build (Maven module `org.eclipse.persistence.nightly`).
Due previous changes there is different path where _eclipselink.zip_ is unzipped. This directory is used by `org.eclipse.persistence.nightly` to prepare files for the upload into "Nightly build" "page" server at Eclipse.org.
See error at https://ci.eclipse.org/eclipselink/view/Current%20Jobs/job/eclipselink-nightly-master/103/console .
> [master] Nightly build fix

- bundles/nightly/pom.xml
It seems, that there is some change (XPath) in test results pages. This fix reflects it to correctly generate ResultSummary.dat used at https://www.eclipse.org/eclipselink/downloads/nightly.php
> [master] Nightly build - test status generation

- antbuild.properties
- antbuild.xml
- dbws/eclipselink.dbws.test/antbuild.xml
- features/antbuild.xml
- jpa/org.eclipse.persistence.jpa.jpql.test/antbuild.xml
- utils/eclipselink.utils.workbench.test/build.xml
- utils/eclipselink.utils.workbench/build.xml
This is fix for Ant build - clean task. Before this fix command `ant -f antbuild.xml clean` didn't deleted all working (build temporary) files and directories from all projects.
> Ant build - clean task fix

- uploadToNexus.xml
- staging server hostname change into jakarta.oss.sonatype.org
- Javadoc generation before upload to staging server to fulfill staging repo closing policy
> [2.6] Jenkins - promotion/release script update

- .travis.yml
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/mappings/AggregateObjectMapping.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/models/jpa/complexaggregate/ComplexAggregateTableCreator.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/models/jpa/complexaggregate/HockeyPuck.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/models/jpa/complexaggregate/HockeyRink.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/models/jpa/complexaggregate/HockeySponsor.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa/complexaggregate/ComplexAggregateTestSuite.java
- Resolves an issue in AggregateObjectMapping buildAggregateFromRow() by passing in the CacheKey (within buildCloneFromRow()) and checking if the aggregate is referenced within the target object and the CacheKey is null before instantiating a new aggregate instance.
- Added ComplexAggregateTestSuite test: testInvalidateAndRefreshEmbeddableParent within the complex aggregate suite, with new, specialized Entities: HockeyPuck, HockeyRink and HockeySponsor (and associated table creation to ComplexAggregateTableCreator)
Backport from 2.7 https://github.com/eclipse-ee4j/eclipselink/commit/e27a5785c49f790bed1b9d4965f14ffdc0e279c5
> [2.6] Fix for Bug 474956 - RepeatableUnitOfWork linked by Embeddable in shared cache in specific scenario

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/queries/ExpressionQueryMechanism.java
- jpa/eclipselink.jpa.test.jse/src/META-INF/persistence.xml
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/returninsert/TestReturnInsert.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/returninsert/model/ReturnInsertDetailJoined.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/returninsert/model/ReturnInsertMasterJoined.java
bugfix + test for bug #803
Backport from master #806
> [2.6] EclipseLink doesn't generate SQL INSERT correctly if @ReturnInsert if used in InheritanceType.JOINED

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/queries/ExpressionQueryMechanism.java
- jpa/eclipselink.jpa.test.jse/src/META-INF/persistence.xml
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/returninsert/TestReturnInsert.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/returninsert/model/ReturnInsertDetailJoined.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/returninsert/model/ReturnInsertMasterJoined.java
bugfix + test for bug #803
Backport from master #806 
> [2.7] EclipseLink doesn't generate SQL INSERT correctly if @ReturnInsert if used in InheritanceType.JOINED

- dbws/eclipselink.dbws.test.oracle/pom.xml
- foundation/org.eclipse.persistence.oracle.nosql/pom.xml
- foundation/org.eclipse.persistence.oracle.test/pom.xml
- utils/eclipselink.dbws.builder.test.oracle.server/pom.xml
- utils/eclipselink.dbws.builder.test.oracle/pom.xml
Due a changes in PR #828 (pom_oracle.xml removal) some integration tests in *.oracle.test modules must be moved into Maven "oracle" profile.
Without this change `mvn verify` or `mvn verify -Pmysql,test-lrg` commands used by _eclipselink-cb-master_ and _eclipselink-nightly-master_ jobs will execute Oracle tests against Derby or MySQL databases.
> [master] Maven build Oracle tests refactoring

- etc/jenkins/build.groovy
- etc/jenkins/promote.groovy
This is change based on recommendations from https://bugs.eclipse.org/bugs/show_bug.cgi?id=564240 .
It improves build time and stability at https://ci.eclipse.org/eclipselink .
> [2.7] Jenkins build resources change

- etc/jenkins/build.groovy
- etc/jenkins/promote.groovy
This is change based on recommendations from https://bugs.eclipse.org/bugs/show_bug.cgi?id=564240 .
It improves build time and stability at https://ci.eclipse.org/eclipselink .
> [2.6] Jenkins build resources change

- antbuild.xml
- etc/jenkins/build.sh
- etc/jenkins/init.sh
- etc/jenkins/promote_init.sh
This is fix for a Jenkins/Ant build by switch into Oracle public JDBC driver (see PR #839). 
There was some issue with `ant -f antbuild clean` command.
There is some fix for Jenkins build script too.
> Jenkins/Ant build fix 2.7

- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/metadata/accessors/objects/MetadataAsmFactory.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/weaving/ClassWeaver.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/weaving/MethodWeaver.java
for #877
The ASM 8.0.1 update for 2.7 (#805) did not include updates to the jpa portion of the project to use the ASM8 opcode.  Thus Eclipselink is not gaining the full benefit of using ASM 8.
> [2.7] Update ASM 8.0.1 change to enable Eclipselink to use ASM8

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/oxm/record/XMLStreamReaderReader.java
Before this fix MOXy produced incomplete error message in case of XML Schema validation failure during unmarshall operation, if schema validation was enabled and non-valid XML document used at the input.
E.G. Error message before fix
`Internal Exception: org.xml.sax.SAXParseException; cvc-complex-type.2.4.a: Invalid content was found starting with element ''. One of '{"http://myschema.com":elementOne}' is expected.]`
Error message after fix
`Internal Exception: org.xml.sax.SAXParseException; cvc-complex-type.2.4.a: Invalid content was found starting with element 'elementTwo'. One of '{"http://myschema.com":elementOne}' is expected.]`
> [2.6] Fix for a bug 553439 - JAXB Unmarshaller with Schema does not show location of error. - backport from master

- pom.xml
Temporary disabled test modules activated and moved to the new Maven profile extra-tests.
Main reason is to let `org.codehaus.mojo:versions-maven-plugin` set version (release, next version) during release to all EclipseLink project modules.
> [master] Maven build - temporary disabled test modules activated and moved to the new Maven profile extra-tests.

- bundles/moxy-standalone/pom.xml
- pom.xml
This is fix for broken build too because 2.0.0-RC3 was removed from staging repo.
See https://jakarta.oss.sonatype.org/content/repositories/staging/jakarta/resource/jakarta.resource-api/
> [master] Dependency jakarta.resource-api upgrade 2.0.0-RC3 -> 2.0.0

- performance/eclipselink.perf.test/pom.xml
- pom.xml
There is dependency fix for _jakarta.persistence_ and JMH + _exec-maven-plugin_ upgrade.
Performance test should be executed by `mvn test -pl :org.eclipse.persistence.performance.test -Ptest-performance` comand.
> [master] Maven build - performance test fix

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/config/SystemProperties.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/helper/ConversionManager.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/localization/i18n/TraceLocalizationResource.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/conversion/TestJavaTimeTypeConverter.java
for #893
Fix for https://bugs.eclipse.org/bugs/show_bug.cgi?id=538296
Corrected a number of issues in the java.time conversion logic, and added unit tests to verify conversion  operations.
Prior to this fix, the ConversionManager defaulted to the JVM's system default time zone instead of UTC.  This could lead to unexpected time zone changes, especially for an application system that  could be distributed over multiple timezones.  This fix changes the default time zone used in certain conversions* to UTC.
Applications which want to return to the prior behavior, or select a specific timezone may take advantage of one of two JVM system properties introduced by this fix:
- `org.eclipse.persistence.conversion.useTimeZone` - Set this to a value that is an acceptable input for …
> [Master] Bug 538296: Wrong month is returned if OffsetDateTime is used

- dbws/org.eclipse.persistence.dbws/src/it/java/dbws/testing/relationships/RelationshipsTestSuite.java
This fixes #916 .
Tested by setting the computer time zone to various ones around the world, and rerunning the test.
> RelationshipsTestSuite offset now accounts for daylight savings and any other offset

- moxy/org.eclipse.persistence.moxy/src/org/eclipse/persistence/jaxb/compiler/Property.java
The issue is that on OpenJ9. Method adapterCls.getMethods() returns all the classes' methods. The current code add all the methods to "marshalMethods", so marshal methods but also getClass, equals and so on.
On openjdk the marshal method is the first one to pop, which is not the case on OpenJ9, the first one is getClass
So in the second loop:
JavaClass paramType = method.getParameterTypes()[0]; an ArrayIndexOutOfBoundsException is thrown.
The modification will only add to "marshalMethods" methods named marshal with one argument. Which seems to me the wanted behaviour from the start.
> [2.7] Property: only add marshal methods - backport from master

- foundation/eclipselink.core.test/src/it/java/org/eclipse/persistence/testing/tests/expressions/ExpressionTestSuite.java
- foundation/eclipselink.core.test/src/it/java/org/eclipse/persistence/testing/tests/expressions/ReadObjectExpressionTest.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/expressions/ExpressionSQLPrinter.java
- jpa/eclipselink.jpa.test/src/it/java/org/eclipse/persistence/testing/tests/jpa/criteria/AdvancedCriteriaQueryTestSuite.java
Bug fix + unit test for #847 .
Before this fix EclipseLink for (assume the `inList` is empty or `null`)
`Predicate in = from.get("projektID").in(inList);`
produced invalid SQL query like
`SELECT ... FROM ... WHERE PROJEKTID IN ()`
After this fix generated SQL query for empty or null collection used in `.in(...)` method/expression is e.g.
`SELECT ... FROM ... WHERE PROJEKTID IN (NULL)`
Which is valid SQL query.
> [master] JPA Criteria API: Empty IN Statement leads to SQL-Error

- bundles/nightly/pom.xml
- pom.xml
This is fix of nightly Maven module. Due previous changes there is different _eclipselink.zip_ file name e.g. _eclipselink-3.0.0-SNAPSHOT.zip_. This fix reflect this change.
For bug details see https://ci.eclipse.org/eclipselink/view/Current%20Jobs/job/eclipselink-nightly-master/141/console
> [master] Maven build - Nightly module fix.

- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/tests/expressions/ExpressionTestSuite.java
- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/tests/expressions/ReadObjectExpressionTest.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/expressions/ExpressionSQLPrinter.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa/criteria/AdvancedCriteriaQueryTestSuite.java
Bug fix + unit test for #847 .
Before this fix EclipseLink for (assume the `inList` is empty or `null`)
`Predicate in = from.get("projektID").in(inList);`
produced invalid SQL query like
`SELECT ... FROM ... WHERE PROJEKTID IN ()`
After this fix generated SQL query for empty or null collection used in `.in(...)` method/expression is e.g.
`SELECT ... FROM ... WHERE PROJEKTID IN (NULL)`
Which is valid SQL query.
> [2.7] JPA Criteria API: Empty IN Statement leads to SQL-Error - backport from master

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/oxm/record/XMLStreamReaderReader.java
This is additional bug fix for reopened bug https://bugs.eclipse.org/bugs/show_bug.cgi?id=553439 .
> [master] Fix for a bug 553439 v2.0 - JAXB Unmarshaller with Schema does not show location of error.

- .travis.yml
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/oxm/record/XMLStreamReaderReader.java
This is additional bug fix for reopened bug https://bugs.eclipse.org/bugs/show_bug.cgi?id=553439 .
> [2.6] Fix for a bug 553439 2.0 - JAXB Unmarshaller with Schema does not show location of error - backport from master

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/oxm/record/XMLStreamReaderReader.java
This is additional bug fix for reopened bug https://bugs.eclipse.org/bugs/show_bug.cgi?id=553439 .
> [2.7] Fix for a bug 553439 v2.0 - JAXB Unmarshaller with Schema does not show location of error - backport from master

- etc/jenkins/build.groovy
- etc/jenkins/publish_snapshots.sh
- pom.xml
This PR extends Jenkins build with new stage **Publish to snapshots**. Output from Nightly build job after successful tests will be published to https://jakarta.oss.sonatype.org/content/repositories/snapshots/ too. Other outputs (Nightly download page at https://www.eclipse.org/eclipselink/downloads/nightly.php) remains untouched.
There is minor cleanup in project pom. Maven properties `sonatypeOssDistMgmtNexusUrl` and `sonatypeOssDistMgmtStagingUrl` were removed due duplication with parent pom `org.eclipse.ee4j:project:1.0.6` .
> Jenkins build - Snapshots promotion during Nightly build

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/helper/ExplainDeadLockUtil.java
There is small fix to improve readability of massive dump Page 7 of Concurrency manager state.
> [master] Bug/New Feature 559307: EclipseLink on all versions can dead-lock forever 2.0

- etc/jenkins/publish_snapshots.sh
This fix has two parts:
1. Bash condition `if [ ${CONTINUOUS_BUILD} = "true" ]; then` ensure, that snapshots publishing will be active only during "Nightly build".
2. Maven target change from `... clean deploy` to `... deploy` ensure, that tests results from previous Jenkins stages will remain there for last Jenkins pipeline stage "Proceed test results"
> [master] Jenkins build fix - Snapshots publishing

- antbuild.xml
- dbws/eclipselink.dbws.test/antbuild.xml
- jpa/eclipselink.jpa.test/antbuild.xml
- moxy/eclipselink.moxy.test/antbuild.xml
- utils/eclipselink.utils.workbench.test/build.xml
- utils/eclipselink.utils.workbench/build.xml
This is fix for Ant build - clean task. Before this fix command `ant -f antbuild.xml clean` didn't deleted all working (build temporary) files and directories from all projects.
> [2.6] Ant build - clean task fix

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/helper/ConcurrencyUtil.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/security/PrivilegedGetThreadInfo.java
Addresses the doPriv() issues as commented in #972.
> [Master] Add doPriv blocks to use of protected ThreadMXBean methods in ConcurrencyUtil

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/databaseaccess/DatabaseAccessor.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/queries/ReportQueryResult.java
@dazey3 fix in #925 for bug 567891 caused TCK failure, in particular com/sun/ts/tests/jpa/core/criteriaapi/CriteriaBuilder/Client.java#toStringTest_from_standalone test fails with:
```
[javatest.batch] 12-07-2020 14:29:09:  ERROR: java.lang.ClassCastException: java.lang.Character cannot be cast to java.lang.String
[javatest.batch] 	at com.sun.ts.tests.jpa.core.criteriaapi.CriteriaBuilder.Client.toStringTest(Client.java:6345)
[javatest.batch] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[javatest.batch] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[javatest.batch] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[javatest.batch] 	at java.lang.reflect.Method.invoke(Method.java:498) …
```
> #567891: improving fix to pass TCKs

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/databaseaccess/DatabaseAccessor.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/querydef/CriteriaBuilderImpl.java
Fix #983 broken JPA.WDF tests see https://ci.eclipse.org/eclipselink/view/Current%20Jobs/job/eclipselink-nightly-master/153/console . This PR removes unnecessary change in CriteriaBuilderImpl and extends fix in DatabaseAccessor.
> CriteriaBuilderImpl fix revert and code improvement in DatabaseAccessor to fix JPA.WDF tests.

- pom.xml
This property is required for nightly build location/version at Eclipse.org.
> Maven build - release version update to 3.0.1

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/helper/ConcurrencyUtil.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/security/PrivilegedGetThreadInfo.java
> [2.6] Add doPriv blocks to use of protected ThreadMXBean methods in ConcurrencyUtil - backport from master

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/config/PersistenceUnitProperties.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/databaseaccess/DatabaseAccessor.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/queries/ReportQueryResult.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/sessions/Project.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/query/TestQueryCase.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/EntityManagerSetupImpl.java
This is backport from #983 and #984 .
This is simplified and more correct fix for 567891 . It partially change #925 .
> [2.7] Bug 567891: Boolean literals are replaced with Integer values in CASE queries - backport

- features/antbuild.xml
- uploadToMaven.xml
- uploadToNexus.xml
This is fix for the promotion. Ant scripts don't reflect current ASM version. There was a limit into < 9.0 version. It leads into not initialized `asm.version` property in build scripts.
> Ant build - catchup ASM upgrade

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/helper/ConcurrencyUtil.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/localization/i18n/TraceLocalizationResource.java
There is some minor change is log output produced by cache dead-lock diagnostic. concurrencyManagerCreationDate format is changed to display time with milliseconds and cache key hash code is added.
> [master] Concurrency manager logging - extension

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/helper/ConcurrencyUtil.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/localization/i18n/LoggingLocalizationResource.java
There is some minor change is log output produced by cache dead-lock diagnostic. concurrencyManagerCreationDate format is changed to display time with milliseconds and cache key and cached object hash code is added. There are some formatting changes too.
> [2.6] Concurrency manager logging - extension (backport from master)

- autobuild.xml
- etc/jenkins/build.groovy
- etc/jenkins/publish_snapshots.sh
- pom.xml.template
- uploadToNexus.xml
There are changes in build scripts called in Jenkins environment to publish build outputs/artifacts to Jakarta snapshots repository.
It's useful for tests (TCKs or use nightly build output in Maven environment).
There is parent pom (org.eclipse.ee4j:project) upgrade from 1.0.5 to 1.0.6 in pom files attached to published artifacts.
> [2.7] Ant/Jenkins build - Nightly build extension to publish output to Jakarta snapshots

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/config/PersistenceUnitProperties.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/databaseaccess/DatabaseAccessor.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/sessions/Project.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/property/TestConvertResultToBoolean.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/query/TestQueryCase.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/EntityManagerSetupImpl.java
I changed the name of the persistence property for this fix to more accurately describe what it is gating. Since the old property was not released in a 2.7 release, I think renaming the property is fine.
for #922
> [2.7] Fix TCK failure for Character type

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/config/PersistenceUnitProperties.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/databaseaccess/DatabaseAccessor.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/queries/ReportQueryResult.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/sessions/Project.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/property/TestConvertResultToBoolean.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/query/TestQueryCase.java
You may notice that I did not alter the name of the persistence property for this port. This was intentional as the current property name was already released for WebSphere and is now supported. Rather than change the property name and break customers, the property will remain named the same for the 2.6_WAS release.
for #922
> [2.6_WAS] Fix TCK failure for java.lang.Character type

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/config/PersistenceUnitProperties.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/queries/ObjectBuildingQuery.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/sessions/Project.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/EntityManagerSetupImpl.java
New `eclipselink.cache.query-force-deferred-locks` property force all queries and relationships
to use deferred lock strategy during object building and L2 cache population.
It helps to solve dead lock issues in multithreaded environments where one L2 cache is accessed/populated
by multiple threads.
Threads create objects from the same object graph but from different starting point.
Dead lock issue should happens in large object graphs and entities connected with relationships with EAGER fetch strategy.
> [master] Force deferred locks persistence query property

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/config/PersistenceUnitProperties.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/queries/ObjectBuildingQuery.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/sessions/Project.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/EntityManagerSetupImpl.java
New `eclipselink.cache.query-force-deferred-locks` property force all queries and relationships
to use deferred lock strategy during object building and L2 cache population.
It helps to solve dead lock issues in multithreaded environments where one L2 cache is accessed/populated
by multiple threads.
Threads create objects from the same object graph but from different starting point.
Dead lock issue should happens in large object graphs and entities connected with relationships with EAGER fetch strategy.
> [2.6] Force deferred locks persistence query property - backport from master

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/config/PersistenceUnitProperties.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/config/SystemProperties.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/helper/ConcurrencyUtil.java
There is small fix for performance improvement when dead-lock detection/logging is enabled.
`eclipselink.concurrency.manager.allow.readlockstacktrace` default value will be false.
Stack trace collection for read locks consumes so much resources.
> [master] Bug/New Feature 559307: EclipseLink on all versions can dead-lock forever - performance fix

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/config/PersistenceUnitProperties.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/config/SystemProperties.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/helper/ConcurrencyUtil.java
There is small fix for performance improvement when dead-lock detection/logging is enabled.
"eclipselink.concurrency.manager.allow.readlockstacktrace" default value will be false.
Stack trace collection for read locks consumes so much resources.
> [2.7] Bug/New Feature 559307: EclipseLink on all versions can dead-lock forever - performance fix

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/config/PersistenceUnitProperties.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/config/SystemProperties.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/helper/ConcurrencyUtil.java
There is small fix for performance improvement when dead-lock detection/logging is enabled.
"eclipselink.concurrency.manager.allow.readlockstacktrace" default value will be false.
Stack trace collection for read locks consumes so much resources.
> [2.6] Bug/New Feature 559307: EclipseLink on all versions can dead-lock forever - performance fix

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/queries/ExpressionQueryMechanism.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/returninsert/TestReturnInsert.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/returninsert/model/ReturnInsertDetailJoined.java
> EclipseLink doesn't generate SQL UPDATE correctly if @ReturnUpdate is used in InheritanceType.JOINED

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/queries/ExpressionQueryMechanism.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/returninsert/TestReturnInsert.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/returninsert/model/ReturnInsertDetailJoined.java
> [2.7] EclipseLink doesn't generate SQL UPDATE correctly if @ReturnUpdate is used in InheritanceType.JOINED - backport from master

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/queries/ExpressionQueryMechanism.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/returninsert/TestReturnInsert.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/returninsert/model/ReturnInsertDetailJoined.java
> [2.6] EclipseLink doesn't generate SQL UPDATE correctly if @ReturnUpdate is used in InheritanceType.JOINED - backport from master

- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/tests/expressions/ExpressionSubSelectTestSuite.java
I think, that behind this test failure is some race condition with another test. It seems, that due a parallel test execution there are values in the DB tables which leads, that query in the test returns at least one row. But this test is focused on `ExpressionBuilder` syntax and doesn't expect any rows from DB. Additional condition/criteria ensures, that nothing is selected.
> [2.7] Bug 535088 - [test] SubSelectFromClauseTest2 failing randomly on public infra 2.0

- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/tests/expressions/ExpressionSubSelectTestSuite.java
I think, that behind this test failure is some race condition with another test. It seems, that due a parallel test execution there are values in the DB tables which leads, that query in the test returns at least one row. But this test is focused on `ExpressionBuilder` syntax and doesn't expect any rows from DB. Additional condition/criteria ensures, that nothing is selected.
> [2.6] Bug 535088 - [test] SubSelectFromClauseTest2 failing randomly on public infra 2.0 - backport

- foundation/eclipselink.core.test/src/it/java/org/eclipse/persistence/testing/tests/expressions/ExpressionSubSelectTestSuite.java
I think, that behind this test failure is some race condition with another test. It seems, that due a parallel test execution there are values in the DB tables which leads, that query in the test returns at least one row. But this test is focused on `ExpressionBuilder` syntax and doesn't expect any rows from DB. Additional condition/criteria ensures, that nothing is selected.
> [master] Bug 535088 - [test] SubSelectFromClauseTest2 failing randomly on public infra 2.0 - backport

- etc/jenkins/build.groovy
This is change to prevent SQL timeout errors during build and test execution. It reflects some environment changes done by Eclipse.org admins.
> [2.7] Jenkins build/tests fix - resources increase

- etc/jenkins/build.groovy
This is change to prevent SQL timeout errors during build and test execution. It reflects some environment changes done by Eclipse.org admins.
> [master] Jenkins build/tests fix - resources increase

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/config/PersistenceUnitProperties.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/config/SystemProperties.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/descriptors/ObjectBuilder.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/helper/ConcurrencyManager.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/helper/ConcurrencySemaphore.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/helper/ConcurrencyUtil.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/helper/ExplainDeadLockUtil.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/helper/WriteLockManager.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/localization/i18n/TraceLocalizationResource.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/cachedeadlock/CacheDeadLockDetectionTest.java
- jpa/eclipselink.jpa.test.jse/src/it/resources/META-INF/persistence.xml
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/EntityManagerSetupImpl.java
This is second part of dead-lock detection diagnostic improvement 2.0 related with previous PR #1038 .
Previous PR content was passive from point of the view of the EclipseLink code execution.
This PR has has active component `org.eclipse.persistence.internal.helper.ConcurrencySemaphore` which should be used to control/limit how many threads should execute selected code.
In this case is `ConcurrencySemaphore` used to limit parallel access to `org.eclipse.persistence.internal.descriptors.ObjectBuilder` and `org.eclipse.persistence.internal.helper.WriteLockManager` to prevent possible dead-lock issues there.
If `ConcurrencySemaphore` will be active, there should be negative impact to the performance.
By default `ConcurrencySemaphore` is disabled and must be enabled by persistence or system …
>  ConcurrencyManager dead-lock detection diagnostic improvement 2.0 - semaphores

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/config/PersistenceUnitProperties.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/config/SystemProperties.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/descriptors/ObjectBuilder.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/helper/ConcurrencyManager.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/helper/ConcurrencySemaphore.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/helper/ConcurrencyUtil.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/helper/ExplainDeadLockUtil.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/helper/WriteLockManager.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/helper/type/ConcurrencyManagerState.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/localization/i18n/LoggingLocalizationResource.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/security/PrivilegedAccessHelper.java
- jpa/eclipselink.jpa.test.jse/src/META-INF/persistence.xml
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/cachedeadlock/CacheDeadLockDetectionTest.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/EntityManagerSetupImpl.java
This backport of PRs #1038,  #1041 and #1048
This is extension to current dead-lock detection diagnostic.
Major updates are:
- New system/persistence property `eclipselink.concurrency.manager.build.object.complete.waittime` to control how much time ConcurrencyManager will wait before it will identify, that thread which builds new object/entity instance should be identified as a potential dead lock source and log info.
- Addition to current dead-lock detection log output with method name (from ConcurrencyManager) where dead-lock should happen
- `org.eclipse.persistence.internal.helper.ConcurrencyManager#isBuildObjectOnThreadComplete` minor changes to log some dead-lock diagnostic output
- Implementation of  `org.eclipse.persistence.internal.helper.ConcurrencySemaphore` which should be used …
> [2.6] ConcurrencyManager dead-lock detection diagnostic improvement (+ Semaphores) 2.0 - backport from master

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/config/PersistenceUnitProperties.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/queries/ObjectBuildingQuery.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/sessions/Project.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/EntityManagerSetupImpl.java
New `eclipselink.cache.query-force-deferred-locks` property force all queries and relationships
to use deferred lock strategy during object building and L2 cache population.
It helps to solve dead lock issues in multithreaded environments where one L2 cache is accessed/populated
by multiple threads.
Threads create objects from the same object graph but from different starting point.
Dead lock issue should happens in large object graphs and entities connected with relationships with EAGER fetch strategy.
> [2.7] Force deferred locks persistence query property - backport from master

- foundation/eclipselink.core.test/src/test/java/org/eclipse/persistence/testing/tests/junit/helper/ConcurrencySemaphoreTest.java
- foundation/eclipselink.core.test/src/test/java/org/eclipse/persistence/testing/tests/junit/helper/ConcurrencySemaphoreThread.java
This is unit test for `org.eclipse.persistence.internal.helper.ConcurrencySemaphore` implemented in #1041 .
> [master] ConcurrencySemaphore unit test

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/config/PersistenceUnitProperties.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/descriptors/ObjectBuilder.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/identitymaps/CacheKey.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/identitymaps/IdentityMapManager.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/localization/i18n/TraceLocalizationResource.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/sessions/IdentityMapAccessor.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/sessions/UnitOfWorkImpl.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/sessions/Project.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/EntityManagerSetupImpl.java
This PR contains extension to the EclipseLink logging to print information about persistence cache operations and usage.
It prints info when entity is stored, refreshed, removed, invalidated in the cache and info about cache hits/miss.
This feature is controlled by new `eclipselink.cache.extended.logging` property and generates messages at the `FINEST` log level.
It prints additional message if one thread stored item into cache and different picking item.
> [master] Extended logging of JPA L2 cache usage with thread info.

- pom.xml
This is small fix to reflect Maven project 3.1.0-SNAPSHOT changed before.
> [master] Maven build - release version property change to 3.1.0

- pom.xml
There is Weld SE dependency update to fix org.eclipse.persistence.jpa.test.cachedeadlock.CacheDeadLockDetectionTest in JPA JSE test module.
Test failure happens on JDK 16 only.
> Maven build - JPA JSE test fix on JDK 16

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/config/PersistenceUnitProperties.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/descriptors/ObjectBuilder.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/identitymaps/CacheKey.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/identitymaps/IdentityMapManager.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/localization/i18n/TraceLocalizationResource.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/sessions/IdentityMapAccessor.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/sessions/UnitOfWorkImpl.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/sessions/Project.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/EntityManagerSetupImpl.java
This commit contains extension to the EclipseLink logging to print information about persistence cache operations and usage.
It prints info when entity is stored, refreshed, removed, invalidated in the cache and info about cache hits/miss.
This feature is controlled by new "eclipselink.cache.extended.logging property" and generates messages at the FINEST log level.
It prints additional message if one thread stored item into cache and different picking item.
(cherry picked from commit f2c4e5230ec553b0fc5958cee3572b1849588bb8)
> [3.0] Extended logging of JPA L2 cache usage with thread info. - backport from master

- pom.xml
There is Weld SE dependency update to fix org.eclipse.persistence.jpa.test.cachedeadlock.CacheDeadLockDetectionTest in JPA JSE test module.
Test failure happens on JDK 16 only.
(cherry picked from commit fa5bb0a5dc4069560ab739feb650a0ae019ae308)
> [3.0] Maven build - JPA JSE test fix on JDK 16 (#1068) - backport from master

- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/tests/junit/helper/ConcurrencySemaphoreTest.java
- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/tests/junit/helper/ConcurrencySemaphoreThread.java
This is unit test for org.eclipse.persistence.internal.helper.ConcurrencySemaphore.
> [2.7] ConcurrencySemaphores unit test - backport from master

- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/tests/helper/ConcurrencySemaphoreTest.java
- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/tests/helper/ConcurrencySemaphoreThread.java
- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/tests/helper/HelperTestModel.java
This is unit test for org.eclipse.persistence.internal.helper.ConcurrencySemaphore.
> [2.6] ConcurrencySemaphores unit test - backport from master

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/config/PersistenceUnitProperties.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/helper/ConcurrencyUtil.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/localization/i18n/LoggingLocalizationResource.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/localization/i18n/TraceLocalizationResource.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/sessions/UnitOfWorkImpl.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/logging/LogCategory.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/logging/SessionLog.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/sessions/Project.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/EntityManagerSetupImpl.java
This PR contains extension to logging code.
Main purpose is display info if cached entity is picked by another thread and WorkManager is called in different threads.
This logging is by default disabled and must be enabled by persistence properties
Major changes are:
- new `thread` log category specified in `org.eclipse.persistence.logging.LogCategory` and `org.eclipse.persistence.logging.SessionLog`
- Two new persistence unit properties `eclipselink.thread.extended.logging` to enable this logging and `eclipselink.thread.extended.logging.threaddump` to add to the log output threads stack trace
- new log messages are called from `org.eclipse.persistence.internal.sessions.UnitOfWorkImpl`
> [master] Extended Thread logging

- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/basic/TestSessionCustomizer.java
- jpa/eclipselink.jpa.test/src/it/java/org/eclipse/persistence/testing/tests/jpa/advanced/EntityManagerJUnitTestSuite.java
- jpa/eclipselink.jpa.test/src/it/java/org/eclipse/persistence/testing/tests/jpa/composite/advanced/EntityManagerJUnitTestSuite.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/jpa/JpaEntityManager.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/jpa/JpaEntityManagerFactory.java
this is to allow EMF/EMF to be used in try-with-resources statements.
Sample usage:
```
try (JpaEntityManagerFactory emf = (JpaEntityManagerFactory) Persistence.createEntityManagerFactory(...);
JpaEntityManager em = (JpaEntityManager) emf.createEntityManager()) {
em.find(...);
} catch (PersistenceException pe)  {
// emf/em are already closed here
}
```
> Fixes #1069: let JpaEntityManager(Factory) extend (Auto)Closeable

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/config/PersistenceUnitProperties.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/helper/ConcurrencyUtil.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/localization/i18n/LoggingLocalizationResource.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/localization/i18n/TraceLocalizationResource.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/sessions/UnitOfWorkImpl.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/logging/LogCategory.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/logging/SessionLog.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/sessions/Project.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/EntityManagerSetupImpl.java
This commit contains extension to logging code.
Main purpose is display info if cached entity is picked by another thread and WorkManager is called in different threads.
This logging is by default disabled and must be enabled by persistence properties
Major changes are:
- new thread log category specified in org.eclipse.persistence.logging.LogCategory and org.eclipse.persistence.logging.SessionLog
- Two new persistence unit properties eclipselink.thread.extended.logging to enable this logging and eclipselink.thread.extended.logging.threaddump to add to the log output threads stack trace
- new log messages are called from org.eclipse.persistence.internal.sessions.UnitOfWorkImpl
(cherry picked from commit …
> [3.0] Extended Thread logging - backport from master

- jpa/eclipselink.jpa.test.jse/antbuild.xml
The antbuild.xml for the `eclipselink.jpa.test.jse` test bucket has hard coded entries for the core, jpa, jpa.jpql, jpa.modelgen jars, which doesn't play nicely if you build eclipselink with the `-Dgit.hash=$GIT_REVISION` option.  Modifying the antbuild.xml to allow for more flexibility with the version portion of the file name.
> [2.6_WAS] Update jpa.jse test antbuild.xml  for jars with git hash

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/localization/i18n/LoggingLocalizationResource.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/localization/i18n/TraceLocalizationResource.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/sessions/UnitOfWorkImpl.java
This change makes log output less confusing as cached entity should be reused/picked by different threads.
> [master] Extended Thread logging - Cache thread info severity change

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/localization/i18n/LoggingLocalizationResource.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/sessions/UnitOfWorkImpl.java
This change makes log output less confusing as cached entity should be reused/picked by different threads.
> [2.6] Extended Thread logging - Cache thread info severity change - backport from master

- foundation/eclipselink.core.test/src/it/java/org/eclipse/persistence/testing/models/mapping/Employee.java
- foundation/eclipselink.core.test/src/it/java/org/eclipse/persistence/testing/models/mapping/MappingProject.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/databaseaccess/DatasourcePlatform.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/helper/ConversionManager.java
- jpa/eclipselink.jpa.test/src/it/java/org/eclipse/persistence/testing/models/jpa/advanced/compositepk/CompositePKTableCreator.java
- jpa/eclipselink.jpa.test/src/it/java/org/eclipse/persistence/testing/models/jpa/advanced/derivedid/LackeyCrewMember.java
* `RANK` is reserved word in MySQL 8
* Connector/J 8.0.24 returns `LocalDateTime` from `rs.getObject()` for `TimeStamp` type
To test, update MySQL JDBC driver to the latest one (8.0.24)
> fix test failures for mysql driver 8.0.24

- etc/jenkins/build.groovy
- etc/jenkins/build.sh
- etc/jenkins/publish_snapshots.sh
- etc/jenkins/release.groovy
- etc/jenkins/release.sh
- etc/jenkins/release_asm.sh
- etc/jenkins/test.sh
- etc/jenkins/test_nosql.sh
- etc/jenkins/test_server.sh
Default JDK for build and tests will be Open JDK 11 instead of previous Oracle JDK 8.0.
Maven is switched to latest version 3.6.3.
This change is related with implementation/activation Java Module System JPMS  in PR #1093.
There is also notification system enabled in the Jenkins pipeline to send a mail on unsuccessful and fixed builds and some minor release scripts changes.
> [master] Jenkins build - switch to JDK 11

- uploadToNexus.xml
There is small fix related with changes in #1055 "[2.7] use o.e.p.asm from maven central" .
This is fix for "Publishing artifacts to Jakarta Snapshots" build stage in Jenkins.
See error message at https://ci.eclipse.org/eclipselink/job/eclipselink-nightly-2.7/162/console .
> [2.7] Ant/Jenkins build - Snapshots Publishing fix

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/sessions/UnitOfWorkImpl.java
There is change in log message severity and log category. This log message is also produced if persistence `eclipselink.cache.extended.logging` is set to true instead of previous `eclipselink.thread extended.logging`.
> [2.6] Extended Thread logging - Cache thread info change

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/sessions/UnitOfWorkImpl.java
There is change in log message severity and log category. This log message is also produced if persistence `eclipselink.cache.extended.logging` is set to true instead of previous `eclipselink.thread.extended.logging`.
> [master] Extended Thread logging - Cache thread info change

- .github/workflows/codeql-analysis.yml
GitHub now offers static analysis scans for open-source projects. The scans are based on CodeQL engine that is also used on LGTM.com
https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code/enabling-code-scanning-for-a-repository
When enabled on pull requests, the scans help to prevent introducing multiple issues (including security ones).
This pull requests adds a GitHub action that runs a scan for master branch and pull requests.
This fixes #946
Signed-off-by: Artem Smotrakov <artem.smotrakov@gmail.com>
> [master] Set up CodeQL checks

- bundles/eclipselink/pom.xml
- bundles/others/src/main/assembly/eclipselink-plugins.zip.xml
- etc/jenkins/build.groovy
- etc/jenkins/build_asm.groovy
- etc/jenkins/release.groovy
- etc/jenkins/release_asm.groovy
This is fix for the bug #1107 "Incorrect content of the bundles at Eclipse.org download pages for versions 3.0.0 and higher."
There is also change in Jenkins pipelines from OpenJDK to AdoptOpenJDK as AdoptOpenJDK integrates latest JDK fixes more quickly.
> [master] Maven build - Plugin bundle content fix

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/OraclePlatform.java
This is fix related with changes in #1085 "Bug 573094: TRIM function generates incorrect SQL for CriteriaBuilder" based on bug #1084 "Bug 573094: TRIM function generates incorrect SQL for CriteriaBuilder".
It's cover Oracle DB (OraclePlatform). In Oracle DB `LTRIM` and `RTRIM` are simple SQL functions with two arguments see
LTRIM   https://docs.oracle.com/database/121/SQLRF/functions108.htm#SQLRF00664
RTRIM  https://docs.oracle.com/database/121/SQLRF/functions174.htm#SQLRF06104
Before this fix there were test failures in
CORE: `org.eclipse.persistence.testing.tests.expressions.ReadAllExpressionTest.RightTrim`
JPA: `org.eclipse.persistence.testing.tests.jpa.relationships.ExpressionJUnitTestSuite.testLeftTrimWithTrimChar(ExpressionJUnitTestSuite.java:100)` …
> [master] Bug 573094: TRIM function generates incorrect SQL for CriteriaBuilder (Oracle platform fix)

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/OraclePlatform.java
This is fix related with changes in #1085 "Bug 573094: TRIM function generates incorrect SQL for CriteriaBuilder" based on bug #1084 "Bug 573094: TRIM function generates incorrect SQL for CriteriaBuilder".
It's cover Oracle DB (OraclePlatform). In Oracle DB `LTRIM` and `RTRIM` are simple SQL functions with two arguments see
LTRIM   https://docs.oracle.com/database/121/SQLRF/functions108.htm#SQLRF00664
RTRIM  https://docs.oracle.com/database/121/SQLRF/functions174.htm#SQLRF06104
Before this fix there were test failures in
CORE: `org.eclipse.persistence.testing.tests.expressions.ReadAllExpressionTest.RightTrim`
JPA: `org.eclipse.persistence.testing.tests.jpa.relationships.ExpressionJUnitTestSuite.testLeftTrimWithTrimChar(ExpressionJUnitTestSuite.java:100)` …
> [3.0] Bug 573094: TRIM function generates incorrect SQL for CriteriaBuilder (Oracle platform fix) (#1129) - backport from master

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/OraclePlatform.java
This is fix related with changes in #1085 "Bug 573094: TRIM function generates incorrect SQL for CriteriaBuilder" based on bug #1084 "Bug 573094: TRIM function generates incorrect SQL for CriteriaBuilder".
It's cover Oracle DB (OraclePlatform). In Oracle DB `LTRIM` and `RTRIM` are simple SQL functions with two arguments see
LTRIM   https://docs.oracle.com/database/121/SQLRF/functions108.htm#SQLRF00664
RTRIM  https://docs.oracle.com/database/121/SQLRF/functions174.htm#SQLRF06104
Before this fix there were test failures in
CORE: `org.eclipse.persistence.testing.tests.expressions.ReadAllExpressionTest.RightTrim`
JPA: `org.eclipse.persistence.testing.tests.jpa.relationships.ExpressionJUnitTestSuite.testLeftTrimWithTrimChar(ExpressionJUnitTestSuite.java:100)` …
> [2.7] Bug 573094: TRIM function generates incorrect SQL for CriteriaBuilder (Oracle platform fix) (#1129) - backport from master

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/oxm/XMLMarshaller.java
- moxy/org.eclipse.persistence.moxy/src/test/java/org/eclipse/persistence/testing/oxm/xmlmarshaller/CustomCharacterEscapeHandler.java
- moxy/org.eclipse.persistence.moxy/src/test/java/org/eclipse/persistence/testing/oxm/xmlmarshaller/XMLMarshalTestCases.java
Bugfix + unit test for "Indention not working if custom CharacterEscapeHandler is set and encoding is set to 'UTF-8" bug #1119 .
> [master] Bugfix for - Indention not working if custom CharacterEscapeHandler is set and encoding is set to 'UTF-8

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/oxm/XMLMarshaller.java
- moxy/org.eclipse.persistence.moxy/src/test/java/org/eclipse/persistence/testing/oxm/xmlmarshaller/CustomCharacterEscapeHandler.java
- moxy/org.eclipse.persistence.moxy/src/test/java/org/eclipse/persistence/testing/oxm/xmlmarshaller/XMLMarshalTestCases.java
Bugfix + unit test for "Indention not working if custom CharacterEscapeHandler is set and encoding is set to 'UTF-8" bug #1119 .
(cherry picked from commit 7f68c9ec5a6f822c496cc68b0a05e3b5ecb52e8e)
> [3.0] Bugfix for - Indention not working if custom CharacterEscapeHandler is set and encoding is set to 'UTF-8 - backport from master

- jpa/org.eclipse.persistence.jpars/pom.xml
- jpa/org.eclipse.persistence.jpars/src/it/resources/META-INF/persistence.xml
Behind this fix is some issue with `org.apache.felix:maven-bundle-plugin`. This plugin inserts into generated `MANIFEST.MF` file Maven project properties, but only properties in capital characters. Maven properties in lowercase characters are ignored and not included into manifest. I tried to upgrade into latest version of `org.apache.felix:maven-bundle-plugin:5.1.2`, but without any change.
> [master] Maven build - JPARS module Manifest generation

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/oxm/XMLMarshaller.java
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/oxm/xmlmarshaller/CustomCharacterEscapeHandler.java
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/oxm/xmlmarshaller/XMLMarshalTestCases.java
Bugfix + unit test for "Indention not working if custom CharacterEscapeHandler is set and encoding is set to 'UTF-8" bug.
> [2.7] Bugfix for - Indention not working if custom CharacterEscapeHandler is set and encoding is set to 'UTF-8 - backport from master

- jpa/org.eclipse.persistence.jpars/pom.xml
- jpa/org.eclipse.persistence.jpars/src/it/resources/META-INF/persistence.xml
Behind this fix is some issue with `org.apache.felix:maven-bundle-plugin`. This plugin inserts into generated `MANIFEST.MF` file Maven project properties, but only properties in capital characters. Maven properties in lowercase characters are ignored and not included into manifest. I tried to upgrade into latest version of `org.apache.felix:maven-bundle-plugin:5.1.2`, but without any change.
> [3.0] Maven build - JPARS module Manifest generation - backport from master

- bundles/eclipselink/pom.xml
- bundles/others/src/main/assembly/eclipselink-plugins.zip.xml
This is fix for the bug #1107 "Incorrect content of the bundles at Eclipse.org download pages for versions 3.0.0 and higher".
> [3.0] Maven build - Plugin bundle content fix - backport from master

- .lgtm.yml
Updates:
- Set Java and Maven version in the LGTM config. For some reason, jobs on LGTM still fail because Maven Enforcer complains about Maven version. Maybe it's a bug in LGTM. To overcome this, `-Denforcer.skip` has been added to the build command. LGTM uses Maven 3.6.0 by default that works for EclipseLink.
- ~Updated the CodeQL workflow to analyse pull requests against all branches, not only master.~
Java build passes with the updated config:
https://lgtm.com/logs/6866d0b9a7d8f2f98e882d4e5a0115c8d1efab85/lang:java
Fixes #1159
Signed-off-by: Artem Smotrakov <artem.smotrakov@gmail.com>
> [master] Better config for CodeQL analysis

- utils/org.eclipse.persistence.dbws.builder/src/org/eclipse/persistence/tools/dbws/Util.java
Bugfix for "DBWS Builder generates incorrect ORM mapping for SQL TIMESTAMP" #1162 
> [2.6] DBWS Builder generates incorrect ORM mapping for SQL TIMESTAMP bugfix

- utils/org.eclipse.persistence.dbws.builder/src/org/eclipse/persistence/tools/dbws/Util.java
Bugfix for "DBWS Builder generates incorrect ORM mapping for SQL TIMESTAMP" #1162
> [2.7] DBWS Builder generates incorrect ORM mapping for SQL TIMESTAMP bugfix - backport from 2.6

- utils/org.eclipse.persistence.dbws.builder/src/main/java/org/eclipse/persistence/tools/dbws/Util.java
Bugfix for "DBWS Builder generates incorrect ORM mapping for SQL TIMESTAMP" #1162
> [3.0] DBWS Builder generates incorrect ORM mapping for SQL TIMESTAMP bugfix - backport from 2.6

- utils/org.eclipse.persistence.dbws.builder/src/main/java/org/eclipse/persistence/tools/dbws/Util.java
Bugfix for "DBWS Builder generates incorrect ORM mapping for SQL TIMESTAMP" #1162
> [master] DBWS Builder generates incorrect ORM mapping for SQL TIMESTAMP bugfix - backport from 2.6

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/config/PersistenceUnitProperties.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/descriptors/ObjectBuilder.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/helper/ConcurrencyUtil.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/identitymaps/CacheKey.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/identitymaps/IdentityMapManager.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/localization/i18n/LoggingLocalizationResource.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/localization/i18n/TraceLocalizationResource.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/sessions/IdentityMapAccessor.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/sessions/UnitOfWorkImpl.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/logging/LogCategory.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/logging/SessionLog.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/sessions/Project.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/EntityManagerSetupImpl.java
This is backport from 2.6 PRs #1080, #1101, #1121 and master #1076.
This commit contains extension to logging code.
Main purpose is display info if cached entity is picked by another thread and WorkManager is called in different threads.
Log cached item lifecycle events (insert, refresh, remove, invalidate) from cache.
This logging is by default disabled and must be enabled by persistence properties
Major changes are:
- new thread log category specified in `org.eclipse.persistence.logging.LogCategory` and `org.eclipse.persistence.logging.SessionLog`
- three new persistence unit properties `eclipselink.cache.extended.logging` about cached item lifecycle, `eclipselink.thread.extended.logging` to enable this logging and `eclipselink.thread.extended.logging.threaddump` to add to the log …
> Extended logging of JPA L2 cache usage and UnitOfWork with thread info - backport from 2.6 and master

- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/query/TestQueryHaving.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/querydef/AbstractQueryImpl.java
> [master] Bug 417259: Add support for parameters within CriteriaBuilder HAVING clause

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/descriptors/ClassDescriptor.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/mappings/OneToManyMapping.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/mapping/TestMultitenantOneToMany.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/mapping/model/ChildMultitenant.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/mapping/model/ParentMultitenant.java
Fix #1161: Clone appropriate fields in OneToManyMapping.clone(). 
Fix ConcurrentModificationException when EntityManager.find() is called in multithread environment.
> Fix #1161: Clone appropriate fields in OneToManyMapping.clone(). Fix ConcurrentModificationException.

- etc/jenkins/build.groovy
- etc/jenkins/build_asm.groovy
- etc/jenkins/pr_verify.groovy
- etc/jenkins/release.groovy
- etc/jenkins/release_asm.groovy
- etc/jenkins/tck.groovy
This PR contains two parts:
- New Jenkins pipeline which will be used by GitHub pull request verification job as a replacement for Travis-CI (.org)
- Fixes in current Jenkins pipelines to reflect some changes made by Eclipse.org stuff. Without these fixes Jenkins jobs should throw errors like `java.lang.RuntimeException: [ssh-agent] Could not find a suitable ssh-agent provider.`
> [master] Jenkins pipelines - GitHub PR verification and SSH ID fix

- etc/jenkins/build.groovy
- etc/jenkins/pr_verify.groovy
- etc/jenkins/release.groovy
> [3.0] Jenkins pipelines - GitHub PR verification and SSH ID fix

- bundles/eclipselink/pom.xml
- bundles/nightly/pom.xml
- bundles/others/pom.xml
- bundles/others/src/main/assembly/eclipselink-plugins.zip.xml
- bundles/pom.xml
- pom.xml
This is fix for issue related with eclipselink-plugins.zip bundle.
Main purpose of this fix is to keep names of the `orc.eclipse.persistence` artifacts packed in `eclipselink-plugins.zip` bundle consistent with older versions of the EclipseLink.
EclipseLink artifacts in eclipselink-plugins-*.zip are named in the same way as in 2.6, 2.7 bundles
e.g. `org.eclipse.persistence.core_2.7.9.v20210604-2c549e2208.jar`	x	`org.eclipse.persistence.core_3.0.2.v20210610-1fda5b4d4e.jar`
`MANIFEST.MF` content is changed too.
`Bundle-Version` contains `major.minor.micro.version.vYYYYMMDDHHmm` e.g. `Bundle-Version: 3.0.2.v202106101448`
plus new additional properties e.g.
```
Implementation-Version: 3.0.2-SNAPSHOT
Implementation-SCM-Revision: 1fda5b4d4e
Implementation-SCM-Branch: 3.0
```
Some note about …
> [3.0] Maven/Nightly build fix - bundle names change

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/descriptors/ObjectBuilder.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/models/jpa/advanced/fetchgroup/AdvancedFetchGroupTableCreator.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/models/jpa/advanced/fetchgroup/Helmet.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/models/jpa/advanced/fetchgroup/Shelf.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa/advanced/fetchgroup/AdvancedFetchGroupJunitTest.java
Backport of https://bugs.eclipse.org/bugs/show_bug.cgi?id=485984 to 2.6_WAS
> [2.6_WAS] Bug 485984: When object obtained thru em.getReference() is cached, and retrieved later in a txn

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/descriptors/ClassDescriptor.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/mappings/OneToManyMapping.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/mapping/TestMultitenantOneToMany.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/mapping/model/ChildMultitenant.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/mapping/model/ParentMultitenant.java
Fix #1161: Clone appropriate fields in OneToManyMapping.clone(). Fix ConcurrentModificationException. (backport for 3.0)
> Fix #1161: Clone appropriate fields in OneToManyMapping.clone(). Fix ConcurrentModificationException. (backport for 3.0)

- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/returninsert/TestReturnInsert.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/cachedeadlock/CacheDeadLockDetectionTest.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/conversion/TestJavaTimeTypeConverter.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/criteria/TestCoalesceFunction.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/criteria/model/CoalesceEntity.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/criteria/model/CoalesceEntity_.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/query/TestQueryHints.java
1. CacheDeadLockDetectionTest - Failing on DB2
```
Internal Exception: com.ibm.db2.jcc.am.SqlSyntaxErrorException: DB2 SQL Error: SQLCODE=-542, SQLSTATE=42831, SQLERRMC=ID, DRIVER=3.72.24
Error Code: -542
Call: CREATE TABLE cachedeadlock_master (id integer PRIMARY KEY, name varchar(200))
```
This failure is because DB2 expects the "NOT NULL" clause for PRIMARY KEY columns: https://www.ibm.com/docs/en/db2-for-zos/11?topic=codes-542 
2. TestJavaTimeTypeConverter.timeConvertUtilDateToLocalDate - Failing depending on the JDK locale
```
<failure message="expected: '120' but was: '119'" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: expected: '120' but was: '119'
at org.eclipse.persistence.jpa.test.conversion.TestJavaTimeTypeConverter.timeConvertUtilDateToLocal …
```
> [master] Minor JSE test failure fixes

- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/metadata/accessors/objects/MetadataAsmFactory.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/weaving/ClassWeaver.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/weaving/MethodWeaver.java
- pom.xml
Eclipselink*Visitor types have been added to the Eclipselink ASM project, which moves the use of the ASM# constants out of the Eclipselink project and into the Eclipselink ASM project.  This should make it easier to avoid missing updating all of the constants when moving up to new major versions of ASM.
> [Master] Update Eclipselink to use Eclipselink*Visitor types

- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/returninsert/TestReturnInsert.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/cachedeadlock/CacheDeadLockDetectionTest.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/conversion/TestJavaTimeTypeConverter.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/criteria/TestCoalesceFunction.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/criteria/model/CoalesceEntity.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/criteria/model/CoalesceEntity_.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/property/TestConvertResultToBoolean.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/query/TestQueryHints.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/query/TestQueryProperties.java
5. TestQueryProperties / TestQueryHints - Failing on Oracle
```
Caused by: java.sql.SQLSyntaxErrorException: ORA-00955: name is already used by an existing object
at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:447)
at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:396)
at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:951)
```
Failing because drop/create was not used for all EMFs. Not sure why Oracle specifically had issues with this an no other database...
6. TestConvertResultToBoolean - Failing on DB2 & Oracle
On Oracle, the return type is BigDecimal and on DB2/Derby, the return type is Integer.
> [2.7] Minor JSE test failure fixes

- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/returninsert/TestReturnInsert.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/cachedeadlock/CacheDeadLockDetectionTest.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/conversion/TestJavaTimeTypeConverter.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/criteria/TestCoalesceFunction.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/criteria/model/CoalesceEntity.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/criteria/model/CoalesceEntity_.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/query/TestQueryHints.java
5. TestQueryProperties / TestQueryHints - Failing on Oracle
```
Caused by: java.sql.SQLSyntaxErrorException: ORA-00955: name is already used by an existing object
at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:447)
at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:396)
at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:951)
```
Failing because drop/create was not used for all EMFs. Not sure why Oracle specifically had issues with this an no other database...
6. TestConvertResultToBoolean - Failing on DB2 & Oracle
On Oracle, the return type is BigDecimal and on DB2/Derby, the return type is Integer.
> [3.0] Minor JSE test failure fixes

- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/metadata/accessors/objects/MetadataAsmFactory.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/weaving/ClassWeaver.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/weaving/MethodWeaver.java
- pom.xml
Eclipselink*Visitor types have been added to the Eclipselink ASM project, which moves the use of the ASM# constants out of the Eclipselink project and into the Eclipselink ASM project. This should make it easier to avoid missing updating all of the constants when moving up to new major versions of ASM.
(Updating to use Eclipselink ASM 9.1.1)
> [3.0] Update Eclipselink to use Eclipselink*Visitor types

- buildsystem/compdeps/pom.xml
- dbws/org.eclipse.persistence.dbws/META-INF/MANIFEST.MF
- foundation/org.eclipse.persistence.core/META-INF/MANIFEST.MF
- jpa/org.eclipse.persistence.jpa/META-INF/MANIFEST.MF
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/metadata/accessors/objects/MetadataAsmFactory.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/weaving/ClassWeaver.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/weaving/MethodWeaver.java
- moxy/org.eclipse.persistence.moxy/META-INF/MANIFEST.MF
- sdo/org.eclipse.persistence.sdo/META-INF/MANIFEST.MF
Eclipselink*Visitor types have been added to the Eclipselink ASM project, which moves the use of the ASM# constants out of the Eclipselink project and into the Eclipselink ASM project. This should make it easier to avoid missing updating all of the constants when moving up to new major versions of ASM.
(Updating to use Eclipselink ASM 9.1.1)
> [2.7] Update Eclipselink to use Eclipselink*Visitor types

- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/criteria/TestCoalesceFunction.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/criteria/model/CoalesceEntity.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/criteria/model/CoalesceEntity_.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/property/TestConvertResultToBoolean.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/query/TestQueryHints.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/query/TestQueryProperties.java
1. CacheDeadLockDetectionTest - Failing on DB2
```
Internal Exception: com.ibm.db2.jcc.am.SqlSyntaxErrorException: DB2 SQL Error: SQLCODE=-542, SQLSTATE=42831, SQLERRMC=ID, DRIVER=3.72.24
Error Code: -542
Call: CREATE TABLE cachedeadlock_master (id integer PRIMARY KEY, name varchar(200))
```
This failure is because DB2 expects the "NOT NULL" clause for PRIMARY KEY columns: https://www.ibm.com/docs/en/db2-for-zos/11?topic=codes-542 
2. TestJavaTimeTypeConverter.timeConvertUtilDateToLocalDate - Failing depending on the JDK locale
```
<failure message="expected: '120' but was: '119'" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: expected: '120' but was: '119'
at org.eclipse.persistence.jpa.test.conversion.TestJavaTimeTypeConverter.timeConvertUtilDateToLocal …
```
> [2.6_WAS] Minor JSE test failure fixes

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/queries/BatchFetchPolicy.java
> [3.0] Bug 1245: NullPointerException from BatchFetchPolicy dataResults

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/helper/ConcurrencyUtil.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/localization/i18n/LoggingLocalizationResource.java
Minor fix in logging output to remove <ENTITY>.toString() call during logging. It should be potentially not safe (e.g. resources consuming, dead-lock, infinite loop). Class name and primary key is enough there to identify cache object.
> [2.6] ConcurrencyManager dead-lock detection diagnostic improvement 2.0.2 - backport from master

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/helper/ConcurrencyUtil.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/localization/i18n/TraceLocalizationResource.java
Minor fix in logging output to remove <ENTITY>.toString() call during logging. It should be potentially not safe (e.g. resources consuming, dead-lock, infinite loop). Class name and primary key is enough there to identify cache object.
> [3.0] ConcurrencyManager dead-lock detection diagnostic improvement 2.0.2 - backport

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/helper/ConcurrencyUtil.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/localization/i18n/TraceLocalizationResource.java
Minor fix in logging output to remove `<ENTITY>.toString()` call during logging. It should be potentially not safe (e.g. resources consuming, dead-lock, infinite loop). Class name and primary key is enough there to identify cache object.
> [master] ConcurrencyManager dead-lock detection diagnostic improvement 2.0.2

- etc/jenkins/release.groovy
This is fix for `git push` call, which failed with `git@github.com: Permission denied (publickey).` error message. It's related with some Eclipse-CI infrastructure security settings. `release.sh` script must be called within `el-build` container and this container is wrapped by `sshagent([SSH_CREDENTIALS_ID]) {`.
Opposite nesting `sshagent([SSH_CREDENTIALS_ID]) {` inside `container('el-build') {` instruction leads into error.
> [3.0] Jenkins release job fix

- etc/jenkins/build.sh
- etc/jenkins/publish_snapshots.sh
- etc/jenkins/release.sh
- etc/jenkins/test.sh
- etc/jenkins/test_nosql.sh
- etc/jenkins/test_server.sh
This fix removes `. /etc/profile` call from scripts called by various Jenkins pipelines.
In `. /etc/profile` was hardcoded JDK 8 so Jenkins build/test didn't reflect JDK settings from pipeline.
> [3.0] Jenkins build fix to reflect/use JDK specified in the Jenkins pipeline

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/descriptors/DescriptorQueryManager.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/descriptors/WrapperPolicy.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/dynamic/DynamicEntity.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/databaseaccess/DatabasePlatform.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/expressions/RelationExpression.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/localization/i18n/DMSLocalizationResource.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/localization/i18n/LoggingLocalizationResource.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/oxm/XMLMarshaller.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/oxm/XMLSequencedDescriptor.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/sessions/AbstractSession.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/sessions/CommitOrderCalculator.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/sessions/factories/SessionsFactory.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/mappings/OneToOneMapping.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/oxm/mappings/XMLAnyAttributeMapping.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/server/ServerPlatform.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/server/ServerPlatformBase.java
- foundation/org.eclipse.persistence.nosql/src/main/java/org/eclipse/persistence/internal/eis/cobol/helper/Helper.java
- jpa/org.eclipse.persistence.jpa.jpql/src/main/java/org/eclipse/persistence/jpa/jpql/ExpressionTools.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/deployment/DirectoryArchive.java
- moxy/org.eclipse.persistence.moxy/src/main/java/org/eclipse/persistence/jaxb/compiler/AnnotationsProcessor.java
- moxy/org.eclipse.persistence.moxy/src/main/java/org/eclipse/persistence/jaxb/javamodel/xjc/XJCJavaClassImpl.java
- sdo/org.eclipse.persistence.sdo/src/main/java/org/eclipse/persistence/sdo/helper/SDOTypesGenerator.java
> few errors/warnings from static analysis

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/databaseaccess/DatabasePlatform.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/helper/ComplexDatabaseType.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/mappings/structures/ObjectRelationalDataTypeDescriptor.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/oracle/plsql/PLSQLStoredProcedureCall.java
- foundation/org.eclipse.persistence.oracle/src/main/java/org/eclipse/persistence/platform/database/oracle/Oracle12Platform.java
- jpa/eclipselink.jpa.test/src/it/java/org/eclipse/persistence/testing/models/jpa/plsql/InnerObjBlob.java
- jpa/eclipselink.jpa.test/src/it/java/org/eclipse/persistence/testing/models/jpa/plsql/OuterObjBlob.java
- jpa/eclipselink.jpa.test/src/it/java/org/eclipse/persistence/testing/models/jpa/plsql/SaveComplexBlob.java
- jpa/eclipselink.jpa.test/src/it/java/org/eclipse/persistence/testing/tests/jpa/plsql/PLSQLTestSuite.java
Fixes #1299
Bugfix and unit test.
[Oracle_Test_Results.zip](https://github.com/eclipse-ee4j/eclipselink/files/7175620/Oracle_Test_Results.zip)
> [master] SQL Struct with @Lob (BLOB, CLOB) used as stored procedure parameter type - fix

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/security/PrivilegedAccessHelper.java
- jpa/org.eclipse.persistence.jpars.server/src/main/java/org/eclipse/persistence/jpa/rs/util/PreLoginMappingAdapter.java
- moxy/org.eclipse.persistence.moxy/src/main/java/org/eclipse/persistence/internal/jaxb/MultiArgInstantiationPolicy.java
- moxy/org.eclipse.persistence.moxy/src/main/java/org/eclipse/persistence/internal/jaxb/XMLJavaTypeConverter.java
- moxy/org.eclipse.persistence.moxy/src/main/java/org/eclipse/persistence/jaxb/JAXBBeanValidator.java
- moxy/org.eclipse.persistence.moxy/src/main/java/org/eclipse/persistence/jaxb/JAXBContext.java
- moxy/org.eclipse.persistence.moxy/src/main/java/org/eclipse/persistence/jaxb/JAXBEnumTypeConverter.java
- moxy/org.eclipse.persistence.moxy/src/main/java/org/eclipse/persistence/jaxb/JAXBMarshalListener.java
- moxy/org.eclipse.persistence.moxy/src/main/java/org/eclipse/persistence/jaxb/JAXBUnmarshalListener.java
- moxy/org.eclipse.persistence.moxy/src/main/java/org/eclipse/persistence/jaxb/MOXySystemProperties.java
- moxy/org.eclipse.persistence.moxy/src/main/java/org/eclipse/persistence/jaxb/ReflectionUtils.java
- moxy/org.eclipse.persistence.moxy/src/main/java/org/eclipse/persistence/jaxb/ValidationXMLReader.java
- moxy/org.eclipse.persistence.moxy/src/main/java/org/eclipse/persistence/jaxb/compiler/MappingsGenerator.java
- moxy/org.eclipse.persistence.moxy/src/main/java/org/eclipse/persistence/jaxb/compiler/MarshalCallback.java
- moxy/org.eclipse.persistence.moxy/src/main/java/org/eclipse/persistence/jaxb/compiler/UnmarshalCallback.java
- moxy/org.eclipse.persistence.moxy/src/main/java/org/eclipse/persistence/jaxb/dynamic/DynamicJAXBContext.java
- moxy/org.eclipse.persistence.moxy/src/main/java/org/eclipse/persistence/jaxb/plugins/BeanValidationPlugin.java
- moxy/org.eclipse.persistence.moxy/src/test/java/org/eclipse/persistence/testing/oxm/classloader/JARClassLoader.java
Classes to be removed:
- PrivilegedClassForName
- PrivilegedMethodInvoker
- PrivilegedNewInstanceFromClass
> Prepare for the removal of the securitymanager in moxy.

- foundation/org.eclipse.persistence.oracle/src/main/java/org/eclipse/persistence/platform/database/oracle/Oracle12Platform.java
Additional fix in `Oracle12Platform` class to use standard `java.sql.Connection.createStruct(....)` method instead of `org.eclipse.persistence.platform.database.oracleOracle8Platform.createStruct(...)` with deprecated `new oracle.sql.STRUCT(...)` call.
> [master] SQL Struct with @Lob (BLOB, CLOB) used as stored procedure parameter type - fix 2.0

- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/weave/TestWeaving.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/weave/model/WeavedAbstractMS.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/weave/model/WeavedEntityA.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/weaving/TransformerFactory.java
> [master] Bug 412391: Add support for hidden mappedsuperclass attributes

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/helper/ConcurrencyManager.java
for #1343
Signed-off-by: Joshua Dettinger <joshuad@us.ibm.com>
> [3.0] Bug 1343: Remove getStackTrace to fix throughput degredation

- buildsystem/compdeps/pom.xml
- dbws/org.eclipse.persistence.dbws/META-INF/MANIFEST.MF
- foundation/org.eclipse.persistence.core/META-INF/MANIFEST.MF
- jpa/org.eclipse.persistence.jpa/META-INF/MANIFEST.MF
- moxy/org.eclipse.persistence.moxy/META-INF/MANIFEST.MF
- sdo/org.eclipse.persistence.sdo/META-INF/MANIFEST.MF
Update Eclipselink 2.7 to use Eclipselink ASM 9.2.0.
> [2.7] Update ECL 2.7 to use Eclipselink ASM 9.2.0.

- pom.xml
> [3.0] Update Eclipselink 3.0 to use Eclipselink ASM 9.2.0

- foundation/eclipselink.core.test/src/it/java/org/eclipse/persistence/testing/tests/expressions/ExpressionOperatorUnitTestSuite.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/expressions/ExpressionOperator.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/expressions/ListExpressionOperator.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/expressions/ArgumentListFunctionExpression.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/expressions/ExpressionOperatorConverter.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/concurrency/TestConcurrencyPersistence.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/concurrency/model/User.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/query/TestQueryCase.java
> [master] Bug 463042: Concurrency issue with Case expression operator

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/expressions/ArgumentListFunctionExpression.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/concurrency/TestConcurrencyPersistence.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/concurrency/model/User.java
> [2.7] Bug 463042: Concurrency issue with Case expression operator

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/databaseaccess/DatabasePlatform.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/helper/ComplexDatabaseType.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/mappings/structures/ObjectRelationalDataTypeDescriptor.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/oracle/plsql/PLSQLStoredProcedureCall.java
- foundation/org.eclipse.persistence.oracle/src/main/java/org/eclipse/persistence/platform/database/oracle/Oracle12Platform.java
- jpa/eclipselink.jpa.test/src/it/java/org/eclipse/persistence/testing/models/jpa/plsql/InnerObjBlob.java
- jpa/eclipselink.jpa.test/src/it/java/org/eclipse/persistence/testing/models/jpa/plsql/OuterObjBlob.java
- jpa/eclipselink.jpa.test/src/it/java/org/eclipse/persistence/testing/models/jpa/plsql/SaveComplexBlob.java
- jpa/eclipselink.jpa.test/src/it/java/org/eclipse/persistence/testing/tests/jpa/plsql/PLSQLTestSuite.java
Fixes #1299
Bugfix and unit test.
Signed-off-by: Radek Felcman radek.felcman@oracle.com
> [3.0] SQL Struct with @Lob (BLOB, CLOB) used as stored procedure parameter type - backport from master

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/queries/ExpressionQueryMechanism.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/returninsert/TestReturnInsert.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/returninsert/model/ReturnInsertDetail.java
Standalone usage ReturnUpdate annotation was broken in PR #1016.
fixes #1363
(cherry picked from commit fb1cc69d09a70bf74935132181a105ddd37e07d6)
> [3.0] problems with session customizer when upgrading to 2.7.9 - bugfix + unit test (#1364) - backport from master

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/localization/i18n/ExceptionLocalizationResource.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/models/jpa/metamodel/Bar.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/models/jpa/metamodel/Foo.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/models/jpa/metamodel/FooBar.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/models/jpa/metamodel/FooBarId.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa/metamodel/MetamodelMetamodelTest.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa/metamodel/MetamodelTableCreator.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/metamodel/IdentifiableTypeImpl.java
Because there are four new objects (java classes) in org.eclipse.persistence.testing.models.jpa.metamodel package MetamodelMetamodelTest.METAMODEL_ALL_TYPES is increased into 56.
These four objects have eights new attributes. This is why MetamodelMetamodelTest.METAMODEL_ALL_ATTRIBUTES_SIZE is increased into 158.
fixes #1228
> [2.7] IdentifiableTypeImpl throws IllegalArgumentException with EmbeddedId and relations - bugfix + unit test - backport from master

- bundles/eclipselink/pom.xml
- dbws/eclipselink.dbws.test.oracle/pom.xml
- foundation/eclipselink.extension.oracle.spatial.test/pom.xml
- foundation/org.eclipse.persistence.oracle.nosql/pom.xml
- foundation/org.eclipse.persistence.oracle.test/pom.xml
- foundation/org.eclipse.persistence.oracle.test/src/it/java/org/eclipse/persistence/testing/framework/oracle/SessionExchanger.java
- foundation/org.eclipse.persistence.oracle.test/src/it/java/org/eclipse/persistence/testing/tests/distributedservers/rcm/jms/JMSSetupHelper.java
- foundation/org.eclipse.persistence.oracle.test/src/it/java/org/eclipse/persistence/testing/tests/jpa/proxyauthentication/ProxyAuthenticationTestSuite.java
- foundation/org.eclipse.persistence.oracle.test/src/it/java/org/eclipse/persistence/testing/tests/proxyauthentication/oci/ProxyTestHelper.java
- foundation/org.eclipse.persistence.oracle/pom.xml
- jpa/eclipselink.jpa.oracle.test/pom.xml
- pom.xml
- utils/eclipselink.dbws.builder.test.oracle/pom.xml
In 21.3.0.0 are some changes in:
1. Maven artifacts naming (groupId)
2. Some deprecated methods in 19.3.0.0 were removed in 21.3.0.0 (e.g. close(), DataSources with connection pooling has to be created by Oracle Universal Connection Pool API)
> [master] Oracle dependencies update (JDBC Driver, XMLParser, DMS) to 21c

- jpa/eclipselink.jpa.test/src/it/java/org/eclipse/persistence/testing/tests/jpa/advanced/PersistenceUnitProcessorTest.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/deployment/PersistenceUnitProcessor.java
This small fix allows using/loading persistence.xml from WAR file from `.../WEB-INF/classes/META-INF/persistence.xml` location in JSE environment.
It is still required to point EclipseLink (EntityManagerFactory) to this location in JSE environment by:
`System.setProperty(PersistenceUnitProperties.ECLIPSELINK_PERSISTENCE_XML, "WEB-INF/classes/META-INF/persistence.xml");`
or
``
Properties persistenceUnitProperties = new Properties();
persistenceUnitProperties.setProperty(PersistenceUnitProperties.ECLIPSELINK_PERSISTENCE_XML, "WEB-INF/classes/META-INF/persistence.xml");
EntityManagerFactory entityManagerFactory = Persistence.createEntityManagerFactory("test-jpa-pu2", persistenceUnitProperties);
``
Before this fix ValidationException
e.g.
``
Internal Exception: Exception [EclipseLink-7357] …
> Bug in the PersistenceUnitProcessor.findPersistenceArchives(ClassLoader loader, String descriptorPath) - bugfix

- bundles/eclipselink/pom.xml
- dbws/eclipselink.dbws.test.oracle/pom.xml
- foundation/eclipselink.extension.oracle.spatial.test/pom.xml
- foundation/org.eclipse.persistence.oracle.nosql/pom.xml
- foundation/org.eclipse.persistence.oracle.test/pom.xml
- foundation/org.eclipse.persistence.oracle.test/src/it/java/org/eclipse/persistence/testing/framework/oracle/SessionExchanger.java
- foundation/org.eclipse.persistence.oracle.test/src/it/java/org/eclipse/persistence/testing/tests/distributedservers/rcm/jms/JMSSetupHelper.java
- foundation/org.eclipse.persistence.oracle.test/src/it/java/org/eclipse/persistence/testing/tests/jpa/proxyauthentication/ProxyAuthenticationTestSuite.java
- foundation/org.eclipse.persistence.oracle.test/src/it/java/org/eclipse/persistence/testing/tests/proxyauthentication/oci/ProxyTestHelper.java
- foundation/org.eclipse.persistence.oracle/pom.xml
- jpa/eclipselink.jpa.oracle.test/pom.xml
- pom.xml
- utils/eclipselink.dbws.builder.test.oracle/pom.xml
In 21.3.0.0 are some changes in:
1. Maven artifacts naming (groupId)
2. Some deprecated methods in 19.3.0.0 were removed in 21.3.0.0 (e.g. close(), DataSources with connection pooling has to be created by Oracle Universal Connection Pool API)
(cherry picked from commit 1158e028cff444c23fb22638cb3fcd3aac3e6757)
> [3.0] Oracle dependencies update (JDBC Driver, XMLParser, DMS) to 21c (#1376) - backport from master

- jpa/eclipselink.jpa.test/src/it/java/org/eclipse/persistence/testing/tests/jpa/advanced/PersistenceUnitProcessorTest.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/deployment/PersistenceUnitProcessor.java
This small fix allows using/loading persistence.xml from WAR file from `.../WEB-INF/classes/META-INF/persistence.xml` location in JSE environment.
It is still required to point EclipseLink (EntityManagerFactory) to this location in JSE environment by:
``
System.setProperty(PersistenceUnitProperties.ECLIPSELINK_PERSISTENCE_XML, "WEB-INF/classes/META-INF/persistence.xml");
``
or
``
Properties persistenceUnitProperties = new Properties();
persistenceUnitProperties.setProperty(PersistenceUnitProperties.ECLIPSELINK_PERSISTENCE_XML, "WEB-INF/classes/META-INF/persistence.xml");
EntityManagerFactory entityManagerFactory = Persistence.createEntityManagerFactory("test-jpa-pu2", persistenceUnitProperties);
``
Before this fix ValidationException
e.g.
``
Internal Exception: Exception …
> [3.0] Bug in the PersistenceUnitProcessor.findPersistenceArchives(ClassLoader loader, String descriptorPath) - bugfix - backport from master

- foundation/org.eclipse.persistence.core/pom.xml
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/oxm/OXMSystemProperties.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/oxm/XMLConversionManager.java
- foundation/org.eclipse.persistence.core/src/test/java/org/eclipse/persistence/testing/oxm/systemproperties/DateAndTimeNonDefaultTestCases.java
- foundation/org.eclipse.persistence.core/src/test/java/org/eclipse/persistence/testing/oxm/systemproperties/OXMSystemPropertiesNonDefaultTestCases.java
- foundation/org.eclipse.persistence.core/src/test/java/org/eclipse/persistence/testing/oxm/systemproperties/OXMSystemPropertiesTestCases.java
- foundation/org.eclipse.persistence.core/src/test/java/org/eclipse/persistence/testing/oxm/xmlconversionmanager/DateAndTimeTestCases.java
This new feature optionally add suffix/decimal part to time part/seconds in case of conversion from supported date/time formats into String. This suffix is controlled by new `org.eclipse.persistence.xml.time.suffix` system property.
It happens only if source time doesn't contain fraction of seconds and for XML, JSON conversion. E.g.:
For `-Dorg.eclipse.persistence.xml.time.suffix=.0`
Source value: 2003-08-29T03:00:00-04:00  -> Output string: 2003-08-29T03:00:00.0-04:00
Source value: 1975-02-21T07:47:15  -> Output string: 1975-02-21T07:47:15.0
It simplifies migration from WebLogic Server 11g to 12c.
Origin bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=404069
> [master] Fix/new feature for Bug 404069 - MOXy should not append .0 to time info for dateTime and time formats + unit test

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/oxm/OXMSystemProperties.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/oxm/XMLConversionManager.java
- moxy/eclipselink.moxy.test/antbuild.xml
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/oxm/systemproperties/DateAndTimeNonDefaultTestCases.java
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/oxm/systemproperties/OXMSystemPropertiesNonDefaultTestCases.java
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/oxm/systemproperties/OXMSystemPropertiesTestCases.java
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/oxm/xmlconversionmanager/DateAndTimeTestCases.java
This new feature optionally add suffix/decimal part to time part/seconds in case of conversion from supported date/time formats into String. This suffix is controlled by new `org.eclipse.persistence.xml.time.suffix` system property.
It happens only if source time doesn't contain fraction of seconds and for XML, JSON conversion. E.g.:
For `-Dorg.eclipse.persistence.xml.time.suffix=.0`
Source value: 2003-08-29T03:00:00-04:00  -> Output string: 2003-08-29T03:00:00.0-04:00
Source value: 1975-02-21T07:47:15  -> Output string: 1975-02-21T07:47:15.0
It simplifies migration from WebLogic Server 11g to 12c.
Origin bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=404069
> [2.6] Fix/new feature for Bug 404069 - MOXy should not append .0 to time info for dateTime and time formats + unit test - backport from master

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/oxm/OXMSystemProperties.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/oxm/XMLConversionManager.java
- moxy/org.eclipse.persistence.moxy/pom.xml
- moxy/org.eclipse.persistence.moxy/src/test/java/org/eclipse/persistence/testing/oxm/systemproperties/DateAndTimeNonDefaultTestCases.java
- moxy/org.eclipse.persistence.moxy/src/test/java/org/eclipse/persistence/testing/oxm/systemproperties/OXMSystemPropertiesNonDefaultTestCases.java
- moxy/org.eclipse.persistence.moxy/src/test/java/org/eclipse/persistence/testing/oxm/systemproperties/OXMSystemPropertiesTestCases.java
- moxy/org.eclipse.persistence.moxy/src/test/java/org/eclipse/persistence/testing/oxm/xmlconversionmanager/DateAndTimeTestCases.java
This new feature optionally add suffix/decimal part to time part/seconds in case of conversion from supported date/time formats into String. This suffix is controlled by new `org.eclipse.persistence.xml.time.suffix` system property.
It happens only if source time doesn't contain fraction of seconds and for XML, JSON conversion. E.g.:
For `-Dorg.eclipse.persistence.xml.time.suffix=.0`
Source value: 2003-08-29T03:00:00-04:00  -> Output string: 2003-08-29T03:00:00.0-04:00
Source value: 1975-02-21T07:47:15  -> Output string: 1975-02-21T07:47:15.0
It simplifies migration from WebLogic Server 11g to 12c.
Origin bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=404069
> [3.0] Fix/new feature for Bug 404069 - MOXy should not append .0 to time info for dateTime and time formats + unit test - backport from master

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/databaseaccess/DatasourcePlatform.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/descriptors/ObjectBuilder.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/mappings/foundation/AbstractDirectMapping.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/OraclePlatform.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/embeddable/model/ElementCollectionEmbeddableTemporal.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/lob/TestLobMerge.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/mapping/TestMultitenantOneToMany.java
This PR contains fixes for following test errors if JPA JSE tests are executed against Oracle DB:
1. org.eclipse.persistence.jpa.embeddable.TestCollectionTableEmbeddable
```
[ERROR] Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.281 s <<< FAILURE! - in org.eclipse.persistence.jpa.embeddable.TestCollectionTableEmbeddable
[ERROR] org.eclipse.persistence.jpa.embeddable.TestCollectionTableEmbeddable.mergeTest  Time elapsed: 0.325 s  <<< ERROR!
org.eclipse.persistence.exceptions.ConversionException: 
Exception Description: The object [04-DEC-21 03.56.45.937000000 AM], of class [class java.lang.String], from mapping [org.eclipse.persistence.mappings.DirectToFieldMapping[temporalValue-->EntMapDateTemporal.TEMPORALVALUE]] with descriptor …
```
> [3.0] org.eclipse.persistence.jpa.jse.test test fixes against Oracle DB - backport from master

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/mappings/ForeignReferenceMapping.java
- jpa/eclipselink.jpa.test/src/it/java/org/eclipse/persistence/testing/tests/jpa/advanced/AdvancedJPAJunitTest.java
Fixes #1148 (bugfix + unit test)
> [master] BatchFetchType.IN causes IndexOutOfBoundsException in ForeignReferenceMapping.extractResultsFromBatchQuery

- jpa/org.eclipse.persistence.jpa.modelgen/src/main/java/org/eclipse/persistence/internal/jpa/modelgen/objects/PersistenceUnit.java
- jpa/org.eclipse.persistence.jpa.modelgen/src/test/java/org/eclipse/persistence/jpa/test/modelgen/TestProcessor.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/metadata/xml/XMLEntityMappingsReader.java
- jpa/org.eclipse.persistence.jpa/src/main/resources/org/eclipse/persistence/jpa/eclipselink_orm_3_1.xsd
- jpa/org.eclipse.persistence.jpa/src/main/resources/org/eclipse/persistence/jpa/orm_3_1.xsd
This code change add into EclipseLink new ORM 3.1 schema from JPA 3.1.
There is also version fix in `eclipselink_orm_3_0.xsd`.
> [master] JPA 3.1 (ORM 3.1 implementation)

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/queries/StoredProcedureCall.java
The old implementation causes a NPE if the `session` or the `project` is null in line 1102.  This new implementation of will not.
The session being NULL is plausible, because the `appendLogParameters` function, which is called in line 1111, starts with a NULL check.
> Modified getLogString with more NULL Safety

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/expressions/SQLSelectStatement.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/query/TestQueryOrderBy.java
for #1429
For DB2/Derby, it is illegal to include untyped parameter markers in the ORDER BY clause. There are two JPQL scenarios where these untyped parameters can occur:
1) via JPQL "... ORDER BY ?1"
2) via JPQL "... ORDER BY 1" with `shouldBindLiterals=true`
My previous fix for 578686 included a minor fix to allow databases, that do not support untyped parameters, to disable parameter binding in the event that a marker is used within the ORDER BY clause. This fix was flawed and I ultimately decided it would be best to remove completely. 
The issue is that EclipseLink does not have the ability at this time to disable parameter binding per variable instance and instead disables binding for the whole query. The change that I made, and am now removing, altered existing behavior with …
> [2.6_WAS] Bug 578686: Remove OrderBy parameter binding use case

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/expressions/SQLSelectStatement.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/query/TestQueryOrderBy.java
for #1429
For DB2/Derby, it is illegal to include untyped parameter markers in the ORDER BY clause. There are two JPQL scenarios where these untyped parameters can occur:
1) via JPQL "... ORDER BY ?1"
2) via JPQL "... ORDER BY 1" with `shouldBindLiterals=true`
My previous fix for 578686 included a minor fix to allow databases, that do not support untyped parameters, to disable parameter binding in the event that a marker is used within the ORDER BY clause. This fix was flawed and I ultimately decided it would be best to remove completely. 
The issue is that EclipseLink does not have the ability at this time to disable parameter binding per variable instance and instead disables binding for the whole query. The change that I made, and am now removing, altered existing behavior with …
> [master] Bug 578686: Remove OrderBy parameter binding use case

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/mappings/ForeignReferenceMapping.java
- jpa/eclipselink.jpa.test/src/it/java/org/eclipse/persistence/testing/tests/jpa/advanced/AdvancedJPAJunitTest.java
Fixes #1148 (bugfix + unit test)
> [3.0] BatchFetchType.IN causes IndexOutOfBoundsException in ForeignReferenceMapping.extractResultsFromBatchQuery - backport from master

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/mappings/ForeignReferenceMapping.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa/advanced/AdvancedJPAJunitTest.java
Fixes #1148 (bugfix + unit test)
> [2.7] BatchFetchType.IN causes IndexOutOfBoundsException in ForeignReferenceMapping.extractResultsFromBatchQuery - backport from master

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/MySQLPlatform.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/criteria/TestDateTimeFunctions.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/query/TestDateTimeFunctions.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/query/model/DateTimeQueryEntity.java
DATETIME precision modified to DATETIME(6) to strore microsecond fraction.
Some tests modified to be more stable.
Added test with LocalDateTime.now() in WHERE condition. This scenario was failing in TCK.
> Changed second fraction precision of LocalDateTime and OffsetDateTime MySQL related type.

- jpa/eclipselink.jpa.test/pom.xml
this allows the build to pass on recent jdk19
> Remove models for which static weaving is expected to fail,

- pom.xml
Most important part of this PR is ASM (org.eclipse.persistence.asm) upgrade to 9.3 version.
> [3.0] ASM and Checkstyle dependencies update

- .gitignore
- etc/el-test.mysql.properties
- etc/jenkins/build.groovy
- etc/jenkins/docker/image/Dockerfile
- etc/jenkins/docker/image/install.sh
- etc/jenkins/docker/pom.xml
- etc/jenkins/docker/scripts/mongo-start.sh
- etc/jenkins/docker/scripts/mongo-stop.sh
- etc/jenkins/docker/scripts/mysql-start.sh
- etc/jenkins/docker/scripts/mysql-stop.sh
- etc/jenkins/pr_verify.groovy
- etc/jenkins/release.groovy
- etc/jenkins/tck.groovy
Please do not merge yet. I would like to do few experiments with jobs.
> New EF build image

- .github/codeql/codeql-config.yml
- .github/workflows/codeql-analysis.yml
This change enable/configure LGTM analysis on 2.7 branch built by Ant.
> [2.7] LGTM analysis

- bundles/eclipselink/pom.xml
This is fix for `version.properties` file content included in `eclipselink.jar` bundle.
It more precisely specifies filtered and non-filtered resources included in eclipselink.jar bundle.
> [master] Eclipselink.jar bundle - version.properties fix

- bundles/eclipselink/pom.xml
This is fix for `version.properties` file content included in `eclipselink.jar` bundle.
Before this fix version information related properties like `${release.version}, ${build.*}` wasn't replaced by correct values.
`version.properties` file content in `org.eclipse.persistence.core` is replaced correctly.
It happens in 3.0 branch only.
> [3.0] Eclipselink.jar bundle - version.properties fix

- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/criteria/TestNegFunction.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/criteria/model/CritEntity.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/querydef/CriteriaBuilderImpl.java
> Bug 579726: CriteriaBuilder neg() only returns Integer type.

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/expressions/ExpressionOperator.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/DB2Platform.java
for #1504
```
Caused by: java.lang.NullPointerException
at org.eclipse.persistence.expressions.ExpressionOperator.printCollection(ExpressionOperator.java:2369)
at org.eclipse.persistence.platform.database.DB2Platform$3.printCollection(DB2Platform.java:936)
at org.eclipse.persistence.internal.expressions.ArgumentListFunctionExpression.printSQL(ArgumentListFunctionExpression.java:99)
at org.eclipse.persistence.internal.expressions.FunctionExpression.writeFields(FunctionExpression.java:723)
at org.eclipse.persistence.internal.expressions.SQLSelectStatement.writeFieldsFromExpression(SQLSelectStatement.java:2082)
at org.eclipse.persistence.internal.expressions.SQLSelectStatement.writeFieldsIn(SQLSelectStatement.java:2097)
at org.eclipse.persistence.internal.expressions.SQLSelectStatement.printS …
```
> Fix NPE initializing ExpressionOperator indices Array

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/helper/DBPlatformHelper.java
Fixes #1507 
there were 2 problems:
- we need to ask the right module for the resource (from 9+)
- we need to catch `Throwable` to be able to recover/fallback from unexpected state and log appropriate warning
> #1507: Failing to create entity manager when running an app using module path

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/expressions/SQLSelectStatement.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/DB2ZPlatform.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/DerbyPlatform.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/property/TestParameterBinding.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/query/TestQueryOrderBy.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/query/TestQuerySyntaxAggregateTests.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/query/TestQuerySyntaxArithmeticTests.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/query/TestQuerySyntaxComparisonTests.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/query/TestQuerySyntaxFunctionTests.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/query/TestQuerySyntaxOrderingTests.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/query/TestQuerySyntaxUpdateTests.java
for #1443
There were several test failures in the `TestMathFunctions` tests on Derby. These failures were because using untyped parameters with the new "ROUND" operator syntax is invalid
```sql
SELECT FLOOR((DOUBLEVALUE)*1e?+0.5)/1e? FROM NUMBERENTITY WHERE (ID = ?)
```
I updated the implementation in DerbyPlatform to that issue by not allowing parameter binding. Also, I cleaned up the implementation.
for #1504
The tests delivered by for this issue didn't respect that `DB2Platform.shouldBindLiterals` was changing the default from "false" -> "true". As a result, almost all the `TestQuerySyntax*Tests` failed as the expected default query syntax was not correct for DB2 & Derby
Also, there were failures with the "IN" operator for Derby and DB2/zOS. Those failures were because it is invalid on …
> [master] Fix JSE tests failing on derby

- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/property/TestParameterBinding.java
A test fix was missed in https://github.com/eclipse-ee4j/eclipselink/pull/1534
`org.eclipse.persistence.jpa.test.property.TestParameterBinding.testIN_ForceBindJPQLParameters()` 
```
java.sql.SQLSyntaxErrorException: It is not allowed for both operands of 'IN' to be ? parameters.
Error Code: 30000
Call: SELECT 2 FROM GENERICENTITY WHERE (? IN (?, ?, ?))
bind => [a, a, b, c]
Query: ReportQuery(referenceClass=GenericEntity sql="SELECT 2 FROM GENERICENTITY WHERE (? IN (?, ?, ?))")
```
This test was failing on Derby because the test is testing the persistence property `eclipselink.jdbc.force-bind-parameters`. With this property set, all parameters are bound as parameters, which is illegal on Derby. I recently changed `DB2Platform.shouldBindLiterals` to default to "true", making the literals in …
> [master] Fix issue 1504 JSE test failure on Derby pt2

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/databaseaccess/DatabaseAccessor.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/criteria/TestMathFunctions.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/criteria/TestSimpleCase.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/criteria/model/NumberEntity.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/query/TestMathFunctions.java
Fixes DB ResultSet conversion when returned type is common Number and specific type is stored only in `typeName`.
Fixes issue #1538
> Issue #1538: Type Conversion error with the CEILING/FLOOR Operations

- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/EntityManagerSetupImpl.java
tested by composite.advanced tests on WildFly (uses 'vfs' protocol and provides custom factory to handle it)
> Fix propagation of ArchiveFactory from composite unit to its members,

- foundation/org.eclipse.persistence.core.test.framework/src/main/java/org/eclipse/persistence/testing/framework/junit/JUnitTestCaseHelper.java
- jpa/org.eclipse.persistence.jpa.test.framework/pom.xml
- jpa/org.eclipse.persistence.jpa.test.framework/src/main/java/org/eclipse/persistence/testing/framework/server/GenericTestRunner.java
- jpa/org.eclipse.persistence.jpa.test.framework/src/main/java/org/eclipse/persistence/testing/framework/server/JEEPlatform.java
- jpa/org.eclipse.persistence.jpa.test.framework/src/main/java/org/eclipse/persistence/testing/framework/server/SingleUnitTestRunnerBean.java
on the server by introducing the ability to provide it directly to the test itself
via env-entry in ejb-jar.xml;
provide temporary hook to NOT prefix member PU names for extended.xml.composite members
> avoid the need to set ejb.lookup property

- .github/workflows/codeql-analysis.yml
- jpa/eclipselink.jpa.testapps/pom.xml
> integrate eclipselink-testbuild-plugin 0.0.1 (from staging)

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/oxm/XMLConversionManager.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/oxm/conversion/Base64.java
- foundation/org.eclipse.persistence.core/src/test/java/org/eclipse/persistence/testing/oxm/xmlconversionmanager/Base64TestCases.java
Makes this method more memory efficient getting rid of a byte[] having the base64 encoded.
Although that byte[] will be garbage collected when the method finishes, this is relevant when there are many bytes to encode and multiple tasks like this in parallel.
> buildBase64StringFromBytes more memory efficient

- foundation/eclipselink.core.test/src/it/java/org/eclipse/persistence/testing/tests/weaving/EmployeeWeavingTestModel.java
- jpa/eclipselink.jpa.test/pom.xml
- jpa/eclipselink.jpa.testapps/pom.xml
skip spotbugs and javadoc in testapps
> remove dependency between core and jpa tests,

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/exceptions/i18n/JSONExceptionResource.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/exceptions/i18n/QueryExceptionResource.java
> [master] Minor messaging fix for apostrophe usage

- etc/jenkins/docker/image/install.sh
- etc/jenkins/docker/pom.xml
It's required for 2.7 release job.
> [master] Docker build image update - zip, unzip utilities installation

- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/uuid/TestUUIDGenerator.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/uuid/model/EmbeddableUUID_ID.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/uuid/model/UUIDAutoGenEntity.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/uuid/model/UUIDEmbeddableIdEntity.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/uuid/model/UUIDIdClassEntity.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/uuid/model/UUIDUUIDGenEntity.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/uuid/model/UUID_IDClass.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/uuid/model/XMLEmbeddableUUID_ID.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/uuid/model/XMLUUIDEmbeddableIdEntity.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/uuid/model/XMLUUIDEntity.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/uuid/model/XMLUUIDIdClassEntity.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/uuid/model/XMLUUIDUUIDGenEntity.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/uuid/model/XMLUUID_IDClass.java
- jpa/eclipselink.jpa.test.jse/src/it/resources/META-INF/uuid-orm.xml
Adding more detailed testing for the UUID function, including a disabled test (see #1625) .  These tests include the addition of testing the 3.1 ORM XML declaration of UUID generators, to ensure that parsing is exercised.
> [Master] Add additional UUID tests, including ORM XML declared generators.

- etc/jenkins/build.groovy
- etc/jenkins/pr_verify.groovy
- etc/jenkins/promote.groovy
Docker build image revert as is unable to create 2.0.2. Promotion pipeline is reverted to 1.1.9 due a zip, unzip tools requirement.
> [2.7] Jenkins build - Docker build image revert

- etc/jenkins/docker/pom.xml
Looks like this feature is broken in current maven Docker plugin.
> FS layers squash turned off (commented out) in Docker build.

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/exceptions/i18n/QueryExceptionResource.java
Minor error in https://github.com/eclipse-ee4j/eclipselink/pull/1619 during rebase
> [master] minor documentation fix

- etc/el-test.mssql.properties
- etc/el-test.oracle.properties
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/expressions/ExpressionOperator.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/expressions/ExtractOperator.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/expressions/ExtractOperator.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/jpa/jpql/ExpressionBuilderVisitor.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/DerbyPlatform.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/MySQLPlatform.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/OraclePlatform.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/PostgreSQLPlatform.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/SQLServerPlatform.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/criteria/TestDateTimeFunctions.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/query/TestDateTimeFunctions.java
Issue #1573 - EXTRACT() on second should return a float
Derby EXTRACT(SECOND FROM ...) returns just seconds (0..55) but added cast to Float type.
Issue #1574 - JPQL parser now sets default expression type based on extracted field.
Also added test to verify EXTRACT(SECOND FROM ...) fraction with expected FP/rounding error less than 1e-6. This test is skipped on Derby where EXTRACT(SECOND FROM ...) returns just seconds.
Tested on Oracle DB/SQL Server/Postgres/MySQL/Derby
TODO: Criteria API implementation for EXTRACT may require similar default type settings.
> Issue 1573 and 1574 - Fixed types returned by JPQL EXTRACT()

- bundles/others/pom.xml
- bundles/others/src/main/assembly/eclipselink-jpatest-framework.jar.xml
This fixes missing files in _eclipselink-jpatest-framework.jar_ bundle.
Backport from 3.0 branch.
> [master] JPA Test Framework - distribution bundle fix

- README.md
- jpa/eclipselink.jpa.testapps/README.md
> document running tests in testapps

- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/metadata/accessors/objects/MetadataAsmFactory.java
should log only exceptional cases and definitely not info about "internal" virtual metadataclasses
fixes #1606
> remove the noisy entries from the logs

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/tools/schemaframework/SequenceDefinition.java
> #1648: SchemaManager should consistently suppress logging on schema generation

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/config/QueryHints.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/expressions/ExpressionBuilder.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/databaseaccess/DatabasePlatform.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/expressions/QueryKeyExpression.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/expressions/RelationExpression.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/expressions/SQLSelectStatement.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/expressions/TreatAsExpression.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/queries/ObjectBuildingQuery.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/queries/ObjectLevelReadQuery.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/query/TestQueryHints.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/query/model/QueryOrder.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/query/model/QueryOrderLine.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/QueryHintsHandler.java
This change extend usage of `PrintInnerJoinInWhereClause` from current persistence unit property into query hint like
```
@NamedQuery(
name="QueryOrder.findAllOrdersWithEmptyOrderLinesHintFalse",
query="SELECT o FROM QueryOrder o WHERE o.queryOrderLines IS EMPTY",
hints={@QueryHint(name=QueryHints.PRINT_INNER_JOIN_IN_WHERE_CLAUSE, value="false")})
```
or
```
String jpql = "SELECT o FROM QueryOrder o WHERE o.queryOrderLines IS EMPTY";
Query query = em.createQuery(jpql, QueryOrder.class);
query.setHint(QueryHints.PRINT_INNER_JOIN_IN_WHERE_CLAUSE, "false");
```
It allows developers more preciously target (optimize) this property to the selected queries.
> [master] PrintInnerJoinInWhereClause as query hint

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/InformixPlatform.java
Signed-off-by: Gaurav Gupta <gaurav.gupta@payara.fish>
EclipseLink generates SQL, that can't be parsed by the database. The problem is located in the handling of the Concat operator (JPQL and the criteria api are both affected).
Informix expectes the concat operation to be: `<op1> || <op2>`
Eclipselink generates: `<op1> + <op2>`
This is rejected by the DB server. The concat operator can be overridden for the db platform and if done so, the correct SQL is generated.
The test program is attached to demonstrate this issue. The program (de.persona.dev.blaesing.eclipselink.jpa.generation.test.Test) generates tables for a Demo Entity and then queries the concatenation of lastname and firstname.
Lines 17-18 instantiate the entitymanager 
Lines 20-21 demonstrate a fix (if commented out, the error …
> Generate correct Informix SQL when parsing Concat Operator

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/config/QueryHints.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/expressions/ExpressionBuilder.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/databaseaccess/DatabasePlatform.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/expressions/QueryKeyExpression.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/expressions/RelationExpression.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/expressions/SQLSelectStatement.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/expressions/TreatAsExpression.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/queries/ObjectBuildingQuery.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/query/TestQueryHints.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/query/model/QueryOrder.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/query/model/QueryOrderLine.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/QueryHintsHandler.java
This change extend usage of `PrintInnerJoinInWhereClause` from current persistence unit property into query hint like
```
@NamedQuery(
name="QueryOrder.findAllOrdersWithEmptyOrderLinesHintFalse",
query="SELECT o FROM QueryOrder o WHERE o.queryOrderLines IS EMPTY",
hints={@QueryHint(name=QueryHints.PRINT_INNER_JOIN_IN_WHERE_CLAUSE, value="false")})
```
or
```
String jpql = "SELECT o FROM QueryOrder o WHERE o.queryOrderLines IS EMPTY";
Query query = em.createQuery(jpql, QueryOrder.class);
query.setHint(QueryHints.PRINT_INNER_JOIN_IN_WHERE_CLAUSE, "false");
```
It allows developers more preciously target (optimize) this property to the selected queries.
Fixes #1522.
> [3.0] PrintInnerJoinInWhereClause as query hint - backport from master

- foundation/org.eclipse.persistence.oracle/src/main/java/org/eclipse/persistence/platform/database/oracle/Oracle21Platform.java
This PR fixes issue which happens if EntityManager API using a remote EntityManager and `org.eclipse.persistence.platform.database.oracle.Oracle21Platform` is specified.
`org.eclipse.persistence.platform.database.oracle.Oracle21Platform` had `private final OracleJsonFactory factory;` field which wasn't used but is serialized via RMI if remote EntityManager is used.
With this field following exception was thrown:
```
...
Internal Exception: java.rmi.UnmarshalException: error unmarshalling return; nested exception is: 
java.io.WriteAbortedException: writing aborted; java.io.NotSerializableException: oracle.sql.json.OracleJsonFactory
[INFO] 
[ERROR] Tests run: 106, Failures: 1, Errors: 99, Skipped: 0
```
in
`mvn verify -pl :org.eclipse.persistence.jpa.testapps.remote -amd -Pstaging,oracle` …
> Oracle21Platform unused field removal to fix JPA remote test

- etc/el-test.oracle.properties
- jpa/eclipselink.jpa.nosql.test/pom.xml
- jpa/eclipselink.jpa.test.jse/pom.xml
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/canonical/TestCanonicalMetaModel.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/criteria/TestDateTimeFunctions.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/criteria/TestMathFunctions.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/criteria/TestSimpleCase.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/jpql/TestDateTimeFunctions.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/oraclefeatures/TestOracleLOBLocatorFeature.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/query/TestDateTimeFunctions.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/query/TestMathFunctions.java
- jpa/eclipselink.jpa.test/pom.xml
- jpa/eclipselink.jpa.testapps/pom.xml
- pom.xml
This is minor test code refactoring to remove code dependency to hamcrest api. These tests with Hamcrest API should work in Maven environments as Hamcrest dependency is transitively loaded by JUnit but there should be problem in Ant and other non-Maven build systems.
> [master] Hamcrest dependency removal

- etc/jenkins/pr_verify.groovy
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/config/QueryHints.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/expressions/ExpressionBuilder.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/databaseaccess/DatabasePlatform.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/expressions/QueryKeyExpression.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/expressions/RelationExpression.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/expressions/SQLSelectStatement.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/expressions/TreatAsExpression.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/queries/ObjectBuildingQuery.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/query/TestQueryHints2.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/query/model/QueryOrder.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/query/model/QueryOrderLine.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/QueryHintsHandler.java
This change extend usage of `PrintInnerJoinInWhereClause` from current persistence unit property into query hint like
```
@NamedQuery(
name="QueryOrder.findAllOrdersWithEmptyOrderLinesHintFalse",
query="SELECT o FROM QueryOrder o WHERE o.queryOrderLines IS EMPTY",
hints={@QueryHint(name=QueryHints.PRINT_INNER_JOIN_IN_WHERE_CLAUSE, value="false")})
```
or
```
String jpql = "SELECT o FROM QueryOrder o WHERE o.queryOrderLines IS EMPTY";
Query query = em.createQuery(jpql, QueryOrder.class);
query.setHint(QueryHints.PRINT_INNER_JOIN_IN_WHERE_CLAUSE, "false");
```
It allows developers more preciously target (optimize) this property to the selected queries.
Fixes #1522.
> [2.7] PrintInnerJoinInWhereClause as query hint - backport from master

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/config/QueryHints.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/expressions/ExpressionBuilder.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/databaseaccess/DatabasePlatform.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/expressions/QueryKeyExpression.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/expressions/RelationExpression.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/expressions/SQLSelectStatement.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/expressions/TreatAsExpression.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/queries/ObjectBuildingQuery.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/query/TestQueryHints2.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/query/model/QueryOrder.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/query/model/QueryOrderLine.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/QueryHintsHandler.java
This change extend usage of `PrintInnerJoinInWhereClause` from current persistence unit property into query hint like
```
@NamedQuery(
name="QueryOrder.findAllOrdersWithEmptyOrderLinesHintFalse",
query="SELECT o FROM QueryOrder o WHERE o.queryOrderLines IS EMPTY",
hints={@QueryHint(name=QueryHints.PRINT_INNER_JOIN_IN_WHERE_CLAUSE, value="false")})
```
or
```
String jpql = "SELECT o FROM QueryOrder o WHERE o.queryOrderLines IS EMPTY";
Query query = em.createQuery(jpql, QueryOrder.class);
query.setHint(QueryHints.PRINT_INNER_JOIN_IN_WHERE_CLAUSE, "false");
```
It allows developers more preciously target (optimize) this property to the selected queries.
Fixes #1522.
> [2.6] PrintInnerJoinInWhereClause as query hint - backport from master

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/databaseaccess/DatasourcePlatform.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/descriptors/ObjectBuilder.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/helper/ConversionManager.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/mappings/foundation/AbstractDirectMapping.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/OraclePlatform.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/embeddable/model/ElementCollectionEmbeddableTemporal.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/conversion/TestJavaTimeTypeConverter.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/lob/TestLobMerge.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/TestMultitenantOneToMany.java
This PR contains fixes for following test errors in JPA JSE module:
- org.eclipse.persistence.jpa.test.conversion.TestJavaTimeTypeConverter#timeConvertUtilDateToLocalDate
There is backport from master https://github.com/eclipse-ee4j/eclipselink/commit/cff665dccda56ce0c125e9509b24b274f88c0b29#diff-94d9bb887b47c8e9471a37fc153dbad9d33c5c233db3af7cb3100e5b4c613b58
- org.eclipse.persistence.jpa.test.mapping.TestMultitenantOneToMany
Test didn't clean environment. Calls `DROP SCHEMA IF EXISTS tenant_*` added.
Backport from #1370
- org.eclipse.persistence.jpa.test.lob.TestLobMerge
Based on product code changes. Backport from #1370
- org.eclipse.persistence.jpa.embeddable.TestCollectionTableEmbeddable
Based on product code changes. Backport from #1370
> [2.7] JPA JSE test fixes - master backports

- etc/jenkins/build.groovy
- etc/jenkins/prepare_nightly.sh
- etc/jenkins/publish_nightly.sh
This fix related with #1703 and `etc/jenkins/build.groovy` pipeline. Due security reason "Publish to nightly" stage is executed under different container, than EclipseLink build and tests. There should be Maven, but in different version, than `el-build`container used for a build and tests.
> [master] Nightly build fix - Jenkins pipeline

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/queries/BatchFetchPolicy.java
See #1506
The memory leak mentioned in the issue has already been solved by #1245 
This PR will fix the ConcurrentModificationException of the attributeExpression list, when running the same (batch)query with different entity managers.
> Fix ConcurrentModificationException in BatchFetchPolicy

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/oxm/mappings/XMLVariableXPathObjectMapping.java
- moxy/org.eclipse.persistence.moxy/src/test/java/org/eclipse/persistence/testing/jaxb/xmlvariablenode/AllVariableElementTestCases.java
- moxy/org.eclipse.persistence.moxy/src/test/java/org/eclipse/persistence/testing/jaxb/xmlvariablenode/Data.java
- moxy/org.eclipse.persistence.moxy/src/test/java/org/eclipse/persistence/testing/jaxb/xmlvariablenode/DataChild.java
- moxy/org.eclipse.persistence.moxy/src/test/java/org/eclipse/persistence/testing/jaxb/xmlvariablenode/XmlVariableNodeQNameNS2TestCases.java
- moxy/org.eclipse.persistence.moxy/src/test/resources/org/eclipse/persistence/testing/jaxb/xmlvariablenode/rootqname2NS.json
- moxy/org.eclipse.persistence.moxy/src/test/resources/org/eclipse/persistence/testing/jaxb/xmlvariablenode/rootqname2NS.xml
- moxy/org.eclipse.persistence.moxy/src/test/resources/org/eclipse/persistence/testing/jaxb/xmlvariablenode/rootqname2NSWrite.xml
Fixes #1709 . Bugfix + unit test.
> [master] Bugfix for: Specifying QName in XmlVariableNode results namespace written twice

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/oxm/mappings/XMLVariableXPathObjectMapping.java
- moxy/org.eclipse.persistence.moxy/src/test/java/org/eclipse/persistence/testing/jaxb/xmlvariablenode/AllVariableElementTestCases.java
- moxy/org.eclipse.persistence.moxy/src/test/java/org/eclipse/persistence/testing/jaxb/xmlvariablenode/Data.java
- moxy/org.eclipse.persistence.moxy/src/test/java/org/eclipse/persistence/testing/jaxb/xmlvariablenode/DataChild.java
- moxy/org.eclipse.persistence.moxy/src/test/java/org/eclipse/persistence/testing/jaxb/xmlvariablenode/XmlVariableNodeQNameNS2TestCases.java
- moxy/org.eclipse.persistence.moxy/src/test/resources/org/eclipse/persistence/testing/jaxb/xmlvariablenode/rootqname2NS.json
- moxy/org.eclipse.persistence.moxy/src/test/resources/org/eclipse/persistence/testing/jaxb/xmlvariablenode/rootqname2NS.xml
- moxy/org.eclipse.persistence.moxy/src/test/resources/org/eclipse/persistence/testing/jaxb/xmlvariablenode/rootqname2NSWrite.xml
> [3.0] Bugfix for: Specifying QName in XmlVariableNode results namespace written twice - backport from master

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/oxm/mappings/XMLVariableXPathObjectMapping.java
- moxy/eclipselink.moxy.test/resource/org/eclipse/persistence/testing/jaxb/xmlvariablenode/rootqname2NS.json
- moxy/eclipselink.moxy.test/resource/org/eclipse/persistence/testing/jaxb/xmlvariablenode/rootqname2NS.xml
- moxy/eclipselink.moxy.test/resource/org/eclipse/persistence/testing/jaxb/xmlvariablenode/rootqname2NSWrite.xml
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/xmlvariablenode/AllVariableElementTestCases.java
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/xmlvariablenode/Data.java
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/xmlvariablenode/DataChild.java
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/xmlvariablenode/XmlVariableNodeQNameNS2TestCases.java
> [2.7] Bugfix for: Specifying QName in XmlVariableNode results namespace written twice - backport from master

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/queries/BatchFetchPolicy.java
Fixes #1506 . This change will fix the ConcurrentModificationException of the attributeExpression list, when running the same (batch)query with different entity managers.
> [master] Fix ConcurrentModificationException in BatchFetchPolicy - backport from 2.7

- pom.xml
> Maven plugin eclipselink-build-support upgrade to 1.0.0.

- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/metadata/accessors/objects/MetadataAsmFactory.java
should log only exceptional cases and definitely not info about "internal" virtual metadataclasses
fixes #1606
> [2.7] remove the noisy entries from the logs - backport from the master

- .github/workflows/maven.yml
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/metadata/accessors/objects/MetadataAsmFactory.java
should log only exceptional cases and definitely not info about "internal" virtual metadataclasses
fixes #1606
(cherry picked from commit e2da068a260cb9bf9afeaf5df23fb7ace188cdcb)
> [3.0] remove the noisy entries from the logs - backport from the master

- jpa/eclipselink.jpa.testapps/jpa.test.jpql/src/test/java/org/eclipse/persistence/testing/tests/jpa/jpql/advanced/JUnitJPQLSimpleTest.java
- jpa/org.eclipse.persistence.jpa.jpql/src/main/java/org/eclipse/persistence/jpa/jpql/parser/FullyQualifyPathExpressionVisitor.java
NPE was caused my missing alias name. 
As you can see in `public void visit(AbstractSchemaName expression)`, which is being called for entity without FQN, default alias name is initialized there.
In `public void visit(CollectionValuedPathExpression expression)`, which is used for FQN entity name there was no default alias name initialization.
> Issue #1727 - Fixed missing default FQN entity alias name.

- foundation/org.eclipse.persistence.oracle.nosql/src/main/java/org/eclipse/persistence/internal/nosql/adapters/sdk/OracleNoSQLConnectionFactory.java
Without this NoSQL instance (driver) from cloud environment should throw
`Caused by: oracle.nosql.driver.TableNotFoundException: .....` although table exist in the DB.
> [master] Oracle NoSQL cloud connection fix to set compartment

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/config/PersistenceUnitProperties.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/config/QueryHints.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/localization/i18n/LoggingLocalizationResource.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/sessions/UnitOfWorkImpl.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/queries/ReadQuery.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/sessions/Project.java
- jpa/eclipselink.jpa.testapps/jpa.test.diagnostic/pom.xml
- jpa/eclipselink.jpa.testapps/jpa.test.diagnostic/src/main/java/org/eclipse/persistence/testing/models/jpa/diagnostic/BranchADiagnostic.java
- jpa/eclipselink.jpa.testapps/jpa.test.diagnostic/src/main/java/org/eclipse/persistence/testing/models/jpa/diagnostic/BranchBDiagnostic.java
- jpa/eclipselink.jpa.testapps/jpa.test.diagnostic/src/main/java/org/eclipse/persistence/testing/models/jpa/diagnostic/DiagnosticTableCreator.java
- jpa/eclipselink.jpa.testapps/jpa.test.diagnostic/src/main/resources/META-INF/persistence.xml
- jpa/eclipselink.jpa.testapps/jpa.test.diagnostic/src/test/java/org/eclipse/persistence/testing/tests/jpa/diagnostic/DiagnosticTest.java
- jpa/eclipselink.jpa.testapps/jpa.test.diagnostic/src/test/java/org/eclipse/persistence/testing/tests/jpa/diagnostic/LogWrapper.java
- jpa/eclipselink.jpa.testapps/pom.xml
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/EntityManagerSetupImpl.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/QueryHintsHandler.java
This is new diagnostic feature which could help developers to analyze inconsistent query results. Inconsistent means, that there is mix of managed and detached entities in the query result by logical error in their code. It should happens if JPA L2 caching is enabled.
E.g. let's have following code:
```
em.remove(branchBDiagnostic);
commitTransaction(em);
//branchBDiagnostic is in Detached state
...
em.getTransaction().begin();
branchADiagnostic.getBranchBs().add(branchBDiagnostic);
branchBDiagnostic.setBranchA(branchADiagnostic);
//Detached entity (branchBDiagnostic) is not persisted again - logical error
commitTransaction(em);
//This em.find() will resolve objects from cache
BranchADiagnostic branchADiagnosticFindResult = em.find(BranchADiagnostic.class, BRANCHA_ID);
...
```
if cache …
> [master] Diagnostic new feature - corrupted cache

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/expressions/TableExpression.java
- jpa/eclipselink.jpa.testapps/jpa.test.advanced/src/main/java/org/eclipse/persistence/testing/models/jpa/advanced/Customizer.java
- jpa/eclipselink.jpa.testapps/jpa.test.advanced/src/test/java/org/eclipse/persistence/testing/tests/jpa/advanced/JoinedAttributeAdvancedJunitTest.java
With the current implementation of `TableExpression#assignAlias` you cannot have multiple aliases against the same table. The code block below prevents the second reference from being added to the table alias list.
```
if (this.baseExpression.isQueryKeyExpression()){
QueryKeyExpression qkExpression = ((QueryKeyExpression)this.baseExpression);
if (qkExpression.getTableAliases() != null && qkExpression.getTableAliases().keyAtValue(table) != null ) {
return;
}
}
```
Removing the override of `assignAlias` in `TableExpression` and deferring to `DataExpression`'s implementation results in the expected behavior.
> fix: issue with multiple aliases against same table

- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/jpql/TestWhiteSpace.java
- jpa/org.eclipse.persistence.jpa.jpql/src/main/java/org/eclipse/persistence/jpa/jpql/AbstractGrammarValidator.java
- jpa/org.eclipse.persistence.jpa.jpql/src/main/java/org/eclipse/persistence/jpa/jpql/AbstractSemanticValidator.java
- jpa/org.eclipse.persistence.jpa.jpql/src/main/java/org/eclipse/persistence/jpa/jpql/AbstractValidator.java
- jpa/org.eclipse.persistence.jpa.jpql/src/main/java/org/eclipse/persistence/jpa/jpql/ExpressionTools.java
- jpa/org.eclipse.persistence.jpa.jpql/src/main/java/org/eclipse/persistence/jpa/jpql/WordParser.java
- jpa/org.eclipse.persistence.jpa.jpql/src/main/java/org/eclipse/persistence/jpa/jpql/tools/AbstractContentAssistVisitor.java
> [master] Issue 1755: Add support for non-breaking spaces

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/eis/EISDescriptor.java
- foundation/org.eclipse.persistence.oracle.nosql/pom.xml
- foundation/org.eclipse.persistence.oracle.nosql/src/it/java/org/eclipse/persistence/testing/models/jpa/nosql/DataTypesEntity.java
- foundation/org.eclipse.persistence.oracle.nosql/src/it/java/org/eclipse/persistence/testing/tests/jpa/nosql/sdk/NoSQLJPADataTypesTest.java
- foundation/org.eclipse.persistence.oracle.nosql/src/main/java/org/eclipse/persistence/internal/nosql/adapters/sdk/OracleNoSQLInteraction.java
This if fix + unit test for following case. Oracle NoSQL database allows store into JSON column type two kinds of values:
- String form which was currently supported
- Object tree based on `oracle.nosql.driver.values.MapValue`
Object tree wasn't supported before and there were incorrect results during various reading operations (find(...), query..)
At the Entity side is JSON stored as a `java.lang.String`.
This PR fixes conversion between JSON data stored as `oracle.nosql.driver.values.MapValue` and `java.lang.String` JPA field.
> [master] Oracle NoSQL Database - Json type fix

- etc/jenkins/build.groovy
- etc/jenkins/promote.groovy
This is technical switch into JDK 11. Output will be still compatible with JDK 8.0 due Tycho setting in `.settings/org.eclipse.jdt.core.prefs`.
> [2.7] Jenkins environment - switch to JDK 11

- etc/el-testjee.wildfly.properties
- foundation/eclipselink.core.test/src/it/java/org/eclipse/persistence/testing/tests/sessionsxml/SessionsXMLSchemaWildFlyPlatformTest.java
- foundation/eclipselink.core.test/src/it/java/org/eclipse/persistence/testing/tests/sessionsxml/SessionsXMLTestModel.java
- foundation/eclipselink.core.test/src/it/resources/org/eclipse/persistence/testing/models/sessionsxml/XMLSchemaSessionWildFlyPlatform.xml
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/config/TargetServer.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/sessions/PropertiesHandler.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/sessions/factories/XMLSessionConfigProject.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/sessions/factories/model/platform/WildFlyPlatformConfig.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/server/wildfly/WildFlyPlatform.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/services/wildfly/ClassSummaryDetail.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/services/wildfly/MBeanWildFlyRuntimeServices.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/services/wildfly/MBeanWildFlyRuntimeServicesMBean.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/services/wildfly/WildFlyRuntimeServices.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/sessions/factories/XMLSessionConfigLoader.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/transaction/wildfly/WildFlyTransactionController.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/transaction/wildfly/WildFlyTransactionController11.java
- foundation/org.eclipse.persistence.core/src/main/resources/org/eclipse/persistence/eclipselink_sessions_2.1.xsd
- foundation/org.eclipse.persistence.core/src/main/resources/org/eclipse/persistence/eclipselink_sessions_2.2.xsd
- jpa/eclipselink.jpa.testapps/pom.xml
- pom.xml
- sdo/eclipselink.sdo.test.server/pom.xml
This change add WildFly server into JEE platforms supported by EclipseLink.
It should better reflect changes in WildFly as latest WildFly (27.0.0.Final) support Jakarta EE10 and JBoss (EAP 7.4) Jakarta EE 8.
There are test dependencies update to the latest WildFly 27.0.0.Final.
> [master] New WildFly EE platform

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/queries/BatchFetchPolicy.java
Fixes #1506 . This change will fix the ConcurrentModificationException of the attributeExpression list, when running the same (batch)query with different entity managers.
> [3.0] Fix ConcurrentModificationException in BatchFetchPolicy - backport from 2.7

- .github/workflows/maven.yml
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/config/PersistenceUnitProperties.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/config/QueryHints.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/localization/i18n/LoggingLocalizationResource.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/sessions/UnitOfWorkImpl.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/queries/ReadQuery.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/sessions/Project.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/diagnostic/LogWrapper.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/diagnostic/TestDiagnostic.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/diagnostic/model/BranchADiagnostic.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/diagnostic/model/BranchBDiagnostic.java
- jpa/eclipselink.jpa.test.jse/src/it/resources/META-INF/persistence.xml
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/EntityManagerSetupImpl.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/QueryHintsHandler.java
This is new diagnostic feature which could help developers to analyze inconsistent query results. Inconsistent means, that there is mix of managed and detached entities in the query result by logical error in their code. It should happens if JPA L2 caching is enabled.
E.g. let's have following code:
```
em.remove(branchBDiagnostic);
commitTransaction(em);
//branchBDiagnostic is in Detached state
...
em.getTransaction().begin();
branchADiagnostic.getBranchBs().add(branchBDiagnostic);
branchBDiagnostic.setBranchA(branchADiagnostic);
//Detached entity (branchBDiagnostic) is not persisted again - logical error
commitTransaction(em);
//This em.find() will resolve objects from cache
BranchADiagnostic branchADiagnosticFindResult = em.find(BranchADiagnostic.class, BRANCHA_ID);
...
```
if cache …
> [3.0] Diagnostic new feature - corrupted cache (backport from master)

- .github/workflows/ant.yml
- .github/workflows/codeql-analysis.yml
- antbuild.xml
- autobuild.xml
- etc/jenkins/init.sh
- uploadToNexus.xml
This is fix for JavaDoc generation for generated Maven artifacts. javadoc utility in the JDK 11 is more strict for missing imported classes in the classpath than previous JDK 8.
> [2.7] Jenkins build pipeline - javadoc build fix

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/DB2ZPlatform.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/query/TestQuerySyntaxFunctionTests.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/sequence/TestIdentityGeneration.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/storedproc/TestStoredProceduresCursors.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/version/TestVersioning.java
for #1779
For non-IBM JDKs, against DB2 zOS, the existing test `org.eclipse.persistence.jpa.test.version.TestVersioning.testTemporalVersionField1()` fails:
```sql
<error message="java.nio.charset.UnsupportedCharsetException: Cp1027" type="javax.persistence.RollbackException">javax.persistence.RollbackException: java.nio.charset.UnsupportedCharsetException: Cp1027
at org.eclipse.persistence.internal.jpa.transaction.EntityTransactionImpl.commit(EntityTransactionImpl.java:159)
at org.eclipse.persistence.jpa.test.version.TestVersioning.testTemporalVersionField1(TestVersioning.java:62)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at …
```
> [2.6_WAS] Issue 1779: Add DB2zOS support for UNICODE Timestamps

- .github/workflows/codeql-analysis.yml
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/config/PersistenceUnitProperties.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/config/QueryHints.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/localization/i18n/LoggingLocalizationResource.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/sessions/UnitOfWorkImpl.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/queries/ReadQuery.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/sessions/Project.java
- jpa/eclipselink.jpa.test.jse/src/META-INF/persistence.xml
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/diagnostic/LogWrapper.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/diagnostic/TestDiagnostic.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/diagnostic/model/BranchADiagnostic.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/diagnostic/model/BranchBDiagnostic.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/EntityManagerSetupImpl.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/QueryHintsHandler.java
This is new diagnostic feature which could help developers to analyze inconsistent query results. Inconsistent means, that there is mix of managed and detached entities in the query result by logical error in their code. It should happens if JPA L2 caching is enabled.
E.g. let's have following code:
```
em.remove(branchBDiagnostic);
commitTransaction(em);
//branchBDiagnostic is in Detached state
...
em.getTransaction().begin();
branchADiagnostic.getBranchBs().add(branchBDiagnostic);
branchBDiagnostic.setBranchA(branchADiagnostic);
//Detached entity (branchBDiagnostic) is not persisted again - logical error
commitTransaction(em);
//This em.find() will resolve objects from cache
BranchADiagnostic branchADiagnosticFindResult = em.find(BranchADiagnostic.class, BRANCHA_ID);
...
```
if cache …
> [2.7] Diagnostic new feature - corrupted cache (backport from master)

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/PostgreSQLPlatform.java
Fix for #1771. Seems PostgreSQL doesn't like it when a `UUID` value is passed as a `String` - using `setObject` ensures the `UUID` value is passed as a `UUID`.
> Fix UUID handling for PostgreSQL

- .github/workflows/maven.yml
Select Adopt JDK 11.0.18+10 which seems doesn't have issue with JavaDoc above `package-info.java` with content like
```
@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.eclipse.org/eclipselink/xsds/persistence/oxm", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.eclipse.persistence.jaxb.xmlmodel;
```
from _src/main/java/org/eclipse/persistence/jaxb/xmlmodel/package-info.java_
> [3.0] GitHub Actions fix for Javadoc generation

- foundation/org.eclipse.persistence.oracle.nosql/src/it/java/org/eclipse/persistence/testing/models/jpa/nosql/NativeQueryEntity.java
- foundation/org.eclipse.persistence.oracle.nosql/src/it/java/org/eclipse/persistence/testing/tests/jpa/nosql/sdk/NoSQLJPADataTypesTest.java
- foundation/org.eclipse.persistence.oracle.nosql/src/it/resources/META-INF/persistence.xml
- foundation/org.eclipse.persistence.oracle.nosql/src/main/java/org/eclipse/persistence/internal/nosql/adapters/sdk/OracleNoSQLInteraction.java
- foundation/org.eclipse.persistence.oracle.nosql/src/main/java/org/eclipse/persistence/internal/nosql/adapters/sdk/OracleNoSQLOperation.java
- foundation/org.eclipse.persistence.oracle.nosql/src/main/java/org/eclipse/persistence/nosql/adapters/sdk/OracleNoSQLPlatform.java
- pom.xml
This change brings into EclipseLink and Oracle NoSQL Database platform support for:
- JPA `@NamedNativeQuery`
- support for more complex Jakarta Persistence queries like `SELECT t FROM DataTypesEntity t WHERE t.id = :id AND t.fieldString = :name`
> [master] Oracle NoSQL Database - NativeQueries and more complex JPA queries support

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/DB2ZPlatform.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/storedproc/TestStoredProceduresCursors.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/version/TestVersioning.java
for #1779
For non-IBM JDKs, against DB2 zOS, the existing test `org.eclipse.persistence.jpa.test.version.TestVersioning.testTemporalVersionField1()` fails:
```sql
<error message="java.nio.charset.UnsupportedCharsetException: Cp1027" type="javax.persistence.RollbackException">javax.persistence.RollbackException: java.nio.charset.UnsupportedCharsetException: Cp1027
at org.eclipse.persistence.internal.jpa.transaction.EntityTransactionImpl.commit(EntityTransactionImpl.java:159)
at org.eclipse.persistence.jpa.test.version.TestVersioning.testTemporalVersionField1(TestVersioning.java:62)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at …
```
> [master] Issue 1779: Add DB2zOS support for UNICODE Timestamps

- autobuild.xml
After nightly build upgrade to JDK 11, nightly build generates little bit different tests results (HTML).
Check https://www.eclipse.org/eclipselink/downloads/nightly.php 2.7.12  20230119-20230112 where are incorrectly displayed red crosses.
First fix was published to https://github.com/eclipse-ee4j/eclipselink-releng/commit/7d96b8d130208c5a39ed4cfea17329ce1ed81182
but due future architectural changes in Eclipse.org (see https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2582 ) Eclipse.org admin didn't allow synchronize this change to `genie.eclipselink@projects-storage.eclipse.org cd /shared/rt/eclipselink/eclipselink.releng`.
Needed `ResultSummary.dat` file is generated now by build process, like master and 3.0, instead separated bash script from eclipselink.releng repository. …
> [2.7] Jenkins - Nightly build page generation fix

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/DB2ZPlatform.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/query/TestQuerySyntaxFunctionTests.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/storedproc/TestStoredProceduresCursors.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/version/TestVersioning.java
for #1779
For non-IBM JDKs, against DB2 zOS, the existing test `org.eclipse.persistence.jpa.test.version.TestVersioning.testTemporalVersionField1()` fails:
```sql
<error message="java.nio.charset.UnsupportedCharsetException: Cp1027" type="javax.persistence.RollbackException">javax.persistence.RollbackException: java.nio.charset.UnsupportedCharsetException: Cp1027
at org.eclipse.persistence.internal.jpa.transaction.EntityTransactionImpl.commit(EntityTransactionImpl.java:159)
at org.eclipse.persistence.jpa.test.version.TestVersioning.testTemporalVersionField1(TestVersioning.java:62)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at …
```
> [2.7] Issue 1779: Add DB2zOS support for UNICODE Timestamps

- foundation/eclipselink.core.test/src/it/java/org/eclipse/persistence/testing/tests/identitymaps/cacheinvalidation/CacheInvalidationPolicyCloneTest.java
- foundation/eclipselink.core.test/src/it/java/org/eclipse/persistence/testing/tests/performance/java/DatePrintingTest.java
- foundation/eclipselink.core.test/src/it/java/org/eclipse/persistence/testing/tests/types/TimeDateTester.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/helper/ConversionManager.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/oxm/XMLConversionManager.java
- foundation/org.eclipse.persistence.core/src/test/java/org/eclipse/persistence/testing/oxm/mappings/typeddirect/TypedDirectMappingTestCases.java
- foundation/org.eclipse.persistence.core/src/test/java/org/eclipse/persistence/testing/oxm/xmlconversionmanager/DateAndTimeTestCases.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/conversion/TestJavaTimeTypeConverter.java
- jpa/eclipselink.jpa.testapps.oracle/jpa.test.oracle.timestamptz/src/test/java/org/eclipse/persistence/testing/tests/jpa/timestamptz/TimeStampTZTest.java
- sdo/org.eclipse.persistence.sdo/src/main/java/org/eclipse/persistence/sdo/helper/SDODataHelper.java
- sdo/org.eclipse.persistence.sdo/src/test/java/org/eclipse/persistence/testing/sdo/helper/datahelper/DataHelperToCalendarTest.java
- sdo/org.eclipse.persistence.sdo/src/test/java/org/eclipse/persistence/testing/sdo/helper/datahelper/DataHelperToCalendarWithLocale.java
- sdo/org.eclipse.persistence.sdo/src/test/java/org/eclipse/persistence/testing/sdo/helper/datahelper/DataHelperToDateTest.java
- sdo/org.eclipse.persistence.sdo/src/test/java/org/eclipse/persistence/testing/sdo/helper/datahelper/DataHelperToDateTimeTest.java
- sdo/org.eclipse.persistence.sdo/src/test/java/org/eclipse/persistence/testing/sdo/helper/datahelper/DataHelperToDurationTest.java
- sdo/org.eclipse.persistence.sdo/src/test/java/org/eclipse/persistence/testing/sdo/helper/datahelper/DataHelperToDurationWithCalnTest.java
- sdo/org.eclipse.persistence.sdo/src/test/java/org/eclipse/persistence/testing/sdo/helper/datahelper/DataHelperToTimeTest.java
Some conversions in EclipseLink use `Calendar.HOUR` instead of `Calendar.HOUR_OF_DAY`, causing times after noon to be processed incorrectly. (`Calendar.HOUR` should only be used in conjunction with `Calendar.AM_PM`, in all other cases `Calendar.HOUR_OF_DAY` must be used)
In particular all sorts of conversions to `OffsetTime` and `OffsetDateTime` in `org.eclipse.persistence.internal.helper.ConversionManager` were producing wrong results.
This PR just fixes the bug, but the conversion code in `ConversionManager` could be streamlined greatly by using Java Time directly rather than converting  with a `Calendar`.
Code like this:
```
} else if (sourceObject instanceof java.util.Date) {
// handles sql.Time, sql.Date, sql.Timestamp
Calendar cal = Helper.allocateCalendar(); …
```
> Correctly handle times after noon

- foundation/org.eclipse.persistence.extension/src/main/java/org/eclipse/persistence/internal/sessions/coordination/jgroups/JGroupsRemoteConnection.java
- foundation/org.eclipse.persistence.extension/src/test/java/org/eclipse/persistence/testing/tests/jgroups/JGroupsCommandProcessor.java
- foundation/org.eclipse.persistence.extension/src/test/java/org/eclipse/persistence/testing/tests/jgroups/JGroupsRemoteConnectionTest.java
- foundation/org.eclipse.persistence.extension/src/test/java/org/eclipse/persistence/testing/tests/jgroups/JGroupsTestCommand.java
- foundation/org.eclipse.persistence.extension/src/test/java/org/eclipse/persistence/testing/tests/jgroups/JGroupsTestTransportManager.java
- pom.xml
This JGroups upgrade reflects JGroups API changes between 4.x and 5.x versions like
https://github.com/belaban/JGroups/commit/e3ce11056735982faba109d9c8e9571c494b00f3
There are new JUnit tests to verify `org.eclipse.persistence.internal.sessions.coordination.jgroups.JGroupsRemoteConnection` class by test commands.
> [master] JGroups dependency upgrade plus additonal JUnit tests

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/DB2ZPlatform.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/query/TestQuerySyntaxFunctionTests.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/storedproc/TestStoredProceduresCursors.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/version/TestVersioning.java
for #1779
For non-IBM JDKs, against DB2 zOS, the existing test `org.eclipse.persistence.jpa.test.version.TestVersioning.testTemporalVersionField1()` fails:
```sql
<error message="java.nio.charset.UnsupportedCharsetException: Cp1027" type="javax.persistence.RollbackException">javax.persistence.RollbackException: java.nio.charset.UnsupportedCharsetException: Cp1027
at org.eclipse.persistence.internal.jpa.transaction.EntityTransactionImpl.commit(EntityTransactionImpl.java:159)
at org.eclipse.persistence.jpa.test.version.TestVersioning.testTemporalVersionField1(TestVersioning.java:62)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at …
```
> [3.0] Issue 1779: Add DB2zOS support for UNICODE Timestamps

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/exceptions/i18n/ValidationExceptionResource.java
It looks like merging #1477 clobbered the message num 7357 (`"The \"[{0}]\" URL for \"[{1}]\" resource does not belong to a valid persistence root (as per Jakarta Persistence Specification)"`) in ValidationExceptionResource.java by mistake (there are two entries for the same message number).  Pushing a correction update.
> Correct clobbered message from git rebase for (#1477)

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/DB2Platform.java
for #1827
testing already exists:
```
org.eclipse.persistence.jpa.test.jpql.TestDateTimeFunctions.testIssue1539LocalDateTime
org.eclipse.persistence.jpa.test.jpql.TestDateTimeFunctions.testIssue1539LocalDate
```
> [master] Issue 1827: Add java.time support for DB2 schema generation

- jpa/eclipselink.jpa.testapps/jpa.test.metamodel.apectj/pom.xml
- jpa/eclipselink.jpa.testapps/jpa.test.metamodel.apectj/src/main/java/org/eclipse/persistence/testing/models/jpa/weaving/aspectj/EntityListenerAspect.java
- jpa/eclipselink.jpa.testapps/jpa.test.metamodel.apectj/src/main/java/org/eclipse/persistence/testing/models/jpa/weaving/aspectj/EntityListenerAspectJ.java
- jpa/eclipselink.jpa.testapps/jpa.test.metamodel.apectj/src/main/java/org/eclipse/persistence/testing/models/jpa/weaving/aspectj/ItemAspectJ.java
- jpa/eclipselink.jpa.testapps/jpa.test.metamodel.apectj/src/main/resources/META-INF/persistence.xml
- jpa/eclipselink.jpa.testapps/jpa.test.metamodel.apectj/src/test/java/org/eclipse/persistence/testing/tests/jpa/weaving/aspectj/MetamodelAspectJTableCreator.java
- jpa/eclipselink.jpa.testapps/jpa.test.metamodel.apectj/src/test/java/org/eclipse/persistence/testing/tests/jpa/weaving/aspectj/MetamodelAspectJTest.java
- jpa/eclipselink.jpa.testapps/pom.xml
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/metadata/accessors/objects/MetadataAsmFactory.java
- pom.xml
Fixes #1832
This PR contains fix for reported error and new JPA test module as this issue happens when AspectJ Weaver is applied to JPA managed classes. It was related with `EntityManagerFactory.getMetamodel();`
> [master] Fix for java.lang.StackOverflowError after bumping from 4.0.0 to 4.0.1 after ASM refactor

- sdo/org.eclipse.persistence.sdo/src/main/java/org/eclipse/persistence/sdo/SDOSystemProperties.java
- sdo/org.eclipse.persistence.sdo/src/main/java/org/eclipse/persistence/sdo/helper/SDOHelperContext.java
- sdo/org.eclipse.persistence.sdo/src/test/java/org/eclipse/persistence/testing/sdo/helper/SDOHelperContextTest.java
- sdo/org.eclipse.persistence.sdo/src/test/java/org/eclipse/persistence/testing/sdo/helper/helpercontext/SDOHelperContextTest.java
- sdo/org.eclipse.persistence.sdo/src/test/java/org/eclipse/persistence/testing/sdo/instanceclass/InstanceClassTestCases.java
This change solve potential memory leak if SDO component used in JEE environment.
There is refactor of `SDOHelperContext.helperContexts` map. Instead of current `ConcurrentHashMap` is `CacheIdentityMap` used which supports Least Recently Used (LRU) strategy. This one should be controlled by new SDO system property `eclipselink.sdo.helper.contexts.max.size`.
> [master] SDO potential memory leak fix

- foundation/eclipselink.core.test/src/it/java/org/eclipse/persistence/testing/tests/queries/ConformResultsWithPrimaryKeyExpressionTest.java
- foundation/eclipselink.core.test/src/it/java/org/eclipse/persistence/testing/tests/unitofwork/DoubleNestedUnitOfWorkDeleteConformedNestedNewObjectTest.java
- foundation/eclipselink.core.test/src/it/java/org/eclipse/persistence/testing/tests/unitofwork/DoubleNestedUnitOfWorkRegisterNewObjectTest.java
- foundation/eclipselink.core.test/src/it/java/org/eclipse/persistence/testing/tests/unitofwork/NestedUnitOfWorkDeleteConformedNestedNewObjectTest.java
- foundation/eclipselink.core.test/src/it/java/org/eclipse/persistence/testing/tests/unitofwork/NestedUnitOfWorkDeleteNestedNewObjectTest.java
- foundation/eclipselink.core.test/src/it/java/org/eclipse/persistence/testing/tests/unitofwork/NestedUnitOfWorkDeleteNewObjectTest.java
- foundation/eclipselink.core.test/src/it/java/org/eclipse/persistence/testing/tests/unitofwork/UnregisterUnitOfWorkTest.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/sessions/UnitOfWorkImpl.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/sessions/remote/RemoteUnitOfWork.java
- Fixes #1596 
When a lookup is performed in a UnitOfWork, eclipselink used to perform a linear search through all new entities. If the UnitOfWork contains many new objects, this becomes a major performance issue, since in the worst case every persisted entity has to be checked and a primary key extraction performed.
By instead maintaining a HashMap of primary key to new objects in the UnitOfWork, the performance impact of a lookup becomes negligible even if there are many persisted entities.
To demonstrate this, I used the UnitTest attached to [this comment](https://github.com/eclipse-ee4j/eclipselink/issues/1596#issuecomment-1252273264) in the original issue with 10k new entities:
In the original implementation 75% of the execution time is spent in …
> [master] fix #1596 Major performance issue in case of many new entities

- .github/workflows/ant.yml
- .github/workflows/codeql-analysis.yml
- buildsystem/compdeps/pom.xml
- dbws/org.eclipse.persistence.dbws/META-INF/MANIFEST.MF
- foundation/org.eclipse.persistence.core/META-INF/MANIFEST.MF
- jpa/org.eclipse.persistence.jpa/META-INF/MANIFEST.MF
- moxy/org.eclipse.persistence.moxy/META-INF/MANIFEST.MF
- sdo/org.eclipse.persistence.sdo/META-INF/MANIFEST.MF
As https://central.sonatype.com/artifact/org.eclipse.persistence/org.eclipse.persistence.asm/9.5.0 is released.
> [2.7] ASM version switch to 9.5 to be ready for JDK 21.

- pom.xml
As https://central.sonatype.com/artifact/org.eclipse.persistence/org.eclipse.persistence.asm/9.5.0 is released.
> [3.0] ASM version switch to 9.5 to be ready for JDK 21.

- foundation/eclipselink.core.test/src/it/java/org/eclipse/persistence/testing/tests/queries/ConformResultsWithPrimaryKeyExpressionTest.java
- foundation/eclipselink.core.test/src/it/java/org/eclipse/persistence/testing/tests/unitofwork/DoubleNestedUnitOfWorkDeleteConformedNestedNewObjectTest.java
- foundation/eclipselink.core.test/src/it/java/org/eclipse/persistence/testing/tests/unitofwork/DoubleNestedUnitOfWorkRegisterNewObjectTest.java
- foundation/eclipselink.core.test/src/it/java/org/eclipse/persistence/testing/tests/unitofwork/NestedUnitOfWorkDeleteConformedNestedNewObjectTest.java
- foundation/eclipselink.core.test/src/it/java/org/eclipse/persistence/testing/tests/unitofwork/NestedUnitOfWorkDeleteNestedNewObjectTest.java
- foundation/eclipselink.core.test/src/it/java/org/eclipse/persistence/testing/tests/unitofwork/NestedUnitOfWorkDeleteNewObjectTest.java
- foundation/eclipselink.core.test/src/it/java/org/eclipse/persistence/testing/tests/unitofwork/UnregisterUnitOfWorkTest.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/sessions/UnitOfWorkImpl.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/sessions/remote/RemoteUnitOfWork.java
* Issue 1596: use a hash-based collection to lookup objects in the cache instead of a linear search
* Adjusted source according to review:
- extended tests
- updated copyright year
- call removeObjectFromPrimaryKeyToNewObjects in preMergeChanges
- remove list from primaryKeyToNewObjects if it is empty
- simplify tests
(cherry picked from commit 76d82744b14f9a3ad11c1a5215542955b43bea1a)
> [3.0] fix #1596 Major performance issue in case of many new entities (#1843) - backport from master

- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa/advanced/EntityManagerJUnitTestSuite.java
There are some minor JPA test issues discovered with tests in WLS environment.
- `public static Test suite() {` ensure, that tables like `EMPLOYEE_SEQ` are created before test. As these tables are created by another tests too error
`Internal Exception: java.sql.SQLSyntaxErrorException: ORA-00942: table or view does not exist Error Code: 942 Call: UPDATE CMP3_EMPLOYEE_SEQ SET SEQ_COUNT = SEQ_COUNT + ? WHERE SEQ_NAME = ? bind => [2 parameters bound] Query: DataModifyQuery(name="EMPLOYEE_SEQ" sql="UPDATE CMP3_EMPLOYEE_SEQ SET SEQ_COUNT = SEQ_COUNT + ? WHERE SEQ_NAME = ?") `
should happen only if this test is executed first in the suite.
- `public void testApplicationManagedInServer() {` there should be two instances of `DatabaseSession` based on same persistence unit from the same JEE …
> [2.7] JPA test fixes

- sdo/org.eclipse.persistence.sdo/src/main/java/org/eclipse/persistence/sdo/SDOSystemProperties.java
- sdo/org.eclipse.persistence.sdo/src/main/java/org/eclipse/persistence/sdo/helper/SDOHelperContext.java
- sdo/org.eclipse.persistence.sdo/src/test/java/org/eclipse/persistence/testing/sdo/helper/SDOHelperContextTest.java
- sdo/org.eclipse.persistence.sdo/src/test/java/org/eclipse/persistence/testing/sdo/instanceclass/InstanceClassTestCases.java
This change solve potential memory leak if SDO component is used in JEE environment. There is refactor of SDOHelperContext.helperContexts map content (nested map). Instead of current ConcurrentHashMap is CacheIdentityMap used which supports Least Recently Used (LRU) strategy. This one should be controlled by new SDO system property eclipselink.sdo.helper.contexts.max.size.
> [3.0] SDO potential memory leak fix 2.0 - backport from master

- sdo/eclipselink.sdo.test/src/org/eclipse/persistence/testing/sdo/helper/SDOHelperContextTest.java
- sdo/eclipselink.sdo.test/src/org/eclipse/persistence/testing/sdo/instanceclass/InstanceClassTestCases.java
- sdo/org.eclipse.persistence.sdo/src/org/eclipse/persistence/sdo/SDOSystemProperties.java
- sdo/org.eclipse.persistence.sdo/src/org/eclipse/persistence/sdo/helper/SDOHelperContext.java
This change solve potential memory leak if SDO component is used in JEE environment. There is refactor of SDOHelperContext.helperContexts map content (nested map). Instead of current ConcurrentHashMap is CacheIdentityMap used which supports Least Recently Used (LRU) strategy. This one should be controlled by new SDO system property eclipselink.sdo.helper.contexts.max.size.
> [2.7] SDO potential memory leak fix 2.0 - backport from the master

- antbuild.xml
With this change, I was able to get EclipseLink 2.6_WAS building with
```
apache-maven-3.6.3
ibm-java-sdk-80-win-x86_64
apache-ant-1.10.2
```
> [2.6_WAS] Update build to use newer Maven

- foundation/eclipselink.core.test/src/it/java/org/eclipse/persistence/testing/tests/queries/QueryTimeoutConnectionReleasedTest.java
- foundation/eclipselink.core.test/src/it/java/org/eclipse/persistence/testing/tests/queries/QueryTimeoutTest.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/databaseaccess/DatasourcePlatform.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/databaseaccess/Platform.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/Oracle23Platform.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/oracle/plsql/PLSQLStoredProcedureCall.java
- foundation/org.eclipse.persistence.core/src/main/resources/org/eclipse/persistence/internal/helper/VendorNameToPlatformMapping.properties
- foundation/org.eclipse.persistence.oracle/src/main/java/org/eclipse/persistence/platform/database/oracle/Oracle23Platform.java
- jpa/eclipselink.jpa.testapps.oracle/jpa.test.oracle.plsql/src/test/java/org/eclipse/persistence/testing/tests/jpa/plsql/PLSQLTest.java
- jpa/eclipselink.jpa.testapps.oracle/jpa.test.oracle.plsql/src/test/java/org/eclipse/persistence/testing/tests/jpa/plsql/XMLPLSQLTest.java
- pom.xml
This PR adds support for a new Oracle 23c database.
It doesn't implement any new features yet.
There are two changes:
- Oracle 23c database has some performance improvement in case of Cartesian product so there is some change in `QueryTimeout` tests
- New Oracle JDBC driver 23.2.0.0 has, in some cases, different behaviour for boolean type. There are changes in PL/SQL calls.
> [master] Oracle 23 platform

- foundation/eclipselink.core.test/src/it/java/org/eclipse/persistence/testing/tests/queries/QueryTimeoutConnectionReleasedTest.java
- foundation/eclipselink.core.test/src/it/java/org/eclipse/persistence/testing/tests/queries/QueryTimeoutTest.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/databaseaccess/DatasourcePlatform.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/databaseaccess/Platform.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/Oracle23Platform.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/oracle/plsql/PLSQLStoredProcedureCall.java
- foundation/org.eclipse.persistence.core/src/main/resources/org/eclipse/persistence/internal/helper/VendorNameToPlatformMapping.properties
- foundation/org.eclipse.persistence.oracle/src/main/java/org/eclipse/persistence/platform/database/oracle/Oracle23Platform.java
- jpa/eclipselink.jpa.testapps.oracle/jpa.test.oracle.plsql/src/test/java/org/eclipse/persistence/testing/tests/jpa/plsql/PLSQLTest.java
- jpa/eclipselink.jpa.testapps.oracle/jpa.test.oracle.plsql/src/test/java/org/eclipse/persistence/testing/tests/jpa/plsql/XMLPLSQLTest.java
- pom.xml
This PR adds support for a new Oracle 23c database.
It doesn't implement any new features yet.
There are two changes:
- Oracle 23c database has some performance improvement in case of Cartesian product so there is some change in `QueryTimeout` tests
- New Oracle JDBC driver 23.2.0.0 has, in some cases, different behaviour for boolean type. There are changes in PL/SQL calls. 
(cherry picked from commit 0a12012e8a8e8f088d37fc988f3abebc0c12f30a)
> [4.0] Oracle 23 platform - backport from master #1876

- foundation/org.eclipse.persistence.oracle.nosql/pom.xml
- foundation/org.eclipse.persistence.oracle.nosql/src/it/java/org/eclipse/persistence/testing/tests/eis/aq/AuthenticationTest.java
- foundation/org.eclipse.persistence.oracle.nosql/src/it/java/org/eclipse/persistence/testing/tests/eis/aq/JMSDirectConnectTest.java
- foundation/org.eclipse.persistence.oracle.nosql/src/it/java/org/eclipse/persistence/testing/tests/eis/aq/JMSDirectInteractionTest.java
- foundation/org.eclipse.persistence.oracle.nosql/src/it/java/org/eclipse/persistence/testing/tests/eis/aq/JavaDirectInteractionTest.java
- foundation/org.eclipse.persistence.oracle.nosql/src/it/java/org/eclipse/persistence/testing/tests/eis/aq/OrderQueueTest.java
- foundation/org.eclipse.persistence.oracle.nosql/src/it/resources/org/eclipse/persistence/testing/models/order/eis/aq/order-project.xml
- foundation/org.eclipse.persistence.oracle.nosql/src/it/resources/org/eclipse/persistence/testing/models/order/eis/nosql/order-project.xml
- foundation/org.eclipse.persistence.oracle.nosql/src/main/java/org/eclipse/persistence/eis/adapters/aq/AQPlatform.java
- foundation/org.eclipse.persistence.oracle.nosql/src/main/java/org/eclipse/persistence/internal/eis/adapters/aq/AQConnection.java
- foundation/org.eclipse.persistence.oracle.nosql/src/main/java/org/eclipse/persistence/internal/eis/adapters/aq/AQConnectionFactory.java
- foundation/org.eclipse.persistence.oracle.nosql/src/main/java/org/eclipse/persistence/internal/eis/adapters/aq/AQDequeueInteractionSpec.java
- foundation/org.eclipse.persistence.oracle.nosql/src/main/java/org/eclipse/persistence/internal/eis/adapters/aq/AQEnqueueInteractionSpec.java
- foundation/org.eclipse.persistence.oracle.nosql/src/main/java/org/eclipse/persistence/internal/eis/adapters/aq/AQInteraction.java
- foundation/org.eclipse.persistence.oracle.test/pom.xml
- foundation/org.eclipse.persistence.oracle.test/src/it/java/org/eclipse/persistence/testing/tests/dbchangenotification/CacheInvalidationHandler.java
- foundation/org.eclipse.persistence.oracle.test/src/it/java/org/eclipse/persistence/testing/tests/dbchangenotification/CacheInvalidationMessageListener.java
- foundation/org.eclipse.persistence.oracle.test/src/it/java/org/eclipse/persistence/testing/tests/dbchangenotification/CacheInvalidationRunnable.java
- foundation/org.eclipse.persistence.oracle.test/src/it/java/org/eclipse/persistence/testing/tests/dbchangenotification/CacheInvalidator.java
- foundation/org.eclipse.persistence.oracle.test/src/it/java/org/eclipse/persistence/testing/tests/dbchangenotification/DbChangeNotificationTest.java
- foundation/org.eclipse.persistence.oracle.test/src/it/java/org/eclipse/persistence/testing/tests/distributedservers/rcm/jms/JMSSetupHelper.java
- pom.xml
This upgrade leads into:
- code changes as there are package name changes `oracle.jms.*` -> `oracle.jakarta.jms.*` and `oracle.AQ.*` -> `oracle.jakarta.AQ.*`
- test dependency `javax.jms:javax.jms-api` was replaced by project default `jakarta.jms:jakarta.jms-api`
- test dependency `javax.transaction-api` still remains due
``
[ERROR] org.eclipse.persistence.testing.tests.eis.aq.JMSDirectInteractionTest.testQueue  Time elapsed: 0.471 s  <<< ERROR!
java.lang.NoClassDefFoundError: javax/transaction/Synchronization
at oracle.jakarta.jms.AQjmsSession.<init>(AQjmsSession.java:561)
at oracle.jakarta.jms.AQjmsConnection.createQueueSession(AQjmsConnection.java:704)
at org.eclipse.persistence.testing.tests.eis.aq.JMSDirectInteractionTest.testQueue(JMSDirectI
``
Signed-off-by: Radek Felcman …
> [4.0] Oracle AQ API upgrade to com.oracle.database.messaging/aqapi-jakarta@23.2.0.0 - backport from master #1882

- foundation/eclipselink.core.test/src/it/java/org/eclipse/persistence/testing/tests/queries/QueryTimeoutConnectionReleasedTest.java
- foundation/eclipselink.core.test/src/it/java/org/eclipse/persistence/testing/tests/queries/QueryTimeoutTest.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/databaseaccess/DatasourcePlatform.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/databaseaccess/Platform.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/Oracle23Platform.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/oracle/plsql/PLSQLStoredProcedureCall.java
- foundation/org.eclipse.persistence.core/src/main/resources/org/eclipse/persistence/internal/helper/VendorNameToPlatformMapping.properties
- foundation/org.eclipse.persistence.oracle/src/main/java/org/eclipse/persistence/platform/database/oracle/Oracle23Platform.java
- jpa/eclipselink.jpa.testapps.oracle/jpa.test.oracle.plsql/src/test/java/org/eclipse/persistence/testing/tests/jpa/plsql/PLSQLTest.java
- jpa/eclipselink.jpa.testapps.oracle/jpa.test.oracle.plsql/src/test/java/org/eclipse/persistence/testing/tests/jpa/plsql/XMLPLSQLTest.java
- pom.xml
This PR adds support for a new Oracle 23c database.
It doesn't implement any new features yet.
There are two changes:
- Oracle 23c database has some performance improvement in case of Cartesian product so there is some change in `QueryTimeout` tests
- New Oracle JDBC driver 23.2.0.0 has, in some cases, different behaviour for boolean type. There are changes in PL/SQL calls. 
(cherry picked from commit 0a12012e8a8e8f088d37fc988f3abebc0c12f30a)
>  [4.0] Oracle 23 platform - backport from master #1876 #1887 

- bundles/nightly/pom.xml
- bundles/nightly/src/site/custom/surefire-report.properties
- pom.xml
- src/main/assembly/test-report.xml
- src/site/custom/surefire-report.properties
This change fixes different location (XPath) in test HTML reports as maven-surefire-report-plugin uses different site skin.
> [4.0] maven-surefire-report-plugin title settings change

- bundles/nightly/pom.xml
This is fix to prevents access issue to the test reports like:
https://download.eclipse.org/rt/eclipselink/nightly/4.0.2/20230612/Eclipse/eclipselink-core-lrg-4.0.2.v20230612-96c4af71c2.html
```
Access Forbidden
The file permissions are either wrong, or there is no default index file for this directory.
Please consider filing [a bug](https://bugs.eclipse.org/bugs/) against the project to let them know.
```
> [4.0] Nightly build reports - permission change

- moxy/eclipselink.moxy.test/antbuild.xml
Merge JVM arguments from internal store (_antbuild.xml_) and outside (passed with `-Dadditional.jvmargs=....` command line parameter).
To correctly handle MOXy test execution command like
`ant -f antbuild.xml -Dadditional.jvmargs='-javaagent:/usr/local/javaApplications/jacoco-0.8.10/lib/jacocoagent.jar=destfile=/0/0000/jacoco.out,append=true,includes=javax.persistence*:org.eclipse.persistence*,excludes=javax.resource*:org.eclipse.persistence.internal.libraries*,sessionid=lrg,output=file' test-moxy` with needed internal `-Ddummy2=dummy --add-opens java.base/java.math=ALL-UNNAMED` JVM options.
> [2.7] Ant build - MOXy tests fix

- moxy/eclipselink.moxy.test/antbuild.xml
Merge JVM arguments from internal store (antbuild.xml) and outside (passed with '-Dadditional.jvmargs=....' command line parameter).
There was issue with previous fix, that Ant will initialize undefined property automatically during calls like `value="${additional.jvmargs}..."` into value `'${additional.jvmargs}'`.
> [2.7] Ant build - MOXy tests fix 2.0

- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/jpa/JpaHelper.java
Fixes #1893
Backport from  #1911
(cherry picked from commit 6d59a82a5b2be5b7e5403a95ce436b071fa744ad)
> [4.0] Bugfix for - Missing error message when calling JpaHelper.getReportQuery() with wrong argument - backport

- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/jpa/JpaHelper.java
Fixes #1893
Backport from #1911
(cherry picked from commit 6d59a82a5b2be5b7e5403a95ce436b071fa744ad)
> [3.0] Bugfix for - Missing error message when calling JpaHelper.getReportQuery() with wrong argument - backport

- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/jpa/JpaHelper.java
Fixes #1893
Backport from #1911
> [2.7] Bugfix for - Missing error message when calling JpaHelper.getReportQuery() with wrong argument - backport

- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/EntityManagerSetupImpl.java
Fixes #1920
This fix is limited on 2.7 branch. In master, 4.0, 3.0 is `setQueryCacheForceDeferredLocks...` placed before possible return.
Reported bug contains two parts
- move `setQueryCacheForceDeferredLocks...` before possible `return`. It's done in this PR
- Change default value in `org.eclipse.persistence.queries.ObjectBuildingQuery.ObjectBuildingQuery()` `this.requiresDeferredLocks = true;` .  Unfortunately this change we can't accept as it will change default behavior and break backward compatibility -> should leads into regressions.
> Configuration of CACHE_QUERY_FORCE_DEFERRED_LOCKS - fix [2.7]

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/sessions/AbstractSession.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/logging/AbstractSessionLog.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/logging/JavaLog.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/logging/LogCategory.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/logging/SessionLog.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/logging/SessionLogEntry.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/sessions/Session.java
deprecate usages of Date/DateFormat for removal,
remove most of the dependencies on internal packages
> Update logging to use java.time,

- foundation/eclipselink.core.test/src/it/java/org/eclipse/persistence/testing/tests/unitofwork/UOWPrimaryKeyToNewObjectsDuplicateObjectsTest.java
- foundation/eclipselink.core.test/src/it/java/org/eclipse/persistence/testing/tests/unitofwork/UnitOfWorkTestSuite.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/sessions/UnitOfWorkImpl.java
- jpa/eclipselink.jpa.testapps/jpa.test.advanced/src/test/java/org/eclipse/persistence/testing/tests/jpa/advanced/EntityManagerJUnitTestSuite.java
- Fixes #1950 
~Objects are now no longer added to `primaryKeyToNewObjects` in `assignSequenceNumber`.~
I've refactored the code to use an `IdentityHashSet` instead of `ArrayList` for `primaryKeyToNewObjects` to prevent duplicates in the future.
Additionally I added two UnitTests. One verifies that calling `registerNewObjectForPersist` does not result in duplicates in `primaryKeyToNewObjects`. The other tests the complete `EntityManager` persist, remove, find workflow from the original issue.
> [master] fix #1950: Duplicate objects in UnitOfWorkImpl.primaryKeyToNewObjects

- antbuild.properties
- antbuild.xml
- features/bundles/eclipselink/src/module-info.java
This change contains two fixes:
- opens some packages in module-info.java as there are some resource files needed to read
- eclipselink source bundle to include there correct module-info.java file
> [2.7] Eclipselink.jar - JPMS fixes

- jpa/eclipselink.jpa.testapps/jpa.test.advanced/pom.xml
- jpa/eclipselink.jpa.testapps/jpa.test.advanced/src/main/resources/META-INF/persistence.xml
It seems, that after transformation from `jpa.test` to `jpa.testapps` `EntityManagerJUnitTestSuite` from `jpa.testapps.advanced` was excluded from the execution. This change returns this suite back.
> [master] JPA Test Advanced fix

- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/tests/unitofwork/UOWPrimaryKeyToNewObjectsDuplicateObjectsTest.java
- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/tests/unitofwork/UnitOfWorkTestSuite.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/sessions/UnitOfWorkImpl.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa/advanced/EntityManagerJUnitTestSuite.java
- fixes #1950 
Backport of #1951 to 2.7. For details see PR to master.
> [2.7] fix #1950: Duplicate objects in UnitOfWorkImpl.primaryKeyToNewObjects - backport from master

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/config/QueryHints.java
Javadoc states that `seconds` is the default unit of time, but the actual default value seem to be `milliseconds`:
https://github.com/eclipse-ee4j/eclipselink/blob/master/foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/descriptors/DescriptorQueryManager.java#L135
> Fix slightly inaccurate QUERY_TIMEOUT hint's javadoc

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/sessions/UnitOfWorkImpl.java
- fixes #1957 
Add initial size to map creation where expected size is known or can be estimated
> [master] fix #1957: Presize HashMap allocations in UnitOfWorkImpl

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/sessions/UnitOfWorkImpl.java
- fixes #1957 
backport of #1958
> [2.7] fix 1957: Presize HashMap allocations in UnitOfWorkImpl - backport from master

- sdo/org.eclipse.persistence.sdo/src/main/java/org/eclipse/persistence/sdo/helper/SDOHelperContext.java
This change allows remove specified SDO helper context. It offers to applications or application frameworks like Oracle ADF to control/remove unused helper context from the memory as in case of older JVMs (1.8.0) high amount of Metaspace memory should be occupied.
Application or application framework must recreate helper context if it will be used again.
> [master] SDO helper context removal

- bundles/eclipselink/pom.xml
- bundles/eclipselink/src/main/java/module-info.java
Adds support for JPMS module-info.java into eclipselink.jar.
There are related changes in _pom.xml_ too.
This is partial backport from #1943
> [3.0] Eclipselink.jar - add JPMS descriptor (module-info.java) - backport from 2.7

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/core/databaseaccess/CorePlatform.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/databaseaccess/DatasourcePlatform.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/sessions/UnitOfWorkImpl.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/mappings/converters/TypeConversionConverter.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/Oracle23Platform.java
- foundation/org.eclipse.persistence.oracle/src/main/java/org/eclipse/persistence/platform/database/oracle/Oracle23Platform.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/oraclefeatures/TestOracleLOBLocatorFeature.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/metadata/converters/LobMetadata.java
This fixes following two issues related with Oracle23c:
- when empty String (`""`) is inserted into table column like `...CLOBDATA CLOB NOT NULL...`
Solution is based on conversion into `java.sql.Clob`, because solution based on `SimpleAppendCallCustomParameter("empty_clob()")` and `DatabasePlatform.appendParameter()` leads into another test failures.
- loss of precision if DB table is automatically created if entity using `java.time.LocalDateTime`, `java.time.LocalTime`
> [master] Oracle 23C platform fixes

- foundation/eclipselink.core.test/src/it/java/org/eclipse/persistence/testing/tests/events/SessionEventTestCase.java
- foundation/eclipselink.core.test/src/it/java/org/eclipse/persistence/testing/tests/events/TestSessionListener.java
- foundation/eclipselink.core.test/src/it/java/org/eclipse/persistence/testing/tests/unitofwork/PostFlushUnitOfWorkTest.java
- foundation/eclipselink.core.test/src/it/java/org/eclipse/persistence/testing/tests/unitofwork/PreFlushUnitOfWorkTest.java
- foundation/eclipselink.core.test/src/it/java/org/eclipse/persistence/testing/tests/unitofwork/UnitOfWorkEventTestSuite.java
- foundation/org.eclipse.persistence.core.test.framework/src/main/java/org/eclipse/persistence/testing/framework/SessionEventTracker.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/sessions/RepeatableWriteUnitOfWork.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/sessions/UnitOfWorkImpl.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/sessions/remote/RemoteUnitOfWork.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/sessions/SessionEvent.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/sessions/SessionEventAdapter.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/sessions/SessionEventListener.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/sessions/SessionEventManager.java
fix #1240 
- Added preFlushUnitOfWork/postFlushUnitOfWork events
- Removed preCommitUnitOfWork event from flush in UnitOfWorkImpl, since triggering a commit event for a flush seems wrong to me.
> [master] fix #1240: SessionEventListener: add pre/post flush() events

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/InformixPlatform.java
Issue: Poor performance of InformixPlatform with IDENTITY generated primary keys#968
https://github.com/eclipse-ee4j/eclipselink/issues/968
> Issue:  Poor performance of InformixPlatform with IDENTITY generated primary keys#968

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/config/PersistenceUnitProperties.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/security/JCEEncryptor.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/security/SecurableObjectHolder.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/security/Securable.java
- jpa/eclipselink.jpa.test/resource/eclipselink-advanced-properties/persistence.xml
- jpa/eclipselink.jpa.test/resource/eclipselink-advanced-properties/server/persistence.xml
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa/jpaadvancedproperties/CustomizedEncryptor.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa/jpaadvancedproperties/JPAAdvPropertiesJUnitTestCase.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/EntityManagerSetupImpl.java
This is implementation of new PersistenceUnit property `eclipselink.login.encryptor`.
Same property (by meaning) `encryption-class` is available in _sessions.xml_ file.
Usage of this avoid limit of Session customizer which called when all
other properties have been processed (too late when database login is configured).
> [2.7] New PersistenceUnit property - eclipselink.login.encryptor - backport from master

- moxy/eclipselink.moxy.test/pom.xml
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/installer/JaxbCompilerTestCase.java
- Installer test is more responsive now and prints in case of failure STDOUT and STDERR
- Remove some warning messages in OSGi test on JDK 21 by tes dependencies update
> [2.7] Installer and OSGi test fixes

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/expressions/Expression.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/jpa/jpql/ExpressionBuilderVisitor.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/json/TestJson.java
Using [SQL operator,](https://wiki.eclipse.org/EclipseLink/UserGuide/JPA/Basic_JPA_Development/Querying/JPQL#SQL) it is not possible to use '?' as a native operator (e.g. on Postgres). This PR is to allow using '??' as an escape mechanism, similar to the escaping mechanism used by [Postgres JDBC](https://jdbc.postgresql.org/documentation/query/#using-the-statement-or-preparedstatement-interface).
This is to fix issue #836
> Allow escaping of '?' using '??' in SQL expression

- buildsystem/compdeps/pom.xml
- foundation/org.eclipse.persistence.core/resource/org/eclipse/persistence/internal/helper/VendorNameToPlatformMapping.properties
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/core/databaseaccess/CorePlatform.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/databaseaccess/DatasourcePlatform.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/databaseaccess/Platform.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/mappings/converters/TypeConversionConverter.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/Oracle23Platform.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/oracle/plsql/PLSQLStoredProcedureCall.java
- foundation/org.eclipse.persistence.oracle/src/org/eclipse/persistence/platform/database/oracle/Oracle23Platform.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/oraclefeatures/TestOracleLOBLocatorFeature.java
- jpa/eclipselink.jpa.test/antbuild.xml
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa/plsql/PLSQLTestSuite.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/metadata/converters/LobMetadata.java
Adds support for Oracle 23c database.
There are following changes
- `Oracle23Platform` platform classes added
- New Oracle JDBC driver 23.x.x.x has, in some cases, different behaviour for boolean type. There are changes in PL/SQL calls.
- Fix when empty String (`""`) is inserted into table column like `...CLOBDATA CLOB NOT NULL...` Solution is based on conversion into `java.sql.Clob`, because solution based on `SimpleAppendCallCustomParameter("empty_clob()")` and `DatabasePlatform.appendParameter()` leads into another test failures.
- Fix for loss of precision if DB table is automatically created if entity using `java.time.LocalDateTime`, `java.time.LocalTime`.
- JDBC Driver update
This PR is based on backports from #1876 and  #1969.
> [2.7] Oracle 23C platform - backport from master

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/databaseaccess/DatabasePlatform.java
Fixes #1970 .
This bug should happens is no `pingSQL` DB platform property is specified and query execution fails.
> [master] DatabasePlatform.wasFailureCommunicationBased() fix

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/databaseaccess/DatabasePlatform.java
Fixes #1970 .
This bug should happens is no pingSQL DB platform property is specified and query execution fails.
> [2.7] DatabasePlatform.wasFailureCommunicationBased() fix - backport from master

- antbuild.properties
- antbuild.xml
- etc/jenkins/pr_verify.groovy
- features/bundles/eclipselink/src/module-info.java
- foundation/bin/passwordUpdate.cmd
- foundation/bin/passwordUpdate.sh
- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/tests/junit/security/SecurableBackwardsCompatibilityTest.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/localization/i18n/LoggingLocalizationResource.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/security/JCEEncryptor.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/security/SecurableObjectHolder.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/xml/XMLComparer.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/tools/security/JCEEncryptorCmd.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/EntityManagerSetupImpl.java
- utils/eclipselink.dbws.builder.test/src/dbws/testing/loglevelvalidation/LogLevelValidationTestSuite.java
JCEEncryptor default encryption algorithm upgrade from AES/CBC/PKCS5Padding to AES/GCM/NoPadding . Plus:
- Standalone conversion tool to re-encrypt passwords
- Extended unit test to verify backwards compatibility.
> [2.7] JCEEncryptor default encryption algorithm upgrade

- etc/archetypes/bug_test_case/jpa/src/main/resources/archetype-resources/pom.xml
- etc/el-test.h2.properties
- foundation/org.eclipse.persistence.core.test.framework/src/main/java/org/eclipse/persistence/testing/tests/ClearDatabaseSchemaTest.java
- pom.xml
Database default storage (persistent) specified in `db.url property` is `~/h2/ecltests` directory.
Not all tests passing now.
> [master] Maven build: H2 database profile added to execute tests against H2

- dbws/eclipselink.dbws.test/antbuild.xml
- foundation/eclipselink.extension.oracle.test/antbuild.xml
- jpa/eclipselink.jpa.test/antbuild.xml
- jpa/eclipselink.jpa.wdf.test/antbuild.xml
- jpa/org.eclipse.persistence.jpa.jpql.test/antbuild.xml
- moxy/eclipselink.moxy.test/antbuild.xml
- sdo/eclipselink.sdo.test/antbuild.xml
- utils/eclipselink.dbws.builder.test/antbuild.xml
To clean some generated files in:
- JPA server-test-lrg target
- All test-lrg target
> [2.7] Ant build cleanup fix

- foundation/eclipselink.core.test/src/it/java/org/eclipse/persistence/testing/models/insurance/PolicyHolder.java
- foundation/eclipselink.core.test/src/it/java/org/eclipse/persistence/testing/tests/unitofwork/changeflag/ALCTEmployeeSystem.java
- foundation/eclipselink.core.test/src/test/java/org/eclipse/persistence/testing/tests/junit/helper/HelperTest.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/exceptions/ConversionException.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/exceptions/i18n/ConversionExceptionResource.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/helper/Helper.java
- jpa/eclipselink.jpa.testapps/jpa.test.inherited/src/test/java/org/eclipse/persistence/testing/tests/jpa/inherited/InheritedModelJunitTest.java
- jpa/eclipselink.jpa.testapps/jpa.test.xml.only/jpa.test.xml.inherited/src/test/java/org/eclipse/persistence/testing/tests/jpa/xml/inherited/EntityMappingsInheritedJUnitTestCase.java
- moxy/org.eclipse.persistence.moxy/pom.xml
Fixes following issues:
- MOXy tests parallel execution
- in some special cases `Calendar` cache in `Helper` should contain `Calendar` instances with different time zone settings than current time zone. It should lead into unexpected date/time conversion results. Special case means that current time zone is changed during JVM execution see `org.eclipse.persistence.testing.oxm.XMLTestCase`
- Incorrect date values were accepted without any warning/exception and incorrect results (overflow) were produced.
I briefly checked there performance for
```
for (int i = 0; i < 10000000; i++) {
java.sql.Date date = dateFromYearMonthDate(YEAR + i, MONTH, DAY);
}
```
and there is some improvement
Origin:		1956 ms
LocalDate:	500 ms
> [master] org.eclipse.persistence.internal.helper.Helper.dateFromYearMonthDate fix

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/descriptors/DescriptorIterator.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/sessions/UnitOfWorkImpl.java
- jpa/eclipselink.jpa.testapps/jpa.test.advanced/src/main/java/org/eclipse/persistence/testing/models/jpa/advanced/Material.java
- jpa/eclipselink.jpa.testapps/jpa.test.advanced/src/test/java/org/eclipse/persistence/testing/tests/jpa/advanced/EntityManagerJUnitTestSuite.java
There are two fixes for EntityManager.detach():
- Lazy collections are fetched on detach
Unnecessary fetch of lazy loaded collection `Indirect...` declared in the detached entity. See #2017
- StackOverflowError because of cyclic DETACH
It happens if there is cross relation between entities like 
`@OneToMany(cascade = {CascadeType.ALL }, fetch = FetchType.LAZY,...` from the first entity and
`@ManyToOne(cascade = { CascadeType.ALL}, fetch = FetchType.EAGER,...` from the second. See #1577
fixes #2017 #1577 
replaces #292
> [master] detach() fixes

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/localization/i18n/ExceptionLocalizationResource.java
- jpa/eclipselink.jpa.testapps/jpa.test.persistence32/src/main/java/org/eclipse/persistence/testing/models/jpa/persistence32/Pokemon.java
- jpa/eclipselink.jpa.testapps/jpa.test.persistence32/src/main/java/org/eclipse/persistence/testing/models/jpa/persistence32/Team.java
- jpa/eclipselink.jpa.testapps/jpa.test.persistence32/src/main/java/org/eclipse/persistence/testing/models/jpa/persistence32/Trainer.java
- jpa/eclipselink.jpa.testapps/jpa.test.persistence32/src/test/java/org/eclipse/persistence/testing/tests/jpa/persistence32/EntityGraphTest.java
- jpa/eclipselink.jpa.testapps/jpa.test.persistence32/src/test/java/org/eclipse/persistence/testing/tests/jpa/persistence32/EntityManagerFactoryTest.java
- jpa/eclipselink.jpa.testapps/jpa.test.persistence32/src/test/java/org/eclipse/persistence/testing/tests/jpa/persistence32/QueryTest.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/EntityGraphImpl.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/EntityManagerFactoryDelegate.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/EntityManagerFactoryImpl.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/EntityManagerImpl.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/QueryHintsHandler.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/TypedQueryReferenceImpl.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/metamodel/AttributeImpl.java
- pom.xml
- jakartaee/persistence#454 - removeAttributeNodes(Attribute.PersistentAttributeType) in Graph
- jakartaee/persistence#512 - factory-level access to named queries and named entity graphs
- Updated jakarta.persistence version to 3.2.0-M1
> Jakarta Persistence 3.2: 6th batch

- jpa/org.eclipse.persistence.jpa.jpql/src/test/java/org/eclipse/persistence/jpa/tests/jpql/parser/JPQLExpressionTurkishLocaleTest.java
- pom.xml
There are three required changes
- Maven compiler target and enforcer plugin into Java 17
- Derby dependency version decrease to 10.16.1.1 as 10.17.x supports Java 21 only
- Code change to create `Locale` by `Locale.Builder` in _JPQLExpressionTurkishLocaleTest.java_
> [master] JDK 17 support

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/exceptions/StaticWeaveException.java
- jpa/eclipselink.jpa.testapps/jpa.test.weaving/pom.xml
- jpa/eclipselink.jpa.testapps/jpa.test.weaving/src/main/resources/META-INF/persistence.xml
- jpa/eclipselink.jpa.testapps/jpa.test.weaving/src/test/java/org/eclipse/persistence/testing/models/jpa/weaving/WeavingChangeListener.java
- jpa/eclipselink.jpa.testapps/jpa.test.weaving/src/test/java/org/eclipse/persistence/testing/models/jpa/weaving/WeavingEntityInDir.java
- jpa/eclipselink.jpa.testapps/jpa.test.weaving/src/test/java/org/eclipse/persistence/testing/tests/jpa/weaving/WeavingTest.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/weaving/ClassWeaver.java
Contains following main changes:
- Replacement of deprecated e.g. `new Integer(...)` by `Integer.valueOf(...)`
- Generated `_persistence_shallow_clone` content is wrapped by `try/catch`
- Remove dependency to JPA module (`org.eclipse.persistence.internal.jpa.EntityManagerImpl` class) in generated `_persistence_checkFetched` and `_persistence_checkFetchedForSet`
There are some extensions in weaving test to more deeply check methods/logic generated by ClassWeaver.
To verify generated code I'd like recommend in extension to decompiler to use some plugin which can display decompiled bytecode as ASMified code. E.g. _ASM Bytecode Viewer_ in _InteliJ_. Reason is that `Integer.valueOf(...)` is not displayed in decompiled bytecode.
> [master] ClassWeaver refresh

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/localization/i18n/LoggingLocalizationResource.java
Added minor messaging improvements.
> [2.7] Minor messaging improvements

- performance/eclipselink.perf.test/src/test/java/org/eclipse/persistence/testing/perf/beanvalidation/MOXyValidationBenchmark.java
- performance/eclipselink.perf.test/src/test/java/org/eclipse/persistence/testing/perf/jpa/tests/basic/JPAMetadataProcessingTests.java
- performance/eclipselink.perf.test/src/test/java/org/eclipse/persistence/testing/perf/largexml/bigpo/channel_code/ChannelCodeContentType.java
- performance/eclipselink.perf.test/src/test/java/org/eclipse/persistence/testing/perf/largexml/bigpo/chip_code/ChipCodeContentType.java
- performance/eclipselink.perf.test/src/test/java/org/eclipse/persistence/testing/perf/largexml/bigpo/core_component_types/BinaryObjectType.java
- performance/eclipselink.perf.test/src/test/java/org/eclipse/persistence/testing/perf/largexml/bigpo/country_identification_code/CountryIdentificationCodeContentType.java
- performance/eclipselink.perf.test/src/test/java/org/eclipse/persistence/testing/perf/largexml/bigpo/currency_code/CurrencyCodeContentType.java
- performance/eclipselink.perf.test/src/test/java/org/eclipse/persistence/testing/perf/largexml/bigpo/document_status_code/DocumentStatusCodeContentType.java
- performance/eclipselink.perf.test/src/test/java/org/eclipse/persistence/testing/perf/largexml/bigpo/latitude_direction_code/LatitudeDirectionCodeContentType.java
- performance/eclipselink.perf.test/src/test/java/org/eclipse/persistence/testing/perf/largexml/bigpo/line_status_code/LineStatusCodeContentType.java
- performance/eclipselink.perf.test/src/test/java/org/eclipse/persistence/testing/perf/largexml/bigpo/longitude_direction_code/LongitudeDirectionCodeContentType.java
- performance/eclipselink.perf.test/src/test/java/org/eclipse/persistence/testing/perf/largexml/bigpo/operator_code/OperatorCodeContentType.java
- performance/eclipselink.perf.test/src/test/java/org/eclipse/persistence/testing/perf/largexml/bigpo/substitution_status_code/SubstitutionStatusCodeContentType.java
- performance/eclipselink.perf.test/src/test/java/org/eclipse/persistence/testing/perf/reflection/ReflectionBenchmark.java
- performance/eclipselink.perf.test/src/test/java/org/eclipse/persistence/testing/perf/reflection/ReflectionUtils.java
- performance/eclipselink.perf.test/src/test/java/org/eclipse/persistence/testing/perf/reflection/SimpleConcurrentReflectionUtils.java
- cleanup some compilation issues on Java 21
- warnings cleanup include some Javadoc warnings
Performance tests against Derby should be executed by
`mvn clean test -pl :org.eclipse.persistence.performance.test -Ptest-performance`
> [master] Performance tests - code refresh

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/databaseaccess/DatabaseCall.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/databaseaccess/DatasourceCall.java
- jpa/eclipselink.jpa.testapps/jpa.test.jpql/src/test/java/org/eclipse/persistence/testing/tests/jpa/jpql/advanced/JUnitJPQLComplexTest.java
This is bugfix for case like
```
...
Query query = em.createQuery("SELECT e from Employee e WHERE e.lastName IN :lastName");
query.setParameter("lastName", null);
...
```
or
```
...
Query query = em.createQuery("SELECT e from Employee e WHERE e.lastName IN :lastName");
query.setParameter("lastName", new ArrayList<>());
...
```
before this fix some `SQLException` was thrown due a incorrect SQL query.
After this fix booth JPQLs will be translated into something like
`SELECT * FROM employee WHERE l_name IN (NULL)`
Database will return empty `ResultSet` for this kind of query.
By default there is handling for
```
...
Query query = em.createQuery("SELECT e from Employee e WHERE e.lastName NOT IN :lastName");
query.setParameter("lastName", List.of());
...
```
which is translated into
`SELECT * …
> [master] Allow an empty collection or null as a parameter in an "IN" expression

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/databaseaccess/DatabasePlatform.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/helper/ClassConstants.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/helper/ConversionManager.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/conversion/TestJavaTimeTypeConverter.java
- jpa/eclipselink.jpa.testapps/jpa.test.datetime/src/main/java/org/eclipse/persistence/testing/models/jpa/datetime/DateTime.java
- jpa/eclipselink.jpa.testapps/jpa.test.datetime/src/main/java/org/eclipse/persistence/testing/models/jpa/datetime/DateTimePopulator.java
- jpa/eclipselink.jpa.testapps/jpa.test.datetime/src/main/java/org/eclipse/persistence/testing/models/jpa/datetime/DateTimeTableCreator.java
- jpa/eclipselink.jpa.testapps/jpa.test.datetime/src/test/java/org/eclipse/persistence/testing/tests/jpa/datetime/NullBindingTest.java
- jpa/eclipselink.jpa.testapps/jpa.test.jpql/src/test/java/org/eclipse/persistence/testing/tests/jpa/jpql/datetime/JUnitJPQLDateTimeTest.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/metadata/accessors/mappings/MappingAccessor.java
This change adds support for java.time.Instant and java.time.Year classes according spec 
2.6. Basic Types, 11.1.6. Basic Annotation
https://jakartaee.github.io/persistence/latest-nightly/nightly.html#a486 https://jakartaee.github.io/persistence/latest-nightly/nightly.html#a14205 or see Specification appendix A.1. Jakarta Persistence 3.2 https://jakartaee.github.io/persistence/latest-nightly/nightly.html#jakarta-persistence-3-2
> [master] Jakarta Persistence 3.2: java.time.Instant and java.time.Year support as a basic types

- jpa/eclipselink.jpa.testapps/jpa.test.persistence32/src/test/java/org/eclipse/persistence/testing/tests/jpa/persistence32/EntityManagerFactoryTest.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/EntityManagerFactoryDelegate.java
According specification to get Persistence unit name `//persistence-unit/@name` like `test_pu1` from `<persistence-unit name="test_pu1" transaction-type="RESOURCE_LOCAL">` instead of current fully qualified name.
> EntityManagerFactory.getName() fix

- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/metadata/accessors/classes/MappedSuperclassAccessor.java
PROBLEM
=======
NullPointerException raising at CacheIndexMetadata.getField() while EntityManager initialising.
CAUSE
=======
Entity metadata XML file contains tag <cache-index><column-name>SOMENAME</column-name></cache-index>.
XML Deserializer call CacheIndexMetadata default constructor. ORMetadata.m_project field stay none initialised.
Call of CacheIndexMetadata.getField() throw to exception.
SOLVING
=======
Set ORMetadata.m_project value after XML deserialization.
Signed-off-by: Vladimir Ivanov <ivvlev@ivvlev.com>
> [3.0] Bugfix: NullPointerException at CacheIndexMetadata.getField()

- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/metadata/accessors/classes/MappedSuperclassAccessor.java
NullPointerException raising at CacheIndexMetadata.getField() while EntityManager initialising is XML mapping (ORM) file is used with following part e.g.:
```
...
<cache isolation="SHARED"/>
<cache-index>
<column-name>deptName</column-name>
</cache-index>
...
```
> [4.0] Bugfix: NullPointerException at CacheIndexMetadata.getField()

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/helper/ConcurrencyManager.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/helper/ReadLockManager.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/helper/WriteLockManager.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/identitymaps/CacheKey.java
- performance/eclipselink.perf.test/el-test.performance.properties
- performance/eclipselink.perf.test/pom.xml
- performance/eclipselink.perf.test/src/test/java/org/eclipse/persistence/testing/perf/CoreBenchmarks.java
- performance/eclipselink.perf.test/src/test/java/org/eclipse/persistence/testing/perf/JPAMetadataBenchmarks.java
- performance/eclipselink.perf.test/src/test/java/org/eclipse/persistence/testing/perf/MOXyBenchmarks.java
- performance/eclipselink.perf.test/src/test/java/org/eclipse/persistence/testing/perf/beanvalidation/MOXyValidationBenchmark.java
- performance/eclipselink.perf.test/src/test/java/org/eclipse/persistence/testing/perf/core/ConcurrencyManagerBenchmark.java
- performance/eclipselink.perf.test/src/test/java/org/eclipse/persistence/testing/perf/jpa/model/basic/DetailEntity.java
- performance/eclipselink.perf.test/src/test/java/org/eclipse/persistence/testing/perf/jpa/model/basic/MasterEntity.java
- performance/eclipselink.perf.test/src/test/java/org/eclipse/persistence/testing/perf/jpa/tests/basic/JPAMetadataProcessingTests.java
- performance/eclipselink.perf.test/src/test/java/org/eclipse/persistence/testing/perf/jpa/tests/basic/JPAReadAbstract.java
- performance/eclipselink.perf.test/src/test/java/org/eclipse/persistence/testing/perf/jpa/tests/basic/JPAReadLargeAmmountAbstract.java
- performance/eclipselink.perf.test/src/test/java/org/eclipse/persistence/testing/perf/jpa/tests/basic/JPAReadLargeAmmountCacheTests.java
- performance/eclipselink.perf.test/src/test/java/org/eclipse/persistence/testing/perf/jpa/tests/basic/JPAReadLargeAmmountNoCacheTests.java
- performance/eclipselink.perf.test/src/test/java/org/eclipse/persistence/testing/perf/jpa/tests/basic/JPAReadSmallAmmountAbstract.java
- performance/eclipselink.perf.test/src/test/java/org/eclipse/persistence/testing/perf/jpa/tests/basic/JPAReadSmallAmmountCacheTests.java
- performance/eclipselink.perf.test/src/test/java/org/eclipse/persistence/testing/perf/jpa/tests/basic/JPAReadSmallAmmountNoCacheTests.java
- performance/eclipselink.perf.test/src/test/java/org/eclipse/persistence/testing/perf/reflection/ReflectionBenchmark.java
- performance/eclipselink.perf.test/src/test/java/org/eclipse/persistence/testing/perf/reflection/ReflectionUtils.java
- performance/eclipselink.perf.test/src/test/java/org/eclipse/persistence/testing/perf/reflection/SimpleConcurrentReflectionUtils.java
- performance/eclipselink.perf.test/src/test/resources/META-INF/persistence.xml
This change improves EclipseLink performance with higher versions of the JDK (21 and above). It's about replacement of synchronized keyword and wait(), notify() methods by objects from java.util.concurrent.locks.* package. Additionally there are some new performance tests to verify it.
Backport from #2116
(cherry picked from commit 1f0cf759092beb031ccc2e5a6950f239f15b5b55)
> [4.0] Performance improvement: synchronize to java.util.concurrent.locks switch to improve performance with VirtualThreads - backport from master

- antbuild.xml
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/helper/ConcurrencyManager.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/helper/ReadLockManager.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/helper/WriteLockManager.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/identitymaps/CacheKey.java
- performance/eclipselink.perf.test/antbuild.properties
- performance/eclipselink.perf.test/antbuild.xml
- performance/eclipselink.perf.test/resource/META-INF/persistence.xml
- performance/eclipselink.perf.test/src/org/eclipse/persistence/testing/perf/CoreBenchmarks.java
- performance/eclipselink.perf.test/src/org/eclipse/persistence/testing/perf/JPAMetadataBenchmarks.java
- performance/eclipselink.perf.test/src/org/eclipse/persistence/testing/perf/MOXyBenchmarks.java
- performance/eclipselink.perf.test/src/org/eclipse/persistence/testing/perf/core/ConcurrencyManagerBenchmark.java
- performance/eclipselink.perf.test/src/org/eclipse/persistence/testing/perf/jpa/model/basic/DetailEntity.java
- performance/eclipselink.perf.test/src/org/eclipse/persistence/testing/perf/jpa/model/basic/MasterEntity.java
- performance/eclipselink.perf.test/src/org/eclipse/persistence/testing/perf/jpa/tests/basic/JPAReadAbstract.java
- performance/eclipselink.perf.test/src/org/eclipse/persistence/testing/perf/jpa/tests/basic/JPAReadLargeAmmountAbstract.java
- performance/eclipselink.perf.test/src/org/eclipse/persistence/testing/perf/jpa/tests/basic/JPAReadLargeAmmountCacheTests.java
- performance/eclipselink.perf.test/src/org/eclipse/persistence/testing/perf/jpa/tests/basic/JPAReadLargeAmmountNoCacheTests.java
- performance/eclipselink.perf.test/src/org/eclipse/persistence/testing/perf/jpa/tests/basic/JPAReadSmallAmmountAbstract.java
- performance/eclipselink.perf.test/src/org/eclipse/persistence/testing/perf/jpa/tests/basic/JPAReadSmallAmmountCacheTests.java
- performance/eclipselink.perf.test/src/org/eclipse/persistence/testing/perf/jpa/tests/basic/JPAReadSmallAmmountNoCacheTests.java
This change improves EclipseLink performance with higher versions of the JDK (21 and above). It's about replacement of synchronized keyword and wait(), notify() methods by objects from java.util.concurrent.locks.* package. Additionally, there are some new performance tests to verify it and performance tests refresh.
Backport from #2116
(cherry picked from commit 1f0cf759092beb031ccc2e5a6950f239f15b5b55)
> [2.7] Performance improvement: synchronize to java.util.concurrent.locks switch to improve performance with VirtualThreads - backport from master

- jpa/eclipselink.jpa.testapps/jpa.test.persistence32/src/test/java/org/eclipse/persistence/testing/tests/jpa/persistence32/CriteriaBuilderTest.java
Fixes Issue
There was issue in new CriteriaBuilder tests in `org.eclipse.persistence.jpa.testapps.persistence32` module. There wasn't from() and select() mentioned in some tests.
Describe the change
Add missing method calls.
> [master] Jakarta Persistence 3.2 - CriteriaQuery test fix

- bundles/eclipselink/src/main/scripts/utils/security/passwordUpdate.cmd
- bundles/eclipselink/src/main/scripts/utils/security/passwordUpdate.sh
- foundation/eclipselink.core.test/src/test/java/org/eclipse/persistence/testing/tests/junit/security/SecurableBackwardsCompatibilityTest.java
- foundation/org.eclipse.persistence.core/src/main/java/module-info.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/exceptions/ValidationException.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/exceptions/i18n/ValidationExceptionResource.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/localization/i18n/LoggingLocalizationResource.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/security/JCEEncryptor.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/xml/XMLComparer.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/security/Securable.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/tools/security/JCEEncryptorCmd.java
- utils/org.eclipse.persistence.dbws.builder/src/it/java/dbws/testing/loglevelvalidation/LogLevelValidationTestSuite.java
JCEEncryptor default encryption algorithm upgrade from AES/CBC/PKCS5Padding to AES/GCM/NoPadding . Plus extended unit test.
- for AES/GCM/NoPadding random initialization vector (IV) instead of static one.
- shell scripts added, resource strings moved to localization bundle DBWS builder test fix
(cherry picked from commit 149e9ce03de38b153ca117e4ce251a879b8d486b)
> [4.0] JCEEncryptor default encryption algorithm upgrade (#2004) - backport from master

- docs/docs.jpa/src/main/asciidoc/persistenceproperties_ref.adoc
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/config/PersistenceUnitProperties.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/security/SecurableObjectHolder.java
- jpa/eclipselink.jpa.testapps/jpa.test.jpaadvancedproperties/src/main/resources/META-INF/persistence.xml
- jpa/eclipselink.jpa.testapps/jpa.test.jpaadvancedproperties/src/test/java/org/eclipse/persistence/testing/tests/jpa/jpaadvancedproperties/CustomizedEncryptor.java
- jpa/eclipselink.jpa.testapps/jpa.test.jpaadvancedproperties/src/test/java/org/eclipse/persistence/testing/tests/jpa/jpaadvancedproperties/JPAAdvPropertiesTest.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/EntityManagerSetupImpl.java
New non-internal org.eclipse.persistence.security.Securable interface to implement custom password encryptor
(cherry picked from commit c8f43afdb8362ab3756291d5216bfa0ee03e0332)
> [4.0] New PersistenceUnit property - eclipselink.login.encryptor - backport from master

- pom.xml
There are a few notes about this change:
Maven plugins were upgraded to the latest available versions
Dependencies were upgraded to the versions which accept JDK 11 and Jakarta EE 10
Project parent pom was updated to 1.0.9
> [4.0] Dependencies, Maven plugin and org.eclipse.ee4j:project versions upgrade

- moxy/org.eclipse.persistence.moxy/src/org/eclipse/persistence/jaxb/MOXySystemProperties.java
- moxy/org.eclipse.persistence.moxy/src/org/eclipse/persistence/jaxb/compiler/Generator.java
- moxy/org.eclipse.persistence.moxy/src/org/eclipse/persistence/jaxb/compiler/SchemaGenerator.java
This switch allows users use previous unordered behavior before PR #365.
> [2.7] MOXy SchemaGenerator WSDL Namespace order switch

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/expressions/ExpressionOperator.java
The bug is described in detail in #2136
We are looping over an array which is located in the instance field which can be set to `null` while lopping which is causing NPE. To fix it we are caching the value of `argumentIndices` by looping over an iterator of the array.
> fixes #2136 - NPE in ExpressionOperator.printCollection 

- foundation/eclipselink.extension.oracle.test/src/org/eclipse/persistence/testing/tests/jpa/proxyauthentication/ProxyAuthenticationServerTestSuite.java
Remove too strong dependency on Oracle error message. There is change between Oracle 23c and Oracle 23ai.
> [2.7] Oracle proxy authentication test fix

- foundation/org.eclipse.persistence.oracle.test/src/it/java/org/eclipse/persistence/testing/tests/jpa/proxyauthentication/ProxyAuthenticationServerTestSuite.java
Remove too strong dependency on Oracle error message. There is change between Oracle 23c and Oracle 23ai.
> [3.0] Oracle proxy authentication test fix - backport from master

- jpa/eclipselink.jpa.testapps.oracle/jpa.test.oracle.proxyauthentication/src/test/java/org/eclipse/persistence/testing/tests/jpa/proxyauthentication/ProxyAuthenticationServerTest.java
Remove too strong dependency on Oracle error message. There is change between Oracle 23c and Oracle 23ai.
> [4.0] Oracle proxy authentication test fix - backport from master

- foundation/org.eclipse.persistence.core.test.framework/src/main/java/org/eclipse/persistence/testing/tests/performance/emulateddb/EmulatedConnection.java
- foundation/org.eclipse.persistence.core.test.framework/src/main/java/org/eclipse/persistence/testing/tests/performance/emulateddb/EmulatedDatabaseMetaData.java
- foundation/org.eclipse.persistence.core.test.framework/src/main/java/org/eclipse/persistence/testing/tests/performance/emulateddb/EmulatedDriver.java
- foundation/org.eclipse.persistence.core.test.framework/src/main/java/org/eclipse/persistence/testing/tests/performance/emulateddb/EmulatedStatement.java
- foundation/org.eclipse.persistence.core.test.framework/src/main/resources/META-INF/services/java.sql.Driver
- performance/eclipselink.perf.test/src/test/java/org/eclipse/persistence/testing/perf/jpa/tests/basic/JPAReadAbstract.java
- performance/eclipselink.perf.test/src/test/resources/META-INF/persistence.xml
This change in EclipseLink JPA performance tests replace physical database by emulated one.
Emulation is based on `org.eclipse.persistence.testing.tests.performance.emulateddb.*` classes (JDBC driver).
There are some fixes like new required `EmulatedDatabaseMetaData` class and change in `EmulatedStatement` to distinguish passed SQL queries with parameters.
> [master] Performance tests improvement - use EmulatedDB

- docs/docs.api/pom.xml
- parent pom version
- MongoDB driver dependency
> [4.0] Maven build - org.eclipse.persistence.javadoc module fix

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/expressions/Expression.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/jpa/jpql/ExpressionBuilderVisitor.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/json/TestJson.java
Backport of #1935 to 4.0
Allow escaping of '?' using '??' in SQL expression and testEscapedQuestionMarkInSQLOperator to test ?? in SQL operator
> Allow escaping of '?' using '??' in SQL expression (#1935)

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/queries/DatabaseQuery.java
- jpa/eclipselink.jpa.testapps/jpa.test.composite.advanced/src/test/java/org/eclipse/persistence/testing/tests/jpa/composite/advanced/EntityManagerJUnitTest.java
This PR fixes issues at https://github.com/eclipse-ee4j/eclipselink/issues/1056
In the fix, the queryTimeoutUnit is also copied which was missed earlier
Added testcase at jpa/eclipselink.jpa.testapps/jpa.test.composite.advanced/src/test/java/org/eclipse/persistence/testing/tests/jpa/composite/advanced/EntityManagerJUnitTest.java
> queryTimeoutUnit is not copied to DataModifyQuery in executeUpdate

- foundation/eclipselink.core.test/src/it/java/org/eclipse/persistence/testing/tests/events/SessionEventTestCase.java
- foundation/eclipselink.core.test/src/it/java/org/eclipse/persistence/testing/tests/events/TestSessionListener.java
- foundation/eclipselink.core.test/src/it/java/org/eclipse/persistence/testing/tests/unitofwork/PostFlushUnitOfWorkTest.java
- foundation/eclipselink.core.test/src/it/java/org/eclipse/persistence/testing/tests/unitofwork/PreFlushUnitOfWorkTest.java
- foundation/eclipselink.core.test/src/it/java/org/eclipse/persistence/testing/tests/unitofwork/UnitOfWorkEventTestSuite.java
- foundation/org.eclipse.persistence.core.test.framework/src/main/java/org/eclipse/persistence/testing/framework/SessionEventTracker.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/sessions/RepeatableWriteUnitOfWork.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/sessions/UnitOfWorkImpl.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/sessions/remote/RemoteUnitOfWork.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/sessions/SessionEvent.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/sessions/SessionEventAdapter.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/sessions/SessionEventListener.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/sessions/SessionEventManager.java
> [4.0] Fix #1240: SessionEventListener: add pre/post flush() events - backport from master

- foundation/eclipselink.core.test/src/test/java/org/eclipse/persistence/testing/tests/junit/policies/NestedDetailRecord.java
- foundation/eclipselink.core.test/src/test/java/org/eclipse/persistence/testing/tests/junit/policies/NestedMasterRecord.java
- foundation/eclipselink.core.test/src/test/java/org/eclipse/persistence/testing/tests/junit/policies/RecordCopyPolicyTest.java
- foundation/eclipselink.core.test/src/test/java/org/eclipse/persistence/testing/tests/junit/policies/RecordInstantiationPolicyTest.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/descriptors/ClassDescriptor.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/descriptors/copying/AbstractCopyPolicy.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/descriptors/copying/InstantiationCopyPolicy.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/descriptors/copying/PersistenceEntityCopyPolicy.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/descriptors/copying/RecordCopyPolicy.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/core/descriptors/CoreObjectBuilder.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/descriptors/ObjectBuilder.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/descriptors/RecordInstantiationPolicy.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/oxm/XPathObjectBuilder.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/mappings/AggregateMapping.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/mappings/AggregateObjectMapping.java
- jpa/eclipselink.jpa.testapps/jpa.test.advanced.embeddable/src/main/java/org/eclipse/persistence/testing/models/jpa/advanced/embeddable/EmbeddableRecordTableCreator.java
- jpa/eclipselink.jpa.testapps/jpa.test.advanced.embeddable/src/main/java/org/eclipse/persistence/testing/models/jpa/advanced/embeddable/RecordAttribute.java
- jpa/eclipselink.jpa.testapps/jpa.test.advanced.embeddable/src/main/java/org/eclipse/persistence/testing/models/jpa/advanced/embeddable/RecordEntity.java
- jpa/eclipselink.jpa.testapps/jpa.test.advanced.embeddable/src/main/java/org/eclipse/persistence/testing/models/jpa/advanced/embeddable/RecordNestedAttribute.java
- jpa/eclipselink.jpa.testapps/jpa.test.advanced.embeddable/src/main/java/org/eclipse/persistence/testing/models/jpa/advanced/embeddable/RecordPK.java
- jpa/eclipselink.jpa.testapps/jpa.test.advanced.embeddable/src/main/resources/META-INF/persistence.xml
- jpa/eclipselink.jpa.testapps/jpa.test.advanced.embeddable/src/test/java/org/eclipse/persistence/testing/tests/jpa/advanced/embeddable/EntityEmbeddableRecordTest.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/weaving/ClassWeaver.java
Implementation plus unit test according https://github.com/jakartaee/persistence/pull/379 https://github.com/jakartaee/persistence/issues/400
There are two kind of usages in the entities:
- `@EmbeddedId` as (composite) primary key
- `@Embedded` as (composite) entity attribute
There is support for nested records.
Resolve review comments from #2155
> [master] Jakarta Persistence 3.2 new feature - java.lang.Record support in @Embedded parts 2.0

- etc/jenkins/pr_verify.groovy
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/indirection/IndirectList.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/indirection/IndirectMap.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/indirection/IndirectSet.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/databaseaccess/DatasourceAccessor.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/indirection/DatabaseValueHolder.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/indirection/UnitOfWorkValueHolder.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/sessions/server/ConnectionPool.java
- jpa/eclipselink.jpa.helidon.test/pom.xml
- jpa/eclipselink.jpa.helidon.test/src/it/java/org/eclipse/persistence/testing/helidon/TestMaster.java
- jpa/eclipselink.jpa.helidon.test/src/main/java/org/eclipse/persistence/testing/helidon/Main.java
- jpa/eclipselink.jpa.helidon.test/src/main/java/org/eclipse/persistence/testing/helidon/dao/BaseDao.java
- jpa/eclipselink.jpa.helidon.test/src/main/java/org/eclipse/persistence/testing/helidon/dao/DetailDao.java
- jpa/eclipselink.jpa.helidon.test/src/main/java/org/eclipse/persistence/testing/helidon/dao/MasterDao.java
- jpa/eclipselink.jpa.helidon.test/src/main/java/org/eclipse/persistence/testing/helidon/models/BaseEntity.java
- jpa/eclipselink.jpa.helidon.test/src/main/java/org/eclipse/persistence/testing/helidon/models/DetailEntity.java
- jpa/eclipselink.jpa.helidon.test/src/main/java/org/eclipse/persistence/testing/helidon/models/MasterEntity.java
- jpa/eclipselink.jpa.helidon.test/src/main/java/org/eclipse/persistence/testing/helidon/provider/MasterProvider.java
- jpa/eclipselink.jpa.helidon.test/src/main/java/org/eclipse/persistence/testing/helidon/resource/MasterResource.java
- jpa/eclipselink.jpa.helidon.test/src/main/resources/META-INF/beans.xml
- jpa/eclipselink.jpa.helidon.test/src/main/resources/META-INF/microprofile-config.properties
- jpa/eclipselink.jpa.helidon.test/src/main/resources/META-INF/persistence.xml
- jpa/eclipselink.jpa.helidon.test/src/main/resources/META-INF/sql/init.sql
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/EntityManagerFactoryDelegate.java
- pom.xml
Plus new Maven test module to test EclipseLink with Helidon
> [4.0] Virtual Threads: performance impact with Helidon integration fix (pinning threads)

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/descriptors/DescriptorIterator.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/sessions/UnitOfWorkImpl.java
- jpa/eclipselink.jpa.testapps/jpa.test.advanced/pom.xml
- jpa/eclipselink.jpa.testapps/jpa.test.advanced/src/main/java/org/eclipse/persistence/testing/models/jpa/advanced/Material.java
- jpa/eclipselink.jpa.testapps/jpa.test.advanced/src/main/resources/META-INF/persistence.xml
- jpa/eclipselink.jpa.testapps/jpa.test.advanced/src/test/java/org/eclipse/persistence/testing/tests/jpa/advanced/EntityManagerJUnitTestSuite.java
There are two fixes for EntityManager.detach():
- Lazy collections are fetched on detach
- StackOverflowError because of cyclic DETACH
plus fixes in jpa.test.advanced module
(cherry picked from commit 4027605eb60a9e8c6fb762ed8e30221071269dc2)
> [4.0] detach() fixes (#2037) - backport from master

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/databaseaccess/DatabasePlatform.java
(cherry picked from commit 3b5da43aac99ba5ce8b7b4531521128cf37e0a7d)
> [4.0] DatabasePlatform.wasFailureCommunicationBased() fix - backport from master

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/databaseaccess/DatabasePlatform.java
(cherry picked from commit 3b5da43aac99ba5ce8b7b4531521128cf37e0a7d)
> [3.0] DatabasePlatform.wasFailureCommunicationBased() fix - backport from master

- bundles/eclipselink/src/main/java/module-info.java
- foundation/org.eclipse.persistence.core/src/main/java/module-info.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/descriptors/DescriptorQueryManager.java
(cherry picked from commit 02b78ac86108a4adcdf2dedd56fc14dcdaa0a5be)
> add export of internal.weaving package

- jpa/eclipselink.jpa.testapps/jpa.test.jpql/src/test/java/org/eclipse/persistence/testing/tests/jpa/jpql/advanced/JUnitJPQLJakartaDataNoAliasTest.java
- jpa/org.eclipse.persistence.jpa.jpql/src/main/java/org/eclipse/persistence/jpa/jpql/parser/AbstractExpression.java
- jpa/org.eclipse.persistence.jpa.jpql/src/main/java/org/eclipse/persistence/jpa/jpql/parser/IdentificationVariable.java
- jpa/org.eclipse.persistence.jpa.jpql/src/main/java/org/eclipse/persistence/jpa/jpql/parser/JPQLExpression.java
- jpa/org.eclipse.persistence.jpa.jpql/src/main/java/org/eclipse/persistence/jpa/jpql/parser/ParentExpression.java
- jpa/org.eclipse.persistence.jpa.jpql/src/main/java/org/eclipse/persistence/jpa/jpql/parser/SubExpression.java
- jpa/org.eclipse.persistence.jpa.jpql/src/test/java/org/eclipse/persistence/jpa/tests/jpql/parser/JPQLExpressionTestJakartaData.java
Fixes issue for Jakarta Data expressions like `FROM Prime WHERE ( numberId = 1 )` when where expression is enclosed by braces. In origin JPQL are braces in where expression supported by default according Jakarta Persistence 3.2 specification - 4.6.1. Conditional Expression Composition.
Fixes #2234 #2235
> [master] Jakarta Persistence 3.2: fix for JPQL with generated this alias with WHERE condition enclosed by braces

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/sessions/UnitOfWorkImpl.java
- jpa/eclipselink.jpa.testapps/jpa.test.advanced2/src/main/java/org/eclipse/persistence/testing/models/jpa21/advanced/weave/IsolatedEntity.java
- jpa/eclipselink.jpa.testapps/jpa.test.advanced2/src/main/java/org/eclipse/persistence/testing/models/jpa21/advanced/weave/Location.java
- jpa/eclipselink.jpa.testapps/jpa.test.advanced2/src/main/java/org/eclipse/persistence/testing/models/jpa21/advanced/weave/Node.java
- jpa/eclipselink.jpa.testapps/jpa.test.advanced2/src/main/java/org/eclipse/persistence/testing/models/jpa21/advanced/weave/Order.java
- jpa/eclipselink.jpa.testapps/jpa.test.advanced2/src/main/resources/META-INF/persistence.xml
- jpa/eclipselink.jpa.testapps/jpa.test.advanced2/src/test/java/org/eclipse/persistence/testing/tests/advanced2/weave/WeaveVersionTest.java
Under specific conditions is `org.eclipse.persistence.exceptions.OptimisticLockException` incorrectly thrown.
Environment conditions are:
- JPA L2 cache enabled
- Weaving is applied to used entities
- `@Version` annotation is used
Test `org.eclipse.persistence.testing.tests.advanced2.weave.WeaveVersionTest#testWeavedEntitiesWithVersionL2Cache` describe sequence of steps which leads into  `org.eclipse.persistence.exceptions.OptimisticLockException` if fix is not applied.
Purpose of fix in `org.eclipse.persistence.internal.sessions.UnitOfWorkImpl#cloneAndRegisterObject(java.lang.Object, org.eclipse.persistence.internal.identitymaps.CacheKey, org.eclipse.persistence.internal.identitymaps.CacheKey, org.eclipse.persistence.descriptors.ClassDescriptor)` is update current working object with …
> [master] OptimisticLockException while using L2 cache fix

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/sessions/UnitOfWorkImpl.java
- jpa/eclipselink.jpa.test/resource/eclipselink-annotation-model/osgi/persistence.xml
- jpa/eclipselink.jpa.test/resource/eclipselink-annotation-model/persistence.xml
- jpa/eclipselink.jpa.test/resource/eclipselink-annotation-model/spring/persistence.xml
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/models/jpa/weave/IsolatedEntity.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/models/jpa/weave/Location.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/models/jpa/weave/Node.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/models/jpa/weave/Order.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa/FullRegressionTestSuite.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa/advanced/WeaveVersionTestSuite.java
Under specific conditions is `org.eclipse.persistence.exceptions.OptimisticLockException` incorrectly thrown.
Environment conditions are:
- JPA L2 cache enabled
- Weaving is applied to used entities
- `@Version` annotation is used
Test `org.eclipse.persistence.testing.tests.advanced2.weave.WeaveVersionTest#testWeavedEntitiesWithVersionL2Cache` describe sequence of steps which leads into  `org.eclipse.persistence.exceptions.OptimisticLockException` if fix is not applied.
Purpose of fix in `org.eclipse.persistence.internal.sessions.UnitOfWorkImpl#cloneAndRegisterObject(java.lang.Object, org.eclipse.persistence.internal.identitymaps.CacheKey, org.eclipse.persistence.internal.identitymaps.CacheKey, org.eclipse.persistence.descriptors.ClassDescriptor)` is update current working object with …
> [2.7] OptimisticLockException while using L2 cache fix - backport from master

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/sessions/UnitOfWorkImpl.java
- jpa/eclipselink.jpa.testapps/jpa.test.advanced2/src/main/java/org/eclipse/persistence/testing/models/jpa21/advanced/weave/IsolatedEntity.java
- jpa/eclipselink.jpa.testapps/jpa.test.advanced2/src/main/java/org/eclipse/persistence/testing/models/jpa21/advanced/weave/Location.java
- jpa/eclipselink.jpa.testapps/jpa.test.advanced2/src/main/java/org/eclipse/persistence/testing/models/jpa21/advanced/weave/Node.java
- jpa/eclipselink.jpa.testapps/jpa.test.advanced2/src/main/java/org/eclipse/persistence/testing/models/jpa21/advanced/weave/Order.java
- jpa/eclipselink.jpa.testapps/jpa.test.advanced2/src/main/resources/META-INF/persistence.xml
- jpa/eclipselink.jpa.testapps/jpa.test.advanced2/src/test/java/org/eclipse/persistence/testing/tests/advanced2/weave/WeaveVersionTest.java
Under specific conditions is `org.eclipse.persistence.exceptions.OptimisticLockException` incorrectly thrown.
Environment conditions are:
- JPA L2 cache enabled
- Weaving is applied to used entities
- `@Version` annotation is used
Test `org.eclipse.persistence.testing.tests.advanced2.weave.WeaveVersionTest#testWeavedEntitiesWithVersionL2Cache` describe sequence of steps which leads into  `org.eclipse.persistence.exceptions.OptimisticLockException` if fix is not applied.
Purpose of fix in `org.eclipse.persistence.internal.sessions.UnitOfWorkImpl#cloneAndRegisterObject(java.lang.Object, org.eclipse.persistence.internal.identitymaps.CacheKey, org.eclipse.persistence.internal.identitymaps.CacheKey, org.eclipse.persistence.descriptors.ClassDescriptor)` is update current working object with …
> [4.0] OptimisticLockException while using L2 cache fix - backport from master

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/expressions/ExpressionOperator.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/expressions/ArgumentListFunctionExpression.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/jpql/TestArgumentListFunctionExpressionConcurrency.java
The bug is described in the issue #2136
TestArgumentListFunctionExpressionConcurrency.java - adds tests that reproduce the bug.
ExpressionOperator.java - printCollection method is modified so it does not modify the shared argumentIndexes field.
ArgumentListFunctionExpression.java - previous "workarounds" are removed
> fixes coalesce and case operators in multithreaded environments (bug #2136)

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/expressions/ExpressionOperator.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/expressions/ArgumentListFunctionExpression.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/jpql/TestArgumentListFunctionExpressionConcurrency.java
The bug is described in the issue #2136. The bug was in the 2.7 version, and it was somewhat fixed in later versions but still failed when statements had different number of parameters.
TestArgumentListFunctionExpressionConcurrency.java - adds tests that reproduce the bug. 
ExpressionOperator.java - fixes getArgumentIndices by disabling the caching of the dynamically created argument indexes.
> Fixes coalesce and case operators in multithreaded environments with different number of arguments

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/expressions/ExpressionOperator.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/expressions/ArgumentListFunctionExpression.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/jpql/TestArgumentListFunctionExpressionConcurrency.java
The bug is described in the issue #2136.
TestArgumentListFunctionExpressionConcurrency.java - adds tests that reproduce the bug. 
ExpressionOperator.java - fixes getArgumentIndices by disabling the caching of the dynamically created argument indexes.
> Fixes coalesce and case operators in multithreaded environments with different number of arguments (backport to 4.0)

- IGOR.md
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/expressions/ExpressionOperator.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/jpql/TestArgumentListFunctionExpressionConcurrency.java
The bug is described in the issue #2136.
TestArgumentListFunctionExpressionConcurrency.java - adds tests that reproduce the bug. 
ExpressionOperator.java - fixes getArgumentIndices by disabling the caching of the dynamically created argument indexes.
> Fixes coalesce and case operators in multithreaded environments with different number of arguments (backport to 3.0)

- jpa/eclipselink.jpa.testapps/jpa.test.advanced/src/main/java/org/eclipse/persistence/testing/models/jpa/advanced/AdvancedTableCreator.java
- jpa/eclipselink.jpa.testapps/jpa.test.advanced/src/main/java/org/eclipse/persistence/testing/models/jpa/advanced/Room.java
- jpa/eclipselink.jpa.testapps/jpa.test.jpql/src/test/java/org/eclipse/persistence/testing/tests/jpa/jpql/advanced/JUnitJPQLJakartaDataNoAliasTest.java
- jpa/org.eclipse.persistence.jpa.jpql/src/main/java/org/eclipse/persistence/jpa/jpql/parser/AbstractPathExpression.java
- jpa/org.eclipse.persistence.jpa.jpql/src/test/java/org/eclipse/persistence/jpa/tests/jpql/parser/JPQLExpressionTestJakartaData.java
> [master] Enum attribute in JPQL is broken when entity identifier is omitted or is 'this.' - bugfix and unit tests

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/config/PersistenceUnitProperties.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/jpa/PersistenceProvider.java
- jpa/org.eclipse.persistence.jpa/src/test/java/org/eclipse/persistence/jpa/PersistenceProviderTest.java
- pom.xml
Added `jakarta.persistence.provider` to `PersistenceUnitProperties`
Added provider class check to `PersistenceProvider#createEntityManagerFactory(PersistenceConfiguration)`
Optimized provider check code.
> Fixed persistence provider check in createEntityManagerFactory(PersistenceConfiguration)

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/DB2Platform.java
This PR contains the fix for issue #2282
> Fixes : Db2: Eclipselink creates table with Db2 data type DOUBLE instead of REAL for a Java float

- jpa/eclipselink.jpa.testapps/jpa.test.jpql/src/test/java/org/eclipse/persistence/testing/tests/jpa/jpql/advanced/JUnitJPQLJakartaDataNoAliasTest.java
- jpa/org.eclipse.persistence.jpa.jpql/src/main/java/org/eclipse/persistence/jpa/jpql/parser/JPQLGrammar3_2.java
- jpa/org.eclipse.persistence.jpa.jpql/src/test/java/org/eclipse/persistence/jpa/tests/jpql/JPQLQueries3_2.java
- jpa/org.eclipse.persistence.jpa.jpql/src/test/java/org/eclipse/persistence/jpa/tests/jpql/parser/JPQLQueriesTest3_2.java
> [master] ID(this) is not accepted as an argument to a function - bugfix + tests

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/dynamic/DynamicClassLoader.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/dynamic/DynamicClassWriter.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/dynamic/DynamicEnumBuilder.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/dynamic/DynamicTypeBuilder.java
- moxy/org.eclipse.persistence.moxy/src/main/java/org/eclipse/persistence/jaxb/JAXBEnumTypeConverter.java
- moxy/org.eclipse.persistence.moxy/src/main/java/org/eclipse/persistence/jaxb/dynamic/metadata/SchemaMetadata.java
- moxy/org.eclipse.persistence.moxy/src/test/java/org/eclipse/persistence/testing/jaxb/dynamic/DynamicJAXBFromXSDTestCases.java
- moxy/org.eclipse.persistence.moxy/src/test/resources/org/eclipse/persistence/testing/jaxb/dynamic/xmlenum-numbers.xsd
To resolve #2272
- Changes EnumInfo literals from List to Map to store intended value
- Adds @XmlEnumValue annotation to DynamicJAXB enum class
- Check for @XmlEnumValue when adding enum conversion values
> Handle xjc XmlEnumValue in DynamicJAXB enum

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/queries/ReportQuery.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/queries/ReportQueryResult.java
- jpa/eclipselink.jpa.testapps/jpa.test.batchfetch/pom.xml
- jpa/eclipselink.jpa.testapps/jpa.test.batchfetch/src/main/java/org/eclipse/persistence/testing/models/jpa/batchfetch/BatchFetchTableCreator.java
- jpa/eclipselink.jpa.testapps/jpa.test.batchfetch/src/main/java/org/eclipse/persistence/testing/models/jpa/batchfetch/Company.java
- jpa/eclipselink.jpa.testapps/jpa.test.batchfetch/src/main/java/org/eclipse/persistence/testing/models/jpa/batchfetch/Count.java
- jpa/eclipselink.jpa.testapps/jpa.test.batchfetch/src/main/java/org/eclipse/persistence/testing/models/jpa/batchfetch/Employee.java
- jpa/eclipselink.jpa.testapps/jpa.test.batchfetch/src/main/java/org/eclipse/persistence/testing/models/jpa/batchfetch/Record.java
- jpa/eclipselink.jpa.testapps/jpa.test.batchfetch/src/main/resources/META-INF/persistence.xml
- jpa/eclipselink.jpa.testapps/jpa.test.batchfetch/src/test/java/org/eclipse/persistence/testing/tests/jpa/batchfetch/BatchFetchJUnitTest.java
- jpa/eclipselink.jpa.testapps/pom.xml
> [4.0] Fix for ReportQuery not fetching relationships with BatchFetch.IN

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/queries/ReportQuery.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/queries/ReportQueryResult.java
- jpa/eclipselink.jpa.test/antbuild.properties
- jpa/eclipselink.jpa.test/antbuild.xml
- jpa/eclipselink.jpa.test/resource/eclipselink-batchfetch-model/persistence.xml
- jpa/eclipselink.jpa.test/resource/eclipselink-batchfetch-model/server/persistence.xml
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/models/jpa/batchfetch/BatchFetchTableCreator.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/models/jpa/batchfetch/Company.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/models/jpa/batchfetch/Count.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/models/jpa/batchfetch/Employee.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/models/jpa/batchfetch/Record.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa/FullRegressionTestSuite.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa/batchfetch/BatchFetchJUnitTest.java
> [2.7] Fix for ReportQuery not fetching relationships with BatchFetch.IN

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/PostgreSQLPlatform.java
Add support for UUID DB type in PostgreSQL for DDL generation.
This type is supported by PostgreSQL from 2008 see
https://www.postgresql.org/docs/9.3/release-8-3.html
This is why target class is `PostgreSQLPlatform`.
Fixes #2190
> [master] UUID field type mapping - PostgreSQLPlatform

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/OraclePlatform.java
Test was not backported, because 3.0 contains old tests where new patch does not fit.
> [3.0] Issue #2301 - Sorting not honored with JPA and Oracle

- foundation/org.eclipse.persistence.core.test.framework/src/main/java/org/eclipse/persistence/testing/framework/TogglingFastTableCreator.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/OraclePlatform.java
- jpa/eclipselink.jpa.testapps/jpa.test.advanced/src/main/java/org/eclipse/persistence/testing/models/jpa/advanced/AdvancedTableCreator.java
- jpa/eclipselink.jpa.testapps/jpa.test.advanced/src/main/java/org/eclipse/persistence/testing/models/jpa/advanced/entities/EntityFloat.java
- jpa/eclipselink.jpa.testapps/jpa.test.jpql/src/main/resources/META-INF/persistence.xml
- jpa/eclipselink.jpa.testapps/jpa.test.jpql/src/test/java/org/eclipse/persistence/testing/tests/jpa/jpql/advanced/AdvancedQueryTest.java
- jpa/eclipselink.jpa.testapps/jpa.test.jpql/src/test/java/org/eclipse/persistence/testing/tests/jpa/jpql/advanced/EntityFloatPopulator.java
> [main] Issue #2301 - Sorting not honored with JPA and Oracle

- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/framework/TogglingFastTableCreator.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/OraclePlatform.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/models/jpa/advanced/AdvancedTableCreator.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/models/jpa/advanced/EntityFloat.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/models/jpa/advanced/EntityFloatPopulator.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa/jpql/AdvancedQueryTestSuite.java
Backport was done manually, original patch does not fit.
Test was not backported, because 3.0 contains old tests where new patch does not fit.
> [2.7] Issue #2301 - Sorting not honored with JPA and Oracle

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/PostgreSQLPlatform.java
Add support for UUID DB type in PostgreSQL for DDL generation.
This type is supported by PostgreSQL from 2008 see
https://www.postgresql.org/docs/9.3/release-8-3.html
This is why target class is `PostgreSQLPlatform`.
Fixes #2190 
(cherry picked from commit 28ffe73f20ec4b4a200951ca26a21c3b39048355)
> [4.0] UUID field type mapping - PostgreSQLPlatform (#2284) - backport from master

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/config/SystemProperties.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/security/JCEEncryptor.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/security/PrivilegedAccessHelper.java
Fixes #2075.
To address hang-up due to blocking PRNG returned by  `SecureRandom.getInstanceStrong()`, this pull request introduces  a system property (`eclipselink.security.encryptor.use.strong.random.number.generator`) to switch  `SecureRandom.getInstanceStrong()` and `new SecureRandom()`.
`new SecureRandom()` returns the default PRNG of Java platform [1].
Since `SecureRandom.getInstanceStrong()` may return a blocking PRNG and is not recommended in server-side code (see [2]),  we prefer to use `new SecureRandom()` as the default setting.
Users can change the behavior by configuring the system property if they want.
[1] https://docs.oracle.com/en/java/javase/21/security/java-cryptography-architecture-jca-reference-guide.html#GUID-AEB77CD8-D28F-4BBE-B9E5-160B5DC35D36
[2] …
> Fix #2075 Slow startup because of low entropy for PRNG

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/helper/WriteLockManager.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/sessions/AbstractSession.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/sessions/IsolatedClientSessionIdentityMapAccessor.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/sessions/ObjectChangeSet.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/sessions/UnitOfWorkIdentityMapAccessor.java
Fixes #2319 in `WriteLockManager` by `toWaitOn.getInstanceLockCondition().await(MAX_WAIT, TimeUnit.MILLISECONDS);` to wait for lock on object (`CacheKey`) to be released.
Before this fix there was 
`toWaitOnLockCondition.await(ConcurrencyUtil.SINGLETON.getAcquireWaitTime(), TimeUnit.MILLISECONDS);`
which was
`toWaitOnLockCondition.await(0, TimeUnit.MILLISECONDS);` in case of default persistence settings -> Zero time ammount to wait. 
Additionally there are some other migrations from `synchronized` to ReentrantLock usage for CacheKey related code.
> [master] ConcurrencyException "Max number of attempts to lock object" in WriteLockManager - bugfix

- etc/jenkins/pr_verify.groovy
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/databaseaccess/DatasourceAccessor.java
- jpa/eclipselink.jpa.spring.test/src/it/resources/appContext.properties
- jpa/eclipselink.jpa.springboot.test/pom.xml
- jpa/eclipselink.jpa.springboot.test/src/it/java/org/eclipse/persistence/testing/models/jpa/springboot/Person.java
- jpa/eclipselink.jpa.springboot.test/src/it/java/org/eclipse/persistence/testing/models/jpa/springboot/PersonRepository.java
- jpa/eclipselink.jpa.springboot.test/src/it/java/org/eclipse/persistence/testing/tests/jpa/springboot/EclipseLinkJpaConfiguration.java
- jpa/eclipselink.jpa.springboot.test/src/it/java/org/eclipse/persistence/testing/tests/jpa/springboot/PersonApplication.java
- jpa/eclipselink.jpa.springboot.test/src/it/java/org/eclipse/persistence/testing/tests/jpa/springboot/TestPersonRepository.java
- jpa/eclipselink.jpa.springboot.test/src/it/resources/META-INF/persistence.xml
- jpa/eclipselink.jpa.springboot.test/src/it/resources/application.properties
- pom.xml
Fixes #2219
Issue with `DatasourceAccessor` `ReentratLock` which was after migration accidentally shared across `DatasourceAccessor` instances as new instances are in some cases created due a `clone()` method and not by `new DatasourceAccessor()`.
There is new Spring Boot test module with HikariCP Datasource as this issue was discovered in this environment, but this initial test doesn't cover mentioned bug scenario due a missing information from customer.
Update in booth Spring test modules to execute them in CI environment.
> [4.0] DatasourceAccessor ReentrantLock fix plus new SpringBoot test

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/helper/WriteLockManager.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/sessions/AbstractSession.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/sessions/IsolatedClientSessionIdentityMapAccessor.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/sessions/ObjectChangeSet.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/sessions/UnitOfWorkIdentityMapAccessor.java
Fixes #2319 in `WriteLockManager` by `toWaitOn.getInstanceLockCondition().await(MAX_WAIT, TimeUnit.MILLISECONDS);` to wait for lock on object (`CacheKey`) to be released.
Before this fix there was 
`toWaitOnLockCondition.await(ConcurrencyUtil.SINGLETON.getAcquireWaitTime(), TimeUnit.MILLISECONDS);`
which was
`toWaitOnLockCondition.await(0, TimeUnit.MILLISECONDS);` in case of default persistence settings -> Zero time ammount to wait. 
Additionally there are some other migrations from `synchronized` to ReentrantLock usage for CacheKey related code.
> [4.0] ConcurrencyException "Max number of attempts to lock object" in WriteLockManager - bugfix - backport from master

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/indirection/IndirectList.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/indirection/IndirectMap.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/indirection/IndirectSet.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/indirection/DatabaseValueHolder.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/indirection/UnitOfWorkValueHolder.java
Fixes #2317
There is regression bug introduced in #2181 . Scope of new `ReentrantLock` variable `instanceLock` was in case of new object instances created by `clone()` method across all cloned instances instead of one `instanceLock` per each instance.
In case of `UnitOfWorkValueHolder` incorrect lock was used `wrappedValueHolderLock` vs `wrappedValueHolder.getInstanceLock()`
> [4.0] NPE in QueryBasedValueHolder due to #2181 - bugfix

- pom.xml
Execute `org.eclipse.persistence.jpa.spring.test,org.eclipse.persistence.jpa.springboot.test` Maven modules conditionally on used Java version. Minimal Java for used test Spring dependencies which support Jakarta is Java 17.
> [4.0] Maven Spring test modules on Java 17 and higher

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/databaseaccess/DatabasePlatform.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/PostgreSQLPlatform.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/storedproc/TestStoredProcedures.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/StoredProcedureQueryImpl.java
Fixes calling stored procedures on Postgres. Without this change, EclipseLink does `SELECT * FROM name_of_proc` which causes an exception. This change also removes the `isJDBCExecuteCompliant()` method, which is not needed anymore as far as I can tell, and enables a few stored procedure tests for Postgres to prevent regressions.
This PR targets the 4.0 branch but would also need to be done for 5.0.
> Fix calling stored procs on Postgres, and enable some tests

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/config/SystemProperties.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/security/JCEEncryptor.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/security/PrivilegedAccessHelper.java
* Fix hang-up due to blocking PRNG returned by SecureRandom.getInstanceStrong() 
* Fixes #2075
backport of #2318
> [4.0] Fix #2075 Slow startup because of low entropy for PRNG (#2318)

- moxy/org.eclipse.persistence.moxy/src/test/java/org/eclipse/persistence/testing/jaxb/schemagen/customizedmapping/xmlelementref/WrappedByteArray.java
- moxy/org.eclipse.persistence.moxy/src/test/java/org/eclipse/persistence/testing/jaxb/xmlelementrefs/adapter/ObjectFactory.java
There are just some javadoc related issues which leads into errors and block EclipseLink build on JDK 24.
There are not fixed any compiler warning messages.
> [master] JDK 24 build fixes

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/helper/ConcurrencyManager.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/helper/ConcurrencyUtil.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/helper/WriteLockManager.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/helper/type/CacheKeyToThreadRelationships.java
Fix for event when massive dumps, triggered by dead lock diagnostic, are produced. Before this fix the concurrency layers should continue to update structures (Maps, Sets) passed to dead lock diagnostic and these structures could be updated in time period between detected dead lock event and print to some log output.
After this fix snapshots are produced.
> [master] DeadLock diagnostic fix - Lock map snapshots

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/descriptors/AbstractTsLockingPolicy.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/descriptors/InstantLockingPolicy.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/descriptors/LocalDateTimeLockingPolicy.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/descriptors/VersionLockingPolicy.java
- jpa/eclipselink.jpa.testapps/jpa.test.persistence32/src/main/java/org/eclipse/persistence/testing/models/jpa/persistence32/InstantVersionEntity.java
- jpa/eclipselink.jpa.testapps/jpa.test.persistence32/src/main/java/org/eclipse/persistence/testing/models/jpa/persistence32/LdtVersionEntity.java
- jpa/eclipselink.jpa.testapps/jpa.test.persistence32/src/main/java/org/eclipse/persistence/testing/models/jpa/persistence32/TimestampVersionEntity.java
- jpa/eclipselink.jpa.testapps/jpa.test.persistence32/src/main/resources/META-INF/persistence.xml
- jpa/eclipselink.jpa.testapps/jpa.test.persistence32/src/test/java/org/eclipse/persistence/testing/tests/jpa/persistence32/AbstractPokemonSuite.java
- jpa/eclipselink.jpa.testapps/jpa.test.persistence32/src/test/java/org/eclipse/persistence/testing/tests/jpa/persistence32/AbstractVersionSuite.java
- jpa/eclipselink.jpa.testapps/jpa.test.persistence32/src/test/java/org/eclipse/persistence/testing/tests/jpa/persistence32/EntityGraphTest.java
- jpa/eclipselink.jpa.testapps/jpa.test.persistence32/src/test/java/org/eclipse/persistence/testing/tests/jpa/persistence32/EntityManagerFactoryTest.java
- jpa/eclipselink.jpa.testapps/jpa.test.persistence32/src/test/java/org/eclipse/persistence/testing/tests/jpa/persistence32/EntityManagerTest.java
- jpa/eclipselink.jpa.testapps/jpa.test.persistence32/src/test/java/org/eclipse/persistence/testing/tests/jpa/persistence32/QueryTest.java
- jpa/eclipselink.jpa.testapps/jpa.test.persistence32/src/test/java/org/eclipse/persistence/testing/tests/jpa/persistence32/SchemaManagerCreateTest.java
- jpa/eclipselink.jpa.testapps/jpa.test.persistence32/src/test/java/org/eclipse/persistence/testing/tests/jpa/persistence32/SchemaManagerDropTest.java
- jpa/eclipselink.jpa.testapps/jpa.test.persistence32/src/test/java/org/eclipse/persistence/testing/tests/jpa/persistence32/SchemaManagerTruncateOnExistingTest.java
- jpa/eclipselink.jpa.testapps/jpa.test.persistence32/src/test/java/org/eclipse/persistence/testing/tests/jpa/persistence32/UnionCriteriaQueryTest.java
- jpa/eclipselink.jpa.testapps/jpa.test.persistence32/src/test/java/org/eclipse/persistence/testing/tests/jpa/persistence32/VersionTest.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/metadata/accessors/mappings/VersionAccessor.java
Implemented missing policies for `java.time.LocalDateTime` and `java.time.Instant`.
> Issue #2343 - EclipseLink disallows @Version attribute of type java.time.LocalDateTime

- README.md
as the @eclipse foundation faded out the old PHP sites recently.
> Fix nightly builds link

- foundation/eclipselink.core.test/src/it/java/org/eclipse/persistence/testing/tests/identitymaps/cacheinvalidation/CacheInvalidationPolicyCloneTest.java
- foundation/eclipselink.core.test/src/it/java/org/eclipse/persistence/testing/tests/performance/java/DatePrintingTest.java
- foundation/eclipselink.core.test/src/it/java/org/eclipse/persistence/testing/tests/types/TimeDateTester.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/helper/ConversionManager.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/oxm/XMLConversionManager.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/conversion/TestJavaTimeTypeConverter.java
- moxy/org.eclipse.persistence.moxy/src/test/java/org/eclipse/persistence/testing/oxm/mappings/typeddirect/TypedDirectMappingTestCases.java
- moxy/org.eclipse.persistence.moxy/src/test/java/org/eclipse/persistence/testing/oxm/xmlconversionmanager/DateAndTimeTestCases.java
- sdo/org.eclipse.persistence.sdo/src/main/java/org/eclipse/persistence/sdo/helper/SDODataHelper.java
- sdo/org.eclipse.persistence.sdo/src/test/java/org/eclipse/persistence/testing/sdo/helper/datahelper/DataHelperToCalendarTest.java
- sdo/org.eclipse.persistence.sdo/src/test/java/org/eclipse/persistence/testing/sdo/helper/datahelper/DataHelperToCalendarWithLocale.java
- sdo/org.eclipse.persistence.sdo/src/test/java/org/eclipse/persistence/testing/sdo/helper/datahelper/DataHelperToDateTest.java
- sdo/org.eclipse.persistence.sdo/src/test/java/org/eclipse/persistence/testing/sdo/helper/datahelper/DataHelperToDateTimeTest.java
- sdo/org.eclipse.persistence.sdo/src/test/java/org/eclipse/persistence/testing/sdo/helper/datahelper/DataHelperToDurationTest.java
- sdo/org.eclipse.persistence.sdo/src/test/java/org/eclipse/persistence/testing/sdo/helper/datahelper/DataHelperToDurationWithCalnTest.java
- sdo/org.eclipse.persistence.sdo/src/test/java/org/eclipse/persistence/testing/sdo/helper/datahelper/DataHelperToTimeTest.java
This PR contains following fixes related with tests against Oracle DB:
- `java.util.Date` to `java.time.LocalDate` conversion fix - from #1255
- Correctly handle times after noon - from #1733
> [3.0] Oracle Database platform fixes

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/expressions/Expression.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/expressions/SQLSelectStatement.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/OraclePlatform.java
- jpa/eclipselink.jpa.testapps/jpa.test.jpql/src/test/java/org/eclipse/persistence/testing/tests/jpa/jpql/advanced/AdvancedQueryTest.java
Fixed printSQLSelectStatement in Oracle Platform. It was not working properly when projection expression was present in the query (e.g. `SELECT e.id from Entity e` instead of `SELECT e from Entity e`).
Added simple test to verify test-case from the bug.
> Issue #2339 - JPQL query for all entities in descending order returns no results on Oracle

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/localization/i18n/LoggingLocalizationResource.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/localization/i18n/TraceLocalizationResource.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/sessions/UnitOfWorkImpl.java
Lowered log level in UnitOfWorkImpl method validateObjectTree to match levels in original validateObjectSpace method.
Moved JPA 3.2 messages with FINEST, FINER and FINE level to TraceLocalizationResource.
> Moved messages to proper bundle. Lowered some logging levels.

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/jpa/jpql/HermesParser.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/jpa/jpql/JPQLQueryHelper.java
- jpa/eclipselink.jpa.testapps/jpa.test.datatypes/src/main/java/org/eclipse/persistence/testing/models/jpa/datatypes/WrapperTypes.java
- jpa/eclipselink.jpa.testapps/jpa.test.jpql/src/test/java/org/eclipse/persistence/testing/tests/jpa/jpql/advanced/JUnitJPQLJakartaDataNoAliasTest.java
Fixes #2253 . Before this fix, different parser validation settings (more strict) were applied to JPQL queries stored in `@NamedQuery`, than JPQL queries created by `em.createQuery(...)`.
> [master] Jakarta Persistence 3.2: fix for JPQL with generated this alias in @NamedQuery

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/queries/DatabaseQueryMechanism.java
- jpa/eclipselink.jpa.testapps/jpa.test.beanvalidation/src/main/java/org/eclipse/persistence/testing/models/jpa/beanvalidation/BeanValidationTableCreator.java
- jpa/eclipselink.jpa.testapps/jpa.test.beanvalidation/src/main/java/org/eclipse/persistence/testing/models/jpa/beanvalidation/Task.java
- jpa/eclipselink.jpa.testapps/jpa.test.beanvalidation/src/main/resources/META-INF/persistence.xml
- jpa/eclipselink.jpa.testapps/jpa.test.beanvalidation/src/test/java/org/eclipse/persistence/testing/tests/jpa/beanvalidation/BeanValidationJunitTest.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/metadata/listeners/BeanValidationListener.java
I wonder if I could propose this change. I'm very happy to incorporate any feedback. Thank you in advance for your reviews and consideration.
A call like:
`Task task = em.find(Task.class, 900, LockModeType.PESSIMISTIC_FORCE_INCREMENT);`
will increment the `@Version` attribute of the entity, and this will be persisted when the transaction completes. The entity will also be validated with Bean Validation at this point, even though there are no other changes to the object. If the data read from the database happens to be invalid according to the bean validation constraints, the validation will fail, and the transaction will be rolled back.
I can't see a reference in the specification as to whether the entity should be validated in this instance, but the behaviour of Eclipselink appears to …
> Don't validate if the only change is to a @Version attribute (e.g. em.find() with PESSIMISTIC_FORCE_INCREMENT)

- jpa/eclipselink.jpa.wdf.test/src/it/java/org/eclipse/persistence/testing/tests/wdf/jpa1/entitymanager/TestFlush.java
- jpa/eclipselink.jpa.wdf.test/src/it/java/org/eclipse/persistence/testing/tests/wdf/jpa1/entitymanager/TestGetReference.java
This is fix for JPA WDF test . There were in some test environments random test failures as there were used same entities with same id across multiple tests.
> [4.0] Random JPA WDF test failures - TestFlush entity collisions

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/DB2Platform.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/DerbyPlatform.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/OraclePlatform.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/PostgreSQLPlatform.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/SQLServerPlatform.java
Update to support java.time.Instant during automatic table creation in Derby, Oracle, PostgreSQL, DB2 and SQLServer.
Fixes #2191
> [Master] Update to support java.time.Instant during automatic table creation.

- jpa/eclipselink.jpa.wdf.test/src/it/java/org/eclipse/persistence/testing/tests/wdf/jpa1/entitymanager/TestFlush.java
- jpa/eclipselink.jpa.wdf.test/src/it/java/org/eclipse/persistence/testing/tests/wdf/jpa1/entitymanager/TestGetReference.java
This is fix for JPA WDF test . There were in some test environments random test failures as there were used same entities with same id across multiple tests. Mainly negative tests for expected PersistenceExceptions.
> [3.0] Random JPA WDF test failures - TestFlush entity collisions

- moxy/org.eclipse.persistence.moxy/pom.xml
This is fix for
`Unable to make field final int java.math.RoundingMode.oldMode accessible: module java.base does not "opens java.math" to unnamed module`
issue which happens in non JPMS enabled 3.0 version in MOXy tests.
> [3.0] MOXy Test Fix in JDK 21

- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/EntityManagerSetupImpl.java
Fix for a bug which happens with Oracle platform and remote EntityManager only. Discovered by `org.eclipse.persistence.testing.tests.jpa.remote.RemoteEntityManagerTest`.
DB Accessor behind `org.eclipse.persistence.sessions.remote.RemoteSession` is not connected before `<platform>..initIdentitySequences(...)` call.
This issue happens on Oracle platform only because other platforms have `initIdentitySequences(...)` empty.
> [master] Initialize platform specific identity sequences for remote entity manager - bugfix

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/helper/ConcurrencyUtil.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/helper/WriteLockManager.java
- jpa/eclipselink.jpa.testapps/jpa.test.diagnostic.deadlock/src/test/java/org/eclipse/persistence/testing/tests/jpa/deadlock/diagnostic/CacheDeadLockManagersTest.java
Fixes #2173
There is incorrect log output in case if deadlock is detected and dump triggered in `WriteLockManager.acquireLocksForClonemessage()`. Mentioned method acquire read lock instead of write lock -> logged output was incorrect.
See log output before
```
...
Concurrency manager - Page 01 end - thread dump about all threads at time of event
Concurrency manager - Page 02 start - information about threads waiting to acquire (write/deferred) cache keys 
Total number of threads waiting to acquire lock: 1
[currentThreadNumber: 1] [ThreadName: main]: Waiting to acquire (write/deferred): --- CacheKey  (org.eclipse.persistence.testing.models.jpa.deadlock.diagnostic.CacheDeadLockDetectionMaster):  (primaryKey: 1) (object hash code: 1680621693) (cacheKeyClass: …
```
> [master] DeadLock detection diagnostic - WriteLockManager.acquireLocksForClonemessage change

- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/EntityManagerSetupImpl.java
Fix for a bug which happens with Oracle platform and remote EntityManager only. Discovered by `org.eclipse.persistence.testing.tests.jpa.remote.RemoteEntityManagerTest`.
DB Accessor behind `org.eclipse.persistence.sessions.remote.RemoteSession` is not connected before `<platform>..initIdentitySequences(...)` call.
This issue happens on Oracle platform only because other platforms have `initIdentitySequences(...)` empty.
(cherry picked from commit 3f10ccf81fddf32cc7d0718524cfa901ebb9db2b)
> [4.0] Initialize platform specific identity sequences for remote entity manager - bugfix (backport from master #2357)

- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/EntityManagerSetupImpl.java
Fix for a bug which happens with Oracle platform and remote EntityManager only. Discovered by `org.eclipse.persistence.testing.tests.jpa.remote.RemoteEntityManagerTest`.
DB Accessor behind `org.eclipse.persistence.sessions.remote.RemoteSession` is not connected before `<platform>..initIdentitySequences(...)` call.
This issue happens on Oracle platform only because other platforms have `initIdentitySequences(...)` empty.
(cherry picked from commit 3f10ccf81fddf32cc7d0718524cfa901ebb9db2b)
> [3.0] Initialize platform specific identity sequences for remote entity manager - bugfix (backport from master #2357)

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/HANAPlatform.java
- foundation/org.eclipse.persistence.oracle/src/main/java/org/eclipse/persistence/platform/database/oracle/Oracle10Platform.java
- foundation/org.eclipse.persistence.oracle/src/main/java/org/eclipse/persistence/platform/database/oracle/Oracle9Platform.java
- jpa/eclipselink.jpa.wdf.test/src/it/java/org/eclipse/persistence/testing/tests/wdf/jpa1/lock/TestOptimistic.java
When the database platform is set as "org.eclipse.persistence.platform.database.oracle.Oracle19Platform" then we get OptismisticLockException without parameters value
This is because org.eclipse.persistence.platform.database.oracle.Oracle10Platform has its own executeBatch method where it was missed to call setExecuteBatchRowCounts which sets this parameters value
So in the fix we have tried to call setExecuteBatchRowCounts where such executeBatch method exist for different database platform
I have added new assertions for this at jpa/eclipselink.jpa.wdf.test/src/it/java/org/eclipse/persistence/testing/tests/wdf/jpa1/lock/TestOptimistic#verifyBatchOLE
> Optimistic lock exception with empty parameters value

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/jpa/jpql/JPQLFunctionsAbstractBuilder.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/jpa/jpql/ReportItemBuilder.java
- jpa/eclipselink.jpa.testapps/jpa.test.jpql/src/test/java/org/eclipse/persistence/testing/tests/jpa/jpql/advanced/JUnitJPQLFunctionsTest.java
- jpa/org.eclipse.persistence.jpa.jpql/src/main/java/org/eclipse/persistence/jpa/jpql/parser/IdExpression.java
Partially fixes #2211 . At this moment `query.getSingleResult()` return array of `Object` which content and order is same are `@Id` entity attributes. Mapping to declared `@IdClass` doesn't work yet.
> [master] SELECT ID(entityvar) only returns part of IdClass - bug fix and unit tests

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/mappings/ForeignReferenceMapping.java
- jpa/eclipselink.jpa.testapps/jpa.test.batchfetch/src/main/java/org/eclipse/persistence/testing/models/jpa/batchfetch/BatchFetchCacheTableCreator.java
- jpa/eclipselink.jpa.testapps/jpa.test.batchfetch/src/main/java/org/eclipse/persistence/testing/models/jpa/batchfetch/Child.java
- jpa/eclipselink.jpa.testapps/jpa.test.batchfetch/src/main/java/org/eclipse/persistence/testing/models/jpa/batchfetch/Parent.java
- jpa/eclipselink.jpa.testapps/jpa.test.batchfetch/src/main/resources/META-INF/persistence.xml
- jpa/eclipselink.jpa.testapps/jpa.test.batchfetch/src/test/java/org/eclipse/persistence/testing/tests/jpa/batchfetch/BatchFetchCacheJUnitTest.java
- jpa/eclipselink.jpa.testapps/jpa.test.batchfetch/src/test/java/org/eclipse/persistence/testing/tests/jpa/batchfetch/BatchFetchJUnitTest.java
Closes #1998 
This PR changes the execution of the batchQuery to utilize a clone for actual execution of the batch fetching. Without the clone it was possible that further batches would overwrite the DataResults of the original batchQuery. These DataResults were then used by the various BatchValueHolders to instantiate the values lazily. However when overwritten the referenced rows had the possibility of not existing in the policy as only the most recently executed batch was present. This could lead to incorrect results being returned. 
Once this is reviewed I will back port it.
> [master] Clone batchQuery to allow for proper nested lazy instantiation

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/mappings/ForeignReferenceMapping.java
- jpa/eclipselink.jpa.testapps/jpa.test.batchfetch/src/main/java/org/eclipse/persistence/testing/models/jpa/batchfetch/BatchFetchCacheTableCreator.java
- jpa/eclipselink.jpa.testapps/jpa.test.batchfetch/src/main/java/org/eclipse/persistence/testing/models/jpa/batchfetch/Child.java
- jpa/eclipselink.jpa.testapps/jpa.test.batchfetch/src/main/java/org/eclipse/persistence/testing/models/jpa/batchfetch/Parent.java
- jpa/eclipselink.jpa.testapps/jpa.test.batchfetch/src/main/resources/META-INF/persistence.xml
- jpa/eclipselink.jpa.testapps/jpa.test.batchfetch/src/test/java/org/eclipse/persistence/testing/tests/jpa/batchfetch/BatchFetchCacheJUnitTest.java
- jpa/eclipselink.jpa.testapps/jpa.test.batchfetch/src/test/java/org/eclipse/persistence/testing/tests/jpa/batchfetch/BatchFetchJUnitTest.java
> [4.0] Clone batchQuery when executing to ensure nested batch fetches retain proper rows

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/databaseaccess/DatabasePlatform.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/PostgreSQLPlatform.java
PostgreSQL JDBC driver doesn't accept parameters passed by names (only index way). This fix allows use it with persistence property `<property name="eclipselink.jpa.naming_into_indexed" value="true"/>` which allows EclipseLink translate naming parameters into indexed (order is important).
Fixes #2369
> [master] Postgres function calls with named parameters - bugfix

- etc/jenkins/pr_verify.groovy
- jpa/eclipselink.jpa.testapps/README.md
- jpa/eclipselink.jpa.testapps/jpa.test.advanced2/src/test/java/org/eclipse/persistence/testing/tests/advanced2/weave/WeaveVersionTest.java
- jpa/eclipselink.jpa.testapps/jpa.test.diagnostic/src/test/java/org/eclipse/persistence/testing/tests/jpa/diagnostic/DiagnosticTest.java
- jpa/eclipselink.jpa.testapps/jpa.test.identity/src/test/java/org/eclipse/persistence/testing/tests/jpa22/identity/IdentityTest.java
- jpa/eclipselink.jpa.testapps/jpa.test.jpaadvancedproperties/src/test/java/org/eclipse/persistence/testing/tests/jpa/jpaadvancedproperties/JPAAdvPropertiesTest.java
- jpa/eclipselink.jpa.testapps/jpa.test.metamodel.apectj/pom.xml
- jpa/eclipselink.jpa.testapps/jpa.test.metamodel.apectj/src/test/java/org/eclipse/persistence/testing/tests/jpa/weaving/aspectj/MetamodelAspectJTest.java
- jpa/eclipselink.jpa.testapps/jpa.test.sessionbean.ha/src/test/java/org/eclipse/persistence/testing/tests/jpa/sessionbean/ha/SessionBeanTest.java
- jpa/eclipselink.jpa.testapps/jpa.test.weaving/pom.xml
- jpa/eclipselink.jpa.testapps/jpa.test.xml.extended/jpa.test.xml.extended.advanced/src/test/java/org/eclipse/persistence/testing/tests/jpa/xml/extended/advanced/XmlExtendedAdvancedJunitTest.java
- jpa/eclipselink.jpa.testapps/jpa.test.xml.extended/jpa.test.xml.extended.advanced/src/test/java/org/eclipse/persistence/testing/tests/jpa/xml/extended/advanced/XmlExtendedAdvancedTest.java
- jpa/eclipselink.jpa.testapps/jpa.test.xml.only/jpa.test.xml.advanced/src/test/java/org/eclipse/persistence/testing/tests/jpa/xml/advanced/XmlAdvancedJunitTest.java
- jpa/eclipselink.jpa.testapps/jpa.test.xml.only/jpa.test.xml.advanced/src/test/java/org/eclipse/persistence/testing/tests/jpa/xml/advanced/compositepk/XmlAdvancedCompositePKTest.java
- jpa/eclipselink.jpa.testapps/nativeapi/src/main/resources-ejb/META-INF/sessions.xml
- jpa/org.eclipse.persistence.jpa.test.framework/src/main/java/org/eclipse/persistence/testing/framework/jpa/junit/JUnitTestCase.java
- pom.xml
This is first part of the fix for JPA test apps executed in JEE server environment. Main changes there:
- `eclipselink-testbuild-plugin` upgrade to 1.1.2 with `<libs>` support
- `(JpaEntityManager)entityManager` -> `entityManager.unwrap(JpaEntityManager)` as server should provide proxy class
- `em.getTransaction().begin()` -> `beginTransaction(em)` to allow JPA test FW identify if test is executed in JSE or JEE environment and call proper code
> [3.0] JPA Server side test fixes - part 1

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/expressions/ParameterExpression.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/queries/ExpressionQueryMechanism.java
- jpa/eclipselink.jpa.testapps/jpa.test.jpql/src/test/java/org/eclipse/persistence/testing/tests/jpa/jpql/advanced/JUnitJPQLModifyTest.java
This is fix for JPQL UPDATE queries when update parameter contains multiple levels of Embeddable classes.
Fixes #2362
> [master] JPQL Update with nested Embeddables - bugfix and unit test

- foundation/org.eclipse.persistence.oracle/src/main/java/org/eclipse/persistence/platform/database/oracle/dcn/OracleChangeNotificationListener.java
fix #2423 
- use unwrap to get the underlying OracleConnection
> [master] fix #2423: ClassCastException in OracleChangeNotificationListener

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/expressions/DataExpression.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/expressions/FunctionExpression.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/expressions/ObjectExpression.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/expressions/QueryKeyExpression.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/queries/ReportQuery.java
- jpa/eclipselink.jpa.testapps/jpa.test.jpql/src/main/resources/META-INF/persistence.xml
- jpa/eclipselink.jpa.testapps/jpa.test.jpql/src/test/java/org/eclipse/persistence/testing/tests/jpa/jpql/relationships/AdvancedQueryTest.java
- jpa/eclipselink.jpa.testapps/jpa.test.relationships/src/main/java/org/eclipse/persistence/testing/models/jpa/relationships/RelationshipsExamples.java
- jpa/eclipselink.jpa.testapps/jpa.test.relationships/src/main/java/org/eclipse/persistence/testing/models/jpa/relationships/ShippingAddress.java
- jpa/eclipselink.jpa.testapps/jpa.test.relationships/src/main/java/org/eclipse/persistence/testing/models/jpa/relationships/StreetAddress.java
Attmepts to resolve mapping using before last item in derivedExpressions, which should contain proper descriptor of `@Embeddable` class.
`descriptor.isAggregateDescriptor()` check was deleted in `ReportQuery#prepareSubSelect(AbstractSession,  AbstractRecord, Map<Expression, Expression>)` but I'm not sure whether it's OK to turn it off completely.
Anyway, the exception says _"Aggregate object cannot be deleted or written"_, but this is sub SELECT preparation code, not DML.
> Issue #2414: Fixed mapping resolution for @Embeddable in ObjectExpression

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/helper/ConcurrencyManager.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/helper/ConcurrencyUtil.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/helper/Helper.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/helper/WriteLockManager.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/helper/type/CacheKeyToThreadRelationships.java
Fix for event when massive dumps, triggered by dead lock diagnostic, are produced. Before this fix the concurrency layers should continue to update structures (Maps, Sets) passed to dead lock diagnostic and these structures could be updated in time period between detected dead lock event and print to some log output. After this fix snapshots are produced.
Backport #2288
(cherry picked from commit 4c55b68b8a989097d1d5d10eeec56f5c74d0c3c4)
> [3.0] DeadLock diagnostic fix - backport from master

- docs/docs.jpa/src/main/asciidoc/persistenceproperties_ref.adoc
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/config/MergeManagerOperationMode.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/config/PersistenceUnitProperties.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/config/SystemProperties.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/helper/ConcurrencyManager.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/helper/ConcurrencyUtil.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/helper/WriteLockManager.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/helper/type/ConcurrencyManagerState.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/localization/i18n/ExceptionLocalizationResource.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/localization/i18n/TraceLocalizationResource.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/sessions/AbstractSession.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/sessions/IsolatedClientSessionIdentityMapAccessor.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/sessions/ObjectChangeSet.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/sessions/UnitOfWorkIdentityMapAccessor.java
- jpa/eclipselink.jpa.testapps/jpa.test.diagnostic.deadlock/src/main/resources/META-INF/persistence.xml
- jpa/eclipselink.jpa.testapps/jpa.test.diagnostic.deadlock/src/test/java/org/eclipse/persistence/testing/tests/jpa/deadlock/diagnostic/CacheDeadLockDetectionTest.java
- jpa/eclipselink.jpa.testapps/jpa.test.diagnostic.deadlock/src/test/java/org/eclipse/persistence/testing/tests/jpa/deadlock/diagnostic/CacheDeadLockManagersTest.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/EntityManagerSetupImpl.java
Fixes #2094 
This is enhancement for case of possible deadlock which should happens in `org.eclipse.persistence.internal.sessions.AbstractSession#getCacheKeyFromTargetSessionForMerge` method if used `org.eclipse.persistence.internal.identitymaps.CacheKey` instance is locked by another thread.
There is new system or persistence property `eclipselink.concurrency.manager.allow.getcachekeyformerge.mode` which can control `org.eclipse.persistence.internal.sessions.AbstractSession#getCacheKeyFromTargetSessionForMerge` logic to get `org.eclipse.persistence.internal.identitymaps.CacheKey` instance and object value behind this.
There are two allowed values:
- `ORIGIN` (DEFAULT) - There is infinite `java.lang.Object.wait()` call in case of some conditions during time when object/entity referred …
> [3.0] New eclipselink dead lock scenario ... enhancement and unit test - backport from master

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/helper/ConcurrencyUtil.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/helper/WriteLockManager.java
- jpa/eclipselink.jpa.testapps/jpa.test.diagnostic.deadlock/src/test/java/org/eclipse/persistence/testing/tests/jpa/deadlock/diagnostic/CacheDeadLockManagersTest.java
Fixes #2173
There is incorrect log output in case if deadlock is detected and dump triggered in `WriteLockManager.acquireLocksForClonemessage()`. Mentioned method acquire read lock instead of write lock -> logged output was incorrect.
See log output before
```
...
Concurrency manager - Page 01 end - thread dump about all threads at time of event
Concurrency manager - Page 02 start - information about threads waiting to acquire (write/deferred) cache keys 
Total number of threads waiting to acquire lock: 1
[currentThreadNumber: 1] [ThreadName: main]: Waiting to acquire (write/deferred): --- CacheKey  (org.eclipse.persistence.testing.models.jpa.deadlock.diagnostic.CacheDeadLockDetectionMaster):  (primaryKey: 1) (object hash code: 1680621693) (cacheKeyClass: …
```
> [3.0] DeadLock detection diagnostic - WriteLockManager.acquireLocksForClonemessage change - backport from master

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/core/databaseaccess/CorePlatform.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/databaseaccess/DatasourcePlatform.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/mappings/converters/TypeConversionConverter.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/Oracle21Platform.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/Oracle23Platform.java
- foundation/org.eclipse.persistence.oracle/src/main/java/module-info.java
- foundation/org.eclipse.persistence.oracle/src/main/java/org/eclipse/persistence/platform/database/oracle/Oracle21Platform.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/json/TestJson.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/oraclefeatures/TestOracleLOBLocatorFeature.java
- jpa/eclipselink.jpa.testapps/jpa.test.beanvalidation/src/test/java/org/eclipse/persistence/testing/tests/jpa/beanvalidation/BeanValidationJunitTest.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/metadata/converters/LobMetadata.java
This fixes following two issues related with Oracle23c:
- when empty String (`""`) is inserted into table column like `...CLOBDATA CLOB NOT NULL...` Solution is based on conversion into `java.sql.Clob`, because solution based on `SimpleAppendCallCustomParameter("empty_clob()")` and `DatabasePlatform.appendParameter()` leads into another test failures.
- loss of precision if DB table is automatically created if entity using `java.time.LocalDateTime`, `java.time.LocalTime`
- JSON test with query like `SELECT v FROM JsonEntity v WHERE v.value = :value` where `v.value` and `:value` is disabled on Oracle platform as this DB can't compare by `=` or `<` two JSON object types.
- BeanValidationJunitTest fix to avoid platform dependent result types in dr.get(...) Integer, Long, BigDecimal.... …
> [4.0] Oracle 21C and 23AI platform fixes

- jpa/eclipselink.jpa.testapps/README.md
- jpa/eclipselink.jpa.testapps/jpa.test.advanced2/src/test/java/org/eclipse/persistence/testing/tests/advanced2/weave/WeaveVersionTest.java
- jpa/eclipselink.jpa.testapps/jpa.test.diagnostic/src/test/java/org/eclipse/persistence/testing/tests/jpa/diagnostic/DiagnosticTest.java
- jpa/eclipselink.jpa.testapps/jpa.test.identity/src/test/java/org/eclipse/persistence/testing/tests/jpa22/identity/IdentityTest.java
- jpa/eclipselink.jpa.testapps/jpa.test.jpaadvancedproperties/src/test/java/org/eclipse/persistence/testing/tests/jpa/jpaadvancedproperties/JPAAdvPropertiesTest.java
- jpa/eclipselink.jpa.testapps/jpa.test.metamodel.apectj/pom.xml
- jpa/eclipselink.jpa.testapps/jpa.test.metamodel.apectj/src/test/java/org/eclipse/persistence/testing/tests/jpa/weaving/aspectj/MetamodelAspectJTest.java
- jpa/eclipselink.jpa.testapps/jpa.test.sessionbean.ha/src/test/java/org/eclipse/persistence/testing/tests/jpa/sessionbean/ha/SessionBeanTest.java
- jpa/eclipselink.jpa.testapps/jpa.test.weaving/pom.xml
- jpa/eclipselink.jpa.testapps/jpa.test.xml.extended/jpa.test.xml.extended.advanced/src/test/java/org/eclipse/persistence/testing/tests/jpa/xml/extended/advanced/XmlExtendedAdvancedJunitTest.java
- jpa/eclipselink.jpa.testapps/jpa.test.xml.extended/jpa.test.xml.extended.advanced/src/test/java/org/eclipse/persistence/testing/tests/jpa/xml/extended/advanced/XmlExtendedAdvancedTest.java
- jpa/eclipselink.jpa.testapps/jpa.test.xml.only/jpa.test.xml.advanced/src/test/java/org/eclipse/persistence/testing/tests/jpa/xml/advanced/XmlAdvancedJunitTest.java
- jpa/eclipselink.jpa.testapps/jpa.test.xml.only/jpa.test.xml.advanced/src/test/java/org/eclipse/persistence/testing/tests/jpa/xml/advanced/compositepk/XmlAdvancedCompositePKTest.java
- jpa/eclipselink.jpa.testapps/nativeapi/src/main/resources-ejb/META-INF/sessions.xml
- jpa/org.eclipse.persistence.jpa.test.framework/src/main/java/org/eclipse/persistence/testing/framework/jpa/junit/JUnitTestCase.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/jpa/JpaEntityManager.java
- pom.xml
* JPA Server side test fixes - part 1 This is first part of the fix for JPA test apps executed in JEE server environment. Main changes there:
- `(JpaEntityManager)entityManager` -> `entityManager.unwrap(JpaEntityManager)` as server should provide proxy class
- `em.getTransaction().begin()` -> `beginTransaction(em)` to allow JPA test FW identify if test is executed in JSE or JEE environment and call proper code
> [4.0] JPA Server side test fixes - part 1 (backport from 3.0 #2401)

- jpa/eclipselink.jpa.testapps/jpa.test.diagnostic.deadlock/pom.xml
Main changes there:
- `testapps.deadlock.diagnostic` server side tests disabled due dependencies on Weld, CDI and JSE thread management (create additional threads to simulate deadlock)
> JPA Server side test fixes - part 4

- bundles/eclipselink/src/main/java/module-info.java
- jpa/eclipselink.jpa.testapps/jpa.test.jta/src/main/resources-ejb/META-INF/persistence.xml
- jpa/eclipselink.jpa.testapps/jpa.test.sessionbean.ha/src/main/resources-ejb/META-INF/persistence.xml
- jpa/org.eclipse.persistence.jpars.server/src/main/java/module-info.java
- pom.xml
- src/main/assembly/all-sources.xml
Main changes there:
- new Maven profile `all-sources` and assembly config due a Toplink
- _eclipselink.jar_ new exports due a Toplink
- `jpa.testapps.jta` server platform, database platform substitution strings in _resources-ejb/META-INF/persistence.xml_
- `jpa.testapps.sessionbean.ha` server platform, database platform substitution strings in _resources-ejb/META-INF/persistence.xml_
> [4.0] JPA Server side test fixes - part 5

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/helper/DBPlatformHelper.java
There is fix (fallback) to load resource file VendorNameToPlatformMapping.properties with classloader in non JPMS environment.
> [master] Platform autodetection should fail in server side environment - backport from 4.0

- jpa/eclipselink.jpa.testapps/jpa.test.persistence32/src/main/java/org/eclipse/persistence/testing/models/jpa/persistence32/SequenceGeneratorEntity.java
- jpa/eclipselink.jpa.testapps/jpa.test.persistence32/src/main/java/org/eclipse/persistence/testing/models/jpa/persistence32/TableGeneratorEntity.java
- jpa/eclipselink.jpa.testapps/jpa.test.persistence32/src/main/resources/META-INF/persistence.xml
- jpa/eclipselink.jpa.testapps/jpa.test.persistence32/src/test/java/org/eclipse/persistence/testing/tests/jpa/persistence32/SchemaManagerValidateOnMissingSchemaTest.java
- jpa/eclipselink.jpa.testapps/jpa.test.persistence32/src/test/java/org/eclipse/persistence/testing/tests/jpa/persistence32/TableSequenceGeneratorTest.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/metadata/MetadataProject.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/metadata/accessors/classes/MappedSuperclassAccessor.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/metadata/accessors/mappings/BasicAccessor.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/metadata/sequencing/GeneratedValueMetadata.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/metadata/sequencing/SequenceGeneratorMetadata.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/metadata/sequencing/TableGeneratorMetadata.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/metadata/xml/XMLEntityMappings.java
See
[11.1.52. TableGenerator Annotation](https://jakarta.ee/specifications/persistence/3.2/jakarta-persistence-spec-3.2#a16256)
[11.1.49. SequenceGenerator Annotation](https://jakarta.ee/specifications/persistence/3.2/jakarta-persistence-spec-3.2#a16164)
> [master] Jakarta Persistence 3.2 - Makes the name member of TableGenerator and SequenceGenerator optional (implementation and unit test)

- etc/jenkins/publish_snapshots.sh
- pom.xml
Snapshots publishing target change from https://jakarta.oss.sonatype.org/content/repositories/snapshots/ into https://central.sonatype.com/repository/maven-snapshots/
> [master] Maven build - Snapshots publishing change

- etc/jenkins/release.sh
Release publishing target change from https://jakarta.oss.sonatype.org/ into https://central.sonatype.com/publishing/deployments by org.sonatype.central:central-publishing-maven-plugin
(cherry picked from commit c8b11c21586d6b592fcc1234d97c17c254f93380)
> [4.0] Maven build - Release publishing change - backport from master

- etc/jenkins/release.sh
Release publishing target change from https://jakarta.oss.sonatype.org/ into https://central.sonatype.com/publishing/deployments by org.sonatype.central:central-publishing-maven-plugin
(cherry picked from commit c8b11c21586d6b592fcc1234d97c17c254f93380)
> [3.0] Maven build - Release publishing change - backport from master

- foundation/org.eclipse.persistence.core.test.framework/src/main/java/org/eclipse/persistence/testing/tests/ClearDatabaseSchemaTest.java
ClearDatabaseSchema wasn't implemented for DB2. This class is used by various tests during the build. When building EclipseLink in DB2 this would therefor always fail.
> [master] Implement ClearDatabaseSchema for DB2
