eclipse-ee4j/eclipselink

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/mappings/AggregateCollectionMapping.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/concurrency/TestConcurrencyPersistence.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/concurrency/model/User.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/concurrency/model/UserTag.java
> [master] Bug 500753: Synchronize initialization of InsertQuery

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/mappings/AggregateCollectionMapping.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/concurrency/TestConcurrencyPersistence.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/concurrency/model/User.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/concurrency/model/UserTag.java
> [2.6] Bug 500753: Synchronize initialization of InsertQuery

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/mappings/AggregateMapping.java
fix for https://bugs.eclipse.org/bugs/show_bug.cgi?id=413120
> [master] Bug 413120: Nested Embeddable Null pointer

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/sessions/AggregateChangeRecord.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/models/jpa/advanced/AdvancedTableCreator.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/models/jpa/advanced/embeddable/Continent.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/models/jpa/advanced/embeddable/Country.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/models/jpa/advanced/embeddable/Description.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/models/jpa/advanced/embeddable/VisitorPopulator.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa/advanced/EntityEmbeddableTest.java
fix for https://bugs.eclipse.org/bugs/show_bug.cgi?id=496836
tests here do cover also PR #10 
> [master] Bug 496836: NullPointerException on ObjectChangeSet.mergeObjectChanges

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/mappings/AggregateMapping.java
> [2.7] Bug 413120: Nested Embeddable Null pointer

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/sessions/AggregateChangeRecord.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/models/jpa/advanced/AdvancedTableCreator.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/models/jpa/advanced/embeddable/Continent.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/models/jpa/advanced/embeddable/Country.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/models/jpa/advanced/embeddable/Description.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/models/jpa/advanced/embeddable/VisitorPopulator.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa/advanced/EntityEmbeddableTest.java
> Bug 496836: NullPointerException on ObjectChangeSet.mergeObjectChanges

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/config/DescriptorCustomizer.java
> nobug: typo in DescriptorCustomizer

- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/tests/aggregate/AggregateTestModel.java
- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/tests/collections/map/MapCollectionsTestModel.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/mappings/AggregateObjectMapping.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/collection/TestEmbeddableKey.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/collection/model/Level.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/collection/model/MainEntity.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/collection/model/Param.java
test-lrg is passing with this change on my end, see https://bugs.eclipse.org/bugs/show_bug.cgi?id=441498
> [master] Bug 441498: @ElementCollection on Map<@Embeddable,String> cause NPE

- .travis.yml
- dbws/eclipselink.dbws.test/antbuild.xml
- foundation/eclipselink.core.test/antbuild.xml
- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/framework/TestCase.java
- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/framework/TestCollection.java
- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/framework/TestExecutor.java
- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/framework/TestModel.java
- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/framework/TestSuite.java
- foundation/eclipselink.extension.test/antbuild.xml
- jpa/eclipselink.jpa.test.jse/antbuild.xml
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/modelgen/TestProcessor.java
- jpa/eclipselink.jpa.test/antbuild.xml
- jpa/eclipselink.jpa.wdf.test/antbuild.xml
- jpa/eclipselink.jpars.test/antbuild.xml
- jpa/org.eclipse.persistence.jpa.jpql.test/antbuild.xml
- moxy/eclipselink.moxy.test/antbuild.xml
- sdo/eclipselink.sdo.test/antbuild.xml
- utils/eclipselink.dbws.builder.test/antbuild.xml
Initial configuration for travis. Let's try it and tweak it on the go
> [2.7] Add configuration for travis (#24)

- .travis.yml
> Make Travis build cleaner (#33)

- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/framework/TestExecutor.java
> Make Travis build green (#35)

- jpa/eclipselink.jpa.test.jse/antbuild.xml
> Bug 533022: JSE test bucket fails to compile

- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/jpql/TestComplexJPQL.java
> [master] Bug 531062: fix test running on Derby

- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/concurrency/TestConcurrencyPersistence.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/jpql/TestComplexJPQL.java
> [2.6_WAS] Bug 531062: fix test running on Derby

- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/jpql/TestComplexJPQL.java
> [2.7] Bug 531062: fix test running on Derby

- .travis.yml
- dbws/eclipselink.dbws.test/antbuild.properties
- dbws/eclipselink.dbws.test/antbuild.xml
- foundation/eclipselink.core.test/antbuild.properties
- foundation/eclipselink.core.test/antbuild.xml
- jpa/eclipselink.jpa.test.jse/antbuild.properties
- jpa/eclipselink.jpa.test.jse/antbuild.xml
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/modelgen/TestProcessor.java
- jpa/eclipselink.jpa.test/antbuild.properties
- jpa/eclipselink.jpa.test/antbuild.xml
- jpa/eclipselink.jpars.test/antbuild.properties
- jpa/eclipselink.jpars.test/antbuild.xml
- moxy/eclipselink.moxy.test/antbuild.properties
- moxy/eclipselink.moxy.test/antbuild.xml
- sdo/eclipselink.sdo.test/antbuild.properties
- sdo/eclipselink.sdo.test/antbuild.xml
- utils/eclipselink.dbws.builder.test/antbuild.properties
- utils/eclipselink.dbws.builder.test/antbuild.xml
Introducing `test.junit.jvm.modules` test project specific system property for passing module related info to tests
> Implement testing on JDK9

- .travis.yml
- dbws/eclipselink.dbws.test/antbuild.properties
- dbws/eclipselink.dbws.test/antbuild.xml
- foundation/eclipselink.core.test/antbuild.properties
- foundation/eclipselink.core.test/antbuild.xml
- jpa/eclipselink.jpa.test.jse/antbuild.properties
- jpa/eclipselink.jpa.test.jse/antbuild.xml
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/modelgen/TestProcessor.java
- jpa/eclipselink.jpa.test/antbuild.properties
- jpa/eclipselink.jpa.test/antbuild.xml
- jpa/eclipselink.jpars.test/antbuild.properties
- jpa/eclipselink.jpars.test/antbuild.xml
- moxy/eclipselink.moxy.test/antbuild.properties
- moxy/eclipselink.moxy.test/antbuild.xml
- sdo/eclipselink.sdo.test/antbuild.properties
- sdo/eclipselink.sdo.test/antbuild.xml
- utils/eclipselink.dbws.builder.test/antbuild.properties
- utils/eclipselink.dbws.builder.test/antbuild.xml
Introducing test.junit.jvm.modules test project specific system property for passing module related info to tests
> Implement testing on JDK9 (#47)

- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/metadata/accessors/objects/MetadataAsmFactory.java
> Bug 532882: fixed recognition of unknown classes

- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/metadata/accessors/objects/MetadataAsmFactory.java
> [2.7] Bug 532882: fixed recognition of unknown classes (#56)

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/mappings/AggregateCollectionMapping.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/concurrency/model/User.java
> Bug 500753: clean up implementation

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/mappings/AggregateCollectionMapping.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/concurrency/model/User.java
for #3
Missed this PR with the others
> [2.6] Bug 500753: clea up implementation

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/config/PersistenceUnitProperties.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/queries/DatasourceCallQueryMechanism.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/sessions/PropertiesHandler.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/sessions/Project.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/connwrapper/DriverWrapper.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/basic/TestBasicPersistence.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/basic/TestStoredProcedure.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/property/TestSQLCallDeferall.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/property/model/AbstractParent.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/property/model/Child.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/property/model/Parent.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/sequence/model/EntityWithSchema.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/EntityManagerSetupImpl.java
> [master] Bug 533148: Add new 'sql-call-deferral' property

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/config/PersistenceUnitProperties.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/queries/DatasourceCallQueryMechanism.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/sessions/PropertiesHandler.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/sessions/Project.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/connwrapper/DriverWrapper.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/basic/TestBasicPersistence.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/basic/TestStoredProcedure.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/property/TestSQLCallDeferall.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/property/model/AbstractParent.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/property/model/Child.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/property/model/Parent.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/EntityManagerSetupImpl.java
> [2.6_WAS] Bug 533148: Add new 'sql-call-deferral' property

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/config/PersistenceUnitProperties.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/queries/DatasourceCallQueryMechanism.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/sessions/PropertiesHandler.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/sessions/Project.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/connwrapper/DriverWrapper.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/basic/TestBasicPersistence.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/basic/TestStoredProcedure.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/property/TestSQLCallDeferall.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/property/model/AbstractParent.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/property/model/Child.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/property/model/Parent.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/sequence/model/EntityWithSchema.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/EntityManagerSetupImpl.java
> [2.7] Bug 533148: Add new 'sql-call-deferral' property

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/jpa/jpql/ExpressionBuilderVisitor.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/jpql/TestComplexJPQL.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/jpql/model/QueryResult.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/jpql/model/SimpleEntity.java
> [master] Bug 534515: Incorrect return type set for CASE functions

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/jpa/jpql/ExpressionBuilderVisitor.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/jpql/TestComplexJPQL.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/jpql/model/QueryResult.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/jpql/model/SimpleEntity.java
> [2.7] Bug 534515: Incorrect return type set for CASE functions

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/jpa/jpql/ExpressionBuilderVisitor.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/connwrapper/DriverWrapper.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/basic/TestBasicPersistence.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/jpql/TestComplexJPQL.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/jpql/model/QueryResult.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/jpql/model/SimpleEntity.java
> [2.6_WAS] Bug 534515: Incorrect return type set for CASE functions

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/queries/ExpressionQueryMechanism.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/version/TestVersioning.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/version/model/IntegerVersionedEntity.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/version/model/TemporalVersionedEntity.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/version/model/TemporalVersionedEntity2.java
Signed-off-by: Joe Grassel <jgrassel@us.ibm.com>
Master branch for fix https://github.com/eclipse-ee4j/eclipselink/pull/94
> [Master] Eclipselink#93: Resolve issue with JPA Versioning with java.sql.Timestamp

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/queries/ExpressionQueryMechanism.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/version/TestVersioning.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/version/model/IntegerVersionedEntity.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/version/model/TemporalVersionedEntity.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/version/model/TemporalVersionedEntity2.java
Fixes #93 for the 2.6_WAS branch
> [2.6_WAS] Eclipselink#93: Resolve issue with JPA Versioning with java.sql.Timestamp

- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/tests/expressions/ExpressionSubSelectTestSuite.java
backport of #103 to 2.7 branch
> [2.7] Bug 535088: SubSelectFromClauseTest2 failing randomly on public infra

- .travis.yml
- foundation/eclipselink.core.test/antbuild.properties
- foundation/eclipselink.core.test/antbuild.xml
- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/tests/TestRunModel.java
- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/tests/junit/logging/LogCategoryHelper.java
- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/tests/junit/logging/LogCategoryTest.java
- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/tests/junit/logging/LogLevelHelper.java
- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/tests/junit/logging/LogLevelTest.java
- foundation/eclipselink.extension.test/src/org/eclipse/persistence/testing/tests/logging/slf4j/SLF4JLoggerTest.java
> [2.7] Update core.test script to allow easier testing against modules

- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/tests/junit/helper/HelperTest.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/databaseaccess/DatabaseAccessor.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/helper/Helper.java
... when missing nano sec part
Fixes #111 
Signed-off-by: Sven Diedrichsen <sdiedrichsen@yahoo.de>
> Bug 522408: [Master] Fixing timestamp parsing 

- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/metadata/accessors/objects/MetadataAsmFactory.java
> [2.7] [nobug]: log exception at FINEST level

- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/metadata/accessors/objects/MetadataAsmFactory.java
> [nobug]: log exception at FINEST level

- moxy/eclipselink.moxy.test/antbuild.properties
- moxy/eclipselink.moxy.test/antbuild.xml
- moxy/eclipselink.moxy.test/pom.xml
> [2.7] Bug 533271: test-osgi tests are failing on JDK 10

- foundation/eclipselink.core.test/antbuild.xml
> [2.7][nobug]: fix test core cp for running tests against standalone bundles

- moxy/eclipselink.moxy.test/antbuild.properties
- moxy/eclipselink.moxy.test/antbuild.xml
- moxy/eclipselink.moxy.test/pom.xml
> Bug 533271: test-osgi tests are failing on JDK 10

- foundation/eclipselink.core.test/antbuild.xml
> [nobug]: fix test core cp for running tests against standalone bundles

- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/deployment/ArchiveFactoryImpl.java
for #142 
Signed-off-by: Joe Grassel <jgrassel@us.ibm.com>
> [2.6_WAS] Bug 536093: ArchiveFactoryImpl.isJarInputStream() requires doPriv block

- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa22/metadata/MetadataASMFactoryTest.java
- jpa/eclipselink.jpa.test/src/org/eclipse/samples/annotations/CycleA.java
- jpa/eclipselink.jpa.test/src/org/eclipse/samples/annotations/CycleB.java
- jpa/eclipselink.jpa.test/src/org/eclipse/samples/annotations/CycleC.java
- jpa/eclipselink.jpa.test/src/org/eclipse/samples/annotations/CycleSelf.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/metadata/accessors/objects/MetadataAnnotatedElement.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/metadata/accessors/objects/MetadataAsmFactory.java
2.7 backport. See PR 136 for details.
> Bug 535250 - Recursive annotations triggers a StackOverflowError

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/databaseaccess/DatabasePlatform.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/MySQLPlatform.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/OraclePlatform.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/tools/schemaframework/SchemaManager.java
Optimized for MySQL.
Unfortunately platforms need control not just on the statement itself, but also on the way how it's executed and evaluated.
> Table existence check per database platform.

- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/deployment/ArchiveFactoryImpl.java
Reverts eclipse-ee4j/eclipselink#141
> Revert "[2.6_WAS] Bug 536093: ArchiveFactoryImpl.isJarInputStream() requires doPriv block"

- foundation/org.eclipse.persistence.core/.classpath
- moxy/eclipselink.moxy.test/.classpath
- performance/eclipselink.perf.test/.classpath
> [nobug] update eclipse project definitions

- jpa/eclipselink.jpa.test/antbuild.xml
> [nobug] fix test packaging, server testing

- foundation/org.eclipse.persistence.core/resource/org/eclipse/persistence/internal/helper/VendorNameToPlatformMapping.properties
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/sessions/DatabaseSessionImpl.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/Oracle10Platform.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/Oracle11Platform.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/Oracle12Platform.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/Oracle8Platform.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/Oracle9Platform.java
> [master] Bug 532160: Add support for OracleXPlatforms, without extension bundle

- foundation/org.eclipse.persistence.core/resource/org/eclipse/persistence/internal/helper/VendorNameToPlatformMapping.properties
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/sessions/DatabaseSessionImpl.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/Oracle10Platform.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/Oracle11Platform.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/Oracle12Platform.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/Oracle8Platform.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/Oracle9Platform.java
> [2.7] Bug 532160: Add support for OracleXPlatforms, without extension bundle

- foundation/org.eclipse.persistence.core/resource/org/eclipse/persistence/internal/helper/VendorNameToPlatformMapping.properties
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/sessions/DatabaseSessionImpl.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/Oracle10Platform.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/Oracle11Platform.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/Oracle12Platform.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/Oracle8Platform.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/Oracle9Platform.java
> [2.6_WAS] Bug 532160: Add support for OracleXPlatforms, without extension bundle

- CONTRIBUTING.md
- NOTICE.md
add missing contributing and notice files as generated by https://www.eclipse.org/projects/tools/documentation.php?id=ee4j.eclipselink
> [nobug]: add contributing and notice files

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/localization/i18n/ExceptionLocalizationResource.java
Trivial update to this message. Going through ID approvals for 2.7.2, we would like the message updated like this.
> [nobug][master] minor change to ID message

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/localization/i18n/ExceptionLocalizationResource.java
> [nobug][2.7] minor change to ID message

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/helper/JavaSEPlatform.java
> [2.6_WAS] Bug 536730: NPE running with Java 11

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/helper/JavaSEPlatform.java
> [2.6] Bug 536730: NPE running with Java 11

- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/framework/TestSuite.java
- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/tests/TestRunModel.java
- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/tests/schemaframework/TablesCheckTestSuite.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/databaseaccess/DatabasePlatform.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/DatabasePlatform.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/MySQLPlatform.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/OraclePlatform.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/tools/schemaframework/SchemaManager.java
2nd version of the fix - without a new interface and with copy-pasted query evaluation code in child methods.
> Bug 425150 - Fixed bug in query result evaluation.

- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/framework/TestSuite.java
- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/tests/TestRunModel.java
- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/tests/schemaframework/TablesCheckTestSuite.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/databaseaccess/DatabasePlatform.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/DatabasePlatform.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/MySQLPlatform.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/OraclePlatform.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/tools/schemaframework/SchemaManager.java
> [2.7] Bug 425150 - Fixed bug in query result evaluation. (#182)

- dbws/org.eclipse.persistence.dbws/META-INF/MANIFEST.MF
- foundation/org.eclipse.persistence.core/META-INF/MANIFEST.MF
- jpa/org.eclipse.persistence.jpa/META-INF/MANIFEST.MF
- moxy/org.eclipse.persistence.moxy/META-INF/MANIFEST.MF
- plugins/org.eclipse.persistence.asm/README
- sdo/org.eclipse.persistence.sdo/META-INF/MANIFEST.MF
> [2.7][nobug]: bump imported asm version

- dbws/org.eclipse.persistence.dbws/META-INF/MANIFEST.MF
- foundation/org.eclipse.persistence.core/META-INF/MANIFEST.MF
- jpa/org.eclipse.persistence.jpa/META-INF/MANIFEST.MF
- moxy/org.eclipse.persistence.moxy/META-INF/MANIFEST.MF
- plugins/org.eclipse.persistence.asm/README
- sdo/org.eclipse.persistence.sdo/META-INF/MANIFEST.MF
> [nobug]: bump imported asm version

- foundation/eclipselink.core.test/src/org/eclipse/persistence/tools/beans/ExpressionTreeModel.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/descriptors/DescriptorQueryManager.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/expressions/ArgumentListFunctionExpression.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/expressions/CollectionExpression.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/expressions/ConstantExpression.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/expressions/DateConstantExpression.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/expressions/ExpressionSQLPrinter.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/expressions/FunctionExpression.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/expressions/SQLSelectStatement.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/jpa/jpql/ExpressionBuilderVisitor.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/sessions/factories/ObjectPersistenceRuntimeXMLProject.java
- foundation/org.eclipse.persistence.nosql/src/org/eclipse/persistence/nosql/adapters/mongo/MongoPlatform.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/query/TestQueryCase.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/query/model/Dto01.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/query/model/Dto02.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/query/model/Dto03.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/query/model/EntityTbl01.java
> [master] Bug 537795: Case expression uses operand for THEN clause values

- foundation/eclipselink.core.test/src/org/eclipse/persistence/tools/beans/ExpressionTreeModel.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/descriptors/DescriptorQueryManager.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/expressions/ArgumentListFunctionExpression.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/expressions/CollectionExpression.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/expressions/ConstantExpression.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/expressions/DateConstantExpression.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/expressions/ExpressionSQLPrinter.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/expressions/FunctionExpression.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/expressions/SQLSelectStatement.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/jpa/jpql/ExpressionBuilderVisitor.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/sessions/factories/ObjectPersistenceRuntimeXMLProject.java
- foundation/org.eclipse.persistence.nosql/src/org/eclipse/persistence/nosql/adapters/mongo/MongoPlatform.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/query/TestQueryCase.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/query/model/Dto01.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/query/model/Dto02.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/query/model/Dto03.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/query/model/EntityTbl01.java
> [2.7] Bug 537795: Case expression uses operand for THEN clause values

- buildsystem/org.eclipse.persistence.parent/pom.xml
> [master] Issue 221: Failed to load Orbit S20180302171354

- buildsystem/org.eclipse.persistence.parent/pom.xml
> [2.7] Issue 221: Failed to load Orbit S20180302171354

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/queries/DatabaseQueryMechanism.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/sessions/CommitManager.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/mappings/OneToManyMapping.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/mappings/UnidirectionalOneToManyMapping.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/TestUnidirectionalOneToMany.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/model/CommentA.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/model/CommentB.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/model/ComplexIdA.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/model/ComplexIdB.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/model/PostA.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/model/PostB.java
> Bug 391279: Add support for Unidirectional OneToMany with non-nullable value

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/config/SystemProperties.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/queries/DatabaseQueryMechanism.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/security/PrivilegedAccessHelper.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/sessions/CommitManager.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/mappings/OneToManyMapping.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/mappings/UnidirectionalOneToManyMapping.java
> [master] Bug 391279: Add support for Unidirectional OneToMany - Improvement

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/config/SystemProperties.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/security/PrivilegedAccessHelper.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/mappings/OneToManyMapping.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/mappings/UnidirectionalOneToManyMapping.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/TestUnidirectionalOneToMany.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/model/CommentA.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/model/CommentB.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/model/ComplexIdA.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/model/ComplexIdB.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/model/PostA.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/model/PostB.java
@dazey3 what about following approach?
> [2.7] Bug 391279: Improve implementation

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/config/SystemProperties.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/security/PrivilegedAccessHelper.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/mappings/OneToManyMapping.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/mappings/UnidirectionalOneToManyMapping.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/TestUnidirectionalOneToMany.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/model/CommentA.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/model/CommentB.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/model/ComplexIdA.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/model/ComplexIdB.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/model/PostA.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/model/PostB.java
backport of #233 to 2.6
Reviewed-by: Lukas Jungmann <lukas.jungmann@oracle.com>
> [2.6] Bug 391279: Add support for Unidirectional OneToMany with non-nullable value

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/queries/ExpressionQueryMechanism.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/queries/ConstructorReportItem.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/queries/ReportQueryResult.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/criteria/TestCriteriaBuilder.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/criteria/model/L1.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/criteria/model/L1Model.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/criteria/model/L1_.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/criteria/model/L2.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/criteria/model/L2Model.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/criteria/model/L2_.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/querydef/CriteriaQueryImpl.java
> [2.6_WAS] Issue #253: Add support for embedded constructor result expressions

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/queries/ExpressionQueryMechanism.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/queries/ConstructorReportItem.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/queries/ReportQuery.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/queries/ReportQueryResult.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/criteria/TestCriteriaBuilder.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/criteria/model/L1.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/criteria/model/L1Model.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/criteria/model/L1_.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/criteria/model/L2.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/criteria/model/L2Model.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/criteria/model/L2_.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/querydef/CriteriaQueryImpl.java
> [2.7] Issue #253: Add support for embedded constructor result expressions

- buildsystem/compdeps/antbuild.xml
> fix compdeps build

- uploadToNexus.xml
> Fixes #273: poms should not contain optional dependencies

- buildsystem/org.eclipse.persistence.parent/pom.xml
> bump tycho to 1.2.0 to support jdk10, uptake latest orbit and platform

- uploadToNexus.xml
> [2.7] Fixes #273: poms should not contain optional dependencies (#276)

- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/property/TestSQLCast.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/EntityManagerSetupImpl.java
> [master] Bug 540929: jdbc.sql-cast property does not apply

- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/property/TestSQLCast.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/EntityManagerSetupImpl.java
> [2.7] Bug 540929: jdbc.sql-cast property does not apply

- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/osgi/OSGiBundleTest.java
> fix the expected asm version in osgi test

- .travis.yml
- antbuild.xml
> fix broken jenkins build

- antbuild.xml
> fix broken build

- foundation/org.eclipse.persistence.oracle/src/org/eclipse/persistence/platform/database/oracle/Oracle9Platform.java
Signed-off-by: Sureshkumar Balakrishnannair <sureshkumar.balakrishnannair@oracle.com>
> Bug_540456 - MERGE OPERATION FROM OSB IS FAILING IN Weblogic 12C

- foundation/org.eclipse.persistence.oracle/src/org/eclipse/persistence/platform/database/oracle/Oracle9Platform.java
Signed-off-by: Sureshkumar Balakrishnannair <sureshkumar.balakrishnannair@oracle.com>
> Bug_540456 - MERGE OPERATION FROM OSB IS FAILING IN Weblogic 12C (#299)

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/databaseaccess/DatabasePlatform.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/EntityManagerSetupImpl.java
> [2.7] Bug 540929: jdbc.sql-cast property does not apply - fix

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/config/PersistenceUnitProperties.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/databaseaccess/DatabasePlatform.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/DB2Platform.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/property/TestParameterBinding.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/EntityManagerSetupImpl.java
> [master] Bug #542491: Add new property to force parameter binding

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/config/PersistenceUnitProperties.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/databaseaccess/DatabasePlatform.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/DB2Platform.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/property/TestParameterBinding.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/EntityManagerSetupImpl.java
> [2.7] Bug #542491: Add new property to force parameter binding

- antbuild.xml
- buildsystem/compdeps/org.eclipse.persistence.compdeps/feature.xml
- buildsystem/compdeps/pom.xml
- features/antbuild.xml
- features/org.eclipse.persistence.dbws/feature.xml
- features/org.eclipse.persistence.dbwsbuilder/feature.xml
- features/org.eclipse.persistence.jpa/feature.xml
- features/org.eclipse.persistence.moxy/feature.xml
- features/org.eclipse.persistence.nosql/feature.xml
> fix creation of nightly update sites

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/queries/ReadAllQuery.java
> [2.6] Bug 526546: Expression anyOf does not work correct when conforming (#236) (#329)

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/queries/ReadAllQuery.java
> Bug 526546: Expression anyOf does not work correct when conforming (#236)

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/config/PersistenceUnitProperties.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/databaseaccess/DatabasePlatform.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/DB2Platform.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/property/TestParameterBinding.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/EntityManagerSetupImpl.java
> [2.6_WAS] Bug #542491: Add new property to force parameter binding

- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/canonical/BasePersistable.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/canonical/DomainClass.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/canonical/DomainInterface.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/canonical/DomainInterface_.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/canonical/DomainPersistable.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/canonical/TestCanonicalMetaModel.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/metadata/MetadataProject.java
backporting #261 to 2.7
/cc @jvissers
> [2.7] Bug 539822: Fixes #260 (#261)

- buildsystem/compdeps/pom.xml
> bump JTA dependency to non-snapshot version

- uploadToNexus.xml
> fix the input for jpaapi version property

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/config/PersistenceUnitProperties.java
> Fix reference in javadoc

- about.html
- buildsystem/org.eclipse.persistence.parent/resource/about.html
- buildsystem/org.eclipse.persistence.parent/resource/readme.html
- plugins/org.eclipse.persistence.antlr/about.html
- plugins/org.eclipse.persistence.antlr/license.html
- plugins/org.eclipse.persistence.antlr/readme.html
- readme.html
> fix versions in readme and about  files

- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/framework/TestCase.java
- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/framework/TransactionIsolationLevelSwitchListener.java
- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/tests/unitofwork/ComplexMultipleUnitOfWorkTest.java
- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/tests/unitofwork/MultipleUnitOfWorkTest.java
- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/tests/unitofwork/UnitOfWorkComplexRefreshTest.java
Radku, this should help tests on Derby...
> Improve test stability on Apache Derby

- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/weaving/ClassWeaver.java
> JAXB is optional in JDK 9+

- foundation/eclipselink.extension.nosql.test/antbuild.xml
- foundation/eclipselink.extension.nosql.test/resource/META-INF/mongo-dynamic.xml
- foundation/eclipselink.extension.nosql.test/resource/META-INF/mongo-orm.xml
- foundation/eclipselink.extension.nosql.test/resource/META-INF/persistence.xml
> move resources to proper folder

- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/metadata/queries/StoredProcedureParameterMetadata.java
- utils/eclipselink.dbws.builder.test/src/dbws/testing/simplesp/SimpleSPTestSuite.java
> [nobug] update copyright year

- jpa/eclipselink.jpa.spring.test/src/test/org/eclipse/persistence/testing/models/jpa/spring/Route.java
this fixes failures in spring tests in maven based build on MySQL
> fix test failures in spring tests

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/mappings/converters/ConverterClass.java
…as CDI is not yet available at creation time  (#395)
Signed-off-by: Patrik Dudits <patrik.dudits@payara.fish>
> Do not eagerly construct converter over Injection Manager

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/mappings/converters/ConverterClass.java
...as CDI is not yet available at creation time  (#395)
Signed-off-by: Patrik Dudits <patrik.dudits@payara.fish>
> [2.7] Do not eagerly construct converter over InjectionManager (#395)

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/config/PersistenceUnitProperties.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/config/QueryHints.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/sessions/AbstractSession.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/sessions/PropertiesHandler.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/sessions/UnitOfWorkImpl.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/queries/ObjectLevelReadQuery.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/sessions/server/ClientSession.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa/jpql/AdvancedQueryTestSuite.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/EntityManagerImpl.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/EntityManagerSetupImpl.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/QueryHintsHandler.java
> [2.7] Bug 533724: JAVAX.PERSISTENCE.LOCK.TIMEOUT IS SET AS SECONDS IN SQL

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/config/PersistenceUnitProperties.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/config/QueryHints.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/sessions/AbstractSession.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/sessions/PropertiesHandler.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/sessions/UnitOfWorkImpl.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/queries/ObjectLevelReadQuery.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/sessions/server/ClientSession.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa/jpql/AdvancedQueryTestSuite.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/EntityManagerImpl.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/EntityManagerSetupImpl.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/QueryHintsHandler.java
> [2.6_WAS] Bug 533724: JAVAX.PERSISTENCE.LOCK.TIMEOUT IS SET AS SECONDS IN SQL

- foundation/eclipselink.extension.oracle.test/src/org/eclipse/persistence/testing/models/jpa/proxyauthentication/PhoneNumber.java
- foundation/org.eclipse.persistence.oracle.nosql/src/org/eclipse/persistence/internal/nosql/adapters/nosql/OracleNoSQLInteraction.java
- foundation/org.eclipse.persistence.oracle/src/org/eclipse/persistence/platform/database/oracle/dcn/OracleChangeNotificationListener.java
- foundation/org.eclipse.persistence.oracle/src/org/eclipse/persistence/tools/profiler/oracle/DMSPerformanceProfiler.java
> adopt cleanup and javadoc fixes in oradb specific modules (#400)(#405)

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/config/PersistenceUnitProperties.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/config/QueryHints.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/descriptors/DescriptorQueryManager.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/databaseaccess/DatabasePlatform.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/OraclePlatform.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/queries/DatabaseQuery.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/sessions/factories/ProjectClassGenerator.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/query/TestQueryHints.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/query/TestQueryProperties.java
- jpa/eclipselink.jpa.test/resource/eclipselink-advanced-field-access-model/osgi/persistence.xml
- jpa/eclipselink.jpa.test/resource/eclipselink-advanced-field-access-model/persistence.xml
- jpa/eclipselink.jpa.test/resource/eclipselink-advanced-field-access-model/server/persistence.xml
- jpa/eclipselink.jpa.test/resource/eclipselink-advanced-field-access-model/spring/persistence.xml
- jpa/eclipselink.jpa.test/resource/eclipselink-annotation-model/osgi/persistence.xml
- jpa/eclipselink.jpa.test/resource/eclipselink-annotation-model/persistence.xml
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/models/jpa/advanced/Employee.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/models/jpa/composite/advanced/member_2/Employee.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa/advanced/EntityManagerJUnitTestSuite.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa/advanced/PessimisticLockingExtendedScopeTestSuite.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa/composite/advanced/EntityManagerJUnitTestSuite.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa/fieldaccess/advanced/EntityManagerJUnitTestSuite.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa/jpql/AdvancedQueryTestSuite.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa/jpql/JUnitJPQLComplexTestSuite.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/QueryHintsHandler.java
> [2.7] Bug 533724: setting the default to MILLISECONDS

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/config/PersistenceUnitProperties.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/config/QueryHints.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/descriptors/DescriptorQueryManager.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/databaseaccess/DatabasePlatform.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/OraclePlatform.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/queries/DatabaseQuery.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/sessions/factories/ProjectClassGenerator.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/query/TestQueryHints.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/query/TestQueryProperties.java
- jpa/eclipselink.jpa.test/resource/eclipselink-advanced-field-access-model/osgi/persistence.xml
- jpa/eclipselink.jpa.test/resource/eclipselink-advanced-field-access-model/persistence.xml
- jpa/eclipselink.jpa.test/resource/eclipselink-advanced-field-access-model/server/persistence.xml
- jpa/eclipselink.jpa.test/resource/eclipselink-advanced-field-access-model/spring/persistence.xml
- jpa/eclipselink.jpa.test/resource/eclipselink-annotation-model/osgi/persistence.xml
- jpa/eclipselink.jpa.test/resource/eclipselink-annotation-model/persistence.xml
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/models/jpa/advanced/Employee.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/models/jpa/composite/advanced/member_2/Employee.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa/advanced/EntityManagerJUnitTestSuite.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa/advanced/PessimisticLockingExtendedScopeTestSuite.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa/composite/advanced/EntityManagerJUnitTestSuite.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa/fieldaccess/advanced/EntityManagerJUnitTestSuite.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa/jpql/AdvancedQueryTestSuite.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa/jpql/JUnitJPQLComplexTestSuite.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/QueryHintsHandler.java
> [2.6_WAS] Bug 533724: setting the default to MILLISECONDS

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/jpa/jpql/AbstractObjectLevelReadQueryVisitor.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/queries/ExpressionQueryMechanism.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/jpql/TestComplexJPQL.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/jpql/model/OtherSubClass.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/jpql/model/SubClass.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/jpql/model/SuperClass.java
> [master] Bug 493804: LEFT OUTER JOIN do not account for empty JOIN results

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/jpa/jpql/AbstractObjectLevelReadQueryVisitor.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/queries/ExpressionQueryMechanism.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/jpql/TestComplexJPQL.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/jpql/model/OtherSubClass.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/jpql/model/SubClass.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/jpql/model/SuperClass.java
> [2.7] Bug 493804: LEFT OUTER JOIN do not account for empty JOIN result

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/jpa/jpql/AbstractObjectLevelReadQueryVisitor.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/queries/ExpressionQueryMechanism.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/jpql/TestComplexJPQL.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/jpql/model/OtherSubClass.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/jpql/model/SubClass.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/jpql/model/SuperClass.java
> [2.6_WAS] Bug 493804: LEFT OUTER JOIN do not account for empty JOIN result

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/expressions/FunctionExpression.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/jpa/jpql/ReportItemBuilder.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/queries/ReportItem.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/mappings/DirectCollectionMapping.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/queries/ReportQueryResult.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/jpql/TestAggregateFunctions.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/jpql/model/NoResultEntity.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/models/jpa/advanced/AdvancedTableCreator.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/models/jpa/advanced/Buyer.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa/jpql/JUnitJPQLComplexAggregateTestSuite.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa/jpql/JUnitJPQLComplexTestSuite.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa/jpql/JUnitJPQLInheritanceTestSuite.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa/jpql/JUnitJPQLValidationTestSuite.java
> [master] Bug 421056: Aggregate functions in JPQL return 0 instead of NULL

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/expressions/FunctionExpression.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/jpa/jpql/ReportItemBuilder.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/queries/ReportItem.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/mappings/DirectCollectionMapping.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/queries/ReportQueryResult.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/jpql/TestAggregateFunctions.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/jpql/model/NoResultEntity.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/models/jpa/advanced/AdvancedTableCreator.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/models/jpa/advanced/Buyer.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa/jpql/JUnitJPQLComplexAggregateTestSuite.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa/jpql/JUnitJPQLComplexTestSuite.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa/jpql/JUnitJPQLInheritanceTestSuite.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa/jpql/JUnitJPQLValidationTestSuite.java
> [2.7] Bug 421056: Aggregate functions in JPQL return 0 instead of NULL

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/expressions/FunctionExpression.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/jpa/jpql/ReportItemBuilder.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/queries/ReportItem.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/mappings/DirectCollectionMapping.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/queries/ReportQueryResult.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/jpql/TestAggregateFunctions.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/jpql/model/NoResultEntity.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/models/jpa/advanced/AdvancedTableCreator.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/models/jpa/advanced/Buyer.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa/jpql/JUnitJPQLComplexAggregateTestSuite.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa/jpql/JUnitJPQLComplexTestSuite.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa/jpql/JUnitJPQLInheritanceTestSuite.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa/jpql/JUnitJPQLValidationTestSuite.java
> [2.6_WAS] Bug 421056: Aggregate functions in JPQL return 0 instead of NULL

- foundation/org.eclipse.persistence.core/.classpath
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/config/PersistenceUnitProperties.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/queries/ReportQueryResult.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/sessions/Project.java
- jpa/org.eclipse.persistence.jpa/.classpath
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/EntityManagerSetupImpl.java
> [2.6_WAS] Bug 421056: Add ability to disable MAX/MIN null result

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/descriptors/changetracking/DeferredChangeDetectionPolicy.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa/beanvalidation/BeanValidationJunitTest.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/metadata/listeners/BeanValidationListener.java
it is causing regressions - validation is not being triggered in JPA/callback case
> [2.6] Rollback the fix for bug 411013

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/logging/LogCategory.java
PR #423 backport from Master to 2.7 branch.
> Bug moxy 521424 add moxy to logger categories (backport from Master)

- moxy/org.eclipse.persistence.moxy/src/org/eclipse/persistence/jaxb/rs/MOXyJsonProvider.java
PR #457 backport from Master to 2.7 branch.
> add @Provider annotation to simplify auto-registration (backport from Master)

- jpa/eclipselink.jpa.test.jse/antbuild.xml
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/criteria/TestCriteriaBuilder.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/jpql/TestComplexJPQL.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/lob/TestLobMerge.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/TestUnidirectionalOneToMany.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/property/TestParameterBinding.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/property/TestSQLCallDeferall.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/property/TestSQLCast.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/query/TestQueryCase.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/query/TestQueryHints.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/query/TestQueryProperties.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/query/model/QueryEmployee.java
> [master] Bug 547056: JSE test cleanup

- foundation/org.eclipse.persistence.core/.classpath
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/config/PersistenceUnitProperties.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/queries/ReportQueryResult.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/sessions/Project.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/jpql/TestAggregateFunctions.java
- jpa/org.eclipse.persistence.jpa/.classpath
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/EntityManagerSetupImpl.java
> [2.7] Bug 421056: Add ability to disable MAX/MIN null result

- foundation/org.eclipse.persistence.core/core.iml
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/localization/i18n/JAXBLocalizationResource.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/localization/i18n/TraceLocalizationResource.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/oxm/XMLMarshaller.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/oxm/XMLUnmarshaller.java
- moxy/eclipselink.moxy.test/moxy.test.iml
- moxy/org.eclipse.persistence.moxy/src/org/eclipse/persistence/jaxb/JAXBContext.java
- moxy/org.eclipse.persistence.moxy/src/org/eclipse/persistence/jaxb/JAXBContextProperties.java
- moxy/org.eclipse.persistence.moxy/src/org/eclipse/persistence/jaxb/JAXBMarshaller.java
- moxy/org.eclipse.persistence.moxy/src/org/eclipse/persistence/jaxb/JAXBUnmarshaller.java
- moxy/org.eclipse.persistence.moxy/src/org/eclipse/persistence/jaxb/MOXySystemProperties.java
- moxy/org.eclipse.persistence.moxy/src/org/eclipse/persistence/jaxb/MarshallerProperties.java
- moxy/org.eclipse.persistence.moxy/src/org/eclipse/persistence/jaxb/UnmarshallerProperties.java
- moxy/org.eclipse.persistence.moxy/src/org/eclipse/persistence/jaxb/compiler/MappingsGenerator.java
- moxy/org.eclipse.persistence.moxy/src/org/eclipse/persistence/jaxb/rs/MOXyJsonProvider.java
* MOXy logging enhancement
(cherry picked from commit d99ec9b)
> [Non Bug] MOXy logging improvement (backport from master #445)

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/exceptions/JAXBException.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/exceptions/i18n/JAXBExceptionResource.java
- moxy/org.eclipse.persistence.moxy/src/org/eclipse/persistence/jaxb/compiler/AnnotationsProcessor.java
* Bug MOXy 546989 - Have better information in Exceptions
(cherry picked from commit aae2a736c9419188e800e564496c0eb136105eaa)
> Bug MOXy 546989 - Have better information in Exceptions (backport from master #446)

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/mappings/OneToManyMapping.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/TestUnidirectionalOneToMany.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/model/CommentB.java
Backport of https://github.com/eclipse-ee4j/eclipselink/pull/311 
Reviewed-by: Will Dazey<dazeydev.3@gmail.com>
> [2.6_WAS] Bug 391279: fix the case when existing object is being updated

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/mappings/DirectToFieldMapping.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/TestUnidirectionalOneToMany.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/model/CommentC.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/model/CommentD.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/model/ComplexIdC.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/model/ComplexIdD.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/model/PostC.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/model/PostD.java
> [2.7] Bug 391279: Fix usecase with existing FK mapping

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/mappings/DirectToFieldMapping.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/TestUnidirectionalOneToMany.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/model/CommentC.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/model/CommentD.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/model/ComplexIdC.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/model/ComplexIdD.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/model/PostC.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/model/PostD.java
> [2.6_WAS] Bug 391279: Fix usecase with existing FK mapping

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/queries/ReportQueryResult.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/jpql/TestAggregateFunctions.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/jpql/model/SimpleEntity.java
> [2.6_WAS] Bug 548590: Max/Min aggregate incorrectly returns NULL

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/databaseaccess/DatabasePlatform.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/property/TestSQLCast.java
> [2.6_WAS] Bug 540929: jdbc.sql-cast property does not apply

- jpa/eclipselink.jpa.test.jse/antbuild.xml
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/criteria/TestCriteriaBuilder.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/jpql/TestComplexJPQL.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/lob/TestLobMerge.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/TestUnidirectionalOneToMany.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/property/TestParameterBinding.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/property/TestSQLCallDeferall.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/query/TestQueryCase.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/query/TestQueryHints.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/query/TestQueryProperties.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/query/model/QueryEmployee.java
> [2.6_WAS] Bug 547056: JSE test cleanup

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/DB2Platform.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/DB2ZPlatform.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/DerbyPlatform.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/property/TestParameterBinding.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/property/model/GenericEntity.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/storedproc/TestDB2ZPlatform.java
- jpa/org.eclipse.persistence.jpa.jpql/src/org/eclipse/persistence/jpa/jpql/ParameterTypeVisitor.java
for #492
Update JPA to fix EclipseLink bug 542491. 
Original fix by Will Dazey, committing to 2.6_WAS on his behalf.
> [2.6_WAS] EclipseLink: Deliver Bug #542491

- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/property/TestParameterBinding.java
> [2.6_WAS] Bug #542491: 'eclipselink.jdbc.force-bind-parameters' testcase fails for Derby

- buildsystem/compdeps/pom.xml
- foundation/org.eclipse.persistence.extension/pom.xml
- foundation/org.eclipse.persistence.extension/src/org/eclipse/persistence/internal/sessions/coordination/jgroups/JGroupsRemoteConnection.java
- uploadToNexus.xml
Add support for JGroups ver. 4.x in session coordination mechanism.
> Add support for JGroups ver. 4.x in session coordination;

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/helper/DBPlatformHelper.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/sessions/DatabaseSessionImpl.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/ddl/TestDBPlatformHelper.java
> [2.7] Bug 518774: HANAPlatform is not detected; improving platform detection

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/helper/DBPlatformHelper.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/sessions/DatabaseSessionImpl.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/ddl/TestDBPlatformHelper.java
> [master] Bug 518774: HANAPlatform is not detected; improving platform detection

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/helper/DBPlatformHelper.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/sessions/DatabaseSessionImpl.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/ddl/TestDBPlatformHelper.java
> [2.6_WAS] Bug 518774: HANAPlatform is not detected; improving platform detection

- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa/advanced/EntityManagerJUnitTestSuite.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/EntityManagerImpl.java
> [master] Bug 547173: em.unwrap returns NULL in EE application

- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa/advanced/EntityManagerJUnitTestSuite.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/EntityManagerImpl.java
> [2.7] Bug 547173: em.unwrap returns NULL in EE application

- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa/advanced/EntityManagerJUnitTestSuite.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/EntityManagerImpl.java
> [2.6_WAS] Bug 547173: em.unwrap returns NULL in EE application

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/queries/ReportQueryResult.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/jpql/TestAggregateFunctions.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/jpql/model/SimpleEntity.java
> [master] Bug 548590: Max/Min aggregate incorrectly returns NULL

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/queries/ReportQueryResult.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/jpql/TestAggregateFunctions.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/jpql/model/SimpleEntity.java
> [2.7] Bug 548590: Max/Min aggregate incorrectly returns NULL

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/queries/DatasourceCallQueryMechanism.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/queries/ExpressionQueryMechanism.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/TestAggregateObjectMappings.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/model/SimpleMappingEmbeddable.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/model/SimpleMappingEntity.java
> [master] Bug 471144: Bad offset for AggregateObjectMapping using eclipselink.cursor

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/queries/DatasourceCallQueryMechanism.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/queries/ExpressionQueryMechanism.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/TestAggregateObjectMappings.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/model/SimpleMappingEmbeddable.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/model/SimpleMappingEntity.java
> [2.7] Bug 471144: Bad offset for AggregateObjectMapping using eclipselink.cursor

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/databaseaccess/DatabasePlatform.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/jpql/TestJava8DateTime.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/jpql/model/SimpleTimeEntity.java
> [master] Bug 550951: Parameter binding for java.time types results in SQL syntax exception

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/databaseaccess/DatabasePlatform.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/jpql/TestJava8DateTime.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/jpql/model/SimpleTimeEntity.java
> [2.7] Bug 550951: Parameter binding for java.time types results in SQL syntax exception

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/HANAPlatform.java
Signed-off-by: Alexander Parr <alexander.parr@projektraum36.de>
> Enable FK creation for SAP HANA

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/queries/DatasourceCallQueryMechanism.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/queries/ExpressionQueryMechanism.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/TestAggregateObjectMappings.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/TestUnidirectionalOneToMany.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/model/SimpleMappingEmbeddable.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/model/SimpleMappingEntity.java
> [2.6_WAS] Bug 471144: Bad offset for AggregateObjectMapping using eclipselink.cursor

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/databaseaccess/DatabasePlatform.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/DB2ZPlatform.java
> [master] Bug 550951: Remove deprecated java.sql.Timestamp constructor

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/databaseaccess/DatabasePlatform.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/DB2ZPlatform.java
> [2.7] Bug 550951: Remove deprecated java.sql.Timestamp constructor

- foundation/org.eclipse.persistence.core/resource/org/eclipse/persistence/internal/helper/VendorNameToPlatformMapping.properties
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/Oracle19Platform.java
- foundation/org.eclipse.persistence.oracle/src/org/eclipse/persistence/platform/database/oracle/Oracle19Platform.java
Bug 548814 - EL not Auto Detecting Oracle 19C 
Added support for Oracle19C
> Bug29858243 login error with db19 c

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/SQLServerPlatform.java
See issue #410. If this looks okay to whoever reviews it, I will create another PR for master branch.
> [2.7] Bug 546209: improve handling of SQL Server's DATETIMEOFFSET type

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/SQLServerPlatform.java
See issue #410. Master branch version of PR #411 which was just merged.
> Bug 546209: improve handling of SQL Server's DATETIMEOFFSET type

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/databaseaccess/DatabasePlatform.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/models/jpa/datetime/DateTime.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/models/jpa/datetime/DateTimePopulator.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/models/jpa/datetime/DateTimeTableCreator.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa/datetime/NullBindingJUnitTestCase.java
This pr fixes bug 546312 (https://bugs.eclipse.org/bugs/show_bug.cgi?id=546312)
> [master] Bug 546312 - Add missing mapping for java.time classes to DatabasePlatform

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/HANAPlatform.java
Signed-off-by: Alexander Parr <alexander.parr@projektraum36.de>
PR #516 for 2.7 branch
> [2.7] Enable FK creation for SAP HANA

- antbuild.xml
> [2.7] make the build less verbose

- antbuild.xml
> make the build less verbose (#571)

- jpa/org.eclipse.persistence.jpa.jpql.test/src/org/eclipse/persistence/jpa/tests/jpql/parser/JPQLExpressionTurkishLocaleTest.java
- jpa/org.eclipse.persistence.jpa.jpql/src/org/eclipse/persistence/jpa/jpql/AbstractSemanticValidator.java
- jpa/org.eclipse.persistence.jpa.jpql/src/org/eclipse/persistence/jpa/jpql/parser/ExpressionRegistry.java
- jpa/org.eclipse.persistence.jpa.jpql/src/org/eclipse/persistence/jpa/jpql/parser/FullyQualifyPathExpressionVisitor.java
- jpa/org.eclipse.persistence.jpa.jpql/src/org/eclipse/persistence/jpa/jpql/parser/IdentificationVariable.java
- jpa/org.eclipse.persistence.jpa.jpql/src/org/eclipse/persistence/jpa/jpql/parser/JPQLQueryBNF.java
- jpa/org.eclipse.persistence.jpa.jpql/src/org/eclipse/persistence/jpa/jpql/tools/AbstractContentAssistVisitor.java
- jpa/org.eclipse.persistence.jpa.jpql/src/org/eclipse/persistence/jpa/jpql/tools/model/IJPQLQueryFormatter.java
- jpa/org.eclipse.persistence.jpa.jpql/src/org/eclipse/persistence/jpa/jpql/tools/resolver/DeclarationResolver.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/EntityManagerFactoryDelegate.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/EntityManagerImpl.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/EntityManagerSetupImpl.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/QueryHintsHandler.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/metadata/MetadataDescriptor.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/metadata/accessors/MetadataAccessor.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/metadata/accessors/MetadataHelper.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/metadata/accessors/objects/MetadataClass.java
* Bug 527415 #345 - Fix code when locale is tr, az or lt
Signed-off-by: Alexandre Jacob <alexandref.jacob@gmail.com>
* Make sure test resets locale
> [2.7] Bug 527415 #345 - Fix code when locale is tr, az or lt (#370)

- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/tests/junit/identitymaps/CacheIdTest.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/identitymaps/CacheId.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/identitymaps/CacheIdComparator.java
Signed-off-by: Michal Stochmialek <uek@kmd.dk>
> [2.7] #482 - fix for CacheId comparision with BINARY arrays (#496)

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/jpa/jpql/ExpressionBuilderVisitor.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/queries/DatabaseQuery.java
for #492
For some reason, these minor changes were missing from  #497
> [2.6_WAS] Bug #542491: missing changes

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/databaseaccess/DatabasePlatform.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/jpa/jpql/ExpressionBuilderVisitor.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/DB2ZPlatform.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/DBasePlatform.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/HANAPlatform.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/OraclePlatform.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/SQLServerPlatform.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/SybasePlatform.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/oracle/plsql/PLSQLStoredProcedureCall.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/queries/StoredProcedureCall.java
- foundation/org.eclipse.persistence.oracle/src/org/eclipse/persistence/platform/database/oracle/Oracle9Platform.java
> [2.7] Bug 550542: Addressing additional test failures

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/databaseaccess/DatabasePlatform.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/jpa/jpql/ExpressionBuilderVisitor.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/DB2ZPlatform.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/DBasePlatform.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/HANAPlatform.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/OraclePlatform.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/SybasePlatform.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/oracle/plsql/PLSQLStoredProcedureCall.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/queries/StoredProcedureCall.java
- foundation/org.eclipse.persistence.oracle/src/org/eclipse/persistence/platform/database/oracle/Oracle9Platform.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa/advanced/AdvancedJunitTest.java
for #512
I included a port of `Bug 469182` in this PR as it was needed for the Coalesce fix and was never ported to 2.6_WAS originally
> [2.6_WAS] Bug 550542: Addressing additional test failures

- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa/jpql/AdvancedQueryTestSuite.java
JPA test fix for SELECT...FOR UPDATE WAIT xx
This is fix for JPA with `SELECT...FOR UPDATE WAIT xx` queries.
It's executed on OraclePlatform only.
Some description for SQL SELECT FOR UPDATE WAIT xx option (from Oracle DB doc):
The NOWAIT and WAIT clauses let you tell the database how to proceed if
the SELECT statement attempts to lock a row that is locked by another user.
Specify WAIT to instruct the database to wait integer seconds for the row to become available and then return control to you.
Before this fix `QueryHints.PESSIMISTIC_LOCK_TIMEOUT` was applied to first query, but
to test this feature correctly it should be applied to the second query in test.
This is not instruction how long DB keeps lock, but how long query will
wait for a lock release if there are some locked rows in …
> [master] JPA test fix for SELECT...FOR UPDATE WAIT xx

- etc/jenkins/build.groovy
JUnit test results upload to Jenkins master moved to the end of the pipeline.
There is retry instruction to retry upload again (in case of crash).
> [2.7] EclipseLink - Jenkins pipeline

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/databaseaccess/DatabasePlatform.java
for #512
Fixing a mistake in #517 
> [2.7] Bug 550542: Fix to add back line that was mistakenly removed

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/databaseaccess/DatabasePlatform.java
for #512
Fixing a mistake in #513  
> [2.6_WAS] Bug 550542: Fix to add back line that was mistakenly removed

- jpa/org.eclipse.persistence.jpa.modelgen/src/main/java/org/eclipse/persistence/internal/jpa/modelgen/visitors/AnnotationValueVisitor.java
- jpa/org.eclipse.persistence.jpa.modelgen/src/main/java/org/eclipse/persistence/internal/jpa/modelgen/visitors/ElementVisitor.java
- jpa/org.eclipse.persistence.jpa.modelgen/src/main/java/org/eclipse/persistence/internal/jpa/modelgen/visitors/TypeVisitor.java
- jpa/org.eclipse.persistence.jpa.modelgen/src/test/java/org/eclipse/persistence/jpa/test/modelgen/TestProcessor.java
> Fix #595: annotations with ElementType.TYPE_USE are not handled properly

- .travis.yml
[master] Travis - added jpa.modelgen.processor test
> [master] Travis - added jpa.modelgen.processor test

- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/deployment/PersistenceUnitProcessor.java
- moxy/org.eclipse.persistence.moxy/src/test/java/org/eclipse/persistence/testing/jaxb/schemagen/inheritance/ParentEntity.java
[master] Fix for #494 - JPA Weave: File handle leak: persistence.xml not properly closed
> [master] Fix for #494 - JPA Weave: File handle leak: persistence.xml not properly closed

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/DB2Platform.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/storedproc/TestStoredProceduresCursors.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/storedproc/model/StoredProcedureEntity.java
> [master] Bug 558414: Unrecognized JDBC type for Cursor type for DB2

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/DB2Platform.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/storedproc/TestStoredProceduresCursors.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/storedproc/model/StoredProcedureEntity.java
> [2.7] Bug 558414: Unrecognized JDBC type for Cursor type for DB2

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/DB2Platform.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/storedproc/TestStoredProceduresCursors.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/storedproc/model/StoredProcedureEntity.java
> [2.6_WAS] Bug 558414: Unrecognized JDBC type for Cursor type for DB2

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/server/wls/WebLogicPlatformDetector.java
> Fixes #651: WebLogic version is not detected properly on JDK11

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/server/wls/WebLogicPlatformDetector.java
> Fixes #651: WebLogic version is not detected properly on JDK11 (#652)

- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/metadata/listeners/BeanValidationListener.java
> jpa callback validation not being invoked for changed object

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/databaseaccess/DatabaseCall.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/databaseaccess/DatabasePlatform.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/DB2Platform.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/DB2ZPlatform.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/oracle/plsql/PLSQLStoredProcedureCall.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/queries/StoredProcedureCall.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/jpql/TestComplexJPQL.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/storedproc/TestStoredProcedures.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa21/advanced/StoredProcedureQueryTestSuite.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa22/advanced/StoredProcedureQueryTestSuite.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/StoredProcedureQueryImpl.java
> [2.7] Bug 558283: Missing parameter markers from DB2z Stored Procedures

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/databaseaccess/DatabaseCall.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/databaseaccess/DatabasePlatform.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/DB2Platform.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/DB2ZPlatform.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/oracle/plsql/PLSQLStoredProcedureCall.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/queries/StoredProcedureCall.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/jpql/TestComplexJPQL.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/storedproc/TestStoredProcedures.java
- jpa/eclipselink.jpa.test/src/it/java/org/eclipse/persistence/testing/tests/jpa21/advanced/StoredProcedureQueryTestSuite.java
- jpa/eclipselink.jpa.test/src/it/java/org/eclipse/persistence/testing/tests/jpa22/advanced/StoredProcedureQueryTestSuite.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/StoredProcedureQueryImpl.java
> [master] Bug 558283: Missing parameter markers from DB2z Stored Procedures

- etc/jenkins/promote_init.sh
> Jenkins promotion fix v2.0

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/descriptors/ClassDescriptor.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/mappings/AggregateObjectMapping.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/mappings/foundation/AbstractDirectMapping.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/mapping/TestAttributeOverride.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/mapping/model/OverrideEmbeddableA.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/mapping/model/OverrideEmbeddableIdA.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/mapping/model/OverrideEntityA.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/mapping/model/OverrideNestedEmbeddableA.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/mapping/model/OverrideNestedEmbeddableIdA.java
> [master] Bug 347987: primaryKeyUpdateDisallowedException on Embedded Class with attributeOverride

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/descriptors/ClassDescriptor.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/mappings/AggregateObjectMapping.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/mappings/foundation/AbstractDirectMapping.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/TestAttributeOverride.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/model/OverrideEmbeddableA.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/model/OverrideEmbeddableIdA.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/model/OverrideEntityA.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/model/OverrideNestedEmbeddableA.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/model/OverrideNestedEmbeddableIdA.java
> [2.7] Bug 347987: primaryKeyUpdateDisallowedException on Embedded Class with attributeOverride

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/descriptors/ClassDescriptor.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/mappings/AggregateObjectMapping.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/mappings/foundation/AbstractDirectMapping.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/TestAttributeOverride.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/model/OverrideEmbeddableA.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/model/OverrideEmbeddableIdA.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/model/OverrideEntityA.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/model/OverrideNestedEmbeddableA.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/model/OverrideNestedEmbeddableIdA.java
> [2.6_WAS] Bug 347987: primaryKeyUpdateDisallowedException on Embedded Class with attributeOverride

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/mappings/ForeignReferenceMapping.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/criteria/TestCollectionTable.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/criteria/TestCriteriaBuilder.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/criteria/model/CriteriaCar.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/criteria/model/CriteriaCarId.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/criteria/model/CriteriaCar_.java
> [2.6_WAS] Bug 559346: CastCastException DataReadQuery incompatible with ObjectLevelReadQuery

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/mappings/ForeignReferenceMapping.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/criteria/TestCollectionTable.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/criteria/model/CriteriaCar.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/criteria/model/CriteriaCarId.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/criteria/model/CriteriaCar_.java
> [2.7] Bug 559346: CastCastException DataReadQuery incompatible with ObjectLevelReadQuery

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/mappings/ForeignReferenceMapping.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/criteria/TestCollectionTable.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/criteria/model/CriteriaCar.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/criteria/model/CriteriaCarId.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/criteria/model/CriteriaCar_.java
> [master] Bug 559346: CastCastException DataReadQuery incompatible with ObjectLevelReadQuery

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/DB2ZPlatform.java
> [2.6_WAS] Bug 559896: pingSQL is incorrect for DB2ZPlatform

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/DB2ZPlatform.java
> [master] Bug 559896: pingSQL is incorrect for DB2ZPlatform

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/DB2ZPlatform.java
> [2.7] Bug 559896: pingSQL is incorrect for DB2ZPlatform

- .travis.yml
> [2.7] Reflect Travis-CI Maven upgrade to 3.6.3

- .travis.yml
> Reflect Travis-CI Maven upgrade to 3.6.3

- foundation/org.eclipse.persistence.core/resource/org/eclipse/persistence/internal/helper/VendorNameToPlatformMapping.properties
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/Oracle19Platform.java
- foundation/org.eclipse.persistence.oracle/src/org/eclipse/persistence/platform/database/oracle/Oracle19Platform.java
Bug 548814 - EL not Auto Detecting Oracle 19C
Added support for Oracle19C
> [2.6_WAS] Bug548814 : EL not Auto Detecting Oracle 19C

- foundation/org.eclipse.persistence.core/resource/org/eclipse/persistence/internal/helper/VendorNameToPlatformMapping.properties
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/Oracle19Platform.java
- foundation/org.eclipse.persistence.oracle/src/org/eclipse/persistence/platform/database/oracle/Oracle19Platform.java
Bug 548814 - EL not Auto Detecting Oracle 19C
Added support for Oracle19C
> [2.7] https://github.com/jgrassel/eclipselink/pull/new/Bug548814_2.7

- buildsystem/mavenize/test.properties/el-test.pgsql.properties
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/PostgreSQLPlatform.java
- pom.xml
Bug fix and new Maven PostgreSQL profile to test it
> [master] Bug 537657 - Inserting empty or null varchar arrays doesn't work with PostgreSQL since driver version 42.2.4

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/queries/ReportQuery.java
- jpa/eclipselink.jpa.test/src/it/java/org/eclipse/persistence/testing/tests/jpa/FullRegressionTestSuite.java
- jpa/eclipselink.jpa.test/src/it/java/org/eclipse/persistence/testing/tests/jpa/datatypes/BooleanJUnitTestCase.java
Bug fix and unit test for #716
> [master] Bug fix - Missing data in Query result when selecting single boolean field. #716

- .travis.yml
Additional test to verify/generate Javadoc by oss-release profile.
> [master] Travis-CI Javadoc test

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/queries/ReportQuery.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa/FullRegressionTestSuite.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa/datatypes/BooleanJUnitTestCase.java
Bug fix and unit test for #716
> [2.7] Missing data in Query result when selecting single boolean field.

- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/tests/unitofwork/NestedUnitOfWorkDeleteFromNestedObjectTest.java
- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/tests/unitofwork/UnitOfWorkIsolatedAlwaysTestModel.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/sessions/MergeManager.java
> [2.7] Bugfix for #624 - New Object created and deleted in nested UnitOfWork is commited to DB

- foundation/eclipselink.core.test/src/it/java/org/eclipse/persistence/testing/tests/sessionsxml/SessionsXMLSchemaJavaLogTest.java
- foundation/eclipselink.core.test/src/test/java/org/eclipse/persistence/testing/tests/junit/localization/LocalizationTest.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/descriptors/ClassDescriptor.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/databaseaccess/DatasourceAccessor.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/localization/i18n/LoggingLocalizationResource.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/localization/i18n/TraceLocalizationResource.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/sessions/AbstractSession.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/sessions/DatabaseSessionImpl.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/tools/profiler/FetchGroupMonitor.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/tools/schemaframework/TableCreator.java
> [master] Minor logging improvements

- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/tests/junit/localization/LocalizationTest.java
- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/tests/sessionsxml/SessionsXMLSchemaJavaLogTest.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/descriptors/ClassDescriptor.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/databaseaccess/DatasourceAccessor.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/localization/i18n/LoggingLocalizationResource.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/localization/i18n/TraceLocalizationResource.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/sessions/AbstractSession.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/sessions/DatabaseSessionImpl.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/tools/profiler/FetchGroupMonitor.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/tools/schemaframework/TableCreator.java
> [2.7] Minor logging improvements

- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/tests/localization/LocalizationTest.java
- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/tests/sessionsxml/SessionsXMLSchemaJavaLogTest.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/descriptors/ClassDescriptor.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/databaseaccess/DatasourceAccessor.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/localization/i18n/LoggingLocalizationResource.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/localization/i18n/TraceLocalizationResource.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/sessions/AbstractSession.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/sessions/DatabaseSessionImpl.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/tools/profiler/FetchGroupMonitor.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/tools/schemaframework/TableCreator.java
> [2.6_WAS] Minor logging improvements

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/databaseaccess/DatabaseCall.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/databaseaccess/DatasourcePlatform.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/OraclePlatform.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/criteria/TestCriteriaBuilder.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/jpql/TestComplexJPQL.java
> [master] Bug 392762: Add Oracle support for IN Clause parameter limit

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/databaseaccess/DatabaseCall.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/databaseaccess/DatasourcePlatform.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/OraclePlatform.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/criteria/TestCriteriaBuilder.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/jpql/TestComplexJPQL.java
> [2.7] Bug 392762: Add Oracle support for IN Clause parameter limit

- pom.xml
> [master] ASM upgrade to 7.3.1

- foundation/org.eclipse.persistence.corba/pom.xml
- jpa/eclipselink.jpa.test/src/it/resources/eclipselink-advanced-field-access-model/osgi/persistence.xml
- jpa/eclipselink.jpa.test/src/it/resources/eclipselink-advanced-field-access-model/persistence.xml
- jpa/eclipselink.jpa.test/src/it/resources/eclipselink-advanced-field-access-model/server/persistence.xml
- jpa/eclipselink.jpa.test/src/it/resources/eclipselink-advanced-field-access-model/spring/persistence.xml
- jpa/eclipselink.jpa.test/src/it/resources/eclipselink-annotation-model/osgi/persistence.xml
- jpa/eclipselink.jpa.test/src/it/resources/eclipselink-annotation-model/persistence.xml
- jpa/eclipselink.jpa.test/src/it/resources/eclipselink-beanvalidation-dynamic-model/persistence.xml
- jpa/eclipselink.jpa.test/src/it/resources/eclipselink-beanvalidation-dynamic-model/server/persistence.xml
- jpa/eclipselink.jpa.test/src/it/resources/eclipselink-composite-advanced-model-member_2/persistence.xml
- jpa/eclipselink.jpa.test/src/it/resources/eclipselink-composite-advanced-model-member_3/persistence.xml
- jpa/eclipselink.jpa.test/src/it/resources/eclipselink-extensibility-model/repository/extension.properties
- jpa/eclipselink.jpa.test/src/it/resources/eclipselink-identity-model/persistence.xml
- jpa/eclipselink.jpa.test/src/it/resources/eclipselink-jpa21-model/persistence.xml
- jpa/eclipselink.jpa.test/src/it/resources/eclipselink-jpa21-model/server/persistence.xml
- jpa/eclipselink.jpa.test/src/it/resources/eclipselink-jpa22-model/persistence.xml
- jpa/eclipselink.jpa.test/src/it/resources/eclipselink-jpa22-model/server/persistence.xml
- jpa/eclipselink.jpa.test/src/it/resources/eclipselink-partitioned-model/persistence.xml
- jpa/eclipselink.jpa.test/src/it/resources/eclipselink-plsql-model/persistence.xml
- jpa/eclipselink.jpa.test/src/it/resources/eclipselink-xml-composite-advanced-model-member_2/persistence.xml
- jpa/eclipselink.jpa.test/src/it/resources/eclipselink-xml-composite-advanced-model-member_3/persistence.xml
- jpa/eclipselink.jpa.test/src/it/resources/eclipselinkorm/eclipselink-xml-extended-composite-advanced-model-member_2/persistence.xml
- jpa/eclipselink.jpa.test/src/it/resources/eclipselinkorm/eclipselink-xml-extended-composite-advanced-model-member_3/persistence.xml
> Make JPA LRG Green again

- bundles/distribution/pom.xml
- bundles/eclipselink/pom.xml
- bundles/others/pom.xml
- bundles/p2site/pom.xml
- foundation/org.eclipse.persistence.core.test.framework/pom.xml
- foundation/org.eclipse.persistence.core/pom.xml
- jpa/eclipselink.jpars.test/pom.xml
- jpa/org.eclipse.persistence.jpa.jpql/pom.xml
- jpa/org.eclipse.persistence.jpa.test.framework/pom.xml
- jpa/org.eclipse.persistence.jpa/pom.xml
- pom.xml
> remove dependency on old (javax) non-jakarta jpa artifacts

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/mappings/OneToOneMapping.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/TestAggregateObjectMappings.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/model/BaseChild.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/model/BaseEmbeddable.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/model/BaseParent.java
> [2.6_WAS] Bug 561664: JoinColumn with same name and referencedColumnName throws exception

- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/TestAggregateObjectMappings.java
for #757 
I forgot to include a change in the JSE tests
> [2.6_WAS] Bug 561664: fix for jse tests

- etc/jenkins/tck.groovy
- etc/jenkins/tck_init.sh
- etc/jenkins/tck_run.sh
Content of https://ci.eclipse.org/eclipselink/job/eclipselink-tck-run/
> Added JPA TCK test scripts.

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/mappings/OneToOneMapping.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/mapping/TestAggregateObjectMappings.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/mapping/model/BaseChild.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/mapping/model/BaseEmbeddable.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/mapping/model/BaseParent.java
> [master] Bug 561664: JoinColumn with same name and referencedColumnName throws exception

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/mappings/OneToOneMapping.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/TestAggregateObjectMappings.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/model/BaseChild.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/model/BaseEmbeddable.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/model/BaseParent.java
> [2.7] Bug 561664: JoinColumn with same name and referencedColumnName throws exception

- .travis.yml
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/oxm/XPathObjectBuilder.java
- moxy/org.eclipse.persistence.moxy/src/main/java/org/eclipse/persistence/jaxb/compiler/AnnotationsProcessor.java
- moxy/org.eclipse.persistence.moxy/src/main/java/org/eclipse/persistence/jaxb/compiler/CompilerHelper.java
- moxy/org.eclipse.persistence.moxy/src/test/java/org/eclipse/persistence/testing/jaxb/annotations/xmlaccessorfactory/ClassLevelAccessorFactory.java
- moxy/org.eclipse.persistence.moxy/src/test/java/org/eclipse/persistence/testing/jaxb/annotations/xmlaccessorfactory/CustomerClassOverride.java
- moxy/org.eclipse.persistence.moxy/src/test/java/org/eclipse/persistence/testing/jaxb/annotations/xmlaccessorfactory/MyCustomAccessorFactory.java
- moxy/org.eclipse.persistence.moxy/src/test/java/org/eclipse/persistence/testing/jaxb/annotations/xmlaccessorfactory/package-info.java
- moxy/org.eclipse.persistence.moxy/src/test/java/org/eclipse/persistence/testing/jaxb/cycle/Employee.java
- moxy/org.eclipse.persistence.moxy/src/test/java/org/eclipse/persistence/testing/jaxb/sun/idresolver/NonELIDResolver.java
- moxy/org.eclipse.persistence.moxy/src/test/java/org/eclipse/persistence/testing/jaxb/sun/idresolver/collection/NonELIDResolver.java
- moxy/org.eclipse.persistence.moxy/src/test/java/org/eclipse/persistence/testing/jaxb/sun/prefixmapper/NonELPrefixMapperSuperClass.java
- pom.xml
> Integrate jaxb-impl 3.0.0-M2

- foundation/eclipselink.core.test/src/it/java/org/eclipse/persistence/testing/tests/classpath/DeploymentXMLXDBEISDependencyTest.java
> missed move to jakarta

- pom.xml
- utils/org.eclipse.persistence.dbws.builder/pom.xml
> Integrate jaxws-ri 3.0.0-M1 (for tests)

- etc/jenkins/build.groovy
> Jenkins pipeline at Eclipse.org - resources increase

- bundles/distribution/pom.xml
This is fix for integration tests.
> [master] Distribution module - unpack phase change

- etc/jenkins/tck_init.sh
Running TCK witn 3.0.0-M1: https://ci.eclipse.org/eclipselink/job/eclipselink-tck-run/48/console
> TCK test job: Eclipselink download changed.

- pom.xml
> [master] ASM upgrade 7.3.1 -> 8.0.1 (new CQ #22146)

- .travis.yml
- etc/jenkins/test_server.sh
There is temporary server tests deactivation until JEE server with "Jakarta" packages will be available.
> [master] Jenkins build - server test deactivation

- foundation/org.eclipse.persistence.core/pom.xml
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/oxm/CycleRecoverableContextProxy.java
- moxy/org.eclipse.persistence.moxy/pom.xml
- moxy/org.eclipse.persistence.moxy/src/main/java/org/eclipse/persistence/jaxb/JAXBContext.java
- moxy/org.eclipse.persistence.moxy/src/main/java/org/eclipse/persistence/jaxb/JAXBMarshaller.java
- moxy/org.eclipse.persistence.moxy/src/main/java/org/eclipse/persistence/jaxb/JAXBUnmarshaller.java
- moxy/org.eclipse.persistence.moxy/src/main/java/org/eclipse/persistence/jaxb/compiler/AnnotationsProcessor.java
- moxy/org.eclipse.persistence.moxy/src/main/java/org/eclipse/persistence/jaxb/compiler/CompilerHelper.java
- moxy/org.eclipse.persistence.moxy/src/test/java/org/eclipse/persistence/testing/jaxb/annotations/xmlaccessorfactory/XmlAccessorFactorySupportTestCases.java
- moxy/org.eclipse.persistence.moxy/src/test/java/org/eclipse/persistence/testing/jaxb/cycle/CycleRecoverableTestCases.java
- moxy/org.eclipse.persistence.moxy/src/test/java/org/eclipse/persistence/testing/jaxb/listofobjects/ns/MapNamespaceTestCases.java
- moxy/org.eclipse.persistence.moxy/src/test/java/org/eclipse/persistence/testing/jaxb/properties/PropertyTestCases.java
- moxy/org.eclipse.persistence.moxy/src/test/java/org/eclipse/persistence/testing/jaxb/sun/charescape/AbstractNonELCharacterEscapeHandler.java
- moxy/org.eclipse.persistence.moxy/src/test/java/org/eclipse/persistence/testing/jaxb/sun/charescape/NonELCharacterEscapeHandlerTestCases.java
- moxy/org.eclipse.persistence.moxy/src/test/java/org/eclipse/persistence/testing/jaxb/sun/idresolver/NonELIDResolverTestCases.java
- moxy/org.eclipse.persistence.moxy/src/test/java/org/eclipse/persistence/testing/jaxb/sun/idresolver/collection/NonELIDResolverTestCases.java
- moxy/org.eclipse.persistence.moxy/src/test/java/org/eclipse/persistence/testing/jaxb/sun/prefixmapper/NonELPrefixMapperTestCases.java
- moxy/org.eclipse.persistence.moxy/src/test/java/org/eclipse/persistence/testing/jaxb/sun/xmllocation/Data.java
- moxy/org.eclipse.persistence.moxy/src/test/java/org/eclipse/persistence/testing/jaxb/sun/xmllocation/DataError.java
- moxy/org.eclipse.persistence.moxy/src/test/java/org/eclipse/persistence/testing/jaxb/sun/xmllocation/DataNT.java
- moxy/org.eclipse.persistence.moxy/src/test/java/org/eclipse/persistence/testing/jaxb/sun/xmllocation/SubData.java
- moxy/org.eclipse.persistence.moxy/src/test/java/org/eclipse/persistence/testing/jaxb/sun/xmllocation/SubDataNT.java
- moxy/org.eclipse.persistence.moxy/src/test/java/org/eclipse/persistence/testing/jaxb/xmlmarshaller/MarshallerPropertiesTestCases.java
- moxy/org.eclipse.persistence.moxy/src/test/java/org/eclipse/persistence/testing/jaxb/xmlmarshaller/XMLDeclarationTestCases.java
- pom.xml
> Integrate jaxb-ri 3.0.0-M3

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/sessions/cdi/InjectionManagerImpl.java
Signed-off-by: s.niel@everwin.fr <s.niel@everwin.fr>
> Bug 563264: tomcat jndi expected is java:comp/env/BeanManager (#792)

- .travis.yml
- antbuild.properties
- antbuild.xml
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/descriptors/CMPPolicy.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/descriptors/ClassDescriptor.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/queries/DatasourceCallQueryMechanism.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/queries/ExpressionQueryMechanism.java
- jpa/eclipselink.jpa.test.jse/antbuild.xml
- jpa/eclipselink.jpa.test.jse/src/META-INF/persistence.xml
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/property/model/AbstractParent.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/property/model/Child.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/property/model/Parent.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/returninsert/TestReturnInsert.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/returninsert/model/ReturnInsertDetail.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/returninsert/model/ReturnInsertDetailEmbedded.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/returninsert/model/ReturnInsertDetailEmbeddedEmbedded.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/returninsert/model/ReturnInsertDetailPK.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/returninsert/model/ReturnInsertDetailParent.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/returninsert/model/ReturnInsertMaster.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/returninsert/model/ReturnInsertMasterPK.java
Bugfix for #709 + test
Backport from master and 2.7
> [2.6] EclipseLink doesn't update field marked with @ReturnInsert annotation of composite Id marked with @Embeddable + JPA.JSE test refresh

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/sessions/UnitOfWorkImpl.java
Signed-off-by: Ravi Babu Tummuru <ravi.babu.tummuru@oracle.com>
> BUG#562811 - HEAP DUMP HAS LARGE SIZED ECLIPSELINK REPEATABLEWRITEUNI

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/queries/ExpressionQueryMechanism.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/returninsert/TestReturnInsert.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/returninsert/model/ReturnInsertDetailJoined.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/returninsert/model/ReturnInsertMasterJoined.java
- jpa/eclipselink.jpa.test.jse/src/it/resources/META-INF/persistence.xml
> EclipseLink doesn't generate SQL INSERT correctly if @ReturnInsert if used in InheritanceType.JOINED

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/oxm/record/UnmarshalRecordImpl.java
- moxy/org.eclipse.persistence.moxy/src/test/java/org/eclipse/persistence/testing/jaxb/xmlelement/nulls/NullTestCases.java
- moxy/org.eclipse.persistence.moxy/src/test/java/org/eclipse/persistence/testing/jaxb/xmlelement/nulls/Root.java
> Bugfix MOXy 561757 unmarshalling JSON null value ignored in the payload

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/oxm/record/UnmarshalRecordImpl.java
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/xmlelement/nulls/NullTestCases.java
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/xmlelement/nulls/Root.java
> [2.6] Bugfix MOXy 561757 unmarshalling JSON null value ignored in the payload

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/oxm/record/UnmarshalRecordImpl.java
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/xmlelement/nulls/NullTestCases.java
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/xmlelement/nulls/Root.java
> [2.7] Bugfix MOXy 561757 unmarshalling JSON null value ignored in the payload

- etc/jenkins/build.groovy
> Jenkins build resources increase

- etc/jenkins/build.groovy
- etc/jenkins/release.groovy
- etc/jenkins/tck.groovy
This is change based on recommendations from https://bugs.eclipse.org/bugs/show_bug.cgi?id=564240 .
It improves build time and stability at https://ci.eclipse.org/eclipselink .
> [master] Jenkins build resources change

- foundation/org.eclipse.persistence.core/resource/org/eclipse/persistence/internal/helper/VendorNameToPlatformMapping.properties
- foundation/org.eclipse.persistence.oracle/src/org/eclipse/persistence/platform/database/oracle/Oracle18Platform.java
- foundation/org.eclipse.persistence.oracle/src/org/eclipse/persistence/platform/database/oracle/Oracle19Platform.java
Signed-off-by: Lalitha Ananda <lalitha.ananda@oracle.com>
> [2.6] This is bugfix for 548814 - backport from master

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/oxm/record/DOMReader.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/oxm/record/DOMUnmarshaller.java
#870
Reviewed-by: Roman, Ondra
> [2.6_WAS] Bug 515563: Eclipselink refers to internal api

- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/metadata/accessors/objects/MetadataAsmFactory.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/weaving/ClassWeaver.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/weaving/MethodWeaver.java
for #877
Similar change as per #805
> [master] Update ASM 8.0.1 change to enable Eclipselink to use ASM8

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/DerbyPlatform.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/criteria/TestCoalesceFunction.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/criteria/model/CoalesceEntity.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/criteria/model/CoalesceEntity_.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/querydef/CriteriaBuilderImpl.java
> [master] Bug 341074: CriteriaBuilder coalesce ClassCastException using literals

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/DerbyPlatform.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/criteria/TestCoalesceFunction.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/criteria/model/CoalesceEntity.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/criteria/model/CoalesceEntity_.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/querydef/CriteriaBuilderImpl.java
> [2.7] Bug 341074: CriteriaBuilder coalesce ClassCastException using literals

- utils/eclipselink.dbws.builder.test.oracle/pom.xml
Maven build - org.eclipse.persistence.dbws.builder.oracle.test tests fix
> [master] Maven build - org.eclipse.persistence.dbws.builder.oracle.test tests fix

- pom.xml
> add missing entries to project pom

- etc/jenkins/release.sh
This is fix for EclipseLink 3.0.x release job. It's related with Oracle previous dependencies changes.
> [master] Release script fix.

- pom.xml
> pom_oracle_test_server.xml included as a module due a versions-maven-plugin set version operation.

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/databaseaccess/DatabaseCall.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/databaseaccess/DatasourcePlatform.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/OraclePlatform.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/criteria/TestCriteriaBuilder.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/jpql/TestComplexJPQL.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa/criteria/AdvancedCriteriaQueryTestSuite.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/querydef/ExpressionImpl.java
for #628
In order to add this support, 2.6_WAS needs Bug 349477 backported and is added in the commits
> [2.6_WAS] Bug 392762: Add Oracle support for IN Clause parameter limit

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/mappings/AggregateCollectionMapping.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/TestAttributeOverride.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/model/OverrideEmbeddableA.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/model/OverrideEmbeddableB.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/model/OverrideEntityA.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/model/OverrideEntityB.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/model/OverrideNestedEmbeddableB.java
> [2.6_WAS] Bug 564260: ElementCollection lowercase AttributeOverride is ignored

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/mappings/AggregateCollectionMapping.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/TestAttributeOverride.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/model/OverrideEmbeddableA.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/model/OverrideEmbeddableB.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/model/OverrideEntityA.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/model/OverrideEntityB.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/mapping/model/OverrideNestedEmbeddableB.java
> [2.7] Bug 564260: ElementCollection lowercase AttributeOverride is ignored

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/expressions/ExpressionOperator.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/jpql/TestCoalesceFunction.java
> [2.6_WAS] Bug 567087: Minor fix to whitespace characters used in COALESCE function

- pom.xml
> Oracle DDL Parser upgrade to 3.0.0-M1

- moxy/org.eclipse.persistence.moxy/src/test/resources/org/eclipse/persistence/testing/jaxb/beanvalidation/sgen_xjc/customized_schema.xsd
- moxy/org.eclipse.persistence.moxy/src/test/resources/org/eclipse/persistence/testing/jaxb/dynamic/bindings.xjb
- moxy/org.eclipse.persistence.moxy/src/test/resources/org/eclipse/persistence/testing/jaxb/dynamic/bindings2.xjb
- moxy/org.eclipse.persistence.moxy/src/test/resources/org/eclipse/persistence/testing/jaxb/dynamic/contextcreation2.xsd
- moxy/org.eclipse.persistence.moxy/src/test/resources/org/eclipse/persistence/testing/jaxb/dynamic/jaxbcustom.xsd
- moxy/org.eclipse.persistence.moxy/src/test/resources/org/eclipse/persistence/testing/oxm/xmlmarshaller/Employee_Choice.xsd
- moxy/org.eclipse.persistence.moxy/src/test/resources/org/eclipse/persistence/testing/oxm/xmlmarshaller/Employee_Group.xsd
- moxy/org.eclipse.persistence.moxy/src/test/resources/org/eclipse/persistence/testing/oxm/xmlmarshaller/Employee_Group_NestedGroup.xsd
- moxy/org.eclipse.persistence.moxy/src/test/resources/org/eclipse/persistence/testing/oxm/xmlmarshaller/Employee_Group_NestedSequence.xsd
- moxy/org.eclipse.persistence.moxy/src/test/resources/org/eclipse/persistence/testing/oxm/xmlmarshaller/Employee_Sequence.xsd
- moxy/org.eclipse.persistence.moxy/src/test/resources/org/eclipse/persistence/testing/oxm/xmlmarshaller/Employee_Sequence_NestedGroup.xsd
- pom.xml
> Intergate latest dependencies

- bundles/moxy-standalone/pom.xml
- bundles/moxy-standalone/src/main/assembly/moxy.xml
- bundles/moxy-standalone/src/main/scripts/jaxb-compiler.cmd
- bundles/moxy-standalone/src/main/scripts/jaxb-compiler.sh
- bundles/pom.xml
> standalone moxy distribution

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/expressions/ExpressionOperator.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/jpql/TestCoalesceFunction.java
> [master] Bug 567087: Minor fix to whitespace characters used in COALESCE function

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/expressions/ExpressionOperator.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/jpql/TestCoalesceFunction.java
> [2.7] Bug 567087: Minor fix to whitespace characters used in COALESCE function

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/sessions/CollectionChangeRecord.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/models/jpa/advanced/AdvancedTableCreator.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/models/jpa/advanced/ConcreteJob.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/models/jpa/advanced/Event.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/models/jpa/advanced/Job.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa/advanced/EntityManagerJUnitTestSuite.java
for #904
Reviewed-by: Tomask, DmitryK
> [2.6_WAS] Bug 463350: java.util.ConcurrentModificationException

- .travis.yml
- foundation/eclipselink.core.test/pom.xml
- foundation/org.eclipse.persistence.corba/pom.xml
- jpa/eclipselink.jpa.test/src/it/assembly/eclipselink-advanced-field-access-model.xml
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/metadata/accessors/objects/MetadataAsmFactory.java
- pom.xml
- utils/eclipselink.dbws.builder.test.oracle/src/it/java/dbws/testing/shadowddlgeneration/oldjpub/PublisherModifier.java
- utils/eclipselink.dbws.builder.test.oracle/src/it/java/dbws/testing/shadowddlgeneration/oldjpub/SqlStmtType.java
and move travis from jdk14 to jdk15
> update dependencies, build plugins

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/descriptors/changetracking/AttributeChangeListener.java
This reverts commit 1b94ba6ae84d5636656b25b1a94942d3e17f84a7.
Open Liberty JPA Relationship tests using Eclipselink 3.0 on Open Liberty began failing randomly after moving to a commit after M-1, with a NPE:
```
java.lang.NullPointerException
at org.eclipse.persistence.mappings.foundation.AbstractDirectMapping.updateChangeRecord(AbstractDirectMapping.java:1163)
at org.eclipse.persistence.internal.descriptors.changetracking.AttributeChangeListener.internalPropertyChange(AttributeChangeListener.java:162)
at org.eclipse.persistence.internal.descriptors.changetracking.AttributeChangeListener.propertyChange(AttributeChangeListener.java:115)
at com.ibm.ws.jpa.fvt.relationships.manyXmany.entities.bi.annotation.MMBiEntA._persistence_propertyChange(MMBiEntA.java)
```
The NPE was a result of …
> [Master] Revert "Change UoW reference to WeakReference for GC"

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/queries/ReportQueryResult.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/query/TestQueryCase.java
> [master] Bug 567891: Boolean literals are replaced with Integer values in CASE queries

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/config/PersistenceUnitProperties.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/queries/ReportQuery.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/queries/ReportQueryResult.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/sessions/Project.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/query/TestQueryCase.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/EntityManagerSetupImpl.java
> [2.6_WAS] Bug 567891: Boolean literals are replaced with Integer values in CASE queries

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/config/PersistenceUnitProperties.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/queries/ReportQueryResult.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/sessions/Project.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/query/TestQueryCase.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/EntityManagerSetupImpl.java
> [2.7] Bug 567891: Boolean literals are replaced with Integer values in CASE queries

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/H2Platform.java
> [master] Bugfix for stored procedures call in H2 database

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/H2Platform.java
> [2.7] Bugfix for stored procedures call in H2 database - backport from master

- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/metadata/accessors/objects/MetadataAsmFactory.java
> first exception when reading a class file should be a warning

- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/metadata/accessors/objects/MetadataAsmFactory.java
> [2.7] first exception when reading a class file should be a warning (#948)

- etc/jenkins/includes/maven.incl.sh
- etc/jenkins/includes/nexus.incl.sh
- etc/jenkins/release.groovy
- etc/jenkins/release.sh
- pom.xml
> Jenkins release job improvement and Oracle DDL parser version upgrade

- pom.xml
> [master] Dependencies upgrade

- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/conversion/TestJavaTimeTypeConverter.java
> fix failing time conversion test

- pom.xml
> Integrate jaxb-ri/jaxws-ri 3.0.0

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/mappings/AggregateCollectionMapping.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/mapping/TestAttributeOverride.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/mapping/model/OverrideEmbeddableA.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/mapping/model/OverrideEmbeddableB.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/mapping/model/OverrideEntityA.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/mapping/model/OverrideEntityB.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/mapping/model/OverrideNestedEmbeddableB.java
> [master] Bug 564260: ElementCollection lowercase AttributeOverride is ignored

- bundles/eclipselink/pom.xml
- bundles/eclipselink/src/main/assembly/eclipselink.zip.xml
> include nosql in distribution zip

- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/modelgen/TestProcessor.java
- jpa/org.eclipse.persistence.jpa.modelgen/src/org/eclipse/persistence/internal/jpa/modelgen/visitors/AnnotationValueVisitor.java
- jpa/org.eclipse.persistence.jpa.modelgen/src/org/eclipse/persistence/internal/jpa/modelgen/visitors/ElementVisitor.java
- jpa/org.eclipse.persistence.jpa.modelgen/src/org/eclipse/persistence/internal/jpa/modelgen/visitors/TypeVisitor.java
> [2.7]Fix #595: annotations with ElementType.TYPE_USE are not handled properly (#597)

- etc/jenkins/includes/maven.incl.sh
- pom_oracle_test_server.xml
- pom_test_server.xml
This is fix of current broken build and release script which didn't included into git commit all modified POM files (pom_oracle_test_server.xml and pom_test_server.xml)
> [master] Maven build fix and release script fix.

- pom.xml
> Integrate glassfish-corba 4.2.3

- pom.xml
> Integrate weld 4.0.0.CR1

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/mappings/AggregateCollectionMapping.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/embeddable/TestCollectionTableEmbeddable.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/embeddable/model/ElementCollectionEmbeddableTemporal.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/embeddable/model/ElementCollectionEntity.java
> [master] Bug 570378: NullPointerException from MapKey Temporals

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/mappings/AggregateCollectionMapping.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/embeddable/TestCollectionTableEmbeddable.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/embeddable/model/ElementCollectionEmbeddableTemporal.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/embeddable/model/ElementCollectionEntity.java
> [2.7] Bug 570378: NullPointerException from MapKey Temporals

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/mappings/AggregateCollectionMapping.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/embeddable/TestCollectionTableEmbeddable.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/embeddable/model/ElementCollectionEmbeddableTemporal.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/embeddable/model/ElementCollectionEntity.java
> [2.6_WAS] Bug 570378: NullPointerException from MapKey Temporals

- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/EntityManagerSetupImpl.java
> [master] Add 'eclipselink.target-database-properties' as a System Property

- pom.xml
> [master] Maven build - plugins and dependencies update

- bundles/eclipselink/src/main/scripts/bin/jaxb-compiler.cmd
- bundles/eclipselink/src/main/scripts/bin/jaxb-compiler.sh
- bundles/moxy-standalone/src/main/scripts/jaxb-compiler.cmd
- bundles/moxy-standalone/src/main/scripts/jaxb-compiler.sh
- bundles/moxy-standalone/src/main/scripts/setenv.cmd
- bundles/moxy-standalone/src/main/scripts/setenv.sh
> #1021: jaxb-compiler command fails to find jaxb implementation

- moxy/org.eclipse.persistence.moxy/src/main/java/org/eclipse/persistence/jaxb/compiler/MappingsGenerator.java
- moxy/org.eclipse.persistence.moxy/src/test/java/org/eclipse/persistence/testing/jaxb/binder/nullpolicy/BinderWithNullPolicyTestCases.java
- moxy/org.eclipse.persistence.moxy/src/test/java/org/eclipse/persistence/testing/jaxb/binder/nullpolicy/EmployeeA.java
- moxy/org.eclipse.persistence.moxy/src/test/java/org/eclipse/persistence/testing/jaxb/binder/nullpolicy/EmployeeB.java
- moxy/org.eclipse.persistence.moxy/src/test/java/org/eclipse/persistence/testing/jaxb/binder/nullpolicy/EmployeeC.java
- moxy/org.eclipse.persistence.moxy/src/test/java/org/eclipse/persistence/testing/jaxb/binder/nullpolicy/Gender.java
- moxy/org.eclipse.persistence.moxy/src/test/resources/org/eclipse/persistence/testing/jaxb/binder/nullpolicy/emptynode.xml
- moxy/org.eclipse.persistence.moxy/src/test/resources/org/eclipse/persistence/testing/jaxb/binder/nullpolicy/nilwithvalue.xml
- moxy/org.eclipse.persistence.moxy/src/test/resources/org/eclipse/persistence/testing/jaxb/binder/nullpolicy/xsinil.xml
> [master] MOXy @XmlNullPolicy not working with enums

- moxy/eclipselink.moxy.test/resource/org/eclipse/persistence/testing/jaxb/binder/nullpolicy/emptynode.xml
- moxy/eclipselink.moxy.test/resource/org/eclipse/persistence/testing/jaxb/binder/nullpolicy/nilwithvalue.xml
- moxy/eclipselink.moxy.test/resource/org/eclipse/persistence/testing/jaxb/binder/nullpolicy/xsinil.xml
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/binder/nullpolicy/BinderWithNullPolicyTestCases.java
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/binder/nullpolicy/EmployeeA.java
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/binder/nullpolicy/EmployeeB.java
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/binder/nullpolicy/EmployeeC.java
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/binder/nullpolicy/Gender.java
- moxy/org.eclipse.persistence.moxy/src/org/eclipse/persistence/jaxb/compiler/MappingsGenerator.java
> [2.7] MOXy @XmlNullPolicy not working with enums - backport from master

- moxy/eclipselink.moxy.test/resource/org/eclipse/persistence/testing/jaxb/binder/nullpolicy/emptynode.xml
- moxy/eclipselink.moxy.test/resource/org/eclipse/persistence/testing/jaxb/binder/nullpolicy/nilwithvalue.xml
- moxy/eclipselink.moxy.test/resource/org/eclipse/persistence/testing/jaxb/binder/nullpolicy/xsinil.xml
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/binder/nullpolicy/BinderWithNullPolicyTestCases.java
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/binder/nullpolicy/EmployeeA.java
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/binder/nullpolicy/EmployeeB.java
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/binder/nullpolicy/EmployeeC.java
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/binder/nullpolicy/Gender.java
- moxy/org.eclipse.persistence.moxy/src/org/eclipse/persistence/jaxb/compiler/MappingsGenerator.java
> [2.6] MOXy @XmlNullPolicy not working with enums - backport from master

- etc/jenkins/build.groovy
- etc/jenkins/release.groovy
- etc/jenkins/tck.groovy
There some UID change to reflect changes at https://ci.eclipse.org/eclipselink .
> [master] Jenkins build fix

- etc/jenkins/build.groovy
- etc/jenkins/promote.groovy
There some UID change to reflect changes at https://ci.eclipse.org/eclipselink .
> [2.7] Jenkins build fix

- etc/jenkins/build.groovy
- etc/jenkins/promote.groovy
There some UID change to reflect changes at https://ci.eclipse.org/eclipselink .
> [2.6] Jenkins build fix

- pom.xml
Most dependencies are in staging, some of them (JAXB Impl) are in progress now.
> [master] Jakarta dependencies upgrade from EE 9.0.1

- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/criteria/TestCriteriaBuilder.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/querydef/AbstractQueryImpl.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/querydef/CriteriaQueryImpl.java
> [master] Bug 571794: Enable Input parameters for Criteria API SELECT clause

- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/criteria/TestCriteriaBuilder.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/querydef/AbstractQueryImpl.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/querydef/CriteriaQueryImpl.java
> [3.0] Bug 571794: Enable Input parameters for Criteria API SELECT clause

- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/criteria/TestCriteriaBuilder.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/querydef/AbstractQueryImpl.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/querydef/CriteriaQueryImpl.java
> [2.6_WAS] Bug 571794: Enable Input parameters for Criteria API SELECT clause

- pom.xml
Dynamic change based on regex evaluation of project.version property.
(cherry picked from commit e6e2053029996958a4f7a646f757cfc95923e5c2)
> [3.0] Maven build - release version property change to reflect project.version Maven property - backport from master

- moxy/org.eclipse.persistence.moxy/src/main/java/org/eclipse/persistence/jaxb/plugins/BeanValidationPlugin.java
> avoid using xsom impl classes

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/jpa/jpql/EclipseLinkSemanticValidatorHelper.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/embeddable/TestCollectionTableEmbeddable.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/embeddable/TestEmbeddable.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/embeddable/TestNestedEmbeddable.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/embeddable/model/SpecAddress.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/embeddable/model/SpecContactInfo.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/embeddable/model/SpecEmployee.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/embeddable/model/SpecPhone.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa/jpql/JUnitJPQLValidationTestSuite.java
- jpa/org.eclipse.persistence.jpa.jpql.test/src/org/eclipse/persistence/jpa/tests/jpql/tools/spi/java/AbstractMapping.java
- jpa/org.eclipse.persistence.jpa.jpql/src/org/eclipse/persistence/jpa/jpql/AbstractSemanticValidator.java
- jpa/org.eclipse.persistence.jpa.jpql/src/org/eclipse/persistence/jpa/jpql/SemanticValidatorHelper.java
- jpa/org.eclipse.persistence.jpa.jpql/src/org/eclipse/persistence/jpa/jpql/tools/GenericSemanticValidatorHelper.java
- jpa/org.eclipse.persistence.jpa.jpql/src/org/eclipse/persistence/jpa/jpql/tools/resolver/FromSubqueryResolver.java
- jpa/org.eclipse.persistence.jpa.jpql/src/org/eclipse/persistence/jpa/jpql/tools/spi/IMapping.java
> [2.6_WAS] Bug 570702: Add support for Embeddable fields as JOIN targets

- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/criteria/TestCriteriaBuilder.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/querydef/AbstractQueryImpl.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/querydef/CriteriaQueryImpl.java
> [2.7] Bug 571794: Enable Input parameters for Criteria API SELECT clause

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/jpa/jpql/EclipseLinkSemanticValidatorHelper.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/embeddable/TestCollectionTableEmbeddable.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/embeddable/TestEmbeddable.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/embeddable/TestNestedEmbeddable.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/embeddable/model/SpecAddress.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/embeddable/model/SpecContactInfo.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/embeddable/model/SpecEmployee.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/embeddable/model/SpecPhone.java
- jpa/eclipselink.jpa.test/src/it/java/org/eclipse/persistence/testing/tests/jpa/jpql/JUnitJPQLValidationTestSuite.java
- jpa/org.eclipse.persistence.jpa.jpql/src/main/java/org/eclipse/persistence/jpa/jpql/AbstractSemanticValidator.java
- jpa/org.eclipse.persistence.jpa.jpql/src/main/java/org/eclipse/persistence/jpa/jpql/SemanticValidatorHelper.java
- jpa/org.eclipse.persistence.jpa.jpql/src/main/java/org/eclipse/persistence/jpa/jpql/tools/GenericSemanticValidatorHelper.java
- jpa/org.eclipse.persistence.jpa.jpql/src/main/java/org/eclipse/persistence/jpa/jpql/tools/resolver/FromSubqueryResolver.java
- jpa/org.eclipse.persistence.jpa.jpql/src/main/java/org/eclipse/persistence/jpa/jpql/tools/spi/IMapping.java
- jpa/org.eclipse.persistence.jpa.jpql/src/test/java/org/eclipse/persistence/jpa/tests/jpql/tools/spi/java/AbstractMapping.java
> [master] Bug 570702: Add support for Embeddable fields as JOIN targets

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/jpa/jpql/EclipseLinkSemanticValidatorHelper.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/embeddable/TestCollectionTableEmbeddable.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/embeddable/TestEmbeddable.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/embeddable/TestNestedEmbeddable.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/embeddable/model/SpecAddress.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/embeddable/model/SpecContactInfo.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/embeddable/model/SpecEmployee.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/embeddable/model/SpecPhone.java
- jpa/eclipselink.jpa.test/src/it/java/org/eclipse/persistence/testing/tests/jpa/jpql/JUnitJPQLValidationTestSuite.java
- jpa/org.eclipse.persistence.jpa.jpql/src/main/java/org/eclipse/persistence/jpa/jpql/AbstractSemanticValidator.java
- jpa/org.eclipse.persistence.jpa.jpql/src/main/java/org/eclipse/persistence/jpa/jpql/SemanticValidatorHelper.java
- jpa/org.eclipse.persistence.jpa.jpql/src/main/java/org/eclipse/persistence/jpa/jpql/tools/GenericSemanticValidatorHelper.java
- jpa/org.eclipse.persistence.jpa.jpql/src/main/java/org/eclipse/persistence/jpa/jpql/tools/resolver/FromSubqueryResolver.java
- jpa/org.eclipse.persistence.jpa.jpql/src/main/java/org/eclipse/persistence/jpa/jpql/tools/spi/IMapping.java
- jpa/org.eclipse.persistence.jpa.jpql/src/test/java/org/eclipse/persistence/jpa/tests/jpql/tools/spi/java/AbstractMapping.java
> [3.0] Bug 570702: Add support for Embeddable fields as JOIN targets

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/jpa/jpql/EclipseLinkSemanticValidatorHelper.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/embeddable/TestCollectionTableEmbeddable.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/embeddable/TestEmbeddable.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/embeddable/TestNestedEmbeddable.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/embeddable/model/SpecAddress.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/embeddable/model/SpecContactInfo.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/embeddable/model/SpecEmployee.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/embeddable/model/SpecPhone.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa/jpql/JUnitJPQLValidationTestSuite.java
- jpa/org.eclipse.persistence.jpa.jpql.test/src/org/eclipse/persistence/jpa/tests/jpql/tools/spi/java/AbstractMapping.java
- jpa/org.eclipse.persistence.jpa.jpql/src/org/eclipse/persistence/jpa/jpql/AbstractSemanticValidator.java
- jpa/org.eclipse.persistence.jpa.jpql/src/org/eclipse/persistence/jpa/jpql/SemanticValidatorHelper.java
- jpa/org.eclipse.persistence.jpa.jpql/src/org/eclipse/persistence/jpa/jpql/tools/GenericSemanticValidatorHelper.java
- jpa/org.eclipse.persistence.jpa.jpql/src/org/eclipse/persistence/jpa/jpql/tools/resolver/FromSubqueryResolver.java
- jpa/org.eclipse.persistence.jpa.jpql/src/org/eclipse/persistence/jpa/jpql/tools/spi/IMapping.java
> [2.7] Bug 570702: Add support for Embeddable fields as JOIN targets

- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/basic/TestSessionCustomizer.java
- jpa/eclipselink.jpa.test/src/it/java/org/eclipse/persistence/testing/tests/jpa/advanced/EntityManagerJUnitTestSuite.java
- jpa/eclipselink.jpa.test/src/it/java/org/eclipse/persistence/testing/tests/jpa/composite/advanced/EntityManagerJUnitTestSuite.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/jpa/JpaEntityManager.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/jpa/JpaEntityManagerFactory.java
> [3.0] Fixes #1069: let JpaEntityManager(Factory) extend AutoCloseable (#1077)

- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/basic/TestSessionCustomizer.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa/advanced/EntityManagerJUnitTestSuite.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa/composite/advanced/EntityManagerJUnitTestSuite.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/jpa/JpaEntityManager.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/jpa/JpaEntityManagerFactory.java
> [2.7] Fixes #1069: let JpaEntityManager(Factory) extend AutoCloseable (#1077)

- etc/jenkins/build_asm.sh
- etc/jenkins/release_asm.sh
Execution flag and staging artifacts overwrite condition.
> [master] Jenkins build - ASM build and release scripts minor fix

- pom.xml
> Integrate eclipselink asm 9.1.0

- foundation/org.eclipse.persistence.core.test.framework/src/main/java/org/eclipse/persistence/testing/framework/SessionEventTracker.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/expressions/Expression.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/expressions/ExpressionOperator.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/sessions/AbstractSession.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/DB2Platform.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/sessions/SessionEvent.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/sessions/SessionEventAdapter.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/sessions/SessionEventListener.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/sessions/SessionEventManager.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/framework/EmfRunnerInjector.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/framework/SQLCallListener.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/query/TestTrimFunction.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/query/model/TrimEntity.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/query/model/TrimEntity_.java
> [master] Bug 573094: TRIM function generates incorrect SQL for CriteriaBuilder

- foundation/org.eclipse.persistence.core.test.framework/src/main/java/org/eclipse/persistence/testing/framework/SessionEventTracker.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/expressions/Expression.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/expressions/ExpressionOperator.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/sessions/AbstractSession.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/DB2Platform.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/sessions/SessionEvent.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/sessions/SessionEventAdapter.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/sessions/SessionEventListener.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/sessions/SessionEventManager.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/framework/EmfRunnerInjector.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/framework/SQLCallListener.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/query/TestTrimFunction.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/query/model/TrimEntity.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/query/model/TrimEntity_.java
> [3.0] Bug 573094: TRIM function generates incorrect SQL for CriteriaBuilder

- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/framework/SessionEventTracker.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/expressions/Expression.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/expressions/ExpressionOperator.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/sessions/AbstractSession.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/DB2Platform.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/sessions/SessionEvent.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/sessions/SessionEventAdapter.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/sessions/SessionEventListener.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/sessions/SessionEventManager.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/framework/EmfRunnerInjector.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/framework/SQLCallListener.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/query/TestTrimFunction.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/query/model/TrimEntity.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/query/model/TrimEntity_.java
> [2.7] Bug 573094: TRIM function generates incorrect SQL for CriteriaBuilder

- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/framework/SessionEventTracker.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/expressions/Expression.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/expressions/ExpressionOperator.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/sessions/AbstractSession.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/DB2Platform.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/sessions/SessionEvent.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/sessions/SessionEventAdapter.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/sessions/SessionEventListener.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/sessions/SessionEventManager.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/framework/EmfRunnerInjector.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/framework/SQLCallListener.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/query/TestTrimFunction.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/query/model/TrimEntity.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/query/model/TrimEntity_.java
> [2.6_WAS] Bug 573094: TRIM function generates incorrect SQL for CriteriaBuilder

- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/query/TestSimpleQuery.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/query/model/SimpleQueryEntity.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/query/model/SimpleQueryEntity_.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/querydef/CriteriaQueryImpl.java
> [master] Bug 521402: Add support for Criteria queries with only literals

- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/query/TestSimpleQuery.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/query/model/SimpleQueryEntity.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/query/model/SimpleQueryEntity_.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/querydef/CriteriaQueryImpl.java
> [3.0] Bug 521402: Add support for Criteria queries with only literals

- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/query/TestSimpleQuery.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/query/model/SimpleQueryEntity.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/query/model/SimpleQueryEntity_.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/querydef/CriteriaQueryImpl.java
> [2.7] Bug 521402: Add support for Criteria queries with only literals

- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/query/TestSimpleQuery.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/query/model/SimpleQueryEntity.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/query/model/SimpleQueryEntity_.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/querydef/CriteriaQueryImpl.java
> [2.6_WAS] Bug 521402: Add support for Criteria queries with only literals

- foundation/eclipselink.core.test/src/it/java/org/eclipse/persistence/testing/models/mapping/Employee.java
- foundation/eclipselink.core.test/src/it/java/org/eclipse/persistence/testing/models/mapping/MappingProject.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/databaseaccess/DatasourcePlatform.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/helper/ConversionManager.java
- jpa/eclipselink.jpa.test/src/it/java/org/eclipse/persistence/testing/models/jpa/advanced/compositepk/CompositePKTableCreator.java
- jpa/eclipselink.jpa.test/src/it/java/org/eclipse/persistence/testing/models/jpa/advanced/derivedid/LackeyCrewMember.java
(cherry picked from commit 2bcbb67aee19cf172d1876ea0a4feb55b1135a93)
> [3.0] fix test failures for mysql driver 8.0.24 (#1108)

- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/models/mapping/Employee.java
- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/models/mapping/MappingProject.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/databaseaccess/DatasourcePlatform.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/helper/ConversionManager.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/models/jpa/advanced/compositepk/CompositePKTableCreator.java
- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/models/jpa/advanced/derivedid/LackeyCrewMember.java
(cherry picked from commit 2bcbb67aee19cf172d1876ea0a4feb55b1135a93)
> [2.7] fix test failures for mysql driver 8.0.24 (#1108)

- etc/jenkins/release.groovy
Missing OVERWRITE_GIT and OVERWRITE_STAGING parameters added.
> [master] Jenkins build - fix to release pipeline

- etc/jenkins/build.groovy
- etc/jenkins/release.groovy
- etc/jenkins/release.sh
> [3.0] Jenkins build - pipeline notifications and release script improvement

- jpa/org.eclipse.persistence.jpa.modelgen/src/main/java/org/eclipse/persistence/internal/jpa/modelgen/objects/PersistenceUnit.java
- jpa/org.eclipse.persistence.jpa.modelgen/src/test/java/org/eclipse/persistence/jpa/test/modelgen/TestProcessor.java
> eclipselink 3.0 JPA Modelgenerator does not recognize jakarta schemas

- etc/jenkins/release_asm.groovy
> [master] Jenkins ASM build - release pipeline fix

- jpa/org.eclipse.persistence.jpa.modelgen/src/main/java/org/eclipse/persistence/internal/jpa/modelgen/objects/PersistenceUnit.java
- jpa/org.eclipse.persistence.jpa.modelgen/src/test/java/org/eclipse/persistence/jpa/test/modelgen/TestProcessor.java
(cherry picked from commit 7f57042e34e65a5ad28acd14f9d8950cd37abe80)
> eclipselink 3.0 JPA Modelgenerator does not recognize jakarta schemas (#1116)

- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/EntityManagerFactoryProvider.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/jpa/PersistenceProvider.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/jpa/config/RuntimeFactory.java
> [3.0] Bug 573198: ConcurrentModificationException in PersistenceProvider

- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/EntityManagerFactoryProvider.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/jpa/PersistenceProvider.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/jpa/config/RuntimeFactory.java
> [2.7] Bug 573198: ConcurrentModificationException in PersistenceProvider

- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/EntityManagerFactoryProvider.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/jpa/PersistenceProvider.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/jpa/config/RuntimeFactory.java
> [2.6_WAS] Bug 573198: ConcurrentModificationException in PersistenceProvider

- SECURITY.md
Added a security policy, fixes #944 
Signed-off-by: Artem Smotrakov <artem.smotrakov@gmail.com>
> [master] Added a security policy

- .lgtm.yml
Added a config for LGTM.com
- Excluded tests and docs
- Specified a build command
Fixes #942
Signed-off-by: Artem Smotrakov <artem.smotrakov@sap.com>
> [master] Added a config for LGTM.com

- .travis.yml
- jpa/eclipselink.jpa.test/src/it/java/org/eclipse/persistence/testing/tests/jpa/jpql/JUnitJPQLComplexTestSuite.java
and fix remaining test failure on MySQL 8
> Update OS for travis, use MySQL 8 for tests

- etc/jenkins/build.groovy
- etc/jenkins/promote.groovy
> [2.7] Jenkins build - pipeline notifications - backport

- etc/jenkins/build.groovy
- etc/jenkins/promote.groovy
> [2.6] Jenkins build - pipeline notifications - backport

- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/query/TestQueryCase.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/query/model/EntityTbl01_.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/querydef/CriteriaBuilderImpl.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/querydef/SelectionImpl.java
> [3.0] Bug 573435: CriteriaBuilder construct throws argument type mismatch exception with Case Select

- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/query/TestQueryCase.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/query/model/EntityTbl01_.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/querydef/CriteriaBuilderImpl.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/querydef/SelectionImpl.java
> [2.7] Bug 573435: CriteriaBuilder construct throws argument type mismatch exception with Case Select

- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/query/TestQueryCase.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/query/model/EntityTbl01_.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/querydef/CriteriaBuilderImpl.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/querydef/SelectionImpl.java
> [2.6_WAS] Bug 573435: CriteriaBuilder construct throws argument type mismatch exception with Case Select

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/expressions/ExpressionOperator.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/OraclePlatform.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/query/TestTrimFunction.java
> [master] Bug 573094: Fix LTRIM/RTRIM inversion of indices

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/expressions/ExpressionOperator.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/OraclePlatform.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/query/TestTrimFunction.java
> [3.0] Bug 573094: Fix LTRIM/RTRIM inversion of indices

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/expressions/ExpressionOperator.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/OraclePlatform.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/query/TestTrimFunction.java
> [2.7] Bug 573094: Fix LTRIM/RTRIM inversion of indices

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/expressions/ExpressionOperator.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/query/TestTrimFunction.java
> [2.6_WAS] Bug 573094: Fix LTRIM/RTRIM inversion of indices

- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/query/TestQueryCase.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/query/TestQueryCoalesce.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/querydef/CriteriaBuilderImpl.java
> [master] Bug 573361: Add support for parameters within CriteriaBuilder case/coalesce expressions

- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/query/TestQueryCase.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/query/TestQueryCoalesce.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/querydef/CriteriaBuilderImpl.java
> [3.0] Bug 573361: Add support for parameters within CriteriaBuilder case/coalesce expressions

- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/query/TestQueryCase.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/query/TestQueryCoalesce.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/querydef/CriteriaBuilderImpl.java
> [2.7] Bug 573361: Add support for parameters within CriteriaBuilder case/coalesce expressions

- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/query/TestQueryCase.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/query/TestQueryCoalesce.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/querydef/CriteriaBuilderImpl.java
> [2.6_WAS] Bug 573361: Add support for parameters within CriteriaBuilder case/coalesce expressions

- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/query/TestQueryIN.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/querydef/InImpl.java
> [master] Bug 573794: Add support for parameters within CriteriaBuilder IN expressions

- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/query/TestQueryIN.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/querydef/InImpl.java
> [3.0] Bug 573794: Add support for parameters within CriteriaBuilder IN expressions

- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/query/TestQueryIN.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/querydef/InImpl.java
> [2.7] Bug 573794: Add support for parameters within CriteriaBuilder IN expressions

- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/query/TestQueryIN.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/querydef/InImpl.java
> [2.6_WAS] Bug 573794: Add support for parameters within CriteriaBuilder IN expressions

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/DerbyPlatform.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/criteria/TestCoalesceFunction.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/criteria/model/CoalesceEntity.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/criteria/model/CoalesceEntity_.java
> [2.6_WAS] Bug 341074: CriteriaBuilder coalesce ClassCastException using literals

- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/query/TestQueryHaving.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/querydef/AbstractQueryImpl.java
> [3.0] Bug 417259: Add support for parameters within CriteriaBuilder HAVING clause

- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/query/TestQueryHaving.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/querydef/AbstractQueryImpl.java
> [2.7] Bug 417259: Add support for parameters within CriteriaBuilder HAVING clause

- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/query/TestQueryHaving.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/querydef/AbstractQueryImpl.java
> [2.6_WAS] Bug 417259: Add support for parameters within CriteriaBuilder HAVING clause

- etc/jenkins/build.groovy
> [master] Jenkins pipelines fix

- etc/jenkins/build.groovy
https://bugs.eclipse.org/bugs/show_bug.cgi?id=574503
> Fix for bug 574503

- etc/jenkins/pr_verify.groovy
git instruction removal from Jenkins pipeline to avoid some build fix
> [master] Pull request verify by Eclipse-CI Jenkis

- etc/jenkins/pr_verify.groovy
Fix Jenkins pipeline used to verify GutHub PRs.
> [3.0] Jenkins pull request verify

- etc/jenkins/pr_verify.groovy
Verify PR by Eclipse.org (CI) Jenkins.
> [2.7] Jenkins pull request verify

- etc/jenkins/pr_verify.groovy
Verify PR by Eclipse.org (CI) Jenkins.
> [2.6] Jenkins pull request verify

- .github/workflows/codeql-analysis.yml
> make codeql build less verbose

- bundles/eclipselink/src/main/scripts/bin/sdo-compiler.cmd
- bundles/eclipselink/src/main/scripts/bin/sdo-compiler.sh
- bundles/eclipselink/src/main/scripts/bin/sdo-jaxb-compiler.cmd
- bundles/eclipselink/src/main/scripts/bin/sdo-jaxb-compiler.sh
> Run sdo tooling on modulepath

- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/query/TestQueryUpdate.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/querydef/CriteriaUpdateImpl.java
> [master] Bug 574548: Add support for parameters with CriteriaBuilder update query

- etc/jenkins/build.sh
- etc/jenkins/build_asm.sh
- etc/jenkins/includes/maven.incl.sh
- etc/jenkins/includes/nexus.incl.sh
- etc/jenkins/pr_verify.groovy
- etc/jenkins/release.sh
- etc/jenkins/tck_init.sh
- etc/jenkins/test.sh
- etc/jenkins/test_nosql.sh
- etc/jenkins/test_server.sh
> let the build print out java version

- etc/jenkins/includes/maven.incl.sh
- etc/jenkins/includes/nexus.incl.sh
- etc/jenkins/release.sh
> [master] Jenkins release pipeline fix

- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/query/TestQueryUpdate.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/querydef/CriteriaUpdateImpl.java
> [2.6_WAS] Bug 574548: Add support for parameters with CriteriaBuilder update query

- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/query/TestQueryUpdate.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/querydef/CriteriaUpdateImpl.java
> [3.0] Bug 574548: Add support for parameters with CriteriaBuilder update query

- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/query/TestQueryUpdate.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/querydef/CriteriaUpdateImpl.java
> [2.7] Bug 574548: Add support for parameters with CriteriaBuilder update query

- etc/jenkins/build.groovy
- etc/jenkins/pr_verify.groovy
- etc/jenkins/release.groovy
- etc/jenkins/release.sh
JDK upgrade, post build actions to capture compiler, JavaDoc, SpotBugs messages.
> [master] Jenkins pipelines refresh

- README.md
This commit extends current project `README.md` with info about latest published version in Maven Central, Nightly build status and latest available snapshot (master only).
> [master] Project README.md update

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/queries/BatchFetchPolicy.java
> [master] Bug 1245: NullPointerException from BatchFetchPolicy dataResults

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/queries/BatchFetchPolicy.java
> [2.7] Bug 1245: NullPointerException from BatchFetchPolicy dataResults

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/queries/BatchFetchPolicy.java
> [2.6_WAS] Bug 1245: NullPointerException from BatchFetchPolicy dataResults

- .github/workflows/maven.yml
- bundles/eclipselink/pom.xml
- bundles/others/src/main/resources/nonfiltered/eclipselink-test-src.zip/antbuild.xml
- bundles/pom.xml
- foundation/org.eclipse.persistence.core/pom.xml
- jpa/eclipselink.jpa.wdf.test/pom.xml
- jpa/org.eclipse.persistence.jpa.test.framework/pom.xml
- pom.xml
- sdo/org.eclipse.persistence.sdo/pom.xml
> Tweak warnings in the build

- bundles/eclipselink/pom.xml
- jpa/org.eclipse.persistence.jpa.modelgen/src/main/java/module-info.java
- jpa/org.eclipse.persistence.jpa.modelgen/src/test/java/org/eclipse/persistence/jpa/test/modelgen/TestProcessor.java
- jpa/org.eclipse.persistence.jpa/src/main/java/module-info.java
> Fix reported compile time errors from tests

- foundation/org.eclipse.persistence.core/pom.xml
- foundation/org.eclipse.persistence.core/src/main/java/module-info.java
- moxy/org.eclipse.persistence.moxy/pom.xml
- pom.xml
> reduce compiler warnings

- .github/workflows/codeql-analysis.yml
- .github/workflows/maven30.yml
> build/test workflow for 3.0

- .github/workflow/maven.yml
- bundles/eclipselink/pom.xml
- bundles/others/pom.xml
- bundles/others/src/main/assembly/eclipselink-plugins-nosql.zip.xml
- bundles/others/src/main/resources/nonfiltered/eclipselink-test-src.zip/antbuild.xml
- bundles/pom.xml
- foundation/org.eclipse.persistence.core.test.framework/pom.xml
- foundation/org.eclipse.persistence.core/pom.xml
- jpa/eclipselink.jpa.test/pom.xml
- jpa/org.eclipse.persistence.jpa.test.framework/pom.xml
- jpa/org.eclipse.persistence.jpa/pom.xml
- pom.xml
- sdo/org.eclipse.persistence.sdo/pom.xml
- utils/org.eclipse.persistence.dbws.builder/pom.xml
this also fixes usability of sdo on jdk11 in 3.0.x
> backport build related changes from master

- .lgtm.yml
> add config for lgtm

- jpa/eclipselink.jaxrs.test/pom.xml
- jpa/eclipselink.jpa.nosql.test/pom.xml
- jpa/eclipselink.jpa.test/pom.xml
- jpa/eclipselink.jpa.wdf.test/src/it/java/org/eclipse/persistence/testing/tests/wdf/jpa1/entitymanager/TestFind.java
- jpa/eclipselink.jpars.test/pom.xml
- pom.xml
- sdo/eclipselink.sdo.test.server/pom.xml
- testing/server-oracle/pom.xml
- testing/server/pom.xml
- utils/eclipselink.dbws.builder.test.oracle.server/pom.xml
> Fix up the build for maven 3.8.2

- bundles/pom.xml
- pom.xml
- src/main/assembly/spotbugs-filter.xml
- src/main/resources/spotbugs-exclude-common.xml
- testing/server/pom.xml
> setup spotbugs

- bundles/eclipselink/pom.xml
- dbws/org.eclipse.persistence.dbws/pom.xml
- foundation/org.eclipse.persistence.core/pom.xml
- moxy/org.eclipse.persistence.moxy/pom.xml
- pom.xml
- sdo/org.eclipse.persistence.sdo/pom.xml
> add raw and uchecked to javac xlint for main sources

- bundles/eclipselink/pom.xml
- bundles/eclipselink/src/main/assembly/eclipselink.zip.xml
- bundles/moxy-standalone/pom.xml
- bundles/moxy-standalone/src/main/assembly/moxy.xml
- bundles/others/pom.xml
- bundles/others/src/main/assembly/eclipselink-plugins-nosql.zip.xml
- bundles/others/src/main/assembly/eclipselink-plugins.zip.xml
- bundles/others/src/main/assembly/eclipselink-test-src.zip.xml
- jpa/eclipselink.jaxrs.test/pom.xml
- jpa/eclipselink.jpa.nosql.test/pom.xml
- jpa/eclipselink.jpa.test/pom.xml
- jpa/eclipselink.jpa.wdf.test/src/it/java/org/eclipse/persistence/testing/tests/wdf/jpa1/entitymanager/TestFind.java
- jpa/eclipselink.jpars.test/pom.xml
- pom.xml
- sdo/eclipselink.sdo.test.server/pom.xml
- src/main/assembly/common-license.xml
- src/main/assembly/test-defaults.xml
- testing/server-oracle/pom.xml
- testing/server/pom.xml
- utils/eclipselink.dbws.builder.test.oracle.server/pom.xml
> [3.0] Maven build issue with Maven 3.8.2 fix - backport

- sdo/org.eclipse.persistence.sdo/src/main/java/org/eclipse/persistence/sdo/helper/jaxb/JAXBValueStore.java
> fix sdo test failures

- jpa/org.eclipse.persistence.jpa.modelgen/src/main/java/org/eclipse/persistence/internal/jpa/modelgen/MetadataMirrorFactory.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/metadata/accessors/classes/ClassAccessor.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/metadata/accessors/classes/MappedSuperclassAccessor.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/metadata/accessors/mappings/ElementCollectionAccessor.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/metadata/accessors/mappings/MappingAccessor.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/metadata/accessors/mappings/VersionAccessor.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/metadata/accessors/objects/MetadataClass.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/metadata/converters/LobMetadata.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/metadata/converters/TemporalMetadata.java
> fix equals on incomparable types

- pom.xml
> update spotbugs to 4.4.1

- jpa/org.eclipse.persistence.jpars/src/it/java/org/eclipse/persistence/jpars/test/model/auction/StaticUser.java
- jpa/org.eclipse.persistence.jpars/src/it/java/org/eclipse/persistence/jpars/test/util/RestUtils.java
- jpa/org.eclipse.persistence.jpars/src/main/java/module-info.java
- jpa/org.eclipse.persistence.jpars/src/main/java/org/eclipse/persistence/jpa/rs/service/JPARSApplication.java
> cleanup jpars module

- dbws/org.eclipse.persistence.dbws/src/main/java/org/eclipse/persistence/internal/xr/ProjectHelper.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/descriptors/ClassDescriptor.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/jpa/jpql/EclipseLinkSemanticValidatorHelper.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/jpa/jpql/ExpressionBuilderVisitor.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/jpa/jpql/JPQLQueryContext.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/oxm/mappings/Descriptor.java
- jpa/org.eclipse.persistence.jpa.jpql/pom.xml
- jpa/org.eclipse.persistence.jpa.jpql/src/main/java/org/eclipse/persistence/jpa/jpql/AbstractSemanticValidator.java
- jpa/org.eclipse.persistence.jpa.jpql/src/main/java/org/eclipse/persistence/jpa/jpql/SemanticValidatorHelper.java
- jpa/org.eclipse.persistence.jpa.jpql/src/main/java/org/eclipse/persistence/jpa/jpql/tools/model/AbstractConditionalExpressionStateObjectBuilder.java
- jpa/org.eclipse.persistence.jpa.jpql/src/main/java/org/eclipse/persistence/jpa/jpql/tools/model/AbstractConditionalStateObjectBuilderWrapper.java
- jpa/org.eclipse.persistence.jpa.jpql/src/main/java/org/eclipse/persistence/jpa/jpql/tools/model/AbstractScalarExpressionStateObjectBuilder.java
- jpa/org.eclipse.persistence.jpa.jpql/src/main/java/org/eclipse/persistence/jpa/jpql/tools/model/IAbstractConditionalExpressionStateObjectBuilder.java
- jpa/org.eclipse.persistence.jpa.jpql/src/main/java/org/eclipse/persistence/jpa/jpql/tools/model/IScalarExpressionStateObjectBuilder.java
- jpa/org.eclipse.persistence.jpa.jpql/src/test/java/jpql/query/AbstractProduct.java
- jpa/org.eclipse.persistence.jpa.jpql/src/test/java/jpql/query/Address.java
- jpa/org.eclipse.persistence.jpa.jpql/src/test/java/jpql/query/Customer.java
- jpa/org.eclipse.persistence.jpa.jpql/src/test/java/jpql/query/Dept.java
- jpa/org.eclipse.persistence.jpa.jpql/src/test/java/jpql/query/Employee.java
- jpa/org.eclipse.persistence.jpa.jpql/src/test/java/jpql/query/Home.java
- jpa/org.eclipse.persistence.jpa.jpql/src/test/java/jpql/query/Phone.java
- jpa/org.eclipse.persistence.jpa.jpql/src/test/java/jpql/query/Product.java
- jpa/org.eclipse.persistence.jpa.jpql/src/test/java/org/eclipse/persistence/jpa/tests/jpql/tools/ContentAssistTest.java
- moxy/org.eclipse.persistence.moxy/src/main/java/org/eclipse/persistence/jaxb/JAXBContext.java
> clean up jpa/jpql parser, turn warnings into errors

- dbws/org.eclipse.persistence.dbws/src/main/java/org/eclipse/persistence/jpa/rs/util/PreLoginMappingAdapter.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/security/PrivilegedAccessHelper.java
- moxy/org.eclipse.persistence.moxy/src/main/java/org/eclipse/persistence/internal/jaxb/MultiArgInstantiationPolicy.java
- moxy/org.eclipse.persistence.moxy/src/main/java/org/eclipse/persistence/internal/jaxb/XMLJavaTypeConverter.java
- moxy/org.eclipse.persistence.moxy/src/main/java/org/eclipse/persistence/jaxb/JAXBBeanValidator.java
- moxy/org.eclipse.persistence.moxy/src/main/java/org/eclipse/persistence/jaxb/JAXBContext.java
- moxy/org.eclipse.persistence.moxy/src/main/java/org/eclipse/persistence/jaxb/JAXBEnumTypeConverter.java
- moxy/org.eclipse.persistence.moxy/src/main/java/org/eclipse/persistence/jaxb/JAXBMarshalListener.java
- moxy/org.eclipse.persistence.moxy/src/main/java/org/eclipse/persistence/jaxb/JAXBUnmarshalListener.java
- moxy/org.eclipse.persistence.moxy/src/main/java/org/eclipse/persistence/jaxb/MOXySystemProperties.java
- moxy/org.eclipse.persistence.moxy/src/main/java/org/eclipse/persistence/jaxb/ReflectionUtils.java
- moxy/org.eclipse.persistence.moxy/src/main/java/org/eclipse/persistence/jaxb/ValidationXMLReader.java
- moxy/org.eclipse.persistence.moxy/src/main/java/org/eclipse/persistence/jaxb/compiler/MappingsGenerator.java
- moxy/org.eclipse.persistence.moxy/src/main/java/org/eclipse/persistence/jaxb/compiler/MarshalCallback.java
- moxy/org.eclipse.persistence.moxy/src/main/java/org/eclipse/persistence/jaxb/compiler/UnmarshalCallback.java
- moxy/org.eclipse.persistence.moxy/src/main/java/org/eclipse/persistence/jaxb/dynamic/DynamicJAXBContext.java
- moxy/org.eclipse.persistence.moxy/src/main/java/org/eclipse/persistence/jaxb/plugins/BeanValidationPlugin.java
- moxy/org.eclipse.persistence.moxy/src/test/java/org/eclipse/persistence/testing/jaxb/events/JAXBMarshalListenerImpl.java
- moxy/org.eclipse.persistence.moxy/src/test/java/org/eclipse/persistence/testing/oxm/classloader/JARClassLoader.java
(cherry picked from commit 88c614793706c3b55600c806c0dfeb16cdb4344f)
> Prepare for the removal of the securitymanager in moxy. (#1320)

- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/weave/TestWeaving.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/weave/model/WeavedAbstractMS.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/weave/model/WeavedEntityA.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/weaving/TransformerFactory.java
> [3.0] Bug 412391: Add support for hidden mappedsuperclass attributes

- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/weave/TestWeaving.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/weave/model/WeavedAbstractMS.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/weave/model/WeavedEntityA.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/weaving/TransformerFactory.java
> [2.7] Bug 412391: Add support for hidden mappedsuperclass attributes

- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/weave/TestWeaving.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/weave/model/WeavedAbstractMS.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/weave/model/WeavedEntityA.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/weaving/TransformerFactory.java
> [2.6_WAS] Bug 412391: Add support for hidden mappedsuperclass attributes

- pom.xml
> [master] ASM dependency update to 9.2.0

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/expressions/ArgumentListFunctionExpression.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/concurrency/TestConcurrencyPersistence.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/concurrency/model/User.java
> [3.0] Bug 463042: Concurrency issue with Case expression operator

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/expressions/ArgumentListFunctionExpression.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/concurrency/TestConcurrencyPersistence.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/concurrency/model/User.java
> [2.6_WAS] Bug 463042: Concurrency issue with Case expression operator

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/queries/ExpressionQueryMechanism.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/returninsert/TestReturnInsert.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/returninsert/model/ReturnInsertDetail.java
> [master] problems with session customizer when upgrading to 2.7.9 - bugfix + unit test

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/queries/ExpressionQueryMechanism.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/returninsert/TestReturnInsert.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/returninsert/model/ReturnInsertDetail.java
> [2.7] problems with session customizer when upgrading to 2.7.9 - bugfix + unit test - backport from master

- etc/jenkins/init.sh
- etc/jenkins/pr_verify.groovy
- etc/jenkins/promote_init.sh
- jpa/eclipselink.jpa.test/antbuild.properties
- moxy/eclipselink.moxy.test/antbuild.properties
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/osgi/OSGITestHelper.java
- performance/eclipselink.perf.test/antbuild.properties
> [2.7] Test dependencies update (JBoss Logging, Classmate)

- moxy/eclipselink.moxy.test/pom.xml
- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/osgi/OSGITestHelper.java
> [2.6] LOG4J dependency update in MOXy OSGi tests

- moxy/eclipselink.moxy.test/pom.xml
> [2.7] LOG4J dependency update in MOXy OSGi tests

- bundles/others/src/main/resources/nonfiltered/eclipselink-test-src.zip/moxy/eclipselink.moxy.test/pom.xml
- pom.xml
> [master] LOG4J dependency update in MOXy OSGi test bundle and MySQL driver update

- bundles/others/src/main/resources/nonfiltered/eclipselink-test-src.zip/moxy/eclipselink.moxy.test/pom.xml
- pom.xml
> [3.0] LOG4J dependency update in MOXy OSGi test bundle and MySQL driver update

- foundation/org.eclipse.persistence.core/pom.xml
- moxy/org.eclipse.persistence.moxy/src/test/java/module-info.java
- pom.xml
> [master] Jakarta dependencies update for Jakarta EE 10

- .github/workflows/ant.yml
This PR add GitHub Actions as an additional verification step for PRs into 2.7 branch.
> [2.7] GitHub Actions

- bundles/eclipselink/src/main/java/module-info.java
- jpa/org.eclipse.persistence.jpa/src/main/java/module-info.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/deployment/JavaSECMPInitializer.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/weaving/PersistenceWeaver.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/tools/weaving/jpa/StaticWeaveClassTransformer.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/tools/weaving/jpa/StaticWeaveProcessor.java
- pom.xml
> [master] JPA API and Parsson dependencies upgrade

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/expressions/SQLSelectStatement.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/OraclePlatform.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/criteria/TestCriteriaBuilder.java
> [master] Cannot set FOR UPDATE in conjunction with ORDER BY and / or LIMIT (OracleDB & Derby) - bugfix + unit test

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/expressions/SQLSelectStatement.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/OraclePlatform.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/criteria/TestCriteriaBuilder.java
Fixes #1369 .
(cherry picked from commit adf28f4cd11703773ed1c93cfe32421789946c19)
> [3.0] Cannot set FOR UPDATE in conjunction with ORDER BY and / or LIMIT (OracleDB & Derby) - bugfix + unit test - backport from master

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/expressions/SQLSelectStatement.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/OraclePlatform.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/criteria/TestCriteriaBuilder.java
> [2.7] Cannot set FOR UPDATE in conjunction with ORDER BY and / or LIMIT (OracleDB & Derby) - bugfix + unit test - backport from master

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/descriptors/TimestampLockingPolicy.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/locking/TestTimestampVersionLocking.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/locking/model/EcallRegistration.java
> [master] Bug 578262: Bulk update queries reuse the same version locking value

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/descriptors/TimestampLockingPolicy.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/locking/TestTimestampVersionLocking.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/locking/model/EcallRegistration.java
> [3.0] Bug 578262: Bulk update queries reuse the same version locking value

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/descriptors/TimestampLockingPolicy.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/locking/TestTimestampVersionLocking.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/locking/model/EcallRegistration.java
> [2.7] Bug 578262: Bulk update queries reuse the same version locking value

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/descriptors/TimestampLockingPolicy.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/locking/TestTimestampVersionLocking.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/locking/model/EcallRegistration.java
> [2.6_WAS] Bug 578262: Bulk update queries reuse the same version locking value

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/sessions/cdi/InjectionManagerImpl.java
> [3.0] CDI 4 update to remove deprecated API

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/sessions/cdi/InjectionManagerImpl.java
> [master] CDI 4 update to remove deprecated API

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/databaseaccess/DatabasePlatform.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/expressions/SQLSelectStatement.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/DB2Platform.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/query/TestQueryOrderBy.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/querydef/CommonAbstractCriteriaImpl.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/querydef/CriteriaQueryImpl.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/querydef/OrderImpl.java
> [2.6_WAS] Bug 578686: ParameterExpression in ORDER BY clause doesn't register

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/expressions/SQLSelectStatement.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/query/TestQueryOrderBy.java
> [2.6_WAS] Bug 578686: Minor update to support 'shouldBindLiterals' property

- jpa/eclipselink.jpa.wdf.test/src/it/java/org/eclipse/persistence/testing/framework/wdf/AbstractBaseTest.java
- jpa/eclipselink.jpa.wdf.test/src/it/java/org/eclipse/persistence/testing/tests/wdf/jpa1/entitymanager/TestGetReference.java
for #1360
Taking a crack at looking at the WDF `TestGetReference` tests and investigate what's going wrong. I cleaned up some of the tests a bit with the Asserts and reworked some of the failing tests logic
> [master] Issue 1360: Random JPA WDF test failures

- bundles/tests/pom.xml
- foundation/org.eclipse.persistence.nosql/pom.xml
- foundation/org.eclipse.persistence.nosql/src/main/java/module-info.java
- jpa/org.eclipse.persistence.jpa/pom.xml
- jpa/org.eclipse.persistence.jpa/src/main/java/module-info.java
- pom.xml
> Integrate latest jakarta dependencies

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/databaseaccess/DatabasePlatform.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/expressions/SQLSelectStatement.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/DB2Platform.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/query/TestQueryOrderBy.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/querydef/CommonAbstractCriteriaImpl.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/querydef/CriteriaQueryImpl.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/querydef/OrderImpl.java
> [2.7] Bug 578686: ParameterExpression in ORDER BY clause doesn't register

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/databaseaccess/DatabasePlatform.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/expressions/SQLSelectStatement.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/DB2Platform.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/query/TestQueryOrderBy.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/querydef/CommonAbstractCriteriaImpl.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/querydef/CriteriaQueryImpl.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/querydef/OrderImpl.java
> [3.0] Bug 578686: ParameterExpression in ORDER BY clause doesn't register

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/databaseaccess/DatabasePlatform.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/expressions/SQLSelectStatement.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/DB2Platform.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/query/TestQueryOrderBy.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/querydef/CommonAbstractCriteriaImpl.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/querydef/CriteriaQueryImpl.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/querydef/OrderImpl.java
> [master] Bug 578686: ParameterExpression in ORDER BY clause doesn't register

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/expressions/SQLSelectStatement.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/query/TestQueryOrderBy.java
for #1429 
backport from master
> [3.0] Bug 578686: Remove OrderBy parameter binding use case

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/DerbyPlatform.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/criteria/TestDateTimeFunctions.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/query/TestDateTimeFunctions.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/query/model/DateTimeQueryEntity.java
All EXTRACT TCK tests added as jUnits.
> Added missing EXTRACT(QUARTER FROM date/datetime) for Derby platform.

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/expressions/SQLSelectStatement.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/query/TestQueryOrderBy.java
for #1429
backport from master
> [2.7] Bug 578686: Remove OrderBy parameter binding use case

- moxy/eclipselink.moxy.test/src/org/eclipse/persistence/testing/jaxb/beanvalidation/ValidationXMLTestCase.java
- moxy/org.eclipse.persistence.moxy/src/org/eclipse/persistence/jaxb/JAXBContext.java
Signed-off-by: lananda <lalitha.ananda@oracle.com>
> [2.6.] Bug 579128: Classloaderleak with beanvaliation

- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/query/TestQueryIsNull.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/querydef/CriteriaBuilderImpl.java
> [master] Bug 579327: ParameterExpression in CriteriaBuilder.isNull() doesn't register

- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/query/TestQueryIsNull.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/querydef/CriteriaBuilderImpl.java
> [2.7] Bug 579327: ParameterExpression in CriteriaBuilder.isNull() doesn't register

- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/query/TestQueryIsNull.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/querydef/CriteriaBuilderImpl.java
> [2.6_WAS] Bug 579327: ParameterExpression in CriteriaBuilder.isNull() doesn't register

- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/query/TestQueryIsNull.java
for #1457
Fixing a test bug where some test iterations are invalid against Derby/DB2z
> [3.0] Bug 579327: Test bug on Derby & DB2z

- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/query/TestQueryIsNull.java
for #1457
Fixing a test bug where some test iterations are invalid against Derby/DB2z
> [2.6_WAS] Bug 579327: Test bug on Derby & DB2z

- pom.xml
> integrate latest dependencies

- etc/jenkins/release.groovy
> Jenkins release pipeline - resources upgrade

- etc/el-test.mysql.properties
- etc/jenkins/build.groovy
- etc/jenkins/pr_verify.groovy
- etc/jenkins/release.groovy
- etc/jenkins/tck.groovy
- pom.xml
> [3.0] Jenkins build image upgrade with MySQL 8.0 and MySQL test settings update - backport from master

- etc/jenkins/docker/image/install.sh
- etc/jenkins/docker/pom.xml
> [master] Jenkins build image upgrade to add needed utilities for 2.7 branch build

- .github/workflows/ant.yml
- etc/jenkins/build.groovy
- etc/jenkins/build.sh
- etc/jenkins/init.sh
- etc/jenkins/pr_verify.groovy
- etc/jenkins/promote.groovy
- etc/jenkins/promote_init.sh
- etc/jenkins/publish_snapshots.sh
> [2.7] Jenkins build image upgrade with MySQL 8.0 and MySQL tests settings update

- pom.xml
> [master] ASM dependency update to 9.3.0

- buildsystem/compdeps/pom.xml
- dbws/org.eclipse.persistence.dbws/META-INF/MANIFEST.MF
- foundation/org.eclipse.persistence.core/META-INF/MANIFEST.MF
- jpa/org.eclipse.persistence.jpa/META-INF/MANIFEST.MF
- moxy/org.eclipse.persistence.moxy/META-INF/MANIFEST.MF
- sdo/org.eclipse.persistence.sdo/META-INF/MANIFEST.MF
> [2.7] ASM dependency update to 9.3.0

- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/criteria/TestNegFunction.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/criteria/model/CritEntity.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/querydef/CriteriaBuilderImpl.java
> Bug 579726: CriteriaBuilder neg() only returns Integer type.

- pom.xml
> [3.0] Apache Ant dependency upgrade

- pom.xml
> [master] MongoDB dependency upgrade

- pom.xml
> Update jakarta dependencies

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/jpa/jpql/ExpressionBuilderVisitor.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/jpa/jpql/TypeResolver.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/jpql/TestDateTimeFunctions.java
- jpa/org.eclipse.persistence.jpa.jpql/src/main/java/org/eclipse/persistence/jpa/jpql/parser/AbstractExpressionVisitor.java
- jpa/org.eclipse.persistence.jpa.jpql/src/main/java/org/eclipse/persistence/jpa/jpql/parser/AnonymousExpressionVisitor.java
- jpa/org.eclipse.persistence.jpa.jpql/src/main/java/org/eclipse/persistence/jpa/jpql/parser/Expression.java
- jpa/org.eclipse.persistence.jpa.jpql/src/main/java/org/eclipse/persistence/jpa/jpql/parser/ExpressionVisitor.java
- jpa/org.eclipse.persistence.jpa.jpql/src/main/java/org/eclipse/persistence/jpa/jpql/parser/JPQLGrammar3_1.java
- jpa/org.eclipse.persistence.jpa.jpql/src/main/java/org/eclipse/persistence/jpa/jpql/parser/LocalDateTime.java
- jpa/org.eclipse.persistence.jpa.jpql/src/main/java/org/eclipse/persistence/jpa/jpql/parser/LocalDateTypeBNF.java
- jpa/org.eclipse.persistence.jpa.jpql/src/main/java/org/eclipse/persistence/jpa/jpql/parser/LocalDateTypeFactory.java
- jpa/org.eclipse.persistence.jpa.jpql/src/main/java/org/eclipse/persistence/jpa/jpql/parser/LocalExpression.java
- jpa/org.eclipse.persistence.jpa.jpql/src/main/java/org/eclipse/persistence/jpa/jpql/parser/LocalExpressionBNF.java
- jpa/org.eclipse.persistence.jpa.jpql/src/main/java/org/eclipse/persistence/jpa/jpql/parser/LocalExpressionFactory.java
- jpa/org.eclipse.persistence.jpa.jpql/src/main/java/org/eclipse/persistence/jpa/jpql/tools/AbstractContentAssistVisitor.java
- jpa/org.eclipse.persistence.jpa.jpql/src/main/java/org/eclipse/persistence/jpa/jpql/tools/resolver/ResolverBuilder.java
- jpa/org.eclipse.persistence.jpa.jpql/src/test/java/org/eclipse/persistence/jpa/tests/jpql/tools/AbstractContentAssistTest.java
> Issue #317 - Implemented LOCAL DATE, LOCAL TIME and LOCAL DATETIME.

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/queries/BatchFetchPolicy.java
> [master] Fix memory leak in BatchFetchPolicy clone()

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/queries/BatchFetchPolicy.java
> [2.7] Fix memory leak in BatchFetchPolicy clone()

- bundles/eclipselink/pom.xml
- bundles/eclipselink/src/main/java/module-info.java
- dbws/org.eclipse.persistence.dbws/src/main/java/module-info.java
- foundation/org.eclipse.persistence.core/src/main/java/module-info.java
- foundation/org.eclipse.persistence.oracle.nosql/pom.xml
- foundation/org.eclipse.persistence.oracle.nosql/src/main/java/module-info.java
- pom.xml
- utils/org.eclipse.persistence.dbws.builder/src/main/java/module-info.java
> fix content of eclipselink zip,

- .github/workflows/maven.yml
- pom.xml
> add owasp and findsecbugs checks to the build

- .github/workflows/codeql-analysis.yml
- bundles/pom.xml
- foundation/org.eclipse.persistence.oracle.nosql/pom.xml
- moxy/org.eclipse.persistence.moxy/pom.xml
> update codeql action

- bundles/eclipselink/src/main/java/module-info.java
- foundation/org.eclipse.persistence.core/src/main/java/module-info.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/helper/IdentityHashSet.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/helper/IdentityWeakHashMap.java
- foundation/org.eclipse.persistence.nosql/src/main/java/module-info.java
- jpa/org.eclipse.persistence.jpa/src/main/java/module-info.java
- sdo/org.eclipse.persistence.sdo/src/main/java/module-info.java
- sdo/org.eclipse.persistence.sdo/src/main/java/org/eclipse/persistence/sdo/SDOSequence.java
- utils/org.eclipse.persistence.dbws.builder/src/main/java/module-info.java
> Fix module related compile time warnings

- .github/workflows/ant.yml
- .github/workflows/codeql-analysis.yml
> [2.7] GitHub actions - Maven home fix

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/databaseaccess/DatabaseAccessor.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/databaseaccess/DatabasePlatform.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/databaseaccess/Platform.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/databaseaccess/PlatformWrapper.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/localization/i18n/LoggingLocalizationResource.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/OraclePlatform.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/SQLServerPlatform.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/sessions/DatasourceLogin.java
- foundation/org.eclipse.persistence.oracle/src/main/java/org/eclipse/persistence/internal/platform/database/oracle/TIMESTAMPLTZWrapper.java
- foundation/org.eclipse.persistence.oracle/src/main/java/org/eclipse/persistence/internal/platform/database/oracle/TIMESTAMPTZWrapper.java
- foundation/org.eclipse.persistence.oracle/src/main/java/org/eclipse/persistence/platform/database/oracle/Oracle9Platform.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/criteria/TestDateTimeFunctions.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/criteria/TestMathFunctions.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/criteria/model/DateTimeEntity.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/jpql/TestDateTimeFunctions.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/query/TestDateTimeFunctions.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/query/TestMathFunctions.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/query/model/DateTimeQueryEntity.java
- fixes issue #1539
- fixes issue #1540
- fixes issue #1541
All LRG tests still wont pass with Oracle DB but all known problems with date/time and math functions should be fixed now.
> Fixed failing Date/time and math functions tests with Oracle DB.

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/exceptions/i18n/ValidationExceptionResource.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/localization/i18n/ToStringLocalizationResource.java
> [master] Issue 1556: minor messaging errors

- jpa/eclipselink.jpa.testapps/pom.xml
- jpa/org.eclipse.persistence.jpa.test.framework/src/main/java/org/eclipse/persistence/testing/framework/junit/JUnitTestCase.java
- jpa/org.eclipse.persistence.jpa.test.framework/src/main/java/org/eclipse/persistence/testing/framework/server/GenericTestRunner.java
- jpa/org.eclipse.persistence.jpa.test.framework/src/main/java/org/eclipse/persistence/testing/framework/server/SingleUnitTestRunnerBean.java
- jpa/org.eclipse.persistence.jpa.test.framework/src/main/java/org/eclipse/persistence/testing/framework/server/TestRunner1Bean.java
- jpa/org.eclipse.persistence.jpa.test.framework/src/main/java/org/eclipse/persistence/testing/framework/server/TestRunner2Bean.java
- jpa/org.eclipse.persistence.jpa.test.framework/src/main/java/org/eclipse/persistence/testing/framework/server/TestRunner3Bean.java
- jpa/org.eclipse.persistence.jpa.test.framework/src/main/java/org/eclipse/persistence/testing/framework/server/TestRunner4Bean.java
- jpa/org.eclipse.persistence.jpa.test.framework/src/main/java/org/eclipse/persistence/testing/framework/server/TestRunner5Bean.java
- jpa/org.eclipse.persistence.jpa.test.framework/src/main/java/org/eclipse/persistence/testing/framework/server/TestRunner6Bean.java
> JPA test framework updates - minor cleanup

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/exceptions/i18n/ValidationExceptionResource.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/localization/i18n/ToStringLocalizationResource.java
> [2.6_WAS] Issue 1556: minor messaging errors

- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/metadata/MetadataProcessor.java
found and tested via xml.extended.composite tests on WildFly
> fix loading mapping files for members of the composite PU

- jpa/eclipselink.jpa.testapps/jpa.test.beanvalidation.dynamic/pom.xml
- jpa/eclipselink.jpa.testapps/jpa.test.composite.advanced/src/main/resources-ejb/META-INF/persistence.xml
- jpa/eclipselink.jpa.testapps/jpa.test.xml.composite.advanced/src/test/java/org/eclipse/persistence/testing/tests/jpa/xml/composite/advanced/XmlCompositeAdvancedJUnitTest.java
- jpa/eclipselink.jpa.testapps/jpa.test.xml.extended.composite.advanced/pom.xml
- jpa/eclipselink.jpa.testapps/pom.xml
> fix testIdentityOutsideTransaction on wildfly

- jpa/eclipselink.jpa.testapps/jpa.test.advanced.multitenant/src/main/resources-ejb/META-INF/persistence.xml
- jpa/eclipselink.jpa.testapps/jpa.test.xml.advanced.multitenant/pom.xml
- jpa/eclipselink.jpa.testapps/jpa.test.xml.advanced.multitenant/src/main/resources-ejb/META-INF/persistence.xml
- jpa/eclipselink.jpa.testapps/jpa.test.xml.advanced.multitenant/src/main/resources/META-INF/persistence.xml
use global logging.level setting for xml mt tests
> add missing properties for xml multitenant-tableC test,

- jpa/eclipselink.jpa.testapps/pom.xml
- jpa/org.eclipse.persistence.jpa.jpql/pom.xml
- jpa/org.eclipse.persistence.jpa.jpql/src/main/java/org/eclipse/persistence/jpa/jpql/tools/utility/filter/CompoundFilter.java
- jpa/org.eclipse.persistence.jpars/pom.xml
- jpa/org.eclipse.persistence.jpars/src/it/java/org/eclipse/persistence/jpars/test/server/RestCallFailedException.java
- utils/eclipselink.dbws.builder.test.oracle/src/it/java/dbws/testing/shadowddlgeneration/oldjpub/ViewCache.java
minor updates for build on JDK18
> Make test run order fixed,

- jpa/eclipselink.jpa.testapps/pom.xml
- jpa/org.eclipse.persistence.jpa.modelgen/pom.xml
- jpa/org.eclipse.persistence.jpa.modelgen/src/main/java/module-info.java
- jpa/org.eclipse.persistence.jpa.modelgen/src/main/java/org/eclipse/persistence/internal/jpa/modelgen/CanonicalModelProcessor.java
- jpa/org.eclipse.persistence.jpa.modelgen/src/main/java/org/eclipse/persistence/internal/jpa/modelgen/MessagerLog.java
- jpa/org.eclipse.persistence.jpa.modelgen/src/main/java/org/eclipse/persistence/internal/jpa/modelgen/objects/PersistenceUnitReader.java
- jpa/org.eclipse.persistence.jpa.modelgen/src/test/java/module-info.java
- jpa/org.eclipse.persistence.jpa.modelgen/src/test/java/org/eclipse/persistence/jpa/test/modelgen/TestProcessor.java
- jpa/org.eclipse.persistence.jpa/src/main/java/module-info.java
> Make canonical model processor usable on the modulepath

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/Oracle10Platform.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/OraclePlatform.java
- foundation/org.eclipse.persistence.oracle/src/main/java/org/eclipse/persistence/platform/database/oracle/Oracle10Platform.java
- foundation/org.eclipse.persistence.oracle/src/main/java/org/eclipse/persistence/platform/database/oracle/Oracle9Platform.java
This shall fix EXTRACT(WEEK FROM DATEVALUE) problem which is still there after Issue #1540 fix.
> Issue 1540: Fixed EXTRACT(WEEK FROM DATEVALUE) in Oracle platorm.

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/descriptors/ClassDescriptor.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/exceptions/IntegrityChecker.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/databaseaccess/Accessor.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/databaseaccess/DatabaseAccessor.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/databaseaccess/DatasourceAccessor.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/tools/schemaframework/SchemaManager.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/tools/schemaframework/StoredProcedureGenerator.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/tools/schemaframework/TableCreator.java
> #1612: DDL generation grabs column info for the wrong table

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/exceptions/i18n/JSONExceptionResource.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/exceptions/i18n/QueryExceptionResource.java
> [2.7] Minor messaging fix for apostrophe usage

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/exceptions/i18n/JSONExceptionResource.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/exceptions/i18n/QueryExceptionResource.java
> [3.0] Minor messaging fix for apostrophe usage

- etc/jenkins/build.groovy
- etc/jenkins/pr_verify.groovy
- etc/jenkins/promote.groovy
> [2.7] Docker build image update - zip, unzip utilities added

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/exceptions/i18n/QueryExceptionResource.java
> [2.6_WAS] Minor messaging fix for apostrophe usage

- etc/jenkins/build.groovy
- etc/jenkins/pr_verify.groovy
- etc/jenkins/release.groovy
- etc/jenkins/tck.groovy
- etc/jenkins/tck_init.sh
port of https://github.com/eclipse-ee4j/eclipselink/pull/1624
> [3.0] Docker build image update - zip, unzip utilities installation

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/sequencing/UUIDSequence.java
> [Master] ECL1535: UUIDGenerator intermittently fails to initialize

- etc/jenkins/build.groovy
- etc/jenkins/pr_verify.groovy
- etc/jenkins/release.groovy
- etc/jenkins/tck.groovy
> [master] Docker build image update - zip, unzip utilities added

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/sessions/serializers/XMLSerializer.java
- jpa/eclipselink.jpa.testapps/jpa.test.lob/pom.xml
- jpa/eclipselink.jpa.testapps/jpa.test.lob/src/test/java/org/eclipse/persistence/testing/tests/jpa/lob/LobTest.java
- jpa/org.eclipse.persistence.jpa/pom.xml
> #1650: Explicitely use MOXy for XML de/serialization

- bundles/others/pom.xml
- bundles/others/src/main/assembly/eclipselink-jpatest-framework.jar.xml
> [3.0] JPA Test Framework - distribution bundle fix

- etc/jenkins/includes/maven.incl.sh
- etc/jenkins/release.sh
This PR fix some parameters in the _release.sh_ script to set correctly properties `buildRevision` and `buildType` in the _version.properties_ file.
> [3.0] Promotion build script fix - version qualifier and buildType property

- foundation/org.eclipse.persistence.core.test.framework/src/main/java/org/eclipse/persistence/tools/sessionconsole/SessionConsolePanel.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/uuid/TestUUIDGenerator.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/uuid/model/XMLUUIDAutoGenEntity.java
- jpa/eclipselink.jpa.test.jse/src/it/resources/META-INF/uuid-orm.xml
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/metadata/sequencing/GeneratedValueMetadata.java
For #1625
(also includes a small fix to SessionControlPanel as an errant character in a comment was causing my compiler to fail)
> [Master] ECL1625: Address incomplete UUID impl with AUTO generator

- etc/jenkins/release.sh
> [3.0] Release script fix to avoid ambiguous git tag results

- pom.xml
> Core and JPA Test Framework - distribution to Maven Central fix

- pom.xml
> [master] Core and JPA Test Framework - distribution to Maven Central fix - backport from 3.0

- etc/jenkins/includes/maven.incl.sh
- etc/jenkins/release.sh
This PR fix some parameters in the release.sh script to set correctly properties `buildRevision` and `buildType` in the _version.properties_ file.
> [master] Promotion build script fix - version qualifier and buildType property - backport from 3.0

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/exceptions/i18n/BeanValidationExceptionResource.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/exceptions/i18n/ConcurrencyExceptionResource.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/exceptions/i18n/DBWSExceptionResource.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/exceptions/i18n/ValidationExceptionResource.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/localization/i18n/LoggingLocalizationResource.java
> [3.0] Minor messaging improvements

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/databaseaccess/DatabaseAccessor.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/criteria/TestMathFunctions.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/criteria/TestSimpleCase.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/criteria/model/NumberEntity.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/query/TestMathFunctions.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/querydef/CriteriaBuilderImpl.java
> Issue #1641 - Fixed ceiling, floor and round return types.

- foundation/org.eclipse.persistence.oracle/src/main/java/org/eclipse/persistence/internal/platform/database/oracle/TIMESTAMPHelper.java
- foundation/org.eclipse.persistence.oracle/src/main/java/org/eclipse/persistence/internal/platform/database/oracle/TIMESTAMPLTZWrapper.java
- foundation/org.eclipse.persistence.oracle/src/main/java/org/eclipse/persistence/internal/platform/database/oracle/TIMESTAMPTZWrapper.java
- foundation/org.eclipse.persistence.oracle/src/main/java/org/eclipse/persistence/platform/database/oracle/Oracle9Platform.java
- jpa/eclipselink.jpa.testapps.oracle/jpa.test.oracle.timestamptz/pom.xml
> Fixed regression caused by issue #1546 fix.

- etc/jenkins/release.sh
> Release script fix

- .lgtm.yml
> [master] LGTM build command fix

- jpa/eclipselink.jpa.test/pom.xml
> fix broken cont. build

- README.md
> [master] Readme update to reflect current versioning (version numbers)

- etc/jenkins/pr_verify.groovy
- etc/jenkins/test_nosql.sh
This fix reflects latest changes in JPA tests.
> [master] Jenkins pipeline - NoSQL (MongoDB) test execution fix

- jpa/eclipselink.jpa.testapps/jpa.test.advanced/src/main/resources/META-INF/persistence.xml
- jpa/eclipselink.jpa.testapps/jpa.test.advanced/src/test/java/org/eclipse/persistence/testing/tests/jpa/advanced/AdvancedJPAJunitTest.java
- jpa/org.eclipse.persistence.jpa.modelgen/src/main/java/org/eclipse/persistence/internal/jpa/modelgen/CanonicalModelProcessor.java
- jpa/org.eclipse.persistence.jpa.modelgen/src/main/java/org/eclipse/persistence/internal/jpa/modelgen/MetadataMirrorFactory.java
- jpa/org.eclipse.persistence.jpa.modelgen/src/test/java/org/eclipse/persistence/jpa/test/modelgen/TestProcessor.java
> #1678: Canonical processor fails on entities shared across persistence units

- bundles/eclipselink/src/main/java/module-info.java
- foundation/org.eclipse.persistence.core/src/main/java/module-info.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/databaseaccess/JsonPlatformManager.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/localization/i18n/LoggingLocalizationResource.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/PostgreSQL10Platform.java
- foundation/org.eclipse.persistence.json/src/main/java/module-info.java
- foundation/org.eclipse.persistence.oracle/src/main/java/module-info.java
- foundation/org.eclipse.persistence.pgsql/src/main/java/module-info.java
Also fixed module info for pgsql and oracle modules.
> Issue #1668 - Lowered log level and made messages less aggressive.

- bundles/eclipselink/src/main/java/module-info.java
- foundation/org.eclipse.persistence.core/src/main/java/module-info.java
> [master] JsonPlatformProvider JPMS refactor to reflect current module-info.java flow

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/queries/CallQueryMechanism.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/queries/StatementQueryMechanism.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/sequence/TestIdentityGeneration.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/sequence/model/StepExecutionEntity.java
> [master] Issue 1711: ClassCastException while updating foreignkeys with identity generation

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/queries/CallQueryMechanism.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/queries/StatementQueryMechanism.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/sequence/TestIdentityGeneration.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/sequence/model/StepExecutionEntity.java
> [2.7] Issue 1711: ClassCastException while updating foreignkeys with identity generation

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/queries/CallQueryMechanism.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/queries/StatementQueryMechanism.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/sequence/TestIdentityGeneration.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/sequence/model/StepExecutionEntity.java
> [2.6_WAS] Issue 1711: ClassCastException while updating foreignkeys with identity generation

- jpa/org.eclipse.persistence.jpa.modelgen/src/main/java/org/eclipse/persistence/internal/jpa/modelgen/visitors/ElementVisitor.java
fixes #1395
Adding a test would require having testRelease set to 14 (or newer) - do we want that?
> #1395: MetaModel Generator fails on Records

- pom.xml
> ASM version switch to 9.4 to be ready for JDK 20.

- .idea/.name
- .idea/ant.xml
- .idea/copyright/profiles_settings.xml
- .idea/scopes/scope_settings.xml
> [2.7] Git repository cleanup - untrack .idea folder

- buildsystem/compdeps/pom.xml
- dbws/org.eclipse.persistence.dbws/META-INF/MANIFEST.MF
- foundation/org.eclipse.persistence.core/META-INF/MANIFEST.MF
- jpa/org.eclipse.persistence.jpa/META-INF/MANIFEST.MF
- moxy/org.eclipse.persistence.moxy/META-INF/MANIFEST.MF
- sdo/org.eclipse.persistence.sdo/META-INF/MANIFEST.MF
> [2.7] ASM dependency update to 9.4.0

- buildsystem/compdeps/org.eclipse.persistence.compdeps.p2repo/pom.xml
- buildsystem/compdeps/pom.xml
- foundation/org.eclipse.persistence.core/resource/org/eclipse/persistence/internal/helper/VendorNameToPlatformMapping.properties
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/Oracle21Platform.java
- foundation/org.eclipse.persistence.oracle/src/org/eclipse/persistence/platform/database/oracle/Oracle21Platform.java
adds Oracle21Platform classes and Oracle JDBC, XML libraries update
> [2.7] Oracle21c support

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/DerbyPlatform.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/query/TestDateTimeFunctions.java
Signed-off-by: Tomáš Kraus <tomas.kraus@oracle.com>
> Issue #1583 - Fixed EXTRACT for WEEK in Derby platform.

- etc/el-test.db2.properties
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/DB2Platform.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/DB2ZPlatform.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/DerbyPlatform.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/query/TestQuerySyntaxComparisonTests.java
- pom.xml
> [master] Add DB2 support for JPA31 ROUND

- foundation/org.eclipse.persistence.oracle.nosql/src/it/java/org/eclipse/persistence/testing/models/jpa/nosql/DataTypesEntity.java
- foundation/org.eclipse.persistence.oracle.nosql/src/it/java/org/eclipse/persistence/testing/tests/jpa/nosql/sdk/NoSQLJPADataTypesTest.java
- foundation/org.eclipse.persistence.oracle.nosql/src/it/java/org/eclipse/persistence/testing/tests/jpa/nosql/sdk/NoSQLJPATestSuite.java
- foundation/org.eclipse.persistence.oracle.nosql/src/it/resources/META-INF/persistence.xml
- foundation/org.eclipse.persistence.oracle.nosql/src/main/java/org/eclipse/persistence/nosql/adapters/sdk/OracleNoSQLPlatform.java
This is fix when Lob type is loaded from the database. There are some additional tests too to verify various JPA/NoSQL data types.
> [master] Oracle NoSQL Database - Lob type fix

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/databaseaccess/JsonPlatformManager.java
> [master] Fix for Failed to link Oracle21JsonPlatform

- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/jpql/TestWhiteSpace.java
- jpa/org.eclipse.persistence.jpa.jpql/src/main/java/org/eclipse/persistence/jpa/jpql/AbstractGrammarValidator.java
- jpa/org.eclipse.persistence.jpa.jpql/src/main/java/org/eclipse/persistence/jpa/jpql/AbstractSemanticValidator.java
- jpa/org.eclipse.persistence.jpa.jpql/src/main/java/org/eclipse/persistence/jpa/jpql/AbstractValidator.java
- jpa/org.eclipse.persistence.jpa.jpql/src/main/java/org/eclipse/persistence/jpa/jpql/ExpressionTools.java
- jpa/org.eclipse.persistence.jpa.jpql/src/main/java/org/eclipse/persistence/jpa/jpql/WordParser.java
- jpa/org.eclipse.persistence.jpa.jpql/src/main/java/org/eclipse/persistence/jpa/jpql/parser/AndExpression.java
- jpa/org.eclipse.persistence.jpa.jpql/src/main/java/org/eclipse/persistence/jpa/jpql/parser/OrExpression.java
- jpa/org.eclipse.persistence.jpa.jpql/src/main/java/org/eclipse/persistence/jpa/jpql/tools/AbstractContentAssistVisitor.java
- jpa/org.eclipse.persistence.jpa.jpql/src/main/java/org/eclipse/persistence/jpa/jpql/tools/model/query/AndExpressionStateObject.java
- jpa/org.eclipse.persistence.jpa.jpql/src/main/java/org/eclipse/persistence/jpa/jpql/tools/model/query/OrExpressionStateObject.java
> [3.0] Issue 1755: Add support for non-breaking spaces

- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/jpql/TestWhiteSpace.java
- jpa/org.eclipse.persistence.jpa.jpql/src/org/eclipse/persistence/jpa/jpql/AbstractGrammarValidator.java
- jpa/org.eclipse.persistence.jpa.jpql/src/org/eclipse/persistence/jpa/jpql/ExpressionTools.java
- jpa/org.eclipse.persistence.jpa.jpql/src/org/eclipse/persistence/jpa/jpql/WordParser.java
- jpa/org.eclipse.persistence.jpa.jpql/src/org/eclipse/persistence/jpa/jpql/tools/AbstractContentAssistVisitor.java
> [2.7] Issue 1755: Add support for non-breaking spaces

- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/jpql/TestWhiteSpace.java
- jpa/org.eclipse.persistence.jpa.jpql/src/org/eclipse/persistence/jpa/jpql/AbstractGrammarValidator.java
- jpa/org.eclipse.persistence.jpa.jpql/src/org/eclipse/persistence/jpa/jpql/ExpressionTools.java
- jpa/org.eclipse.persistence.jpa.jpql/src/org/eclipse/persistence/jpa/jpql/WordParser.java
- jpa/org.eclipse.persistence.jpa.jpql/src/org/eclipse/persistence/jpa/jpql/tools/AbstractContentAssistVisitor.java
> [2.6_WAS] Issue 1755: Add support for non-breaking spaces

- jpa/eclipselink.jpa.test/src/it/java/org/eclipse/persistence/testing/tests/jpa22/metadata/MetadataASMFactoryTest.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/metadata/accessors/objects/MetadataAsmFactory.java
> class read fallback needs to reread the stream from the beginning

- jpa/eclipselink.jpa.test/src/it/java/org/eclipse/persistence/testing/tests/jpa22/metadata/MetadataASMFactoryTest.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/metadata/accessors/objects/MetadataAsmFactory.java
(cherry picked from commit 9fd3f9c51a7a121b02abaa549a7eb19af446d16e)
> [3.0] Class read fallback needs to reread the stream from the beginning (#1766)

- jpa/eclipselink.jpa.test/src/org/eclipse/persistence/testing/tests/jpa22/metadata/MetadataASMFactoryTest.java
- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/metadata/accessors/objects/MetadataAsmFactory.java
(cherry picked from commit 9fd3f9c51a7a121b02abaa549a7eb19af446d16e) (cherry picked from commit e1913d748e4896a2bf5675fdefd73da4c58d7b66)
> [2.7] Class read fallback needs to reread the stream from the beginning (#1766)

- jpa/eclipselink.jpa.test/pom.xml
- jpa/eclipselink.jpa.test/src/it/java/org/eclipse/persistence/testing/tests/jpa22/metadata/MetadataASMFactoryTest.java
> [3.0] Class read fallback needs to reread the stream from the beginning - build fix

- pom.xml
> [master] Maven Dependencies - JDBC and NoSQL drivers update

- pom.xml
> [master] MySQL dependencies revert to unblock nightly build

- .github/workflows/codeql-analysis.yml
- .github/workflows/maven.yml
> [master] GitHub Actions - upgrade

- .github/workflows/maven.yml
- etc/jenkins/build.groovy
- etc/jenkins/docker/image/install.sh
- etc/jenkins/docker/pom.xml
- etc/jenkins/pr_verify.groovy
- etc/jenkins/release.groovy
- etc/jenkins/tck.groovy
- etc/jenkins/test.sh
- pom.xml
This PR contains following changes:
- Updated Docker image used by build
- `LANG = 'en_US.UTF-8'` environment variable applied to the Jenkins pipelines
- MySQL driver update
> [master] Jenkins build - Docker image and MySQL (DB + JDBC driver) upgrade

- .github/workflows/codeql-analysis.yml
To fix build issue:
```
...
Failed to execute goal on project org.eclipse.persistence.moxy: Could not resolve dependencies for project org.eclipse.persistence:org.eclipse.persistence.moxy:jar:4.0.1-SNAPSHOT: Could not find artifact org.eclipse.persistence:org.eclipse.persistence.core:jar:tests:4.0.1-SNAPSHOT -> [Help 1]
...
```
> [master] CodeQL analysis fix

- jpa/eclipselink.jpa.testapps.nosql/pom.xml
> skip mongo tests on arm processors

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/DB2ZPlatform.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/query/TestQuerySyntaxComparisonTests.java
> [master] Issue 1735: Improve DB2 ZOS support for LIKE ESCAPE

- jpa/eclipselink.jpa.testapps/README.md
- pom.xml
> reflect mysql driver location change

- pom.xml
> [master] Maven build - dependencies and plugings upgrade plus org.eclipse.dash:license-tool-plugin under new profile added

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/DB2ZPlatform.java
- jpa/eclipselink.jpa.test.jse/src/org/eclipse/persistence/jpa/test/query/TestQuerySyntaxComparisonTests.java
> [2.7] Issue 1735: Improve DB2 ZOS support for LIKE ESCAPE

- etc/jenkins/build.groovy
- etc/jenkins/pr_verify.groovy
- etc/jenkins/promote.groovy
- etc/jenkins/promote_el_init.sh
- etc/jenkins/promote_init.sh
- etc/jenkins/setEnvironment.sh
> [2.7] Jenkins build - promotion pipeline fix to reflect Eclipse.org security settings

- foundation/org.eclipse.persistence.core/resource/org/eclipse/persistence/internal/helper/VendorNameToPlatformMapping.properties
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/Oracle21Platform.java
- foundation/org.eclipse.persistence.oracle/src/org/eclipse/persistence/platform/database/oracle/Oracle21Platform.java
for #1823
port of https://github.com/eclipse-ee4j/eclipselink/pull/1749
> [2.6_WAS] Add Oracle21c support

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/Oracle21Platform.java
- foundation/org.eclipse.persistence.core/src/main/resources/org/eclipse/persistence/internal/helper/VendorNameToPlatformMapping.properties
- foundation/org.eclipse.persistence.oracle/src/main/java/org/eclipse/persistence/platform/database/oracle/Oracle21Platform.java
> [3.0] Add Oracle21c support

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/DB2Platform.java
> [3.0] Issue 1827: Add java.time support for DB2 schema generation

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/DB2Platform.java
> [2.7] Issue 1827: Add java.time support for DB2 schema generation

- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/weaving/PersistenceWeaver.java
(cherry picked from commit 1092bbf6034f88c7e32a41d0f6e07e6e32d66c16)
> [3.0] Persistence weaver logging (remove useless log message) - backport from master

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/Oracle10Platform.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/OraclePlatform.java
- foundation/org.eclipse.persistence.oracle/src/main/java/org/eclipse/persistence/platform/database/oracle/Oracle10Platform.java
- foundation/org.eclipse.persistence.oracle/src/main/java/org/eclipse/persistence/platform/database/oracle/Oracle9Platform.java
for #1540
backport of https://github.com/eclipse-ee4j/eclipselink/pull/1602
> [3.0] Issue 1540: Improve Oracle platform java time support

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/Oracle10Platform.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/OraclePlatform.java
- foundation/org.eclipse.persistence.oracle/src/org/eclipse/persistence/platform/database/oracle/Oracle10Platform.java
- foundation/org.eclipse.persistence.oracle/src/org/eclipse/persistence/platform/database/oracle/Oracle9Platform.java
for #1540
backport of https://github.com/eclipse-ee4j/eclipselink/pull/1602
> [2.7] Issue 1540: Improve Oracle platform java time support

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/platform/database/DerbyPlatform.java
for #1544
backport of https://github.com/eclipse-ee4j/eclipselink/pull/1581
> [2.7] Issue 1544: Derby mapping of LocalTime should map to TIME type

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/DerbyPlatform.java
for #1544
backport of https://github.com/eclipse-ee4j/eclipselink/pull/1581
> [3.0] Issue 1544: Derby mapping of LocalTime should map to TIME type

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/DB2ZPlatform.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/query/TestQuerySyntaxAggregateTests.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/query/TestQuerySyntaxComparisonTests.java
> [master] Add DB2 z/OS support for new JPA 3.1 supported functions

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/DB2ZPlatform.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/query/TestQuerySyntaxComparisonTests.java
> [3.0] Issue 1735: Improve DB2 ZOS support for LIKE ESCAPE

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/localization/i18n/LoggingLocalizationResource.java
Improving the messaging for "corrupt_object_referenced_through_mapping"
> [master] Update LoggingLocalizationResource messages

- dbws/org.eclipse.persistence.dbws/pom.xml
- foundation/eclipselink.core.test/pom.xml
- foundation/org.eclipse.persistence.core/pom.xml
- foundation/org.eclipse.persistence.core/src/main/java/module-info.java
- foundation/org.eclipse.persistence.nosql/pom.xml
- jpa/eclipselink.jpa.test.jse/pom.xml
- jpa/eclipselink.jpa.test/pom.xml
- jpa/eclipselink.jpa.testapps/pom.xml
- jpa/eclipselink.jpa.wdf.test/pom.xml
- jpa/org.eclipse.persistence.jpa.modelgen/pom.xml
- jpa/org.eclipse.persistence.jpars/pom.xml
- moxy/org.eclipse.persistence.moxy/pom.xml
- sdo/org.eclipse.persistence.sdo/pom.xml
- utils/org.eclipse.persistence.dbws.builder/pom.xml
> [4.0] Maven build asm dependency change

- jpa/eclipselink.jpa.testapps/jpa.test.persistence32/pom.xml
- jpa/eclipselink.jpa.testapps/jpa.test.persistence32/src/main/java/org/eclipse/persistence/testing/models/jpa/persistence32/Persistence32TableCreator.java
- jpa/eclipselink.jpa.testapps/jpa.test.persistence32/src/main/java/org/eclipse/persistence/testing/models/jpa/persistence32/Pokemon.java
- jpa/eclipselink.jpa.testapps/jpa.test.persistence32/src/main/java/org/eclipse/persistence/testing/models/jpa/persistence32/Type.java
- jpa/eclipselink.jpa.testapps/jpa.test.persistence32/src/main/resources/META-INF/persistence.xml
- jpa/eclipselink.jpa.testapps/jpa.test.persistence32/src/test/java/org/eclipse/persistence/testing/tests/jpa/persistence32/EntityManagerFactoryTest.java
- jpa/eclipselink.jpa.testapps/pom.xml
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/jpa/JpaEntityManagerFactory.java
Temporary JPA API proposed changes in JpaEntityManagerFactory.
Added tests to verify it in EclipseLink.
> EntityManagerFactory.withTransaction() as default implementation.

- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/jpa/JpaHelper.java
> Bugfix for - Missing error message when calling JpaHelper.getReportQuery() with wrong argument

- bundles/nightly/pom.xml
- bundles/nightly/src/site/custom/surefire-report.properties
- foundation/org.eclipse.persistence.oracle.nosql/pom.xml
- foundation/org.eclipse.persistence.oracle.test/pom.xml
- pom.xml
- src/main/assembly/test-report.xml
- src/site/custom/surefire-report.properties
Plus:
- fixes different location (XPath) in test HTML reports as maven-surefire-report-plugin uses different site skin
- jar-test-sources unnecessary calls removal
- document generation (asciidoctorj) plugin and dependencies update (latest are not functional)
> [master] Maven plugins and dependencies update

- bundles/tests/src/test/java/org/eclipse/persistence/testing/osgi/OSGITestHelper.java
> #1919: 4.0.2 tag fails to run the Bundles tests

- bundles/tests/src/test/java/org/eclipse/persistence/testing/osgi/OSGITestHelper.java
> #1919: 4.0.2 tag fails to run the Bundles tests (2)

- jpa/org.eclipse.persistence.jpa.jpql/src/main/java/org/eclipse/persistence/jpa/jpql/parser/LocateExpression.java
- jpa/org.eclipse.persistence.jpa.jpql/src/main/java/org/eclipse/persistence/jpa/jpql/tools/model/query/LocateExpressionStateObject.java
Remove wrong comments for locate function
> [4.0] Remove wrong comments for locate function

- jpa/org.eclipse.persistence.jpa.jpql/src/main/java/org/eclipse/persistence/jpa/jpql/parser/LocateExpression.java
- jpa/org.eclipse.persistence.jpa.jpql/src/main/java/org/eclipse/persistence/jpa/jpql/tools/model/query/LocateExpressionStateObject.java
Remove wrong comments for locate function
> [3.0] Remove wrong comments for locate function 

- jpa/org.eclipse.persistence.jpa.jpql/src/org/eclipse/persistence/jpa/jpql/parser/LocateExpression.java
- jpa/org.eclipse.persistence.jpa.jpql/src/org/eclipse/persistence/jpa/jpql/tools/model/query/LocateExpressionStateObject.java
Remove wrong comments for locate function
> [2.7] Remove wrong comments for locate function

- etc/jenkins/pr_verify.groovy
- jpa/eclipselink.jpa.spring.test/pom.xml
- pom.xml
`org.eclipse.persistence.jpa.spring.test` module is included now into test (GH action, PR verified, SRG + LRG in the Jenkins)
> [master] JDK 17 minimal build version and Derby and Spring dependency upgrade

- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/framework/SessionEventTracker.java
- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/tests/events/SessionEventTestCase.java
- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/tests/events/TestSessionListener.java
- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/tests/unitofwork/PostFlushUnitOfWorkTest.java
- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/tests/unitofwork/PreFlushUnitOfWorkTest.java
- foundation/eclipselink.core.test/src/org/eclipse/persistence/testing/tests/unitofwork/UnitOfWorkEventTestSuite.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/sessions/RepeatableWriteUnitOfWork.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/sessions/UnitOfWorkImpl.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/sessions/remote/RemoteUnitOfWork.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/sessions/SessionEvent.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/sessions/SessionEventAdapter.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/sessions/SessionEventListener.java
- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/sessions/SessionEventManager.java
- for #1240 
backport of #1978 to 2.7
> [2.7] fix #1240: SessionEventListener: add pre/post flush() events - backport from master

- jpa/org.eclipse.persistence.jpa.jpql/src/main/java/org/eclipse/persistence/jpa/jpql/parser/AbstractExpression.java
- jpa/org.eclipse.persistence.jpa.jpql/src/main/java/org/eclipse/persistence/jpa/jpql/tools/DefaultSemanticValidator.java
- jpa/org.eclipse.persistence.jpa.jpql/src/main/java/org/eclipse/persistence/jpa/jpql/tools/model/query/AbstractStateObject.java
Added doPrivileged for setAccessible when parsing JPQL query with EXTRACT for resolving issue:https://github.com/eclipse-ee4j/eclipselink/issues/1981
for https://github.com/eclipse-ee4j/eclipselink/issues/1981
>  Added doPrivileged for setAccessible when parsing JPQL query with EXTRACT

- foundation/eclipselink.extension.oracle.test/src/org/eclipse/persistence/testing/framework/oracle/SessionExchanger.java
- foundation/eclipselink.extension.oracle.test/src/org/eclipse/persistence/testing/tests/distributedservers/rcm/jms/JMSSetupHelper.java
- foundation/eclipselink.extension.oracle.test/src/org/eclipse/persistence/testing/tests/jpa/proxyauthentication/ProxyAuthenticationTestSuite.java
- foundation/eclipselink.extension.oracle.test/src/org/eclipse/persistence/testing/tests/proxyauthentication/oci/ProxyTestHelper.java
Contains changes related with latest version of Oracle JDBC driver and related libraries like _ucp.jar_.
This is java code backport from #1376
> [2.7] Oracle extension test build fixes - backport from master

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- etc/archetypes/bug_test_case/jpa/pom.xml
- etc/archetypes/bug_test_case/jpa/src/main/resources/META-INF/maven/archetype-metadata.xml
- etc/archetypes/bug_test_case/jpa/src/main/resources/archetype-resources/README.md
- etc/archetypes/bug_test_case/jpa/src/main/resources/archetype-resources/pom.xml
- etc/archetypes/bug_test_case/jpa/src/main/resources/archetype-resources/src/main/java/eclipselink/jpa/bugtest/domain/TestEntityDetail.java
- etc/archetypes/bug_test_case/jpa/src/main/resources/archetype-resources/src/main/java/eclipselink/jpa/bugtest/domain/TestEntityMaster.java
- etc/archetypes/bug_test_case/jpa/src/main/resources/archetype-resources/src/main/java/module-info.java
- etc/archetypes/bug_test_case/jpa/src/main/resources/archetype-resources/src/main/resources/META-INF/persistence.xml
- etc/archetypes/bug_test_case/jpa/src/main/resources/archetype-resources/src/main/resources/META-INF/sql/init.sql
- etc/archetypes/bug_test_case/jpa/src/main/resources/archetype-resources/src/main/resources/PoJoTest.xml
- etc/archetypes/bug_test_case/jpa/src/main/resources/archetype-resources/src/test/java/eclipselink/jpa/bugtest/TestBug.java
- etc/archetypes/bug_test_case/jpa/src/main/resources/archetype-resources/src/test/java/module-info.java
- etc/archetypes/bug_test_case/moxy/pom.xml
- etc/archetypes/bug_test_case/moxy/src/main/resources/META-INF/maven/archetype-metadata.xml
- etc/archetypes/bug_test_case/moxy/src/main/resources/archetype-resources/README.md
- etc/archetypes/bug_test_case/moxy/src/main/resources/archetype-resources/pom.xml
- etc/archetypes/bug_test_case/moxy/src/main/resources/archetype-resources/src/main/java/eclipselink/moxy/bugtest/domain/Container.java
- etc/archetypes/bug_test_case/moxy/src/main/resources/archetype-resources/src/main/java/eclipselink/moxy/bugtest/domain/ObjectFactory.java
- etc/archetypes/bug_test_case/moxy/src/main/resources/archetype-resources/src/test/java/eclipselink/moxy/bugtest/TestBug.java
- etc/archetypes/bug_test_case/moxy/src/main/resources/archetype-resources/src/test/resources/input.xml
- etc/archetypes/bug_test_case/moxy/src/main/resources/archetype-resources/src/test/resources/input.xsd
- etc/archetypes/bug_test_case/moxy/src/main/resources/archetype-resources/src/test/resources/input_attribute_first.json
- etc/archetypes/bug_test_case/moxy/src/main/resources/archetype-resources/src/test/resources/input_value_first.json
- etc/archetypes/bug_test_case/pom.xml
Main purpose of this change is help users with description of the bug or new feature.
Bug template should navigate user to provide required information to analyze bug.
There are Maven archetypes which user should use to create test case applications.
> [master] GitHub issue template and Maven archetypes for testcases

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/oxm/record/SAXUnmarshaller.java
> Bugfix for Faulty char SAXUnmarshaller.getMediaType

- foundation/eclipselink.core.test/src/it/java/org/eclipse/persistence/testing/tests/queries/repreparation/AddJoinedAttributeTest.java
- foundation/eclipselink.core.test/src/it/java/org/eclipse/persistence/testing/tests/queries/repreparation/AddNonFetchedJoinedAttributeTest.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/expressions/Expression.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/expressions/CompoundExpression.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/expressions/ExpressionIterator.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/expressions/FunctionExpression.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/expressions/SQLSelectStatement.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/queries/ExpressionQueryMechanism.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/mappings/querykeys/ForeignReferenceQueryKey.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/mappings/querykeys/QueryKey.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/embeddable/TestCollectionTableEmbeddable.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/embeddable/TestEmbeddable.java
- jpa/eclipselink.jpa.testapps.nosql/pom.xml
make sure ordering in from is guaranteed and fixed
> Add generics to ExpressionIterator,

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/exceptions/i18n/ValidationExceptionResource.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/localization/i18n/LoggingLocalizationResource.java
Changed messages in LogginLocalizationResource and ValidationExceptionResource
> Changed messages in LogginLocalizationResource and ValidationExceptionResource

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/exceptions/i18n/ValidationExceptionResource.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/localization/i18n/LoggingLocalizationResource.java
Improved messages in LogginLocalizationResource and ValidationExceptionResource
> [master] Improved messages in LogginLocalizationResource and ValidationExceptionResource

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/expressions/Expression.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/expressions/SQLUpdateAllStatementForOracleAnonymousBlock.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/queries/ExpressionQueryMechanism.java
ExpressionQueryMechanism refactor with target to replace expressions like Map<DatabaseField, Object> to Map<DatabaseField, Expression>
> [master] ExpressionQueryMechanism refactor

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/mappings/converters/UUIDConverter.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/uuid/TestUuidCommon.java
> [master] UUID not working as GeneratedValue Id with merge - fix

- jpa/eclipselink.jpa.testapps/jpa.test.advanced2/src/test/java/org/eclipse/persistence/testing/tests/advanced2/AnnotationsTest.java
- jpa/eclipselink.jpa.testapps/jpa.test.advanced2/src/test/java/org/eclipse/persistence/testing/tests/advanced2/ConverterTest.java
- jpa/eclipselink.jpa.testapps/jpa.test.advanced2/src/test/java/org/eclipse/persistence/testing/tests/advanced2/CriteriaQueryCastTest.java
- jpa/eclipselink.jpa.testapps/jpa.test.advanced2/src/test/java/org/eclipse/persistence/testing/tests/advanced2/CriteriaQueryMetamodelTest.java
- jpa/eclipselink.jpa.testapps/jpa.test.advanced2/src/test/java/org/eclipse/persistence/testing/tests/advanced2/CriteriaQueryTest.java
- jpa/eclipselink.jpa.testapps/jpa.test.advanced2/src/test/java/org/eclipse/persistence/testing/tests/advanced2/EmployeePopulator.java
- jpa/eclipselink.jpa.testapps/jpa.test.advanced2/src/test/java/org/eclipse/persistence/testing/tests/advanced2/EntityGraphTest.java
- jpa/eclipselink.jpa.testapps/jpa.test.advanced2/src/test/java/org/eclipse/persistence/testing/tests/advanced2/EntityManagerFactoryTest.java
- jpa/eclipselink.jpa.testapps/jpa.test.advanced2/src/test/java/org/eclipse/persistence/testing/tests/advanced2/EntityManagerTest.java
- jpa/eclipselink.jpa.testapps/jpa.test.advanced2/src/test/java/org/eclipse/persistence/testing/tests/advanced2/NamedStoredProcedureQueryTest.java
- jpa/eclipselink.jpa.testapps/jpa.test.advanced2/src/test/java/org/eclipse/persistence/testing/tests/advanced2/QueryTest.java
- jpa/eclipselink.jpa.testapps/jpa.test.advanced2/src/test/java/org/eclipse/persistence/testing/tests/advanced2/StoredProcedureQueryTest.java
- jpa/eclipselink.jpa.testapps/jpa.test.advanced2/src/test/java/org/eclipse/persistence/testing/tests/advanced2/WeaverTest.java
- jpa/eclipselink.jpa.testapps/jpa.test.advanced2/src/test/java/org/eclipse/persistence/testing/tests/advanced2/ddl/DDLSchemaTest.java
- jpa/eclipselink.jpa.testapps/jpa.test.advanced2/src/test/java/org/eclipse/persistence/testing/tests/advanced2/ddl/DDLTest.java
- jpa/eclipselink.jpa.testapps/jpa.test.advanced2/src/test/java/org/eclipse/persistence/testing/tests/advanced2/ddl/ForeignKeyTest.java
- jpa/eclipselink.jpa.testapps/jpa.test.advanced2/src/test/java/org/eclipse/persistence/testing/tests/advanced2/ddl/IndexTest.java
- jpa/eclipselink.jpa.testapps/jpa.test.advanced2/src/test/java/org/eclipse/persistence/testing/tests/advanced2/xml/EmployeePopulator.java
- jpa/eclipselink.jpa.testapps/jpa.test.advanced2/src/test/java/org/eclipse/persistence/testing/tests/advanced2/xml/XMLConverterTest.java
- jpa/eclipselink.jpa.testapps/jpa.test.advanced2/src/test/java/org/eclipse/persistence/testing/tests/advanced2/xml/XMLEntityGraphTest.java
- jpa/eclipselink.jpa.testapps/jpa.test.advanced2/src/test/java/org/eclipse/persistence/testing/tests/advanced2/xml/XMLNamedStoredProcedureQueryTest.java
- jpa/eclipselink.jpa.testapps/jpa.test.advanced2/src/test/java/org/eclipse/persistence/testing/tests/advanced2/xml/ddl/XMLForeignKeyTest.java
- jpa/eclipselink.jpa.testapps/jpa.test.advanced2/src/test/java/org/eclipse/persistence/testing/tests/advanced2/xml/ddl/XMLIndexTest.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/StoredProcedureQueryImpl.java
Fix plus unit tests.
Package refactor in `org.eclipse.persistence.jpa.testapps.advanced2` as tests are not limited to JPA 2.1 now.
> [master] StoredProcedureQuery getSingleResultOrNull() fix

- jpa/org.eclipse.persistence.jpars/src/it/java/org/eclipse/persistence/jpars/test/util/TestHttpHeaders.java
- jpa/org.eclipse.persistence.jpars/src/it/java/org/eclipse/persistence/jpars/test/util/TestURIInfo.java
- pom.xml
- other dependencies and Maven plugins upgrade
- some JPARS test classes changes to reflect latest JAX-WS-RS API
> [master] Jakarta Persistence API 3.2.0 and ASM 9.7 upgrade

- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/querydef/FromImpl.java
> Queries created with criteria api with many joins - fix

- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/querydef/FromImpl.java
> [4.0] Queries created with criteria api with many joins - fix - backport from master

- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/querydef/FromImpl.java
> [3.0] Queries created with criteria api with many joins - fix - backport from master

- jpa/org.eclipse.persistence.jpa/src/org/eclipse/persistence/internal/jpa/querydef/FromImpl.java
> [2.7] Queries created with criteria api with many joins - fix - backport from master

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/expressions/ExpressionOperator.java
Fixes #2136 
Backport from #2137
> [3.0] NPE in ExpressionOperator.printCollection  - backport from 2.7

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/expressions/ExpressionOperator.java
Fixes #2136 
Backport from #2137
> [4.0] NPE in ExpressionOperator.printCollection - backport from 2.7

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/sessions/UnitOfWorkImpl.java
Fixes #1957.
Backport of #1958.
> [4.0] fix #1957: Presize HashMap allocations - backport from master

- foundation/eclipselink.core.test/src/it/java/org/eclipse/persistence/testing/tests/queries/QueryTimeoutConnectionReleasedTest.java
- foundation/eclipselink.core.test/src/it/java/org/eclipse/persistence/testing/tests/queries/QueryTimeoutTest.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/databaseaccess/DatasourcePlatform.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/databaseaccess/Platform.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/Oracle23Platform.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/oracle/plsql/PLSQLStoredProcedureCall.java
- foundation/org.eclipse.persistence.core/src/main/resources/org/eclipse/persistence/internal/helper/VendorNameToPlatformMapping.properties
- foundation/org.eclipse.persistence.oracle/src/main/java/org/eclipse/persistence/platform/database/oracle/Oracle23Platform.java
- jpa/eclipselink.jpa.test/src/it/java/org/eclipse/persistence/testing/tests/jpa/plsql/PLSQLTestSuite.java
- pom.xml
[3.0] Oracle 23 platform - backport from master
> [3.0] Oracle 23 platform - backport from master

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/jpa/jpql/ExpressionBuilderVisitor.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/jpa/jpql/HermesParser.java
- jpa/eclipselink.jpa.testapps/jpa.test.jpql/src/test/java/org/eclipse/persistence/testing/tests/jpa/jpql/advanced/JUnitJPQLJakartaDataNoAliasTest.java
- jpa/eclipselink.jpa.testapps/jpa.test.persistence32/src/test/java/org/eclipse/persistence/testing/tests/jpa/persistence32/QueryTest.java
- jpa/org.eclipse.persistence.jpa.jpql/src/main/java/org/eclipse/persistence/jpa/jpql/AbstractSemanticValidator.java
- jpa/org.eclipse.persistence.jpa.jpql/src/main/java/org/eclipse/persistence/jpa/jpql/parser/AbstractPathExpression.java
Fixes #2197, #2198, #2199 and adds a test to verify that #2183 is already fixed.
> Various fixes for using "this" variable in JPQL

- pom.xml
> [master] Maven build - OSGi Bundle-Version fix

- pom.xml
Fixes #2221
(cherry picked from commit efbce400392c65c9440641ceae74889e157173fd)
> [4.0] Maven build - OSGi Bundle-Version fix (#2230) - backport from master

- pom.xml
> [3.0] Maven build - OSGi Bundle-Version fix - backport from master

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/dynamic/DynamicTypeBuilder.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/dynamic/DynamicPropertiesInitializatonPolicy.java
- moxy/org.eclipse.persistence.moxy/src/test/java/org/eclipse/persistence/testing/jaxb/dynamic/DynamicJAXBCollectionTestCases.java
Related to https://github.com/eclipse-ee4j/eclipselink/issues/2255
Here I've been able to resolve the problem as per my reported issue. Though with only a moderate understanding of the entire library, please indicate if this has any unintended side-effects?
> Instantiate collections for DynamicType properties

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/queries/ReportQuery.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/queries/ReportQueryResult.java
- jpa/eclipselink.jpa.test/pom.xml
- jpa/eclipselink.jpa.test/src/it/assembly/eclipselink-batchfetch-model.xml
- jpa/eclipselink.jpa.test/src/it/java/org/eclipse/persistence/testing/models/jpa/batchfetch/BatchFetchTableCreator.java
- jpa/eclipselink.jpa.test/src/it/java/org/eclipse/persistence/testing/models/jpa/batchfetch/Company.java
- jpa/eclipselink.jpa.test/src/it/java/org/eclipse/persistence/testing/models/jpa/batchfetch/Count.java
- jpa/eclipselink.jpa.test/src/it/java/org/eclipse/persistence/testing/models/jpa/batchfetch/Employee.java
- jpa/eclipselink.jpa.test/src/it/java/org/eclipse/persistence/testing/models/jpa/batchfetch/Record.java
- jpa/eclipselink.jpa.test/src/it/java/org/eclipse/persistence/testing/tests/jpa/FullRegressionTestSuite.java
- jpa/eclipselink.jpa.test/src/it/java/org/eclipse/persistence/testing/tests/jpa/batchfetch/BatchFetchJUnitTest.java
- jpa/eclipselink.jpa.test/src/it/resources/eclipselink-batchfetch-model/persistence.xml
- jpa/eclipselink.jpa.test/src/it/resources/eclipselink-batchfetch-model/server/persistence.xml
>  [3.0] Fix for ReportQuery not fetching relationships with BatchFetch.IN

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/databaseaccess/DatabasePlatform.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/PostgreSQLPlatform.java
- jpa/eclipselink.jpa.test.jse/src/it/java/org/eclipse/persistence/jpa/test/storedproc/TestStoredProcedures.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/StoredProcedureQueryImpl.java
Port of #2308 to master branch.
> Fix calling stored procs on Postgres, and enable some tests

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/database/MySQLPlatform.java
> [master] MySQLPlatform update to support `java.time.Instant` during automatic table creation.

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/queries/DatabaseQueryMechanism.java
- jpa/eclipselink.jpa.testapps/jpa.test.beanvalidation/src/main/java/org/eclipse/persistence/testing/models/jpa/beanvalidation/BeanValidationTableCreator.java
- jpa/eclipselink.jpa.testapps/jpa.test.beanvalidation/src/main/java/org/eclipse/persistence/testing/models/jpa/beanvalidation/Task.java
- jpa/eclipselink.jpa.testapps/jpa.test.beanvalidation/src/main/resources/META-INF/persistence.xml
- jpa/eclipselink.jpa.testapps/jpa.test.beanvalidation/src/test/java/org/eclipse/persistence/testing/tests/jpa/beanvalidation/BeanValidationJunitTest.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/metadata/listeners/BeanValidationListener.java
This is a backport of https://github.com/eclipse-ee4j/eclipselink/pull/2265
> Don't validate if the only change is to a @Version attribute (e.g. em.find() with PESSIMISTIC_FORCE_INCREMENT)

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/localization/i18n/LoggingLocalizationResource.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/server/NoServerPlatform.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/platform/server/ServerPlatformBase.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/transaction/JTA11TransactionController.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/transaction/JTATransactionController.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/EntityManagerSetupImpl.java
> Issue #2391 - Fixed JTATransactionController JNDI initialization

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/exceptions/i18n/ValidationExceptionResource.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/localization/i18n/LoggingLocalizationResource.java
Minor message changes; backport from master
> [4.0]Minor message changes; backport from master

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/oxm/record/WriterRecord.java
- moxy/org.eclipse.persistence.moxy/src/test/java/org/eclipse/persistence/testing/jaxb/JAXBTestSuite.java
- moxy/org.eclipse.persistence.moxy/src/test/java/org/eclipse/persistence/testing/jaxb/xmlanyelement/ns3/DefaultNamespace3TestCases.java
- moxy/org.eclipse.persistence.moxy/src/test/java/org/eclipse/persistence/testing/jaxb/xmlanyelement/ns3/Root.java
- moxy/org.eclipse.persistence.moxy/src/test/java/org/eclipse/persistence/testing/jaxb/xmlanyelement/ns3/package-info.java
- moxy/org.eclipse.persistence.moxy/src/test/resources/org/eclipse/persistence/testing/jaxb/xmlanyelement/ns/root3.xml
> [master] MOXy - Missing namespace when marshalling org.w3c.dom.Element with namespaced attribute - bugfix and unit test

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/oxm/record/WriterRecord.java
- moxy/org.eclipse.persistence.moxy/src/test/java/org/eclipse/persistence/testing/jaxb/JAXBTestSuite.java
- moxy/org.eclipse.persistence.moxy/src/test/java/org/eclipse/persistence/testing/jaxb/xmlanyelement/ns3/DefaultNamespace3TestCases.java
- moxy/org.eclipse.persistence.moxy/src/test/java/org/eclipse/persistence/testing/jaxb/xmlanyelement/ns3/Root.java
- moxy/org.eclipse.persistence.moxy/src/test/java/org/eclipse/persistence/testing/jaxb/xmlanyelement/ns3/package-info.java
- moxy/org.eclipse.persistence.moxy/src/test/resources/org/eclipse/persistence/testing/jaxb/xmlanyelement/ns/root3.xml
Fixes #2390
(cherry picked from commit e22c0e49ddc104dfb22b265d18ef0e941bc9bc53)
> [4.0] Missing namespace when marshalling org.w3c.dom.Element with namespaced attribute - bugfix and unit test - backport from master

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/exceptions/QueryException.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/exceptions/i18n/QueryExceptionResource.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/queries/ConstructorReportItem.java
> [master] JPQL NEW operator check for unsupported types

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/exceptions/ConversionException.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/exceptions/ValidationException.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/exceptions/i18n/ConversionExceptionResource.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/exceptions/i18n/ValidationExceptionResource.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/helper/Helper.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/mappings/converters/EnumTypeConverter.java
- jpa/eclipselink.jpa.testapps/jpa.test.persistence32/src/main/java/org/eclipse/persistence/testing/models/jpa/persistence32/Trainer.java
- jpa/eclipselink.jpa.testapps/jpa.test.persistence32/src/main/java/org/eclipse/persistence/testing/models/jpa/persistence32/TrainerStatusOrdinal.java
- jpa/eclipselink.jpa.testapps/jpa.test.persistence32/src/main/java/org/eclipse/persistence/testing/models/jpa/persistence32/TrainerStatusString.java
- jpa/eclipselink.jpa.testapps/jpa.test.persistence32/src/test/java/org/eclipse/persistence/testing/tests/jpa/persistence32/AbstractPokemonSuite.java
- jpa/eclipselink.jpa.testapps/jpa.test.persistence32/src/test/java/org/eclipse/persistence/testing/tests/jpa/persistence32/EnumTest.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/metadata/MetadataConstants.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/metadata/converters/EnumeratedMetadata.java
Implementation and unit test of @EnumeratedValue described in Jakarta Persistence 3.2 (11.1.19. EnumeratedValue Annotation) https://jakarta.ee/specifications/persistence/3.2/jakarta-persistence-spec-3.2#a14720
Fixes #2460
> [master] Jakarta Persistence 3.2 new feature - @EnumeratedValue annotation support in Java enum

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/expressions/FunctionExpression.java
- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/expressions/SubSelectExpression.java
- jpa/eclipselink.jpa.testapps/jpa.test.jpql/src/test/java/org/eclipse/persistence/testing/tests/jpa/jpql/relationships/AdvancedQueryTest.java
- jpa/eclipselink.jpa.testapps/jpa.test.relationships/src/main/java/org/eclipse/persistence/testing/models/jpa/relationships/AlternateAddress.java
- jpa/eclipselink.jpa.testapps/jpa.test.relationships/src/main/java/org/eclipse/persistence/testing/models/jpa/relationships/RelationshipsExamples.java
- jpa/eclipselink.jpa.testapps/jpa.test.relationships/src/main/java/org/eclipse/persistence/testing/models/jpa/relationships/ShippingAddress.java
Bugfix + unit tests
Fixes #2477
> [master] EclipseLink IndexOutOfBoundsException: Index 0 out of bounds for length 0 - bugfix

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/mappings/converters/EnumTypeConverter.java
- jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/metadata/converters/EnumeratedMetadata.java
Behind this bug is class loading issue in JEE environment for Java enum at the phase of EntityManager predeployment.
Fixes #2501
> [master] Jakarta Persistence 3.2 - Persistence unit deployment fails when using @EnumeratedValue annotation #2501 - bugfix

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/queries/ExpressionQueryMechanism.java
> [master] JPQL Update with Null Embedded Object Fails on PostgreSQL Due to Type Mismatch #2517 - bugfix

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/queries/DatabaseQueryMechanism.java
Fixes #2366
(cherry picked from commit c9185a80cac40e43ae80f1c944b26886fccb4fc6)
> [4.0] Added statement cleanup into updateObjectAndRowWithSequenceNumber (#2523) - backport from master

- foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/queries/DatabaseQueryMechanism.java
> [master] JDBC prepared statements aren't closed - bugfix 2.0

- foundation/org.eclipse.persistence.core/src/org/eclipse/persistence/internal/localization/i18n/LoggingLocalizationResource.java
Added minor messaging improvements.
> [2.7] Minor messaging improvements
